### PR TITLE
Add CLI option to prevent errors on unmatched patterns

### PR DESCRIPTION
**Pull request by daronmcintosh**
## Description

Fixes: https://github.com/prettier/prettier/issues/8233

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by thorn0 — APPROVED** [review]
Looks great! Thank you.

**Comment by daronmcintosh** [comment]
👍 

When can expect this to be released?

**Review by sosukesuzuki — APPROVED** [review]

**Comment by thorn0** [comment]
@daronmcintosh Sorry, can't answer that. The project has no fixed release schedule. All we have is an attempt to discuss it in #9095. 🤷‍♂️

**Comment by baileytincher** [comment]
> @daronmcintosh Sorry, can't answer that. The project has no fixed release schedule. All we have is an attempt to discuss it in #9095. 🤷‍♂️

Why do releases need a schedule for small, unbreaking changes like this?

**Pull request merged**
