### PR TITLE
Upgrade SVGO and more settings

### PR DESCRIPTION
**Pull request by lipis**

### CODE REVIEW

**Comment by j-f1** [comment]
Looks like Prettier is unhappy with the plugin docs.

**Comment by lipis** [comment]
hmm.. left the office.. will be able to check it later..

**Comment by lipis** [comment]
Not sure what's wrong with the docs :/  The [deployed version](https://deploy-preview-4018--prettier.netlify.com/) looks fine..

**Comment by lipis** [comment]
All green this time! 📗

**Pull request merged**
