### PR TITLE
Update Jest to v29

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Jest 29 has been released:tada:

https://jestjs.io/blog/2022/08/25/jest-29

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Everything seems working fine, let's wait for https://github.com/nicolo-ribaudo/jest-light-runner/pull/56

**Comment by sosukesuzuki** [comment]
Thank you

**Comment by nicolo-ribaudo** [comment]
jest-light-runner 0.4.0 released

**Comment by fisker** [comment]
Thank you

**Pull request merged**
