### PR TITLE
deduplicate entries in yarn.lock

### PR DESCRIPTION
**Pull request by thorn0**
I used this tool: https://github.com/atlassian/yarn-deduplicate

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
I have one more fix coming. For printing bigints parsed by Flow.

**Comment by lydell** [comment]
The tests failed :(

**Comment by thorn0** [comment]
They were okay locally. :(

**Comment by lydell** [comment]
Maybe you didn’t run Node.js 4 locally?

**Comment by thorn0** [comment]
I didn't.

**Comment by lydell** [comment]
Should we try to fix this before releasing 1.19, or does it not matter?

**Comment by thorn0** [comment]
Does not matter.

**Pull request merged**
