### PR TITLE
feat: add new option `html-top-level-indent`

### PR DESCRIPTION
**Pull request by Justineo**
Added a new option: `html-top-level-indent`, which is described in https://github.com/prettier/prettier/issues/3888#issuecomment-473973916.

The new option has the following possible values:

- `"always"` - Always apply top-level indent for templates, scripts and styles.
- `"never"` - Avoid top-level indent for templates, scripts and styles.
- `"auto"` - Avoid top-level indent for scripts and styles inside Vue files.

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by lydell** [comment]
I like it! :+1:

Considering the last couple of comments in #3888 I'm also open to only doing `--vue-indent true/false` (should be an easy change). What to think, @azz (re https://github.com/prettier/prettier/pull/5574#pullrequestreview-212594873)?

**Comment by Justineo** [comment]
@lydell Should I update the website code as well? (Not sure how to do it and may need some help.)

**Comment by lydell** [comment]
I'd say we should apply it to all levels:

```html
<script>
let foo
</script>
<body>
  <script>
  let bar
  </script>
</body>
```

But this feels like another argument to making the option specific to Vue SFCs.

> Should I update the website code as well?

Do you mean the playground? I haven't touch it since the React rewrite, so I'm a bit unsure myself.

**Comment by ForsakenHarmony** [comment]
To me indenting template but not script and style (in vue) by default seems like an inconsistency, should at least not be the default

**Comment by Justineo** [comment]
@ForsakenHarmony Changing the default behavior will be a breaking change.

**Comment by ForsakenHarmony** [comment]
I know, but maybe it should be

**Comment by berrylaw** [comment]
Can u wait me ?


Berry Law

**Comment by azz** [comment]
I'm not sure I like the name for `auto`, since it's vue-specific it should something like `not-vue`, no?

**Comment by Justineo** [comment]
`auto` is for those who do not care about this option. We shouldn’t expose implementation details in the option value to those users IMO. It’s not Vue-specific and will apply to any embedded language inside an HTML context.

**Comment by tszulc** [comment]
Is there any word on when this will go in?

**Comment by lydell** [comment]
The code of this PR looks really good! I tried it out locally and realized something.

The reason I thought https://github.com/prettier/prettier/pull/5574#pullrequestreview-212594873 sounded like a good idea was because it sounded like there would be nothing Vue-specific about the option. But there is.

```
~/forks/prettier implement-3888 %  
❯ ./bin/prettier.js test.vue --html-top-level-indent auto
<template>
  <div>test</div>
</template>

<script>
test;
</script>

~/forks/prettier implement-3888 %  
❯ ./bin/prettier.js test.vue --html-top-level-indent always
<template>
  <div>test</div>
</template>

<script>
  test;
</script>

~/forks/prettier implement-3888 %  
❯ ./bin/prettier.js test.vue --html-top-level-indent never
<template>
<div>test</div>
</template>

<script>
test;
</script>
```

Notice the indentation of `<template>` with the different option values. This _does_ work as described by the help text and PR description, but didn't realize this until now.

Now I'm a little confused. What is it that users want really?

It makes sense from a logical point of view not to indent `<template>` if you're not indenting `<script>` and `<style>`. But nobody has complained about that? It feels more like there are two camps in #3888: Those who want to keep things as-is, and those who want to indent everything.

So maybe a `--vue-indent-script-and-style` boolean flag would make more sense? (On the other hand, we could just as well end up in the situation with `--jsx-bracket-same-line` where people want it in HTML as well: #5377) 

Sorry for all the back and forth! I really wanted to press the "Approve" button on this PR this morning, but now I'm not sure. Prettier's goal is a low amount of options. When we add a new one we must make sure that it is _really_ making people happier. And I'm not sure that `auto` users will be happy with `never` (if we remove `auto` in 2.0) since that also dedents `<template>`. Or maybe the would? Who knows? :cry:

**Comment by bytesnz** [comment]
My understanding is the auto value will keep the indentation as it currently is with the HTML and vue formatters (the indenting `template` but not `script` and `style` seems to be one of the standards in vue) and the `always` and `never` values will change to be all indented or not indented. The PR works as I was hoping it would.

**Comment by Justineo** [comment]
@lydell

> Sorry for all the back and forth! I really wanted to press the "Approve" button on this PR this morning, but now I'm not sure.

No worries. 

What I had in my mind when making this PR is:

1. provide a language-agnostic option API for all markup languages
2. keep current behavior as default to prevent a breaking change
3. having `always` but no `never` seems a little weird to me

But as you say, there's not yet huge demand for `never` yet so I'm totally okay with dropping `never` (though I personally prefer `never` but `auto` is just fine as well).

> So maybe a `--vue-indent-script-and-style` boolean flag would make more sense? (On the other hand, we could just as well end up in the situation with `--jsx-bracket-same-line` where people want it in HTML as well: #5377)

I see #5377 has a lot of upvotes, and I think it doesn't make much sense that we only allow it in JSX but not HTML (I'd say people waiting for that feature can't be very happy about it). So in this case I agree with your earliest opinion (https://github.com/prettier/prettier/issues/3888#issuecomment-471307248) to make it work beyond Vue templates.

> And I'm not sure that `auto` users will be happy with `never` (if we remove `auto` in 2.0) since that also dedents `<template>`.

If you are dropping the current behavior, I'd say it will be very likely that some users will get unhappy, whether you have `never` or not. I think we should consider whether to apply the option beyond Vue files first, then talk about possible option values and wording.

**Comment by ForsakenHarmony** [comment]
`auto` to me seems like a very misleading name if it only changes something for Vue, I'd really prefer for it to not be merged in the current form.

If not making this very specific thing which most people don't like according to the polls a breaking change is important, the default value should have some kind of special name

**Comment by Justineo** [comment]
@ForsakenHarmony `auto` actually means you don't care about how Prettier handles this by conventions we can find (in this case: the recommendation of the Vue.js official style guide).  And since it applies to all HTML-base language, I don't think we should add a Vue-specific option value. Maybe I should change the help text.

**Comment by lydell** [comment]
- always – the easy to understand one
- auto – the Vue one
- never – the one you won't use

:thinking:

**Comment by ForsakenHarmony** [comment]
@Justineo thing is it currently is Vue specific?

**Comment by Justineo** [comment]
@ForsakenHarmony Yes.

**Comment by kamilic** [comment]
Any plans to merge these changes in next version?

**Comment by lydell** [comment]
I think the conclusion from what we’ve learned from this PR is that the `--html-top-level-indent` option sounded good on paper, but reality calls for a Vue-specific option `--vue-indent-script-and-style`.

**Comment by kamilic** [comment]
I vote `--vue-indent-script-and-style`.
I think that no or few people will use this as html-specific option.
Maybe we can move this feature to internal, providing ability for`--vue-indent-script-and-style`  implementing.

**Comment by Justineo** [comment]
As mentiond earlier, this PR aims to:

1. Answer the needs of Vue/Prettier users.
2. Respect the opinion of the Prettier team, to make it available for all HTML-base languages: https://github.com/prettier/prettier/issues/3888#issuecomment-471307248, https://github.com/prettier/prettier/issues/3888#issuecomment-473979489. And as @lydell said it's more future-proof and help us avoid situations like #5377.
3. Avoid introducing breaking changes.

Unfortunately, it's not ideal at last. Let's wait for a `vue-indent-script-and-style` implementation then.

**Comment by lydell** [comment]
@Justineo Thank you for your hard work on this PR! I’m really sorry it did not end up merged, but sometimes a PR of exploration is what it takes to find the best solution to a problem. :bowing_man:

**Comment by Justineo** [comment]
To be clear, I don't think `vue-indent-script-and-style` is a better solution. :confused:

But I respect your choice.

**Comment by ForsakenHarmony** [comment]
I like this, but I just don't like `auto` as the name for the current behaviour

**Pull request closed without merging**
