### PR TITLE
Print null argument list item

### LINKED ISSUE #9735: TypeError: Cannot read property 'type' of null
**Prettier 2.2.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEA3AhgG0wF5MBzAVwFsAjCACgHJcGAaTNh6hgShBZAgAHGAEt0yULgBOUiAHcACtIRpkIAnNwBPVf2pTcYANZwYAZUGGRUUshhTycfnBpwAJm-cAZXDfK5SOAAxCClKXBhRGzVcchgIPhAACxhKfAB1JJF4NEswODMVbJFsbK01MDRdEGs0OCkYBQNScOQAMwI6-gArNAAPACEDY1MzXEo4L2s4ds6nEF6+s2tSfDgARXIIeFn8LpBLKTqpNWpcajh8RMEpaxh0kTcYJOQADgAGfhuIOvSDQTUNzgx2wM34AEctvAmkJVChcGgALRQODudyJKRwSEiTFNAKtJAdPbzOqUER2BwklZrTbbGaEub8GDnB5PF5IABMTIMInwKwAwhBKASQMCAKyJch1AAq5zhRP22EcAEkoJ5YGYwLdhABBNVmGBaNa7OoAX1NQA)
```sh
--parser babel
```

**Input:**
```jsx
const val = gumbo('a', , 'b')
```

**Output:**
```jsx
ec@https://prettier.io/lib/standalone.js:15:153287
isFunctionCompositionArgs@https://prettier.io/lib/standalone.js:15:159897
Sg@https://prettier.io/lib/standalone.js:15:235836
printCallExpression@https://prettier.io/lib/standalone.js:15:242269
print@https://prettier.io/lib/standalone.js:15:280369
printComments@https://prettier.io/lib/standalone.js:15:111559
e@https://prettier.io/lib/standalone.js:15:115110
call@https://prettier.io/lib/standalone.js:15:113351
printVariableDeclarator@https://prettier.io/lib/standalone.js:15:247163
print@https://prettier.io/lib/standalone.js:15:280369
printComments@https://prettier.io/lib/standalone.js:15:111559
e@https://prettier.io/lib/standalone.js:15:115110
https://prettier.io/lib/standalone.js:15:113713
each@https://prettier.io/lib/standalone.js:15:113626
map@https://prettier.io/lib/standalone.js:15:113697
https://prettier.io/lib/standalone.js:15:259378
print@https://prettier.io/lib/standalone.js:15:280369
printComments@https://prettier.io/lib/standalone.js:15:111559
e@https://prettier.io/lib/standalone.js:15:115110
Ay@https://prettier.io/lib/standalone.js:15:247810
https://prettier.io/lib/standalone.js:15:113713
each@https://prettier.io/lib/standalone.js:15:113626
map@https://prettier.io/lib/standalone.js:15:113697
printStatementSequence@https://prettier.io/lib/standalone.js:15:248871
call@https://prettier.io/lib/standalone.js:15:113351
https://prettier.io/lib/standalone.js:15:253814
print@https://prettier.io/lib/standalone.js:15:280369
printComments@https://prettier.io/lib/standalone.js:15:111559
e@https://prettier.io/lib/standalone.js:15:115110
call@https://prettier.io/lib/standalone.js:15:113351
https://prettier.io/lib/standalone.js:15:253534
print@https://prettier.io/lib/standalone.js:15:280369
printComments@https://prettier.io/lib/standalone.js:15:111559
e@https://prettier.io/lib/standalone.js:15:115110
ja@https://prettier.io/lib/standalone.js:15:115164
ts@https://prettier.io/lib/standalone.js:15:118269
us@https://prettier.io/lib/standalone.js:15:120602
format@https://prettier.io/lib/standalone.js:55:37351
formatCode@https://prettier.io/worker.js:124:27
handleMessage@https://prettier.io/worker.js:75:28
https://prettier.io/worker.js:36:27
```

**Expected behavior:**

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #9735

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
This error seems too  generic, can we handle `null` in Call.arguments?

**Comment by sosukesuzuki** [comment]
@fisker Should we throw error?

**Comment by fisker** [comment]
I think not.

**Review by fisker — APPROVED** [review]
Looks good, better add some comments test

**Prettier pr-9787**
[Playground link](https://deploy-preview-9787--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAzCEAUAdEBDXAGmygAJzSB6SgRhItMNNwCNcBKAbhJEJAgAOMAJbQAzslB4ATtIgB3AAoyEElHgA28vAE8JfFtLxgA1nBgBlAceFQA5shjSArnD5wAtizgATH74AZPHtnPDs4ADEIaQ88GBF7ZHxnGAheEAALGA8NAHUM4XgxazA4C1VC4QA3Qp0ksDF9EFsxOGkYRSM7WORUTVa+ACsxAA8AISNTcws8DzgA2zhe-rcQYZGLWzsNOABFZwh4ZY0BkGtpVukkljxvDXSBaVsYXOEfGAzkAA4ABj5HiCtXJGARJR5wS5VJZ8ACOB3gnUEanwYgAtFA4L5fOlpHA4cJcZ0wj0kH0TqtWh5hI4XBStjt9oclqSVnwYLdXu9PkgAExsozCDRbADCEA8JJAEIArOlnK0ACq3NRk05VVwASSg-lgFjATyEAEEtRYYDodsdWgBfS1AA)
```sh
--parser babel
```

**Input:**
```jsx
foo("a",
    //1
    , "b");

```

**Output:**
```jsx
foo(
  "a",
  ,
  //1
  "b"
);

```

And, don't forgot change title.

**Comment by thorn0** [comment]
These exceptions still happen: [example 1](https://deploy-preview-9787--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBDAFAGlQShJkCABxgEtoBnZUVAJ1ogHcAFOhKlVAG0dQE8qBAEa1UYANZwYAZSJjSUAObIYtAK5wCcALZC4AE30GAMqiVrUiuADEItbahhklyNGpgR8IABYxtXAHVvUngKOTA4aXYQ0gA3EL5XMApBEAUKOFoYZlFFB2QAM24MggArCgAPACFRCSlpVG04YwU4QuLNEHKK6QVFLjgARTUIeHauEpA5WgzaVyFUPS4vIloFGADSfRhvZAAOAAYCVYgMgNEiV1W4Wdi2ggBHEfgc4g40CgBaKDgDAy9aHAnqRATlLPkkEUJp0MtpSCp1DC+gNhqM2pCOgQYItNttdkgAExY0SkLh9ADCEG0EJANwArF41BkACqLDhQyaxDQASSgRlg0jAaxIAEE+dIYHwBuMMgBfWVAA), [example 2](https://deploy-preview-9787--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBDAFAGgJQkyCABxgEtoBnZUVAJxogHcAFWhSlVAGwdQE9L8AIxqowAazgwAyoVEkoAc2QwaAVzj44AW0FwAJnv0AZVItWoFcAGIQaW1DFKLkaVTAh4QACxhbOAdS8SeHJZMDgpNmCSADdg3hcwcgEQeXI4GhgmEQV7ZAAzLnT8ACtyAA8AIRFxSSlULTgjeTgCoo0QMvKpeQVOOABFVQh4Ns5ikFkadJoXQVRdTk9CGnkYfxI9GC9kAA4ABnwViHT-EUIXFbgZmNb8AEdh+GyidjRyAFooOH19Txo4I8SADshY8khCuMOuktCRlGpob1+kMRq0Ie18DAFhstjskAAmTEiEicXoAYQgWnBIGuAFZPKp0gAVBbsSETGLqACSUEMsCkYFWxAAgrypDBeP0xukAL4yoA)

**Pull request merged**
