### PR TITLE
Safer check before passing to `fill`

### PR DESCRIPTION
**Pull request by fisker**
## Description

Ref https://github.com/prettier/prettier/pull/9847#discussion_r567485818

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
What about this part

> Expects the docs argument to be an array of alternating content and line breaks. In other words, elements with odd indices must be line breaks

?

**Comment by fisker** [comment]
In that case, all `concat` doc parts can't turn into `fill`, no matter it from `normalizeDoc` or `cleanDoc`.

**Comment by fisker** [comment]
I don't know what to do, let's make sure they are `array` first?

**Comment by thorn0** [comment]
> In that case, all concat doc parts can't turn into fill

Sometimes (e.g. the result of `join(line, docs)`), it's safe. But overall - yes, it's not safe.

> no matter it from normalizeDoc or cleanDoc.

Before being passed to `normalizeDoc` or `cleanDoc`, the array might have been constructed in a special way for `fill`.
E.g., something like `[['a', 'b'], line, ['c', 'd']]`.

**Review by thorn0 — APPROVED** [review]
> let's make sure they are array first

OK

**Review by sosukesuzuki — APPROVED** [review]

**Pull request merged**
