### PR TITLE
Refactor `FastPath#get{Name,Value}` to `getter`

### PR DESCRIPTION
**Pull request by fisker**
- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
I do not see any benefits from the approach except that we will break the backward compatibility of all

**Comment by fisker** [comment]
@evilebottnawi Don't you think it's easier to use? If you consider `backward compatibility` , how about deprecate them first.

**Comment by evilebottnawi** [comment]
Why? I really see no benefits

**Comment by evilebottnawi** [comment]
I think it would be better to focus on problems for 2.0 than break backward compatibility without benefits

**Pull request closed without merging**
