### PR TITLE
Fix semicolon duplicated at the end of LESS file

### LINKED ISSUE #11483: Prettier infinitely suggests additional " ;" to the end of less detached rulesets
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAbgQwE4EtMBGANnEgATAA6UZZAZrnEQCbkDOEAtnDABa5QA5tQC+AbhAAaEBAAOMXNDbJQObBADuABRwJlKTEQ2YAnsukFsmMAGseAZUzcAMgLjI6htnAtXbD2WsBQWQYbABXHxA4TgI4ZmZ450whcMxBOAAxCGxOTBgFIWQQTHCYCCkQXhhOIgB1fng2QLA4ez1cBXROk2KwNnMQAW9sGC0rQTyPLyiAKzYAD3tgkgBFcIh4aaJvaUDsEeKSAcrZPFg63GY+ZAAOAAY99W86q1lis7gR9HdpAEcNvBxnJ9CU2ABaKBweLxSrYOAA3Dw8bpKZITw7KLeTi4UIRLErODrTbudEzaQwQiXa68ZAAJgpVlwRGCAGEuGjomwAKyVcLeAAqhH0GN2IHQkQAklBErB7GA8PIAIIy+wwEwkbZi+YLABCfjsMEcLjcWrgIhEQA)

```sh
--parser less
```

**Input:**

```less
@variable: {
  field: something;
};
```

**Output:**

```less
@variable: {
  field: something;
}; ;

```

(If you test it out in the playground, another space + semicolon are always added, no matter how many are in the "input")

**Expected behavior:**
I would expect `prettier` to be satisfied with zero or one semicolon, not always suggest another. See [detached rulesets docs](https://lesscss.org/features/#detached-rulesets-feature).

### PR DESCRIPTION
**Pull request by mvorisek**
## Description

Fix #11483 caused by #8675 (by @fisker) which appends `raws.after` for root CSS node.

I can confirm the test is testing the problem correctly as /wo the fix, it is failing.

## Checklist

- [X] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [X] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Looks good.

Can you fix the linting problem?

**Review by fisker — COMMENTED** [review]
Thanks!

**Review by fisker — APPROVED** [review]

**Comment by fisker** [comment]
Please add a changelog entry.

**Comment by mvorisek** [comment]
changelog entry added

--

it seems every time I push the CI workflow needs to be approved manually, in GH repo there is settings like this:

image

can you please change the setting to the first option, so contributors approved once do not have to wait for the CI results again and again?

**Review by fisker — APPROVED** [review]

**Comment by mvorisek** [comment]
this PR is sitting here for two weeks, it will be great if it can be merged soon

**Review by sosukesuzuki — APPROVED** [review]

**Pull request merged**
