### PR TITLE
fix: guess line ending before preprocess

### LINKED ISSUE #4956: Yaml files with CRLF are formatted as if they use LF
**Prettier 1.14.0**
~[Playground link](#)~ – n/a as the issue is Windows-only

**Input:**
Any yaml with `CRLF` (a.k.a. `\r\n`), e.g. on a Windows laptop where git replaces `LF` with `CRLF` on checkout – see [config docs](https://help.github.com/articles/dealing-with-line-endings/#platform-windows)

**Output:**

The same yaml file, but with `LF` instead of `CRLF`

**Expected behavior:**

`CRLF` preserved, just like for files in other languages that are handled by Prettier

---

After the release of 1.14.0, I added yaml files to my project's `format` and `lint` npm scripts. All worked well on a macbook, just as it does for all other files that Prettier can deal with. However, after I executed `npm run lint` in a VSTS CI/CD pipeline and a colleague's Windows laptop, this script failed. As it turned out, Prettier replaced `CRLF` (Windows-flavoured line endings) with `LF`, which was not expected from it.

If I understand correctly, Prittier's AST printers are able to detect if the file is using `CRLF` or `LF` in the first place and preserve this choice in the output. This ended up being impossible for the yaml files because of an upstream bug (https://github.com/eemeli/yaml/issues/20), so a workaround was implemented (https://github.com/prettier/prettier/pull/4863). Here it is:

https://github.com/prettier/prettier/blob/1fe0b01bd4d547793a112718c6264bce78bb4c60/src/language-yaml/parser-yaml.js#L69-L72

Because of this transformation, Prittier's yaml printer is unable to recall the use of CRLF and produces a file with LF only. AppVeyor build passes because it seems to set `core.autocrlf=input` in it's`~/.gitconfig` (https://github.com/desktop/desktop/pull/5182#issuecomment-408877361).

Given that fixing the upstream bug may take some time, Is there any way to ‘teleport’ the knowledge about `CRLF` from `preprocess()` down to the printer? IMO this may work as a temporary solution.

Having a CI build that runs tests in  ‘`CRLF` mode’ would be also useful to avoid similar bugs in other languages in future.

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #4956 

I originally thought it worked this way, but apparently not.

- [x] I’ve added tests to confirm my change works.
- (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

cc @kachkaev

### CODE REVIEW

**Comment by kachkaev** [comment]
This should work as a fix by the look of the diff. I don't have a Windows machine near me now, but I can test your custom version of Prettier in VSTS. How urgent is that? Can this quickly jump into `1.14.2` or shall we wait for a week or so till there is a bundle of fixes?

**Comment by kachkaev** [comment]
Shame that I did not report it an hour earlier! Looks like I was writing the issue right when you were releasing 1.14.1 😅

**Comment by ikatyang** [comment]
I was writing the changelog, I should wait for this PR to release 1.14.1.. 😭

I'm not sure when should we release the next version but you could install it from GitHub after this PR merged as a temporary workaround.

**Comment by j-f1** [comment]
You could also do `1.14.2`.

**Comment by ikatyang** [comment]
OK, let's release 1.14.2, hope this is the last patch in 1.14.

**Comment by ikatyang** [comment]
--> https://github.com/prettier/prettier/releases/tag/1.14.2

**Comment by kachkaev** [comment]
Upgrading to 1.14.2 solved the issue, many thanks once again @ikatyang! 🎉

**Pull request merged**
