### PR TITLE
fix: don't add semicolon in styled components

### LINKED ISSUE #2350: styled-components formatting issues
Hi team!

~~I'm not sure that the following examples of formatting are bugs, intentional decisions or just corner cases that were skipped during development. So I just want to share them with you and get some feedback.~~

~~I understand the rationale behind prettier, so if these are not bugs but intentional, it is okay, i'd just want to know this :)~~

~~1) When css rule is one line, it is collapsed~~

~~This one is the minor one, but still not very convenient. I'm extending some component and start with one simple rule. I'll probably add more after this initial one and I don't want even one-liners to collapse. If you look [at some examples in styled-components ](https://www.styled-components.com/docs/basics#react-native), you can see that this is a common pattern for many styled components to leave template literal multiline.~~

~~2) Template literal expressions collapsed with next line~~

~~This one is a real pain. If you have an expression that takes full line in template literal and there is no semicolon at the end of the line, newline is removed and the next line is collapsed with it. This could quickly became a total mess if you have several lines of expressions like that.~~

3) Semicolon is inserted at the end of template literal if it ends with expression

This just looks like a bug.

Example:

```jsx
const RedBlock = styled.div`
  display: block;
  background-color: red;
  ${props => props.rounded && 'border-radius: 5px;'}
`;

// After formatting --->

const RedBlock = styled.div`                        
  display: block;
  background-color: red;
  ${props => props.rounded && 'border-radius: 5px;'}; // <-- notice this semicolon
`;
```

### LINKED ISSUE #2636: [styled-components] adding extra semi at the end
[Demo](https://prettier.io/playground/#%7B%22content%22%3A%22export%20const%20ButtonWrapper%20%3D%20styled.button%60%5Cn%20%20%24%7Bbase%7D%5Cn%20%20%24%7Bhover%7D%5Cn%20%20%24%7Bopaque%7D%5Cn%20%20%24%7Bblock%7D%5Cn%20%20%24%7Bactive%7D%5Cn%20%20%24%7Bdisabled%7D%5Cn%20%20%24%7Boutline%7D%5Cn%20%20%24%7Bdashed%7D%5Cn%20%20%24%7Bspacing%7D%5Cn%60%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D)

**Source** 
```
export const ButtonWrapper = styled.button`
  ${base}
  ${hover}
  ${opaque}
  ${block}
  ${active}
  ${disabled}
  ${outline}
  ${dashed}
  ${spacing}
`;
```

**Expected** 
```
export const ButtonWrapper = styled.button`
  ${base}
  ${hover}
  ${opaque}
  ${block}
  ${active}
  ${disabled}
  ${outline}
  ${dashed}
  ${spacing}
`;
```
or 
```
export const ButtonWrapper = styled.button`
  ${base} ${hover} ${opaque} ${block} ${active} ${disabled} ${outline} ${dashed} ${spacing}
`;
```

**Problem**
extra ; added to end of line after ${spacing}
```
export const ButtonWrapper = styled.button`
  ${base} ${hover} ${opaque} ${block} ${active} ${disabled} ${outline} ${dashed} ${spacing};
`;

```

### PR DESCRIPTION
**Pull request by evilebottnawi**
fixes #2350 fixes #2636

### CODE REVIEW

**Comment by duailibe** [comment]
@evilebottnawi can you merge with master to include https://github.com/prettier/prettier/commit/23cd5d44f7715d59144e19fd32f0943fc4141d8d and push into this branch again?

The preview playground is not working, and I'd like to test this PR before we merge

**Comment by evilebottnawi** [comment]
@duailibe just rebase?

**Comment by duailibe** [comment]
Either rebase or `git fetch origin master && git merge origin/master`, whatever you prefer 😄

**Comment by evilebottnawi** [comment]
@duailibe done :+1:

**Comment by duailibe** [comment]
This is the case I was thinking of:

**Prettier pr-4151**
[Playground link](https://deploy-preview-4151--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOlwEsA3AAwB0oACagEmAAcAnCR1agXgD5qLwIWCMyTUAxADMpAbn4BfWTWoAjAIZgA1gHNWAVyi4AtJCEja4gGISLVMtJAAaEGxhFoqZKFXNWAdwAK3ggeKKokEES4jiCq6MgSqliocE7KzOoacDAAyozqRFBayDDMuikguBBg8YnJTgXJzDD+6VoAtqo1SeUAVqgAHgBC6ZpZ2aptcAAyBXBddc66MIxLAEzFpeV5zI3IIGrK2NDRLAUwAOqRMAAWyAAcAAxOLBDJ5+mMeyxwjSRzTsw4ABHXREQEtVTtTpIBLdJzJNpEDZleEFLQ4ACKugg8Hm5RgqmUl1wN2QqycJVURCwaIAwhA2h09lBoP8QLpkgAVQkhWHJORyIA)

**Input:**
```jsx
styled.div`
  ${props => "color: #fff;"};
  background-color:   #FfF
`;
```

**Output:**
```jsx
styled.div`
  ${props => "color: #fff;"}
  background-color: #fff;
`;

```

**Second Output:**
```jsx
styled.div`
  ${props => "color: #fff;"} background-color: #fff
`;

```

**Comment by evilebottnawi** [comment]
@duailibe let's me time, i try to fix it in this PR :+1:

**Comment by suchipi** [comment]
@evilebottnawi friendly ping, do you think we can get this one into 1.13?

**Comment by lipis** [comment]
Just put some friendly pressure I'm adding the 1.13 milestone tag :)

**Comment by evilebottnawi** [comment]
@lipis This is a bad solution, we need search better

**Comment by lipis** [comment]
Fair enough @evilebottnawi :)

**Pull request closed without merging**
