### PR TITLE
Add Google Analytics tracking ID

### PR DESCRIPTION
**Pull request by lipis**
We all like statistics but we can also check where people are spending their time so we can improve different areas.. (mostly numbers though 😄) PM your email on [Twitter](https://twitter.com/lipis) and I'll give you access..

### CODE REVIEW

**Comment by vjeux** [comment]
This is a good idea, thanks for doing it :) vjeuxx@gmail.com for mine

**Comment by lipis** [comment]
Done! Anyone else?

**Comment by j-f1** [comment]
My email in an HTML comment below (click edit ✏️ to see it):



Thanks!

**Comment by lipis** [comment]
@j-f1 Nice one.. :)

**Comment by j-f1** [comment]
Some data from Google:

img_1713 img_1714

The page people are coming from on the React website is https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html.

**Comment by azz** [comment]
That makes intuitive sense. People coming from that blog post are more likely thinking "What is Prettier" than "How do I set up/configure it?", and you can gleam that information pretty quickly from the landing page.

**Comment by ikatyang** [comment]
Mine: ikatyang@gmail.com, thanks!

**Comment by lipis** [comment]
@ikatyang Enjoy!

**Pull request merged**
