### PR TITLE
Normalize numbers in CSS like JS

### PR DESCRIPTION
**Pull request by lydell**
Unlike JS, `1.0` is also normalized to `1`.

### CODE REVIEW

**Comment by lydell** [comment]
Yay, the tests passed when I switched postcss-values-parser to https://github.com/shellscape/postcss-values-parser/pull/36

Do we want to wait for https://github.com/shellscape/postcss-values-parser/pull/36 to be merged first?

**Comment by vjeux** [comment]
Woow, thanks for doing that :) It would be better if it was merged but if it takes too long to get it reviewed, feel free to hit the merge button :)

**Comment by vjeux** [comment]
Looks like the other PR is not being reviewed, so feel free to merge.

**Comment by gaganjakhotiya** [comment]
@lydell the updated SHA _af2c80b2bb558a6e7d61540d97f068f9fa162b38_ of _postcss-values-parser_ doesn't seem to exist. I'm unable to setup the pre-commit hook because of this.

**Comment by lydell** [comment]
@gaganjakhotiya Oops! I accidentally deleted the branch when my PR was merged :( It should be back now. Good catch!

**Pull request merged**
