### PR TITLE
tests: `scss` syntax

### PR DESCRIPTION
**Pull request by evilebottnawi**
Just many `scss` tests to make sure all work as expected. 

I would be glad to join `prettier` as contributor. I can take care of the problems associated with `css/less/scss`. I have many experience with `postcss` and his ecosystems, also i am top of contributors in `stylelint` :star:

### CODE REVIEW

**Comment by suchipi** [comment]
Sorry @evilebottnawi, I merged your import comma fix before this one, it looks like I should have done them the other way around, as there are now merge conflicts.

Could you resolve them and re-push this branch? Then I will merge it.

**Comment by lipis** [comment]
Hey @evilebottnawi :)

**Comment by evilebottnawi** [comment]
@lipis done :+1:

**Comment by lipis** [comment]
🎆

**Comment by j-f1** [comment]
@evilebottnawi Feel free to merge this PR!

(make sure you choose “Squash and merge” from the merge options — that’s the merge type we use since it keeps the commit history cleaner)

**Comment by evilebottnawi** [comment]
@j-f1 :+1:

**Pull request merged**
