### PR TITLE
Fix closure compiler type casts

### LINKED ISSUE #4799: JSDoc type cast parentheses is removed
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMIAWArlANY7AA6UOtOA9AFSPWUw6M4ACATnDER5RcwAEYQIqOOigBfHAHcC-ZTxwQ1UCOxjL8xMooCWqVDgLoAbnBzocPEjCMBbOK3aN67i5gBKjlzgACgBKCnc2ADMNHCDIYXYwA1IAcR4IIgAHdUicXSNMADoAfQBzdKzMMKooNjqYenocAHUbaFQATxwoODgAEzyIHCS4MHJdG0ijHkx2aDdamHq+ASFYiKXNpJJUiszCgoBJKCMndFRQnAAyK436pk4uGA7Mm2AAUVgeF4gjWHlPLFtmQ0hlMiFCqV+P5YIFCDtLgBeZF5AgFah0TFYkIAbg2sg2K0ENEi50wcDxiwJchAABoQBBMk5oJhkKB0Dx0goAAochCslBWX59OkgUQ8dBjfgAZUykr+pWQMAccHpf3JPBg3IlpWc6GQpNQ5PpACtMAAPABCEqlMGl6FcABk-nADWTVSA5TM4DxkGL0KIOqhoKLMjw-jBmkY+rpkAAOAAM9LDEHJzQlmT9YbgGusor4AEciNM4Nr0Lr9UhDcaQOTnEYlSr6ZgFVIAIpEbSuqvu+kwANRmMEZAAJj7EpMCrwEGcer9Wh6oqI5IAKgGBdW4LJZEA)
```sh
--parser babylon
```

JSDoc [`@type`](http://usejsdoc.org/tags-type.html) allows casting types of a reference but it requires a pair parentheses around the target reference. Prettier should not remove it.

**Input:**
```jsx
class Chunk {
    /**
	 * @returns {boolean} whether or not the Chunk will have a runtime
	 */
	hasRuntime() {
		for (const chunkGroup of this._groups) {
			// We only need to check the first one
			return (
				chunkGroup.isInitial() &&
				/** @type {Entrypoint} */ (chunkGroup).getRuntimeChunk() === this
            );
		}
		return false;
	}
}
```

**Output:**
```jsx
class Chunk {
  /**
   * @returns {boolean} whether or not the Chunk will have a runtime
   */
  hasRuntime() {
    for (const chunkGroup of this._groups) {
      // We only need to check the first one
      return (
        chunkGroup.isInitial() &&
        /** @type {Entrypoint} */ (chunkGroup.getRuntimeChunk() === this)
      );
    }
    return false;
  }
}

```

**Expected behavior:**

```js
class Chunk {
    /**
	 * @returns {boolean} whether or not the Chunk will have a runtime
	 */
	hasRuntime() {
		for (const chunkGroup of this._groups) {
			// We only need to check the first one
			return (
				chunkGroup.isInitial() &&
				/** @type {Entrypoint} */ (chunkGroup).getRuntimeChunk() === this
            );
		}
		return false;
	}
}
```

### PR DESCRIPTION
**Pull request by jridgewell**
This fixes casts when they are followed by a closing parenthesis, eg:

```js
foo(/** @type {number} */(num) + 1);
foo(/** @type {!Array} */(arrOrString).length);
```

The old code would see the `CallExpresion`'s closing `)` and assume everything belonged to the typecast up till that closing parenthesis.

This would be easier to accomplish if every AST would tell us if the expression were parenthesized. If they did, we could check that the node were parenthesized and either it or an ancestor has a typecast, stopping when we find an ancestor that is itself parenthesized.

Fixes #4799.

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
> This would be easier to accomplish if every AST would tell us if the expression were parenthesized.

Babel does this: `node.extra.parenthesized`.

**Comment by jridgewell** [comment]
> Babel does this: node.extra.parenthesized.

Yup, prettier seems to use allow using several different AST parsers.

**Comment by thorn0** [comment]
> Yup, prettier seems to use allow using several different AST parsers.

[It does](https://prettier.io/docs/en/options.html#parser), but is this change relevant for TypeScript and Flow? If not, only Babel is left.

**Comment by jridgewell** [comment]
Are the tests run with babel parser? I tried to do this directly with `node.extra.parenthesized` originally, but the tests always failed.

**Comment by thorn0** [comment]
JS tests are usually run with the 3 parsers, e.g. https://github.com/prettier/prettier/blob/master/tests/multiparser_js_html/jsfmt.spec.js

**Comment by jridgewell** [comment]
I'm not sure how to get the tests to pass when running the flow or typescript parsers, then.

**Comment by thorn0** [comment]
You can move your test case to a separate directory and make it babel-only by specifying only `babel` in `jsfmt.spec.js`.

E.g. you changed `tests/comments/closure-compiler-type-cast.js`. This test isn't run against TypeScript. See `tests/comments/jsfmt.spec.js`:
```js
run_spec(__dirname, ["flow", "babel"]);
```

**Comment by jridgewell** [comment]
Awesome, thanks for the help! I've updated to take advantage of Babel's `node.extra.parenthesized`, and it's much nicer.

**Comment by rsimha** [comment]
@vjeux @j-f1 Is this PR good to merge? And if so, any chance it can be pushed as a new release?

For context, this is the last issue that's preventing the AMP Project from adopting Prettier. See https://github.com/ampproject/amphtml/pull/21212#issuecomment-486542534 for more info.

**Comment by vjeux** [comment]
@j-f1 could you merge it assuming it's in a good shape?
@duailibe any way you could release 1.17.1 with this fix?

Thanks!

**Comment by j-f1** [comment]
Thanks for contributing!

**Comment by berrylaw** [comment]
Don’t worry I’ll be good
I won’t make you troubleshoot

「Jed Fox <notifications@github.com>」在 2019年4月27日 週六，上午1:06 寫道：

**Comment by rsimha** [comment]
@duailibe Any chance this fix can be pushed as a new release?

**Comment by rsimha** [comment]
@vjeux @duailibe Bumping this thread to see if this fix can be released anytime soon.

**Comment by j-f1** [comment]
For now you can install `prettier/prettier` to get the latest version from GitHub.

**Comment by duailibe** [comment]
@jridgewell @rsimha 

I'll cut a release today or tomorrow!

**Comment by duailibe** [comment]
1.17.1 is out

**Comment by jridgewell** [comment]
Thanks!

**Pull request merged**
