### PR TITLE
feat(html): support custom self-closing tags

### PR DESCRIPTION
**Pull request by ikatyang**
- switch to `@starptech/prettyhtml-parse` (a fork of `parse5`) for `preserveSelfClosingCustomTags `
- self-closing HTML tags won't be printed as non-self-closing tags
- fix some missing cases in #5116 

---

**Prettier pr-5117**
[Playground link](https://deploy-preview-5117--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAggIQMIHoB8IANCBAA4wCW0AzsqAIYBOTEA7gArMJ0oMBuESgBNiIAEZMGYANZwYAZTLTKUAObIYTAK5wSqmnCYwOUtQFsGyAGYMANoZIArGgA9MU2fIUNzcADKqcDb2jiDKTIZMyOHMhgCsYmRMqjAA6iIwABbIABwADCTJEIZpUmQxyXBR-MEkTHAAjtqUDaYMFlZItg56IIbmlJo6fTSqanZwAIraEPAhvSQwDOIZwtnIAExLUpR249gQ5pYxUNB1INqGACorvD2GAL6PQA)
```sh
--parser parse5
```

**Input:**
```html
<ABC/>
```

**Output:**
```html
<ABC />

```

---

- [x] I’ve added tests to confirm my change works.
- (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ikatyang** [comment]
@flxwu No, we just preserve it.

**Prettier pr-5117**
[Playground link](https://deploy-preview-5117--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4M4AEYANgIYDOFAvADohkAOj9hA9Pm1niADQgRGMTNArJQZAE6SIAdwAKUhGJRlsETOj4gARpLJgA1nBgBlRgcxQA5shiSArnH5WKcSTHn7rAWzLIAMzISN34AKwoADwAhfSMTUzIfOAAZKzhA4NCQC0k3SWQcqTcAVm1GSSsYAHVNGAALZAAOAAZ+Cog3av1GQoq4fOwM-kk4AEcHTFGvMl9-JCCQ5xA3H0w7R2WKK2sSOABFBwh4TKX+GDIdWvQG5AAmc-1MEh2AYQgfP0KoaGGQBzcABVLipFm4AL7goA)
```sh
--parser parse5
```

**Input:**
```html
<div><div class="app" /></div>
```

**Output:**
```html
<div>
  <div class="app" />
</div>

```

**Comment by flxwu** [comment]
@ikatyang but wouldn't it be better to auto-collapse self-closing tags?

**Comment by flxwu** [comment]
@ikatyang but wouldn't it be better to auto-collapse self-closing tags?

**Comment by evilebottnawi** [comment]
@flxwu it is break XHTML

**Pull request closed without merging**
