### PR TITLE
Don't format range if required pragma is missing outside range

### PR DESCRIPTION
**Pull request by josephfrazier**
Fixes https://github.com/prettier/prettier/issues/3985

`formatRange()` is only called from `formatWithCursor()`,
which already checks for the pragma.

EDIT: @JamesHenry, could you try this out and verify that it's working for you?

### CODE REVIEW

**Comment by JamesHenry** [comment]
My naive initial assumption was that the solution would be to check if the source text/file contained the pragma, and then format the range within it if appropriate... (instead of silently setting requirePragma to false regardless of user config)

WDYT?

**Comment by j-f1** [comment]
What’s the status on this? Should we fix the conflicts and merge or close it?

**Comment by josephfrazier** [comment]
Hmm, looks like the then-relevant code has since changed a decent bit. @JamesHenry, can you still reproduce the issue with the latest Prettier?

**Comment by JamesHenry** [comment]
I think my question about the decision to just set the `requirePragma` option is still outstanding, and now that range options are available in the playground (they weren't at the time of the original issue and this PR), it is easy enough to reproduce that the formatting will still _not_ occur in the range (unless the range itself includes the pragma comment):

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgOlABO3AAQAcAnOGGASzlJ31RwDcBDU3eAZxlwF4PSAVzggANCAjFq0TslBtSEAO4AFNglkoWTCFQAmYkACNSLMAGsKAZWJmqUAObIYQuOPudaMFaYcBbFmQAMxYAG09xACtOAA8AIVMLaxY-OAAZexEkEPC3EFtST1JkYxYjAE9Q6EMyexgAdX0YAAtkAA4ABnEyCE9602ISsjgiphFxcgBHQSpyHxZ-QKQXYXFPPypnVzX7B1C4AEVBCHhgsIiQGDLGvRbkACZxFxYqUN2AYQg-AJKoaHGQIJPAAVMqaHIXUyOOAAUSgBiQAGYAKwTFjQqxXUgwB4dAC+eKAA

**Comment by duailibe** [comment]
Nevermind the comment, that’s not how range works

**Comment by JamesHenry** [comment]
Excellent, thanks!

**Pull request merged**
