### PR TITLE
Restructure test files

### PR DESCRIPTION
**Pull request by fisker**
### Motivation

I want add a new directory for #10410, and I think better move everything in to `tests/`.
We may also want add unit tests later, so we can put in `tests/unit`

### Changes

Move test files.

- `tests/` -> `tests/format`
- `tests_config` -> `tests/config`
- `tests_integration` -> `tests/integration`

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by thorn0 — APPROVED** [review]
I'm okay with this change. But it's better to merge other PRs first (yours and Sosuke's) to avoid conflicts.

**Comment by brodybits** [comment]
I have to say that moving this many files around makes it harder for forks to keep up. And forks are needed due to the Prettier option philosophy.

**Comment by fisker** [comment]
@brodybits Thanks for your feedback, but I think it's nessary, we already have 3 directories for tests, adding more directories for test to the project root is bad idea IMHO.  Also this change is not that huge, your fork can easily move them.

**Review by sosukesuzuki — COMMENTED** [review]
Sorry for delay, I'm good with this change.

**Pull request merged**
