### PR TITLE
Lock closed issues and PRs after 3 months of inactivity

### PR DESCRIPTION
**Pull request by lipis**
Mostly to avoid random notifications from people "me too"ing on stuff that no one has touched in ages.

### CODE REVIEW

**Comment by j-f1** [comment]
Looks cool!

Let’s set `setLockReason: true` so it gets locked as “resolved” rather than without a reason, and limit it to issues with `only: issues`.

**Comment by lipis** [comment]
Updated

**Comment by duailibe** [comment]
I don’t think we should limit to issues. People are commenting on closed PRs when they should open new issues

**Comment by lipis** [comment]
@duailibe makes sense.. WDYT @vjeux?

Feel free to merge it..

**Comment by vjeux** [comment]
Hopefully it doesn’t spam me with locked emails (which may be worst that the occasional reply). But I’m in favor, go for it

**Comment by duailibe** [comment]
I didn't check the file before, only the comments here.

I think we should use `lockComment: false` or we'll be spammed with bot comments

**Comment by ikatyang** [comment]
I guess we could create a new label with description from `lockComment` and use `lockLabel` instead.

**Comment by lipis** [comment]
Right I didn't think of the bot comment at all.. the descriptive lock label would be better in that case.. as we might get 4K emails.. :)

Some ideas for the label name? It could be long like: `locked-due-inactivity-since-it-was-closed`

**Comment by j-f1** [comment]
`locked-due-to-age`? We could put a more detailed description in the label’s hover text (although we’re limited to 100 characters).

**Comment by duailibe** [comment]
Won't this spam the Github feed as well? Like:

image

I'd start with just locking issues and moving on and see if people are getting confused by not being able to comment

**Comment by ikatyang** [comment]
I tested it on my repo and it seems only `help wanted` and `good first issue` will appear in the feed:

image

image

**Comment by j-f1** [comment]
Does me adding `type:perf` to #4801 show up on your timelines?

**Comment by ikatyang** [comment]
No.

**Comment by duailibe** [comment]
That's cool!

I should've noticed before though.. we label issues with `lang:*` everyday 🙈

**Comment by lipis** [comment]
I'm out of the office these days.. so feel free to edit and merge with whatever you decide.

**Comment by lipis** [comment]
Per instructions I set the `lockComment: false` to avoid any surprises :)

**Comment by lipis** [comment]
Good luck!

**Comment by lipis** [comment]
I created that Label.. https://github.com/prettier/prettier/labels and ready to press the button! Any last words?

**Comment by j-f1** [comment]
“What could possibly go wrong?”

**Comment by j-f1** [comment]
Description updated.
New:
> Please open a new issue and fill out the template instead of commenting.

Old:

> Issues that haven't been active after they were closed

**Comment by lipis** [comment]
May your gods be with ya!

**Comment by lipis** [comment]
https://github.com/prettier/prettier/issues?q=label%3Alocked-due-to-inactivity+is%3Aclosed

it works.. :)

**Comment by suchipi** [comment]
Thanks everyone!!

**Pull request merged**
