### PR TITLE
Update `@babel/parser` to v7.6.3

### PR DESCRIPTION
**Pull request by fisker**
Update `@babel/parser` to ~v7.5.5~ (2019.10.9 v7.6.3)

all failure tests are fixed, they are basicly just function and variable rename ,

except this one 

https://github.com/prettier/prettier/blob/4b96097a8db7436236585eef93da4a3e8d2a53fc/tests/flow/declare_export/ES6_Default_NamedClass1.js#L11

this line fails, if I use this file from facebook/flow

~~https://github.com/facebook/flow/blob/897413ca0f910cd72b03c8b54760af61374043ad/tests/es6modules/ES6_Default_NamedClass1.js#L1-L11~~

https://github.com/facebook/flow/blob/897413ca0f910cd72b03c8b54760af61374043ad/tests/declare_export/ES6_Default_NamedClass1.js

test will pass, not sure how to fix this, can someone help? maybe it's a babel bug?

### CODE REVIEW

**Comment by duailibe** [comment]
>  if I use this file from facebook/flow [...] test will pass

I don't understand what that file has to do with our test

**Comment by fisker** [comment]
Is our file is from that? same name, similar code

**Comment by fisker** [comment]
maybe this one 

https://github.com/facebook/flow/blob/897413ca0f910cd72b03c8b54760af61374043ad/tests/declare_export/ES6_Default_NamedClass1.js

**Comment by duailibe** [comment]
> maybe this one

Yes, that's the one

**Comment by fisker** [comment]
is this related? 

https://github.com/babel/babel/pull/10220

not sure

**Comment by fisker** [comment]
babel@7.5.5 can't parse this code 

https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=true&code_lz=PQKhCgAIUgBAHATgewG4EsAmBTAzgWWUwFcAbbSAUQGUA2AfQBFsAzAQzIBd6A5NgW2yYAwqTa5cARigxYLUsgDuM4OHA4AxmMQVsAD3jJEnSDnZdIW8bkgAxZMgCS_eKUgBvSAHN0qPAEEeYn4ACgBKAC5IADtggCNsRABuSABfJLVgYEgAJWwvHQl0ZGjITjwTFiNIAAtOTnhcCKyfThriOIA6DWR-YHYNbDiHAGt-hUVgdAliPGAAVklpLPAsyGZzUk4AWn1DYyFLMQlIXBrkMkxINlJcZEgE69Q2dDE48kh0UoUNG9Oe-DYdTYKw6SB7IwmTz2JwuNziOwONLA0G6AyQyAsYjRDScYqlLzYTj-GHhKIw5yuJJAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=flow&prettier=false&targets=&version=7.5.5&externalPlugins=

https://github.com/babel/babel/pull/10220 can fix this

https://babeljs.io/repl/build/11231/#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=PQKhCgAIUgBAHATgewG4EsAmBTAzgWWUwFcAbbSAUQGUA2AfQBFsAzAQzIBd6A5NgW2yYAwqTa5cARigxYLUsgDuM4OHA4AxmMQVsAD3jJEnSDnZdIW8bkgAxZMgCS_eKUgBvSAHN0qPAEEeYn4ACgBKAC5IADtggCNsRABuSABfJLVgYEgAJWwvHQl0ZGjITjwTFiNIAAtOTnhcCKyfThriOIA6DWR-YHYNbDiHAGt-hUVgdAliPGAAVklpLPAsyGZzUk4AWn1DYyFLMQlIXBrkMkxINlJcZEgE69Q2dDE48kh0UoUNG9Oe-DYdTYKw6SB7IwmTz2JwuNziOwONLA0G6AyQyAsYjRDScYqlLzYTj-GHhKIw5yuJJAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=flow&prettier=false&targets=&version=7.5.5%2Bpr.10220&externalPlugins=

let's wait until it's fixed

**Comment by fisker** [comment]
> Why rename in tests?

new parser throws on multi consts and class names, they are not legal code

**Comment by fisker** [comment]
@evilebottnawi babel changed a lot, like this https://github.com/prettier/prettier/pull/6386/commits/018cee669c3e22d34c211df0e39b8d79d9a7a0ff (committed just now)

v7.6.2 not allow class static field `constructor` now , but v7.5.5 (this PR was trying to updated to this version before today ) not has this yet

**Comment by fisker** [comment]
Are we still going to wait for babel/babel#10220 , it has been there for about two month.

Or we disable the only failure test `declare_export/ES6_Default_NamedClass1.js` for now?

#6397 #6496 are also blocked.

@evilebottnawi @lydell

**Comment by evilebottnawi** [comment]
@fisker we can't do this, because it is breaking change for us, need wait to fix release :disappointed:

**Comment by duailibe** [comment]
The failure means if we update this we'll stop formatting code that is valid, unfortunately

**Comment by evilebottnawi** [comment]
@duailibe valid for parser, but code is not valid, nobody use this code in real life

**Comment by duailibe** [comment]
> code is not valid,  nobody use this code in real life

@evilebottnawi what do you mean?

**Comment by evilebottnawi** [comment]
@duailibe i don't think developers have invalid syntax in real code (like duplicate import/export/const name/etc)

**Comment by duailibe** [comment]
@evilebottnawi That's not what I'm talking about

This is the code that's failing https://github.com/facebook/flow/blob/897413ca0f910cd72b03c8b54760af61374043ad/tests/declare_export/ES6_Default_NamedClass1.js

**Comment by evilebottnawi** [comment]
@duailibe we need wait patch release with fix it before merge new version, i written above about it

**Comment by fisker** [comment]
update: https://github.com/babel/babel/pull/10220 is merged

**Comment by evilebottnawi** [comment]
@fisker we need patch release from them

**Comment by fisker** [comment]
@evilebottnawi yes

**Comment by RReverser** [comment]
@evilebottnawi @fisker Did anyone contact them to make it?

**Comment by evilebottnawi** [comment]
@RReverser https://github.com/babel/babel/pull/10220#issuecomment-537922638

**Comment by fisker** [comment]
v7.6.3 released, waiting for CI result

**Comment by fisker** [comment]
We are good to go

**Comment by sosukesuzuki** [comment]
I added this PR to the 1.19 milestone because #6496 that depends on this PR has already been added.

**Pull request merged**
