### PR TITLE
Build: get rid of `webpack`

### PR DESCRIPTION
**Pull request by fisker**
Looks like `postcss` can be bundled by `rollup` now.

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
circular dependency still not handle correctly by `rollup`, but better, just one class is wrong, closing for now.

**Comment by evilebottnawi** [comment]
@fisker rollup violate spec in many cases, I do not advertise webpack, but I would advise migrate on webpack in future and avoid rollup

**Comment by fisker** [comment]
I normally use `rollup` for `library`, and `webpack` for `app`.

I don't have strong opinion, I just try to avoid use two tools.

**Comment by sosukesuzuki** [comment]
@evilebottnawi Out of curiosity, could you tell me how does Rollup violate the spec?

**Comment by evilebottnawi** [comment]
@sosukesuzuki sure:
- their heuristic for deleting code - pretty much the entire reason they can generate small bundles - is flawed, because it's not safe to remove anything that can throw, which includes virtually every builtin method. doing so broke airbnb.com in IE for months, for example. (they've fixed it so they don't delete the specific cases that broke airbnb, but the flawed heuristic remains)
- rollup treeshakes too aggressively at times. when you use import * as, if you can't statically know the import names that are referenced (ie, if any reflection or dynamism is done) then you can not safely treeshake anything. Rather than throw, or leave everything untouched, rollup chose a philosophy of prioritizing small bundles over correct bundles.

from @LJHarb

+ there are a lot of bugs in plugins, because plugins is not official they often do not receive fixes in the right way

**Comment by ljharb** [comment]
Please do not quote me out of context or without my permission.

**Comment by fisker** [comment]
As expected, after upgrade postcss to v8 #9471, we can remove webpack now.

**Comment by evilebottnawi** [comment]
rollup plugins are very buggy and slow, not sure it is good idea

**Comment by fisker** [comment]
We used rollup to bundle all files except `parser-postcss.js`. Having two tools makes the build script hard to maintain. 

Let's remove it and only use `rollup` for now, we can switch to webpack completely if it's necessary, or we could try other tools like `esbuild` too.

**Review by thorn0 — APPROVED** [review]

**Comment by fisker** [comment]
Merge after #9482

**Pull request merged**
