### PR TITLE
Test generics in object methods in TypeScript

### LINKED ISSUE #5817: TypeScript generics are removed incorrectly
**Prettier 1.16.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACAEzgDMBDAVwBt9gAdKPPSiUggHgGkAaPAFQD4AFAGskebnhhjeASjx0GeWjGxwY5bA2DCeMAL4Bueoz309ILiAgYYAS2gBnZKFLZsEAO4AFVwicpSADcIWwILEAAjbFIwYTUAZQwY2ygAc2QVcjhLAAsYAFtKAHUc23gHJLA4eL8y20CygE9kcAcnSxSHOFwvaNT80mQySi7LACsHNAAhaNiE0ny4ABkUuCHSEeyQCbR4lNTKOABFcgh4dc3LJOwu7BaYRow4BzBsWxtwjDfYItCYHOQAA4AAxXdxdIrRDAtL7PbqBNaWVQAR3ItlUvVI-UGSGGoxAXXytgy2Cylgc+0OJzOa1xG3xMFIEV+BH+yAATJYVKRbJR9gBhCD5AYtKDQREgchdXhM-x4uB6PRAA)

```sh
--parser typescript
```

**Input:**
``` ts
export default {
  load<K, T>(k: K, t: T) {
  	return {k, t};
  }
}
```

**Output:**
``` ts
export default {
  load(k: K, t: T) {
    return { k, t };
  }
};
```

**Expected behavior:**
preserve TypeScript generics

### PR DESCRIPTION
**Pull request by brodybits**
Test generics in object methods in TypeScript, as proposed by @j-f1 in PR #5824 _to verify that #5817 is resolved and does not reappear in the future_

_Changes removed since they are no longer needed:_
- ~~`@typescript-eslint/typescript-estree` version `1.4.2` update in dependencies to resolve _the issue described in_ #5817~~ _- not needed since #5817 was already resolved by the newer `@typescript-eslint/typescript-estree` version in f4bcb13d4153fe48d837ea18ac026558aba5ea36 (PR #6027)_
- ~~_update `CHANGELOG.unreleased.md`_~~

- [x] I verified that this update gives me a green build on Azure Pipelines _- verified still green after my rebase_
- [x] I’ve added tests to confirm ~~my change works~~ _the recent update in f4bcb13d4153fe48d837ea18ac026558aba5ea36 resolves the issue described in #5817_.
- ~~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)~~
- ~~(If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.~~ _removed since the needed update was already applied_
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by brodybits** [comment]
> /cc @brodybits can you rebase?

Done, but only the test case remains. I already updated the description, will give some more info after I update the title.

**Comment by brodybits** [comment]
The originally proposed update is no longer needed since it is superseded by an even newer update of `@typescript-eslint/typescript-estree` in merged PR #6027. I think this means that issue #5817 is resolved and should be closed.

I think the new test case, which was authored by @j-f1 as part of PR #5824 and proposed in this PR, should be merged to verify that the resolved bug #5817 does not reappear in the future.

**Comment by duailibe** [comment]
Closes #5817

**Comment by duailibe** [comment]
Yeah I should've known that doesn't work 😝

**Comment by brodybits** [comment]
I think PR #5824 should be closed as well, since it was superseded by this proposal.

I wonder if we should have updated the changelog for #6027 (TypeScript 3.4) since it fixes the bug in #5817?

**Comment by duailibe** [comment]
@brodybits that bug is fixed since 1.16.3

**Pull request merged**
