### PR TITLE
Prettier needs an absolute path instead of relative

### PR DESCRIPTION
**Pull request by nixolas1**
Changed the relative path variable to an absolute one, to get prettier to work.

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Can someone confirm this? If it's correct, [this image](docs/assets/webstorm/file-watcher-prettier.png] need update too.

**Comment by thorn0** [comment]
@prigara Could you probably comment on this? Does this change make sense? Is `$FilePathRelativeToProjectRoot$` always relative to `$ProjectFileDir$` or can `$ProjectFileDir$` be different from the project root?

**Comment by prigara** [comment]
@thorn0 as far as I can see, they can be different in case of multi-module projects in IntelliJ IDEA. 
I'm fine with the changes - using full paths when prettier is installed globally seems to be a good idea.

**Comment by prigara** [comment]
@fisker probably it's ok to remove this screenshot completely since this setup is for older IDE versions only.

**Pull request merged**
