### PR TITLE
Add parentheses around assignment as body of arrow

### LINKED ISSUE #1320: Put parens around assignment in implicit return of arrow function
```js
(function() { return foo = bar + 2 });
() => foo = bar + 2;
```
→
```js
(function() {
  return (foo = bar + 2);
});
() => foo = bar + 2;
```

I think it would be nice if the arrow function got parens around the assignment as well:

```js
() => (foo = bar + 2);
```

Found in prettier/eslint-config-prettier#14.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22(function()%20%7B%20return%20foo%20%3D%20bar%20%2B%202%20%7D)%3B%5Cn(()%20%3D%3E%20foo%20%3D%20bar%20%2B%202)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by bakkot**
Fixes #1320.

### CODE REVIEW

**Comment by vjeux** [comment]
<3

**Comment by lourd** [comment]
🙏🏼 Any chance of a 1.1.1 or 1.2.0 release tonight or tomorrow? This was the last thing keeping me from finishing integrating Prettier into my company's project. Please and thank you!

**Comment by tschaub** [comment]
I'm curious to hear how you'll be deciding on major/minor/patch releases.  For projects using Prettier to enforce a common style, changes in formatting are breaking (e.g. if a linter is being used to ensure that code matches Prettier's output).

I understand that changes like this (and #1344) might be considered enhancements or fixes from the perspective of this project.  Just curious to hear what you would consider a breaking change.

Reading [the post](http://jlongster.com/prettier-1.0) on the 1.0 release, I assumed major versions would be coming when there were changes in formatting.

> For example, we are looking at adjusting ternaries but there will be very few changes of that nature from here on out, and when there are we will make a new major version.

Thank you for all the work on this phenomenal project!  It is a huge relief to be able to put an end to meaningless whitespace comments in code reviews.

**Comment by vjeux** [comment]
@tschaub hey, thanks for raising this. The bar for changes is now much higher, we don't want to change things that are used in a lot of places. This is a fuzzy metric but this one is pretty rare so it's okay.

The thing that sucks right now is that most of the tools in the prettier ecosystem embed their own version of prettier instead of using the one in the project. This is something that I want to change (cc @jlongster).

If all the tooling (lint, CI, editor integration, codemods...) use the version you specify in package.json, then we can release versions of prettier and you can independently upgrade on your own project whenever you feel like it.

Hopefully this gives you a better sense of how the future is going to look like. The current situation is clearly not ideal :(

**Comment by nihgwu** [comment]
This change seems a bit silly for me, see the diffs
image
image
image

**Pull request merged**
