### PR TITLE
Improve format when passing ts arrow function with return type as an argument

### LINKED ISSUE #2581: Don't break polymorphic type arguments in function which is a last breaking argument
from
```es6
const appIDs = createSelector(
  PubXURLParams.APP_IDS,
 (rawAppIDs): Array<AppID> => deserializeList(rawAppIDs),
);
```
to
```es6
const appIDs = createSelector(PubXURLParams.APP_IDS,
 (rawAppIDs): Array<
  AppID
> => deserializeList(rawAppIDs));
```
verified in playground.

### LINKED ISSUE #4070: Weird break on generic instead of putting whole function on new line
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvAFQAsBLKAcz1oFsNC4WEYKB5GanGw16TYAB0oePABMISPAAoYATwxwFlNXACUeALwA+PAAVsEAG60ZQgDxmIGY-rxcWEWgC84i5doW8AEYAVnBgMFrqOgoOVjbYtrwYPM7GwAC+OgDckukgADQgjjC00KTIoMTY5gDuJlUI5SjEFh4yBSBkMMgAZsSEpHCFgdjEYADWcDAAyhhjosgw2ACuQyByYL39g4X0g7hmxAwsxFsDa8GkaABCoxNT08RcADL0cGc7RcswGN8ATB81nNsPtkCBVOpSGBsLRkh0MDDYAB1awCZAADgADIUERBBkjRhgwQi4PsLO9Ctg4ABHZa0KmHY6nJB9c6FQYsWiLFZrUiiDgARWWEHggMKMGIgRRMjRSD+4tGtEIogAwhAWCcwVBoBSQMtBpRJU1WYN0ukgA)
```sh
--parser typescript
```

**Input:**
```tsx
export class Thing implements OtherThing {
  do: (type: Type) => Provider<Prop> = memoize((type: ObjectType): Provider<Opts> => {});
}
```

**Output:**
```tsx
export class Thing implements OtherThing {
  do: (type: Type) => Provider<Prop> = memoize((type: ObjectType): Provider<
    Opts
  > => {});
}

```

**Expected behavior:**
```tsx
export class Thing implements OtherThing {
  do: (type: Type) => Provider<Prop> = memoize(
    (type: ObjectType): Provider<Opts> => {}
  );
}

```

Same number of lines, WAY easier to read

### PR DESCRIPTION
**Pull request by kpdonn**
fixes #4070; fixes #2581

Probably should not be merged until after #4219 is merged and I have a chance to rebase since I added some test cases here that might be affected by the changes there.

### CODE REVIEW

**Comment by j-f1** [comment]
cc @duailibe @vjeux How does this look?

**Comment by vjeux** [comment]
Lgtm

**Comment by duailibe** [comment]
@kpdonn #4219 is merged. Wanna rebase?

**Comment by kpdonn** [comment]
@duailibe rebased, should be good to merge now.

**Comment by duailibe** [comment]
Thanks @kpdonn

**Pull request merged**
