### PR TITLE
Introduce 'ternary' config and extend 'arrowParens' config with 'requireForBlockBody' option

### PR DESCRIPTION
**Pull request by netoctone**
Hello,

What do you think of adding these configs in order to make prettier more flexible?

By the way, it addresses some of the wishes of prettier users (an alternative to changing eslint rules):
https://github.com/prettier/prettier-atom/issues/329
https://github.com/prettier/prettier/issues/812

Cheers,

### CODE REVIEW

**Comment by netoctone** [comment]
@j-f1 it's definitely not an option request, since it's an option implementation

**Comment by netoctone** [comment]
@evilebottnawi it's compatible with eslint rule
` 
'arrow-parens': ['error', 'as-needed', {
      requireForBlockBody: true,
    }]
`

**Comment by evilebottnawi** [comment]
@netoctone You can use prettier first and when use `eslint` for fix it, why not use this workflow?

**Comment by netoctone** [comment]
@evilebottnawi it's less performant and more convoluted. Obviously solves the issue but seems a temporary solution.

**Comment by suchipi** [comment]
We aren't interested in adding more options for things like this. The code looks  great but it's unfortunately not in line with our project goals, so I'm gonna close this PR. However we would love to receive more PRs from you in the future, but opening an issue first to discuss the proposed change before implementing it is the best approach.

**Comment by j-f1** [comment]
You might be interested in checking out #40 and [our option philosophy](https://prettier.io/docs/en/option-philosophy.html) for more information on why we try to avoid adding options.

**Pull request closed without merging**
