### PR TITLE
Stop passing `undefine` and `null` to printer

### PR DESCRIPTION
**Pull request by fisker**
## Description

Should be safe, things like hole in array should checked by printer like [we did](https://github.com/prettier/prettier/blob/5a627651ff648edd38bd0b5e667210a8a1f4e4a1/src/language-js/printer-estree-json.js#L19)

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
This potentially breaks plugins, right?

**Comment by fisker** [comment]
> This potentially breaks plugins, right?

In theory, yes.


The only case I can think, if plugin print holes in array like this

```js
function print(path) {
	if (typeof path.getName() === "number" && !path.getValue()) {
		return "null"
	}
}
```

**Comment by thorn0** [comment]
I guess we should mention that in the changelog.

**Comment by fisker** [comment]
Another possible case,

AST: `{type: "Literal", value: 0}, {type: "Literal", value: false} `

```js
function print(path, print) {
	const node = path.getValue()
	if (!node?.type) {
		return String(node)
	}

	if (node.type === "Literal") {
		return print("value")
	}
}
```

Let's only check `undefined` and `null`, that's only we need for core plugins.

**Pull request merged**
