### PR TITLE
Typescript: Keep question mark for optional computed class property

### LINKED ISSUE #6569: [Typescript] Prettier removes question mark from optional computed class property
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAjAhgJ0wF5MByPfUgbgB0owAbXNNTAMQgk2Dsz8wDaFALoB+WlH6CAjGIlSB5XAC9ScugF86IADQgIABxgBLdMlAF8EAO4AFAgjTIQuAG4RjAE10hs+XGAA1nAwAMoGAcZQAObIMPgArnB6ABYwALYMAOopxvBoEWBwoY55xq55AJ7OYCw+UWhw+DC2-tHpuMgAZrgMjXoAVmgAHgBC-kEhobjpcAAyUXDdvf0gQ8OhUdEMcACKCRDwy33JIBH4jfjOMJUGcGhg+MZGPgZPsFleMCnIABwADHo3hBGll-AZnG97k1XEs9ABHA7wVqGJwoZgAWigcDgnlxPnwcERxkJrVw7U6SB6Jz0jXSxjiiVOaC2O32hyWVJWpxguGwn0832QACY9PFcMYGFsAMIQdIdZxQaBwkAJRoAFT5aOpjQ0GiAA)
```sh
--parser typescript
```

**Input:**
```tsx
const bar = 'bar';
class Foo {
    [bar]?;
    [1]?;
    ['baz']?;
}

```

**Output:**
```tsx
const bar = "bar";
class Foo {
  [bar];
  [1]?;
  ["baz"]?;
}

```

**Expected behavior:**
Prettier should preserve ? in output. Expected output:
```tsx
const bar = "bar";

class Foo {
  [bar]?;
  [1]?;
  ["baz"]?;
}

```

This only happens when the computed property is a variable.

### PR DESCRIPTION
**Pull request by fisker**
- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

fix #6569

this is a bug from `@typescript-eslint/typescript-estree` https://github.com/typescript-eslint/typescript-eslint/issues/1019 , add a test to confirm this works

Notice: `@typescript-eslint/typescript-estree@2.3.2` requires node >=8 ,  so this PR might can't merge until prettier@2

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@fisker it is better to avoid PRs for `2` branch now, since we didn’t even start it, better fix bugs

**Comment by fisker** [comment]
@evilebottnawi How about the idea of using a fork version supports old node version, if this is OK, i will try to make it better

**Comment by sosukesuzuki** [comment]
Personally, considering the maintenance cost of the fork, it is better to hurry for major updates for us.

**Comment by evilebottnawi** [comment]
@fisker it is problem not only for `typescript`, I think we should talk about it and choose the best strategy.

**Comment by thorn0** [comment]
`?` is still lost if the key is an expression, and the AST doesn't even have the relevant info.

**Prettier pr-6601**
[Playground link](https://deploy-preview-6601--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOFOA2gMoCeAtgEYSoB0T6ATgLoD8ACgCUAbjIBfEABoQEAA4wAltEzJQ3LhADuABW4JVKdADcIigCbSQTLujABrODBpy7iqAHNkMLgFc4MgAWMAyoAOqBivCYrmBwNAZRisZRdMjg2FbumHBcMDq2HgzoyABm6Kg5MgBWmAAeAEK2Dk406AxwADLucGUVVSC1dTTuHqhwAIq+EPB9lQEgrlw5XOkwdHJwmGBcigpWcruwYRYwgcgAHAAMMocQOWG2cumHW7nGvTIAjtPwBfKGEBYAC0UDgcHMEKsXDgP0UMIK6CKJSQ5XmMhyDEU3j8C0wo3GUxmvVR-QWMHQTBO5jOyAATDIfOhFKhRgBhCAMYrpKDQT4gXw5AAqlMMaIGxn8AEkoJDYDQdnsYABBWU0dbjOY5cTiIA)
```sh
--parser typescript
```

**Input:**
```tsx
class Foo {
    [Symbol.bar]?();
}
```

**Output:**
```tsx
class Foo {
  [Symbol.bar]();
}

```

**Comment by Lodin** [comment]
@fisker, probably, [my issue](https://github.com/prettier/prettier/issues/6569#issuecomment-542888410) is connected with the one you are fixing in this PR. Could you also take a look at it? I tried it in the PR playground but the issue is still reproducible.

- [PR Playground](https://deploy-preview-6601--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEbMF5MDKAngLYBGEANgBQCUA3ADpTNiUCGaOAgpsM5kwAHAE4R4YeABNMAbTQBdAPx0+AwZnUBfZlpAAaEBCEwAlumSh2IsQHcACtYRpkIdgDcIpqQZBkR7GAA1nAwBEKBplAA5sgwIgCucIYAFjAklADqKabwaBFgcATOuabuuUSuYFy+UWhwIjD2AdEk7MgAZuyU9YYAVmgAHgBCAcGhBOwkcAAyUXCd3b0gA4MEUdGUcACKCeILSF09ySARIvUirjBEQnBoYCKmJr6iUTCZ3jApyAAcAAyGUQQeqZAJCVyiO4NdwLQwARz28GaxhcKE4AFooHA4FIcb4RHAEaYCc12K12oclid6iRTHFEtSNltdvt6UlDDB2GQPlIvsgAEwcgKmSgbADCEBIbVcUGgsJACXqABUuaijst3EkAJJQXGwAgPJ4wbi6gjXLaLY5aLRAA)

**Comment by sosukesuzuki** [comment]
@thorn0 I think this problem caused by parser side.

@Lodin I think your issue is not related to this PR. Probably, it is other problem, so we can fix your issue without updating `typescript-estree`.

**Comment by thorn0** [comment]
#6673 fixes @Lodin 's issue, but only for simple cases where the key is a simple identifier (variable). Cases where the key is a more complex expression indeed require an update of `typescript-estree` to be fixed.

**Pull request closed without merging**
