### PR TITLE
Support styled.div.attr({})`...`

### LINKED ISSUE #2605: Prettier does not format styled.div.attr({...})`...`.
For example:

``` javascript
const Button = styled.button.attr({ type: 'button' })`...`
```

### PR DESCRIPTION
**Pull request by azz**
Closes #2605

### CODE REVIEW

**Comment by vjeux** [comment]
It's annoying that there are so many ways to do it with styled. Maybe we should just toString() the tag and see if `styled` appears in there :p

**Comment by k15a** [comment]
I've created a [small list with all the ways you can create a styled-component](https://prettier.io/playground/#%7B%22content%22%3A%22import%20styled%2C%20%7B%20css%2C%20injectGlobal%20%7D%20from%20%5C%22styled-components%5C%22%3B%5Cn%5Cnconst%20Comp1%20%3D%20styled.div%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60%3B%5Cn%5Cnconst%20Comp2%20%3D%20styled.div.attrs(%7B%20className%3A%20%5C%22hello%5C%22%20%7D)%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60%3B%5Cn%5Cnconst%20Comp3%20%3D%20styled(%5C%22div%5C%22)%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60%3B%5Cn%5Cnconst%20Comp4%20%3D%20styled(%5C%22div%5C%22).attrs(%7B%20className%3A%20%5C%22hello%5C%22%20%7D)%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60%3B%5Cn%5Cnconst%20Comp5%20%3D%20Comp4.withComponent(%5C%22h1%5C%22).extend%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60%3B%5Cn%5Cnconst%20Comp6%20%3D%20Comp5.extend%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60.withComponent(%5C%22h1%5C%22).extend%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60.extend%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60%3B%5Cn%5Cnconst%20Comp7%20%3D%20styled.div%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60.extend%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60.extend%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60%3B%5Cn%5Cnconst%20snippet%20%3D%20css%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60%3B%5Cn%5CninjectGlobal%60%5Cnbackground%3Ablack%3B%5Cncolor%3Awhite%3B%5Cn%60%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D). There are still some CSS strings which aren't formatted.

@philpl Could you check if you can think of other ways we use CSS in a template string?

**Comment by philpl** [comment]
@k15a I think additionally to that, all the nested cases are a bit wonky. I have seen an issue for this somewhere, but I haven't checked them all yet.

**Comment by azz** [comment]
Note to future self: maybe we can share some code with `stylelint-processor-styled-components`to detect.

https://github.com/styled-components/stylelint-processor-styled-components/blob/master/src/utils/styled.js

**Pull request merged**
