### PR TITLE
Backport "Support TS4.9 `satisfies` operator (#13764)"

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Backports #13381 and #13733
This is a first step of backporting `satisfies` (https://github.com/prettier/prettier/pull/13764#issuecomment-1296871186)

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
I'll investigate why CI is failing...

**Comment by fisker** [comment]
Should this diff empty? https://github.com/prettier/prettier/compare/next...sosukesuzuki:prettier:backport-satisfies-2.diff

**Comment by fisker** [comment]
Because `next` not rebased?

**Comment by sosukesuzuki** [comment]
> Shouldn't this diff be empty?

@fisker Why?

**Comment by sosukesuzuki** [comment]
> Because next not rebased?

Sorry, I'm not sure what you mean. How should we do on Git/GitHub for backporting?

**Comment by ngregory-rbi** [comment]
Hello :) Please merge this in if and when you can :)

**Comment by fisker** [comment]
@sosukesuzuki You changed this line here, right? https://github.com/prettier/prettier/pull/9583/commits/cccedf4aa8bbe4fa08d0815634c943be3fce71ad#diff-80beade8c542966a1f813a08f54e879711e84fd32d2a97fd9c28a7885498db38L356

**Comment by sosukesuzuki** [comment]
> @sosukesuzuki You changed this line in this PR, right? [cccedf4 (#9583)](https://github.com/prettier/prettier/pull/9583/commits/cccedf4aa8bbe4fa08d0815634c943be3fce71ad#diff-80beade8c542966a1f813a08f54e879711e84fd32d2a97fd9c28a7885498db38L356)

Yes, I forgot to fix this in the original PR.

**Comment by fisker** [comment]
Can you commit this change to `next`?

**Comment by sosukesuzuki** [comment]
Yes

**Comment by ngregory-rbi** [comment]
thanks for the merge :) just curious though, will this be included in a new mainline release `2.x.x` soon?

**Pull request merged**
