### PR TITLE
Add husky, lint-staged for SVG files

### PR DESCRIPTION
**Pull request by lipis**
In order to force the new SVG files to be formatted with SVGO before commiting.

### CODE REVIEW

**Comment by lipis** [comment]
I was also in doubt if that would work, but it works as is.

screen shot 2018-02-21 at 16 32 44

**Comment by azz** [comment]
Is svgo idempotent? Feels a bit weird adding commit hook for files that aren't really ever updated.

**Comment by j-f1** [comment]
Given the rate that we change SVGs, it would probably be easier to ask contributors to run SVGO after they open PRs.

**Comment by lipis** [comment]
Yeah.. maybe we don't need it.

**Pull request closed without merging**
