### PR TITLE
Print declare for TSInterfaceDeclaration

### LINKED ISSUE #2567: "declare" keyword for typescript interface is remove by prettier
source:
```ts
declare interface Dictionary<T> {
    [index: string]: T
}

declare interface NDictionary<T> {
    [index: number]: T
}
```

prettier output: 
```ts
interface Dictionary<T> {
    [index: string]: T
}

interface NDictionary<T> {
    [index: number]: T
}
```

the expected output should be the same as source.

### PR DESCRIPTION
**Pull request by existentialism**
Fixes #2567.

### CODE REVIEW

**Comment by azz** [comment]
Looks like there's an obsolete snapshot?

**Comment by azz** [comment]
You might have forgot to check in `declare_interface.ts`

**Comment by existentialism** [comment]
@azz lol yep

**Comment by azz** [comment]
Thanks for the fix!

**Comment by e-cloud** [comment]
thanks

**Pull request merged**
