### PR TITLE
Refactor: faster levenshtein

### PR DESCRIPTION
**Pull request by ka-weihe**
## Description
This PR changes the levensthein distance package from `leven` to `fastest-levenshtein`. [leven](https://github.com/sindresorhus/leven) is one of the slowest levenshtein packages out there and the author is trying to deceive people with shitty benchmarks where he is only comparing it slower packages. Please consider using  [fastest-levenshtein]( https://github.com/ka-weihe/fastest-levenshtein) instead which is 10x faster and much higher quality. 

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
👎 for this, 

1. I have no doubt this lib is the fastest public package, but I don't like something called "fastest", how do you know there will no faster one?
2. > the author is trying to deceive people with shitty benchmarks where he is only comparing it slower packages

	That's rude to say that as the owner of 'fastest-levenshtein'.

Similar project `fast-cartesian`, it claim it's fastest, when I [question it](https://github.com/ehmicky/fast-cartesian/issues/2), he just copied my faster algorithm... WTF!

**Comment by ka-weihe** [comment]
> I have no doubt this lib is the fastest public package, but I don't like something called "fastest", how do you know there will no faster one?

@fisker I will not claim that my package is the fastest one unless it actually is. Don't worry, I will make it very clear that the package is not the fastest, if I find out that it is not.

> the author is trying to deceive people with shitty benchmarks where he is only comparing it slower packages.

It is absolutely not rude. His benchmarks are a special case where his implementation skips the main part of the algorithm completely - you can have a look yourself. That is the same as benchmarking a big heavy function with a special case where it returns from an if-statement right in the beginning. That is just deceiving. He is also only comparing it to slower packages, and I have opened a PR to update his benchmarks by adding other packages, but he ignores... probably because it is much slower. 

> Similar project fast-cartesian, it claim it's fastest, when I question it, he just copied my faster algorithm... WTF!

Not okay of him to copy your code, but lets imagine he did not. Would you prefer that he kept saying that his package was the fastest knowing that your package is faster? ... and would you would you prefer that people kept using his package instead of yours, because he was lying?

**Comment by fisker** [comment]
>  would you prefer that people kept using his package instead of yours, despite him lying?

Imagine `leven` package is that package, imagine that "people" is "babel", he already give you the answer.

**Comment by ka-weihe** [comment]
Yes? Babel changed away from leven?

**Comment by fisker** [comment]
I mean the answer is NO.

**Comment by ka-weihe** [comment]
No to what? I'm guessing no to `"would you prefer that he kept claiming that his package is the fastest knowing that your package is faster?"`, but not sure. In that case, I think we agree

**Comment by fisker** [comment]
Yes, answer to that, I quoted it above my comment.

**Comment by fisker** [comment]
Can you open another PR for this, stop saying how `leven` is slow, just say how good is your package.

I think this is the right way to do.

I'm strongly against the `fastest` term in the package name, I won't approve it, but if other maintainers okay will it, I won't block it.

This one is not going to get approved.

**Comment by ka-weihe** [comment]
Okay... but I don't get what is wrong with saying leven is slow, when it is. It is just facts.

**Comment by fisker** [comment]
If you don't get it, I have to say we are different people.

**Comment by ka-weihe** [comment]
You do you. https://github.com/prettier/prettier/pull/9951

**Pull request closed without merging**
