### PR TITLE
Force `else` to break before anything inside it (fixes #616)

### LINKED ISSUE #616: Braceless if + return + object is not stable
```js
function f() {
  if (position)
    return {name: pair};
  else
    return {name: pair.substring(0, position), value: pair.substring(position + 1)};
}
```

turns into

```js
function f() {
  if (position) return { name: pair };
  else return {
      name: pair.substring(0, position),
      value: pair.substring(position + 1)
    };
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20f()%20%7B%5Cn%20%20if%20(position)%5Cn%20%20%20%20return%20%7Bname%3A%20pair%7D%3B%5Cn%20%20else%5Cn%20%20%20%20return%20%7Bname%3A%20pair.substring(0%2C%20position)%2C%20value%3A%20pair.substring(position%20%2B%201)%7D%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

which then turns into

```js
function f() {
  if (position)
    return { name: pair };
  else
    return {
      name: pair.substring(0, position),
      value: pair.substring(position + 1)
    };
}
```

Notice that return are now indented whereas before they were on the same line.

### PR DESCRIPTION
**Pull request by jlongster**
This is a more appropriate fix than #680. The problem is described more in https://github.com/prettier/prettier/pull/680#issuecomment-283103882. The only solution I can think of is to be very careful when objects are expanded. They can be naturally wrapped in the first pass, but the second one will see hard breaks and break everything above it. For the most part, that behavior is identical, but there are a few cases like this one where it wasn't breaking the code around it first.

This changes that and creates a new group that will break before the object breaks. That will force it to add the newline and stabilizes the output.

### CODE REVIEW

**Comment by vjeux** [comment]
<3

Thanks for looking into it!

**Comment by jlongster** [comment]
No problem!

Just realized the `if` part is now unstable, whoops. Need to play with this a little bit more.

**Comment by jlongster** [comment]
So this is the only way to fix it. We need to create separate groups for the `if` and `else` parts so that they can break separately. It's the only way I can think to make the object expansion match in both places.

The core problem is the `conditionalGroup` which suppressed the hardline. It's a pattern we need to avoid, unfortunately. Suppressing that hard line means the measurer won't break the if/else expression but will break things inside of it.

I think this should be OK in real-world code. Hopefully it doesn't change too much code but I think it's pretty rare to mix bracket and no-bracket styles.

**Comment by vjeux** [comment]
One less conditional group <3

I do think that it's rare enough to have both use a different bracket/no-bracket that we shouldn't support this use case.

**Pull request merged**
