### PR TITLE
Fix Travis production builds

### PR DESCRIPTION
**Pull request by lydell**
Context: https://github.com/prettier/prettier/pull/2930#issuecomment-333029192

> Unrelated question: our CI's `NODE_ENV=production job` is always failed, what does it want to test for?

### CODE REVIEW

**Comment by azz** [comment]
Didn't seem to work :/

```
7.82s$ yarn install --production=false
yarn install v1.1.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "ajv-keywords@1.5.1" has unmet peer dependency "ajv@>=4.10.0".
[5/5] Building fresh packages...
0.85s$ if [ "${NODE_ENV}" = "production" ]; then yarn build; fi
yarn run v1.1.0
$ node ./scripts/build/build.js
module.js:327
    throw err;
    ^
Error: Cannot find module 'shelljs'
```

**Comment by lydell** [comment]
Should we remove the `allow_failures` failures thing? Why is it even there?

**Comment by lydell** [comment]
```
❯ git show 532ac0d3f
commit 532ac0d3f8931f1c272ae55453bfa64a3f68db5f
Author: Joseph Frazier <1212jtraceur@gmail.com>
Date:   2017-06-17 19:37:51 -0400

    Build/test dist/ on Travis (#2176)
    
    This helps us keep track of whether or not the dist/ build actually
    works (see https://github.com/prettier/prettier/pull/2174). Note that
    the dist/ jobs are allowed to fail, and do not affect overall build
    time, so they shouldn't slow anything down (see
    https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/).
```

**Comment by lydell** [comment]
Ok, so it’s all about speed:

```
Ran for 5 min 24 sec
Total time 22 min 23 sec 
```

Pros: Travis marks PR as passing after 5 mins
Cons: We might miss that the production build is failing

**Comment by ikatyang** [comment]
Aren't they parallel testing?

**Comment by azz** [comment]
Can we run _just_ on production build?

**Comment by ikatyang** [comment]
The actual test time should be the longest one.

image

**Comment by lydell** [comment]
screenshot from 2017-09-29 09-13-44

Seems like not allowing failures would only add ~1 minute of build time. So I’m going to remove the `allow_failures` thing now.

**Pull request merged**
