### PR TITLE
Fix config file finding when using stdin

### LINKED ISSUE #2689: config file not used with stdin
Vim users that are using neoformat for prettier integration use the `--stdin` option which causes the config not to be picked up.

When using stdin `filePath` is the working directory [here](https://github.com/prettier/prettier/blob/master/src/resolve-config.js#L12) making `fileDir` one level up from where it needs to be.

### PR DESCRIPTION
**Pull request by lydell**
Fixes #2689

### CODE REVIEW

**Comment by lydell** [comment]
@azz As far as I can tell this is how you are supposed to use cosmiconfig. It doesn't break any tests. What do you think? See also how `resolveConfigFile` already works – it passes `filePath` as-is, without any `path.dirname` stuff.

**Comment by azz** [comment]
Yep - fix is good. Can't remember why I did dirname.

**Comment by azz** [comment]
Oh, I remember, it was an attempt to achieve a better caching profile for repeated calls to cosmiconfig. I tested it and it didn't offer any improvements so it is fine to remove.

**Comment by vjeux** [comment]
I released 1.6.1 with this fix, thanks for getting it up so quickly :)

**Pull request merged**
