### PR TITLE
Remove useless escapes in tagged template literals

### LINKED ISSUE #16542: Remove useless escapes in untagged template literals
**Prettier 3.3.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBnA3AHSm0wF5MADffAQ3IKNM3xCuud0xABoQIAHGAEto2ZKGoAnCRADuABUkJRKaqhnUAnqJ4AjCdTABrDAGVqAWzgAZQVDjIAZquxxd+o6b4HbAc2QwJAFdXEBdzQX8gkLgADz44CUFLWFUAFQSoSUE4ZSdUFx5sX3QARUCIeEdnEIArbBiTYrgyivskPIKQAEdy+DlpPmUQamwAWjs4ABMp7hAA6kFUXwBhCHNzamRh1FRZoqgfdABBGADBHUC+hJs7KvyQgAsYc1QAdQfBeGwvMDgTJU+ggAbp8NFswNhtCAgcEAJJQaawExgRICI4IkwwDToO6dPjSFyvfR8Lb4nIJIH2Hi2FwSGD9ag+Da4kJeCS0rY6ag6OC7Hj42wwV6CSYwB7IAAcAAYeBI4D1BHKGUzNu1qjwYNzhaLxUgAEw8QIuVLc3LqkBwcw8ybTSZWagHQKMuAAMQgEg2p18W2olwgIAAvgGgA)

```sh
--parser babel
```

**Input:**

```jsx
let s;
s = `\a`;
s = "\a"; 
```

**Output:**

```jsx
let s;
s = `\a`;
s = "a";

```

**Expected output:**

```jsx
let s;
s = `a`;
s = "a";
```

**Why?**

Prettier already removes useless escapes in regular strings.
While it is not safe to remove useless escapes in tagged template literals, it seems safe to me to do so in untagged template literals.
For consistency with regular strings, Prettier could remove them.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #16542

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
I'm not sure about this, removing escape in string literal already cause confusing.

Anyway if we decide to do this, quotes should be able to unesape too.

**Comment by sosukesuzuki** [comment]
> I'm not sure about this, removing escape in string literal already cause confusing.

The main reason I'm working on this is for consistency of escaping between string literals and template literals: if this escaping is confusing, then it should be removed from string literals as well.

**Comment by sosukesuzuki** [comment]
> Anyway if we decide to do this, quotes should be able to unesape too.

You are right, thank you

**Comment by fisker** [comment]
> if this escaping is confusing, then it should be removed from string literals as well.

I didn't mean escaping is confusing, I mean removing `\` is confusing. Eg https://github.com/prettier/prettier/issues/2789. Stricterly that's really a linter job.

I don't think we removes `\` in RegexpLiteral now, should we do that too?

**Comment by fisker** [comment]
BTW, the title should be "tagged" -> "untagged"

**Comment by fisker** [comment]
How about we do the opposite, stop removing `\` in string literal and let [`no-useless-escape`](https://eslint.org/docs/latest/rules/no-useless-escape) do his job? It not really a breaking change I guess.

**Comment by sosukesuzuki** [comment]
I was just thinking the same thing. Then maybe we should eventually change the public API `makeString` (perhaps in v4)

**Comment by sosukesuzuki** [comment]
I close this for now

**Pull request closed without merging**
