### PR TITLE
Improve `printer-html.js` readability

### PR DESCRIPTION
**Pull request by wafuwafu13**
## Description

Here is too nested so I refactor it.
https://github.com/prettier/prettier/blob/a547330ca97277037d10b60ff5e6b9c3c5cdca1f/src/language-html/printer-html.js#L279-L283

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Looks good, but there are still too many ternaries, can you try to rewrite them? Maybe even extract to a single file.

**Review by sosukesuzuki — COMMENTED** [review]
Looks good!  How about you extract to a function like the following?

```js
function printElement(path, print, options) {
  const node = path.getValue();
  if (shouldPreserveContent(node, options)) {
    return [
      printOpeningTagPrefix(node, options),
      group(printOpeningTag(path, options, print)),
      ...replaceTextEndOfLine(getNodeContent(node, options)),
      ...printClosingTag(node, options),
      printClosingTagSuffix(node, options),
    ];
  }
  /**
   * do not break:
   *
   *     <div>{{
   *         ~
   *       interpolation
   *     }}</div>
   *            ~
   *
   * exception: break if the opening tag breaks
   *
   *     <div
   *       long
   *           ~
   *       >{{
   *         interpolation
   *       }}</div
   *              ~
   *     >
   */
  const shouldHugContent =
    node.children.length === 1 &&
    node.firstChild.type === "interpolation" &&
    node.firstChild.isLeadingSpaceSensitive &&
    !node.firstChild.hasLeadingSpaces &&
    node.lastChild.isTrailingSpaceSensitive &&
    !node.lastChild.hasTrailingSpaces;
  const attrGroupId = Symbol("element-attr-group-id");
  const printTag = (doc) =>
    group([
      group(printOpeningTag(path, options, print), { id: attrGroupId }),
      doc,
      printClosingTag(node, options),
    ]);
  if (node.children.length === 0) {
    return printTag(
      node.hasDanglingSpaces && node.isDanglingSpaceSensitive ? line : ""
    );
  }
  return printTag([
    forceBreakContent(node) ? breakParent : "",
    ((childrenDoc) =>
      shouldHugContent
        ? indentIfBreak(childrenDoc, { groupId: attrGroupId })
        : (isScriptLikeTag(node) || isVueCustomBlock(node, options)) &&
          node.parent.type === "root" &&
          options.parser === "vue" &&
          !options.vueIndentScriptAndStyle
        ? childrenDoc
        : indent(childrenDoc))([
      shouldHugContent
        ? ifBreak(softline, "", { groupId: attrGroupId })
        : node.firstChild.hasLeadingSpaces &&
          node.firstChild.isLeadingSpaceSensitive
        ? line
        : node.firstChild.type === "text" &&
          node.isWhitespaceSensitive &&
          node.isIndentationSensitive
        ? dedentToRoot(softline)
        : softline,
      printChildren(path, options, print),
    ]),
    (
      node.next
        ? needsToBorrowPrevClosingTagEndMarker(node.next)
        : needsToBorrowLastChildClosingTagEndMarker(node.parent)
    )
      ? node.lastChild.hasTrailingSpaces &&
        node.lastChild.isTrailingSpaceSensitive
        ? " "
        : ""
      : shouldHugContent
      ? ifBreak(softline, "", { groupId: attrGroupId })
      : node.lastChild.hasTrailingSpaces &&
        node.lastChild.isTrailingSpaceSensitive
      ? line
      : (node.lastChild.type === "comment" ||
          (node.lastChild.type === "text" &&
            node.isWhitespaceSensitive &&
            node.isIndentationSensitive)) &&
        new RegExp(
          `\\n[\\t ]{${
            options.tabWidth *
            countParents(
              path,
              (node) => node.parent && node.parent.type !== "root"
            )
          }}$`
        ).test(node.lastChild.value)
      ? /**
         *     <div>
         *       <pre>
         *         something
         *       </pre>
         *            ~
         *     </div>
         */
        ""
      : softline,
  ]);
}
```

**Comment by sosukesuzuki** [comment]
> but there are still too many ternaries, can you try to rewrite them?

Reviewing large diffs is hard, so for this PR I personally think it's enough to delete the largest ternary

**Comment by wafuwafu13** [comment]
>How about you extract to a function like the following?

Good Idea, so I've adopted it. (Changed `printElement(path, print, options)` to `printElement(path, options, print)`) https://github.com/prettier/prettier/pull/11425/commits/9d32fa3b6bf39537d1bee7ddd8a16c491200a764

I also want to reduce ternarie in other PRs in stages!

**Review by sosukesuzuki — APPROVED** [review]
LGTM

**Comment by sosukesuzuki** [comment]
@fisker Are you okay with merging this?

**Review by fisker — APPROVED** [review]

**Comment by sosukesuzuki** [comment]
Thanks for this!

**Pull request merged**
