### PR TITLE
chore: tweak azure-pipelines.yml

### PR DESCRIPTION
**Pull request by ikatyang**
- add missing AST_COMPARE
- test on Node 4/10

---

- I’ve added tests to confirm my change works.
- (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by j-f1** [comment]
Can you move the new files to a `.azure-pipelines` directory?

**Comment by kachkaev** [comment]
Can there be two azure pipelines with tests? One with `git config --global core.autocrlf true` (checks out files with CRLF by default) and `git config --global core.autocrlf false` (checks out files as is).

If gitattributes are configured correctly, that should not affect tests.

**Comment by j-f1** [comment]
Netlify is segfaulting :/

**Comment by ikatyang** [comment]
@kachkaev I'd like to use `eol=lf` in #5494 and add another test flag `TEST_CRLF` to test CRLF by replacing LF with CRLF before formatting. We shouldn't need to configure global settings and we should be able to test CRLF locally even if it's on LF system (via `TEST_CRLF`).

@j-f1 It looks like a random error, I've rebuilt it and it's green now.

I'm going to merge this PR now since it's only for tweaking the current settings, CRLF should be handled in #5494.

**Comment by kachkaev** [comment]
> We shouldn't need to configure global settings and we should be able to test CRLF locally even if it's on LF system (via TEST_CRLF).

Testing on Windows machines with globally configured CRLF and LF in git is what I meant. This can be useful because Windows folks have different preferencess and all of them should be able to contribute to Prettier without problems of running local tests. By default, git’s core.autocrlf is true, but some devs set it to false, e.g. create-react-app contribution guidelines [recommend doing so](https://github.com/facebook/create-react-app/blob/master/CONTRIBUTING.md#line-endings).

I did not know Azure pipelines had a flag for that, interesting!

**Comment by kachkaev** [comment]
Running tests on a Windows machine with LF ia different than doing this on Linux, because on Windows [`os.EOL`](
https://nodejs.org/api/os.html#os_os_eol) is CRLF regardless of how git is configured. Some modules refer to this value and this can affect what Prettier generates in the end.

**Comment by ikatyang** [comment]
@kachkaev Can you move your comments to #5494? It should be the better place for CRLF discussion.

**Comment by ikatyang** [comment]
(`TEST_CRLF` is a new flag I added in our `run_spec.js`. 😅)

**Pull request merged**
