### PR TITLE
Simplify babel parser

### PR DESCRIPTION
**Pull request by fisker**
## Description

Use `optionsCombinations` instead of `pluginCombinations`, makes logic easier to understand.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
Kind of not obvious that this is a simplification. It simplifies some lines of code and makes other ones less simple. The net effect seems to be zero.

**Comment by fisker** [comment]
Yes this not simplified too much, but easier to pass different parse options, main reason behind this is https://github.com/prettier/prettier/issues/10406, I remember some where mentioned `eslint` plugin should be the first one in `plugins`(I haven't test, and not sure), then I was thinking previous version should be hard to add some plugin prefer the plugins list, but in current implement, it's very easy.

```js
const parseEslint = createParse("parse", {...parseOptions, plugins: ['eslint', ....parseOptions.plugins]});
```

Same thing, if we still keep `json` parser in this file

```js
const parseJson = createParse('parseExpression', {ranges: true, tokens: true});
```

The old version can't do this.

**Comment by brodybits** [comment]
> previous version

By "previous version" and "old version" do you mean "prettier-stable" in `main` or do you mean something else?

> but in current implement, it's very easy.
> 
> ```js
> const parseEslint = createParse("parse", {...parseOptions, plugins: ['eslint', ....parseOptions.plugins]});
> ```

Wow that would be awesome. Can you maybe show this in a PR?

**Comment by fisker** [comment]
> By "previous version" and "old version" do you mean "prettier-stable" in main or do you mean something else?

No, old versiob of `createParse` function, the deleted code in this PR.

> Can you maybe show this in a PR?

`appendPlugins` function is doing this.

**Comment by fisker** [comment]
@brodybits This is internal change, no effect to the public api,  some part  in this function is just old, I've done several changes to make it clear, it was hard to understand what happened in the parsing process before.

**Review by thorn0 — APPROVED** [review]

**Pull request merged**
