### PR TITLE
Use setlocal in all vim examples

### PR DESCRIPTION
**Pull request by dkarter**

### CODE REVIEW

**Comment by lydell** [comment]
Oh, Vim. Requires ten different collaborators to get it right.

**Comment by jlongster** [comment]
Can you explain the difference? I don't know vim!

**Comment by dkarter** [comment]
@jlongster sure. The short version: `setlocal` applies the setting only for the current buffer or window.

The slightly longer version:
When Vim detects a new file type using the auto-command (think of it as an editor event listener), it will set the `formatprg` globally for all files when using `set` and only on the current file buffer when using `setlocal`. Since we don't want files that are not JavaScript to have their `formatprg` overwritten (e.g. Elm getting prettier as the format program instead of `elm-format`) we prefer `setlocal`.

**Comment by josephfrazier** [comment]
(this fixes https://github.com/prettier/prettier/issues/439)

**Comment by vjeux** [comment]
I have no idea about vim so I'll trust you to make sure it's a good change!

**Pull request merged**
