### PR TITLE
Fix `hasFlowShorthandAnnotationComment` check

### PR DESCRIPTION
**Pull request by ukyo**
Check node.trailingComments.length in hasFlowShorthandAnnotationComment.

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by j-f1** [comment]
Thank you for opening a PR, @ukyo! Can you add a test for this scenario to make sure there isn’t a regression for this in the future?

**Comment by ukyo** [comment]
Hi @j-f1 , I would like to add the following test. Where should I put it? I can't find [custom parser api](https://prettier.io/docs/en/api.html#custom-parser-api) tests.

```js
const prettier = require("prettier/local");
const traverse = require("@babel/traverse").default;

test("replace CallExpression", () => {
  expect(
    prettier.format("a(x)", {
      parser(text, { babylon }) {
        const ast = babylon(text);
        traverse(ast, {
          CallExpression(path) {
            if (path.node.callee.name === "a") {
              path.replaceWithSourceString("b(y)");
            }
          }
        });
        return ast;
      }
    })
  ).toEqual("b(y);\n");
});

```

**Comment by duailibe** [comment]
@ukyo there are a couple of tests already: https://github.com/prettier/prettier/blob/master/tests_integration/__tests__/parser-api.js

**Review by fisker — APPROVED** [review]
I'm sure you already handled your case, but I think we can add this condition to prevent it happen to our users use the custom parser api.

Tests added, condition changed a little bit to make linter happy.

**Pull request merged**
