### PR TITLE
Add checklist for making a release

### PR DESCRIPTION
**Pull request by lipis**
Not sure about the actual filename or the contents.. but the idea is that the contents could be copied into the release issue ticket, for making sure that everything is checked.. WDYT?

### CODE REVIEW

**Comment by azz** [comment]
I'd much rather automate it with https://github.com/sindresorhus/np

**Comment by j-f1** [comment]
`np` won’t post to Twitter or write the blog post @azz.

**Comment by azz** [comment]
Twitter isn't the hard part :P

**Comment by lipis** [comment]
Or update CHANGELOG :) Even if it will be automated with `np` we can update the checklist with that step and remove the ones that it replaces..

**Comment by azz** [comment]
I think we should delete CHANGELOG. It doesn't add any value.

**Comment by azz** [comment]
Anywho the checklist for this release was:

1. Run on other projects (in this case I did `react`, `vue-instantsearch` and `gitlabhq`)
1. Write release notes
1. Complete all milestone items, close milestone
1. Merge release notes
1. Checkout `master`
1. Bump version in `package.json`
1. Update `CHANGELOG.md`
1. Run `yarn test_integration -u` to update snapshots (new parsers, `getSupportInfo`)
1. Commit
1. Run `yarn build`
1. Run `yarn test:dist`
1. `cd dist`
1. (Wasn't done) Check built package (#2955)
1. `npm publish`
1. `npm install prettier@latest`, do smoke tests on CLI and API (forgot this time, did this after the release 😞)
1. Push release commit
1. Create a GitHub release to tag `master`
1. Wait for release notes to deploy
1. Check blog post
1. Tweet
1. Create a new branch
1. Bump own `prettier` dependency (this will update the playground)
1. `yarn lint --fix; yarn lint-docs --fix`
1. Commit, PR, Merge

Then...

1. Monitor Twitter/GitHub for any immediate issues
1. Panic
1. Fix immediate issue
1. Repeat steps 5-16 above
1. Drink 🍷 while watching Parks and Rec
1. Write a list
1. Go to bed, it's 2:30am

**Comment by lipis** [comment]
The `2. Panic` is the best one :) Next time.. use the 🍷 while monitoring Twitter/GitHub :)

**Comment by azz** [comment]
I poured the 🍷 too early and I could smell it while I was fixing the release issue, it was very distracting because it is good 🍷. Order of the steps is important.

**Comment by duailibe** [comment]
Yeah a checklist should be a temporary thing, we should automate it entirely..

React team is doing something in that direction, see https://github.com/facebook/react/pull/11223 for inspiration

**Comment by azz** [comment]
Moved checklist to wiki https://github.com/prettier/prettier/wiki/Release-Checklist

**Comment by lipis** [comment]
Nice.. Added some links there in the checklist.. We can easily then copy paste this checklist into one issue before releasing with the `- [ ]` for the check boxes!

**Comment by azz** [comment]
Wouldn't that just add another item to the checklist? 😉

**Comment by lipis** [comment]
@azz Damn....

giphy

**Pull request closed without merging**
