### PR TITLE
Version 3.0

### PR DESCRIPTION
**Pull request by fisker**
Breaking changes in version 3.0.

Like #6773, use next branch.

#### Try locally:

```console
yarn add prettier/prettier#next --dev

# OR

yarn add prettier@next --dev
```

You can use `import` instead of `require()`

```diff
- const prettier = require("prettier");
+ import * as prettier from "prettier";
```

**✨[Try the playground for this PR](https://deploy-preview-9583--prettier.netlify.app/playground/)✨**

[Docs](https://deploy-preview-9583--prettier.netlify.app/docs/en/next/)

### CODE REVIEW

**Comment by brodybits** [comment]
Hi is there anything we can do to help get a new release with the PostCSS 8 update?

PostCSS pre-8.0 will no longer be supported: https://github.com/postcss/postcss/issues/1574#issuecomment-859226586

Thanks in advance.

**Comment by fisker** [comment]
> Hi is there anything we can do to help get a new release with the PostCSS 8 update?

We don't have a plan yet.

**Comment by sosukesuzuki** [comment]
rollup-plugin-commonjs may be renaming classes since v19...?

**Comment by sosukesuzuki** [comment]
Upgrading postcss-values-parser may help to avoid this problem

**Comment by fisker** [comment]
@sosukesuzuki I was thinking fix those inline `require() `s and add node.js 10 support back, then merge this into main branch. WDYT?

**Comment by liuxingbaoyu** [comment]
https://github.com/babel/babel/pull/14766
Maybe you want to do the same to avoid running CI repeatedly, queuing.

**Comment by fisker** [comment]
@sosukesuzuki Let's merge this into main?

**Comment by sosukesuzuki** [comment]
I don't think we can release it right away since we don't have a release blog and VSCode Ext yet, is that ok?

**Comment by fisker** [comment]
Not release, just merge, seems unnecessary to have two branch for dev, we won't make big changes for v3.

**Comment by sosukesuzuki** [comment]
Okay, go ahead!

**Comment by fisker** [comment]
🎉

**Comment by sosukesuzuki** [comment]
:tada: :tada: :tada:

**Pull request merged**
