### PR TITLE
Build: remove `doc.js`

### PR DESCRIPTION
**Pull request by fisker**
Why are we building this file? It's not used anywhere.

Should use `const {doc} = require("prettier")` instead of `const doc = require("prettier/doc")`

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
After a little digging, it was add on purpose...

https://github.com/prettier/prettier/pull/6009#issuecomment-476282558

**Comment by fisker** [comment]
@rattrayalex Are you using it?

**Comment by evilebottnawi** [comment]
@fisker some plugins also can you it, for me it is breaking change

**Comment by fisker** [comment]
Seems plugins actually using this, close for now.

**Pull request closed without merging**
