### PR TITLE
Upgrade @glimmer/syntax to latest

### PR DESCRIPTION
**Pull request by dcyriller**
## Description

Commit messages will explain minor cleanups done on the way.

Two things are worth noticing:
#### a test removal (EDIT: fixed in https://github.com/prettier/prettier/pull/7306)
```
<script id="entry-template" type="text/x-handlebars-template">
  <div class="entry">
    <h1>{{title}}</h1>
    <div class="body">
      {{body}}
    </div>
  </div>
</script>
```
is legacy hbs syntax not supposed to be parsed by `glimmer`. Here is the AST output of this code: https://astexplorer.net/#/gist/188be5ea74c0d409791417f60a8ea40f/08ee2a309d8e9e0961902f9df82a7fa7ade12767

It was failing, so I've removed the file testing it.

#### a workaround (EDIT: fixed)

glimmer throws on parsing `<TITLE></TITLE`. I am unsure why. So I have changed the tag to `<title></title` while https://github.com/glimmerjs/glimmer-vm/pull/1007 is being answered.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
see https://github.com/prettier/prettier/pull/6570#issuecomment-550266720

**Comment by dcyriller** [comment]
Ow didn’t know that. Thank you for pointing me to it! I’ll have a look.

**Comment by thorn0** [comment]
You're welcome. I know little about Glimmer. For now, I just [pinpointed](https://github.com/prettier/prettier/pull/6773/commits/29e8496384ea1f5c6ace4c9c6eb9f55544ba39d6) the version for `simple-html-tokenizer` in the `next` branch. But of course, it'd be great to find a better solution.

**Comment by dcyriller** [comment]
@thorn0 an attempt at finding a better solution: https://github.com/prettier/prettier/pull/7306 😉

**Comment by thorn0** [comment]
> glimmer throws on parsing `<TITLE></TITLE`. I am unsure why

See https://github.com/emberjs/ember.js/issues/18530

**Comment by fisker** [comment]
Problem solved?

**Comment by dcyriller** [comment]
Not yet, I need https://github.com/tildeio/simple-html-tokenizer/pull/81 to be settled

**Comment by fisker** [comment]
CI is not running, I thought all passed...

**Comment by dcyriller** [comment]
oh indeed, you're right I suspect it is because we're now targetting next

**Comment by fisker** [comment]
Azure won't run if conflicting, merge next into this will trigger CI.

**Comment by rwjblue** [comment]
Just landed https://github.com/tildeio/simple-html-tokenizer/pull/81 and released in 0.5.9.

**Comment by fisker** [comment]
need rebase

**Comment by fisker** [comment]
Forgot this one? This one is important, fixes `install-from-github`

**Pull request merged**
