### PR TITLE
Update plugins.md

### PR DESCRIPTION
**Pull request by bd82**
- Added link to toml prettier plugin (alpha version released).
- Changed link and owner of Java plugin as it was moved to the Jhipster org.

### CODE REVIEW

**Comment by bd82** [comment]
btw: Should no longer active and maintained plugins be removed from the list?
or listed in a different list? (e.g "plugins looking for a new maintainer list")

**Comment by j-f1** [comment]
Which plugins would those be?

**Comment by bd82** [comment]
> Which plugins would those be?
 
- https://github.com/prettier/plugin-python
  - except a README change was last updated ~8  months ago.

- https://github.com/prettier/plugin-swift
  - Last Updated 8 months ago.

- https://github.com/benjie/prettier-plugin-pg
  - Last updated a year ago

- https://github.com/iamsolankiamit/prettier-ruby
  - Last updated 6 months ago.

**Comment by benjie** [comment]
I'd love to keep working on `prettier-plugin-pg` but I don't have time - feel free to move it to unmaintained.

**Comment by kddeisz** [comment]
If we're updating - I've got a much more active `prettier-ruby` here: https://github.com/kddeisz/prettier-ruby

**Comment by azz** [comment]
I'm 50/50 on the "unmaintained" idea. I'd like people to try them out and raise issues/PRs even if they're unmaintained, it'd increase the chances on those plugins picking up traction again. Maybe just moving them to the bottom of the list?

**Comment by bd82** [comment]
> I'm 50/50 on the "unmaintained" idea.

What about a more **positive** distinction?
Listing and distinguishing he "Actively Maintained" plugins first?

- Actively maintained:
  - X
  - Y
  - Z

- Other:
  - T
  - R

**Comment by bd82** [comment]
Merging this would be great 👍 
It would help people **discover** the toml plugin. 😄 

On that note would it be possible to re-tweet about the Toml plugin
in "@prettierCode" on twitter?

- https://twitter.com/Shahar_Soel/status/1092430134353764354

**Comment by azz** [comment]
We could also add a link to the list of plugins on the homepage (in the "Works with the Tools You Use" section)

**Pull request merged**
