### PR TITLE
style: Add new ESLint rule `no-lonely-if` and `unicorn/no-lonely-if`

### PR DESCRIPTION
**Pull request by lipis**
I was expecting more.. but we were already pretty good on that one. Another autofixable rule

### CODE REVIEW

**Comment by fisker** [comment]
FYI: There is an `unicorn/no-lonely-if`

**Comment by lipis** [comment]
hmmm.. what's `unicorn`?

**Comment by fisker** [comment]
https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-lonely-if.md, core one forbid if in else, this one forbid if in if.

**Comment by lipis** [comment]
Seems better.. thanks!

**Comment by fisker** [comment]
If you want enable, should enable both, there are different. And some comments get lost, we can wait for unicorn next version, will fix it.

**Comment by lipis** [comment]
@fisker I see.. could you take over this PR then? and maybe filing an issue to sindre about the comments?

**Comment by fisker** [comment]
Already fixed https://github.com/sindresorhus/eslint-plugin-unicorn/pull/1047

**Review by fisker — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]

**Pull request merged**
