### PR TITLE
refactor: remove unused `css-import` node

### PR DESCRIPTION
**Pull request by evilebottnawi**

### CODE REVIEW

**Comment by j-f1** [comment]
Wheel of blame points to @vjeux: https://github.com/prettier/prettier/pull/1636/files#diff-76f26752c3761490942405c0704a8e1dR2466

**Comment by evilebottnawi** [comment]
@j-f1 :laughing: approve?

**Comment by lydell** [comment]
Cool, how did you find that it was unused? How _are_ imports printed?

**Comment by evilebottnawi** [comment]
@lydell using `css-atrule` node, becaue it is `css-atrule` node :smile:

**Pull request merged**
