### PR TITLE
fix(glimmer): better formatting of boolean attributes

### PR DESCRIPTION
**Pull request by tchak**
I hope this is not controversial...

*input*
```handlebars
<button disabled>Click</button>
<button disabled=disabled>Click</button>
<button ...attributes>Click</button>
```

*before*
```handlebars
<button disabled="">Click</button>
<button disabled="disabled">Click</button>
<button ...attributes="">Click</button>
```

*after*
```handlebars
<button disabled>Click</button>
<button disabled="disabled">Click</button>
<button ...attributes>Click</button>
```

### CODE REVIEW

**Comment by tchak** [comment]
Not sure what's going on here. Local tests seems to pass. I will investigate...

**Comment by j-f1** [comment]
Does running `AST_COMPARE=1 yarn test` fail on your machine? If so, you need to update the AST cleaner to avoid differentiating between the two syntaxes.

**Comment by duailibe** [comment]
I'm not familiar with glimmer so I'm not sure this affects anything. Either way, that's not align with Prettier does things.

So I'd rather not do it, but I'll leave the decision to others more informed.

**Comment by evilebottnawi** [comment]
@duailibe It is invalid code:
```
<button disabled="">Click</button>
<button ...attributes="">Click</button>
```

**Comment by evilebottnawi** [comment]
@duailibe 
Input:
```
<button disabled>Click</button>
<button disabled=disabled>Click</button>
<button ...attributes>Click</button>
```
Output:
```
<button disabled="">Click</button>
<button disabled="disabled">Click</button>
<button ...attributes="">Click</button>
```

Prettier create invalid code in this cases

**Comment by duailibe** [comment]
@evilebottnawi Ah ok :+1:

In that case I think only the `<button disabled=disabled>` => `<button disabled>` transformation looks weird

**Comment by tchak** [comment]
I can see how `<button disabled=disabled>` => `<button disabled>` can be debatable, so I will remove it. I suppose this needs to be aligned with how prettier dose it for other html based dialects.

**Comment by tchak** [comment]
I removed debatable formatting and the test pass now

**Comment by tchak** [comment]
@duailibe it's fine. It's a stylistic concern and we can discuss it, but it is definitely not invalid. I need to look at other html dialects to see what choices they make.

**Comment by duailibe** [comment]
@tchak Thanks! And thank you for the contributions!

**Comment by tchak** [comment]
I fixed the mentioned case with #4897

**Pull request merged**
