### PR TITLE
Change badge to say “formatted”

### PR DESCRIPTION
**Pull request by alanhogan**
“Styled” sounds like a CSS or CSS-like thing to me — Prettier is a code formatter

### CODE REVIEW

**Comment by lydell** [comment]
I agree. Are there any downsides to changing it after the other badge has been out for several months?

**Comment by ikatyang** [comment]
`formatted with` looks a little verbose to me, but it's indeed clearer.

I hope there can be an alias for the badge link, e.g. `https://prettier.io/badge.svg` -> `https://img.shields.io/badge/...`, but it seems it's impossible for static pages.

And also, @alanhogan you have to update the badge below the header as well.

**Comment by azz** [comment]
* 
* 
*  ?

**Comment by alanhogan** [comment]
Updated to get the badge at the top too :) Looks like voters prefer “code style” over “formatted with”

I’m down with either option!

**Comment by alanhogan** [comment]
Updated button text to “code style”

Merge away?

**Comment by azz** [comment]
Looks good. Thanks.

**Pull request merged**
