### PR TITLE
website: Use selected text as range

### PR DESCRIPTION
**Pull request by fisker**
image

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
Please rebase so that we could test it with the fix from https://github.com/prettier/prettier/pull/8086.

**Comment by thorn0** [comment]
Steps:
- select all
- click "Set selected text as range"

Actual result: start=0, end=2

Expected: start=0, end=3

**Prettier pr-8089**
[Playground link](https://deploy-preview-8089--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBGAOlATCANCCABxgEtoBnZUAQwCdaIB3ABToUpWoBtHqBPSvgBGtamADWcGAGVCYklADmyGLQCucfHAC2QuABN9BgDLUla6orgAxCLW3UYpJchDU1MCHhAALGNq4AdR8SeHI5MDhpdlCSADdQvlcwckEQBXI4WhhmUUUHZAAzbkz8ACtyAA8AIVEJKWlqbThjBTgiks0QCsrpBUUuOABFNQh4Dq5SkDlaTNpXIWo9Lm9CWgUYQJJ9GB9kAA4ABnw1iEzA0UJXNbg5uPb8AEdR+FyiDjdyAFooOAMDby0ODPEhA3KWApIYqTLqZbQkFTqWH9QYjMbtKGdfAwJZbHZ7JBYbGiEhcfoAYQg2khIFuAFZvGpMgAVJYcaFTOIaACSUCMsGkYHWxAAgnzpDA+IMJlNREoojjsshjiA5VYAKJ85BYAC+OqAA)
```sh
--parser babel
--range-end 2
--range-start 0
```

**Input:**
```jsx
1
2
```

**Output:**
```jsx
1;
2
```

**Comment by fisker** [comment]
`\n` not counted?

**Comment by fisker** [comment]
Seems should `+1`

**Comment by thorn0** [comment]
I'm not sure what you ask. `rangeEnd` is exclusive. `--range-start 0 --range-end 3` means `code.slice(0, 3 - 0)`

**Comment by thorn0** [comment]
It works correctly without new lines:
**Prettier pr-8089**
[Playground link](https://deploy-preview-8089--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBGATAZhAGhBABxgEtoBnZUAQwCcaIB3ABVoQpSoBsGqBPCvACMaVMAGs4MAMoFRxKAHNkMGgFc4eOAFtBcACZ79AGSqLVVBXABiEGlqowSi5CCqqYEXCAAWMLZwB1b2J4MlkwOCk2EOIANxDeFzAyARB5MjgaGCYRBXtkADMuDLwAKzIADwAhEXFJKSotOCN5OELijRByiql5BU44AEVVCHh2zhKQWRoMmhdBKl1OLwIaeRgA4j0Yb2QADgAGPFWIDICRAhdVuFnYtrwARxH4HMJ2VzIAWig4fX0vGhwJ7EQE5Cz5JBFCadDJaYjKNQwvoDYajNqQjp4GCLTbbXZIdBYkTETh9ADCEC0EJANwArF5VBkACqLdhQyaxdQASSghlgUjAayIAEFeVIYLwBuNJiJFJFsVlkEcQLLLABRXnITAAX21QA)
```sh
--parser babel
--range-end 3
--range-start 0
```

**Input:**
```jsx
123
```

**Output:**
```jsx
123;

```

**Comment by fisker** [comment]
I think it's fixed now.

**Pull request merged**
