### PR TITLE
cleanup EditorConfig handling: Remove unused parsing/ignoring of `insert_final_newline` to `insertFinalNewline`

### PR DESCRIPTION
**Pull request by josephfrazier**
Now that https://github.com/prettier/prettier/pull/15394 has been
merged, this addresses https://github.com/prettier/prettier/issues/14514#issuecomment-1471056464

_EDIT: Note that this is just a code cleanup, and does not change the behavior of Prettier_

### CODE REVIEW

**Comment by celluj34** [comment]
I am not sure I understand - previously we _were_ converting `insert_final_newline` to `insertFinalNewline`, and this PR removes that feature?

**Comment by josephfrazier** [comment]
Previously, the separate `editorconfig-to-prettier` package was converting `insert_final_newline` to `insertFinalNewline`, but [`prettier` was explicitly ignoring it](https://github.com/prettier/prettier/pull/15398/files#diff-8c958fa1cf0642b74c448f11bc10a0b1bb9dcb6030ae582ff2c8c5d37b61a41aL13-L17). This is just a code cleanup, I currently don't have any opinion on how this option should be treated.

**Comment by celluj34** [comment]
> Previously, the separate `editorconfig-to-prettier` package was converting `insert_final_newline` to `insertFinalNewline`, but [`prettier` was explicitly ignoring it](https://github.com/prettier/prettier/pull/15398/files#diff-8c958fa1cf0642b74c448f11bc10a0b1bb9dcb6030ae582ff2c8c5d37b61a41aL13-L17). This is just a code cleanup, I currently don't have any opinion on how this option should be treated.

So that means prettier wasn't respecting `insertFinalNewline` at all? Or only from .editorConfig?

Sorry for all the questions, just trying to gauge whether it's acceptable to ask if prettier _could_ support `insertFinalNewline`.

**Comment by josephfrazier** [comment]
No problem!

As far as I can tell, Prettier does not support any "insert final newline" functionality at all: searching for `insertFinalNewline` only shows results that this cleanup PR removes, rather than any actual formatting differences: https://github.com/search?q=repo%3Aprettier%2Fprettier+insertFinalNewline&type=code

image

Regarding whether Prettier _could/should_ support `insert_final_newline`, I think that a question for another issue/PR.

**Comment by fisker** [comment]
We do want support it, we just don't know how https://github.com/prettier/prettier/pull/10759#issuecomment-825010659
https://github.com/josephfrazier/editorconfig-to-prettier/pull/8

**Comment by josephfrazier** [comment]
Thanks for linking the context, @fisker. Since Prettier currently doesn't support `insert_final_newline`, I'll go ahead and merge this to remove the effectively dead code, knowing that it might be added back later, if we can figure out how to make it work.

**Pull request merged**
