### PR TITLE
 Add NHL to users list

### PR DESCRIPTION
**Pull request by epitaphmike**

### CODE REVIEW

**Comment by duailibe** [comment]
🏒💯

**Comment by j-f1** [comment]
@duailibe/@azz Could one of you make the deploy jobs public so contributors can figure out what’s wrong?

**Comment by ikatyang** [comment]
image

**Comment by duailibe** [comment]
@j-f1 I don't have access either..

Thanks @ikatyang 😊

**Comment by ikatyang** [comment]
Not sure why it failed: https://app.netlify.com/sites/prettier/deploys/5a563222df99532f7a45e5af

I've clicked <kbd>rebuild</kbd>, but [it seems stuck](https://app.netlify.com/sites/prettier/deploys/5a5637820b79b754a19d1a5c).

**Comment by epitaphmike** [comment]
@ikatyang Netlify seems to be running now.

**Pull request merged**
