### PR TITLE
Update flow tests

### PR DESCRIPTION
**Pull request by lydell**
Just felt like running the syncing script for some reason, but I'm not sure if all these added tests provide any value. Thoughts?

### CODE REVIEW

**Comment by vjeux** [comment]
I'm curious, did any added test break something in prettier?

**Comment by lydell** [comment]
I'm not sure what you mean?

**Comment by vjeux** [comment]
Did the tests find any issue with how prettier prints code? If not, I'm not sure it's worth adding them to the codebase. The flow tests were very useful at finding issues and ensuring that we didn't regress. But now that prettier is in a good shape, adding new tests would just make the test suite slower and not provide any added guarantees.

Is there a way to alter you script to just update tests that changed instead of adding a bunch of new test files?

**Comment by lydell** [comment]
When scrolling through all changes nothing stood out to me. I agree – adding this is pretty pointless. I'll close this and think about if there's anything that can be done to the script. 👍

**Pull request closed without merging**
