### PR TITLE
Update to Jest 23

### PR DESCRIPTION
**Pull request by duailibe**
Changes are because of https://github.com/prettier/prettier/pull/3518#issue-158890517

We can do this now that we merged #4537

### CODE REVIEW

**Comment by duailibe** [comment]
Guess not

**Comment by SimenB** [comment]
Segfault? 😭

**Comment by SimenB** [comment]
Oh, syntax error on node 4, gotcha

**Comment by duailibe** [comment]
@SimenB Yes, either Jest or a dependency

The node 6 tests are failing ever since we enabled them but I don't think it's Jest fault (#3457)

**Comment by SimenB** [comment]
Doesn't seems like you set `testEnvironment` in your jest config? jsdom is the default (and uses destructuring, so probably the culprit). `node` is also faster. Might be worth a go?

**Comment by duailibe** [comment]
@SimenB Thanks, I'll try that

**Comment by SimenB** [comment]
Docs, if it helps: https://facebook.github.io/jest/docs/en/configuration.html#testenvironment-string

We have been talking about changing the default to node, but that would break "zero config" for react. Easy enough to google `document is not defined`, I suppose...

@rickhanlonii ^

**Comment by SimenB** [comment]
We discussed it at the summit this week. I do think there's an issue though, lemme see if I can dig it up.

**Comment by duailibe** [comment]
@SimenB I think something else is failing
```
~/Code/prettier master*
❯ node -v
v4.9.1

~/Code/prettier master*
❯ yarn test -v
yarn run v1.6.0
$ jest -v
23.0.0
✨  Done in 0.37s.

~/Code/prettier master*
❯ yarn test
yarn run v1.6.0
$ jest
Test Suites: 0 of 838 total
Tests:       0 total
Snapshots:   0 total
Time:        0.395s, estimated 84s
Ran all test suites.
✨  Done in 1.96s.
```

That happens with `testEnvironment` node or unset

**Comment by SimenB** [comment]
It's `@babel/code-frame` using invalid node 4 syntax. Not sure why it doesn't give any output, but since it's one of jest's dependencies, you can trigger transformation of it either

**Comment by SimenB** [comment]
I'm looking into this now. We can try to do something clever ™ with the lockfile making sure we keep the babel deps on a version supported by node 4

**Comment by SimenB** [comment]
See #4782 - there's syntax issues in Prettier's code base, though

**Pull request closed without merging**
