### PR TITLE
Fix `yarn.lock` for next

### PR DESCRIPTION
**Pull request by fisker**
Lock file in `next` seems not right.

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by kachkaev** [comment]
@fisker WDYT of integrating the repo with [`yarn-deduplicate`](https://www.npmjs.com/package/yarn-deduplicate) in a separate PR? Here's what we have in `package.json` at work since recently:

```json
{
  "scripts": {
    "fix": "yarn fix:eslint && yarn fix:prettier && fix:yarn-deduplicate",
    "fix:eslint": "eslint \"**/*.*\" --fix",
    "fix:prettier": "prettier --write \"**/*.*\"",
    "fix:yarn-deduplicate": "yarn-deduplicate --strategy=fewer",
    "lint": "yarn lint:eslint && yarn lint:prettier && yarn lint:tsc && yarn lint:yarn-deduplicate",
    "lint:eslint": "eslint \"**/*.*\"",
    "lint:prettier": "prettier --check \"**/*.*\"",
    "lint:tsc": "tsc -p .",
    "lint:yarn-deduplicate": "yarn-deduplicate --list --fail --strategy=fewer",
  },
  "devDependencies": {
    "...": "...",
    "yarn-deduplicate": "^1.1.1",
  },
  "...": "..."
}
```

**Comment by thorn0** [comment]
This lock file is still unstable. The issue is caused by https://github.com/yarnpkg/yarn/issues/7770 and `fsevents` 1.x, which is a dependency of Jest (`jest-haste-map`). Should be gone after updating to the [upcoming version](https://github.com/facebook/jest/issues/9355#issuecomment-574059641) 25 of Jest as it'll use `fsevents` 2.x.

**Comment by thorn0** [comment]
```console
thorn@THORN-LNV:/mnt/d/dev/prettier-fisker$ rm -rf node_modules/ yarn.lock && yarn cache clean && yarn
yarn cache v1.21.1
success Cleared cache.
Done in 10.75s.
yarn install v1.21.1
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning cspell > comment-json > json-parser@1.1.5: `json-parser` is deprecated. Please use `comment-json` instead
warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
[3/5] Fetching packages...
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > angular-estree-parser@1.1.5" has incorrect peer dependency "@angular/compiler@^6.0.0 || ^7.0.0".
[5/5] Building fresh packages...

success Saved lockfile.
Done in 61.25s.
thorn@THORN-LNV:/mnt/d/dev/prettier-fisker$ git status
On branch next-lock
Your branch is up to date with 'origin/next-lock'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   yarn.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

`node-pre-gyp` and its dependencies are back in the lock file.

**Comment by fisker** [comment]
I don't mean to regenerate new lock, old one changes when run `yarn`

**Pull request merged**
