### PR TITLE
Drop Node.js 14 for development build

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

https://github.com/prettier/prettier/issues/13142#issuecomment-1238966462

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
> I thought we were going with this suggestion, but the engines and build matrix seem to be changed for all builds

I've not changed workflows for production build.

**Comment by nickmccurdy** [comment]
Will this still test Node 14 in CI?

**Comment by OGherc86** [comment]
Yes sir. Sorry been so busy with work

**Comment by sosukesuzuki** [comment]
> Will this still test main or pull requests with Node 14?

Yes.

**Comment by fisker** [comment]
Should comment https://github.com/sosukesuzuki/prettier/blob/5a116ee14583078ef31ecbe4bb85f8ba9a2d1a3c/.github/workflows/dev-test.yml#L31-L35 out

**Review by fisker — APPROVED** [review]

**Review by thorn0 — APPROVED** [review]

**Pull request merged**
