### PR TITLE
feat(markdown): an option to disable adding spaces between CJK and non-CJK

### LINKED ISSUE #5938: Opt out inserting spaces between Japanese and Latin
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEhlBkHYMhw00B9mh7BkDD-AwgMrH7EBqA4oFIMgEQyDODABrEAyAtAGIDygVgyCWDOkABRoGUIwOYMgfO1Af86AZBkBCNoECGQJEMgGIZA0QyAAOUA0QYBC3XoFPTQDTmgPKjAIr6AJJ3SBAyMBvcoCSGQBhRgB-jA6gyB9BkBBDOjGBNBkBw-yAANCAQAA4wAJbQAM7IoACGAE6JEADuAApJCLEo8QBuEBEAJkEgAEaJ8WAA1nAwxKFVEVAA5sgwiQCucMEAFjAAtgA2AOq9EfDRjWBwxNkTEXkTAJ7I4NGxwc3RcIkw6ZUtA-HIAGbxQzvBAFbRAB4AQpU1dcTxA3CszXBnF1cgtzuxGaLSGcAAip0IPBfpceiBGokdok1sdEtUimkoKVQolmjARsUYL1kAAOAAMwVxEB2I0qoTWuLgyLyP2CiTgAEdOhEOQd4kcTkhznDgjsBhF2l14dEQWDIdCfsK-vCYPEyoSisTkAAmYIdeIRIYgwgQAbHNZQaBskCdHYAFXVORFOwAvq6gA)
```sh
# Options (if any):
--parser markdown
```

**Input:**
```markdown
この文書は，CSS，SVGおよびXSL-FOなどの技術で実現が求められる一般的な日本語組版の要件を記述したものです．
```

**Output:**
```makdown
この文書は，CSS，SVG および XSL-FO などの技術で実現が求められる一般的な日本語組版の要件を記述したものです．
```

**Expected behavior:**
Output and input are identical.

# Opt out inserting spaces between Japanese and Latin

Though Prettier inserts spaces between Japanese and Latin by default, inserting spaces is not widely adopted in Japan. Because adding spaces are considered as part of visual aesthetics and not as inserting physical characters.

## Examples:

Requirements for Japanese Text Layout doesn’t insert spaces
https://www.w3.org/TR/2012/NOTE-jlreq-20120403/ja/
> この文書は，CSS，SVGおよびXSL-FOなどの技術で実現が求められる一般的な日本語組版の要件を記述したものです．

Japanese ministry of education (Ministry of Education, Culture, Sports, Science and Technology) doesn't insert spaces.
http://www.mext.go.jp/b_menu/activity/detail/2019/20190219_2.htm
> 2月19日、柴山大臣は、東洋大学赤羽台キャンパスを訪れ、INIADの教育環境を視察するとともに、安齋隆 理事長、坂村健 学部長と意見交換しました。

Japanese Wikipedia doesn't insert spaces
https://ja.wikipedia.org/wiki/%E3%82%A6%E3%82%A3%E3%82%AD%E3%83%9A%E3%83%87%E3%82%A3%E3%82%A2
> 専門家によるオンライン百科事典プロジェクトNupedia（ヌーペディア）を前身として

Adobe doesn’t insert spaces
https://blogs.adobe.com/japan/cc-web-xd-february-2019-update-integrations-language-support-narration/
> すでにXDはPhotoshop、Illustrator、After Effectsとの連携ワークフローがこれまでになく容易になっています。

## Note

Please note that [Requirements for Japanese Text Layout](https://www.w3.org/TR/jlreq/#handling_of_western_text_in_japanese_text_using_proportional_western_fonts) doesn't recommend inserting physical space (U+0020)s between Japanese and Latin. Instead it recommends software should render text as if it adds quarter em space (Microsoft Word do this).

### LINKED ISSUE #6385: Do not insert whitespaces between latin and cj letters
**Environments:**
- Prettier Version: 1.18.2

**Steps to reproduce:**

```md
// Input
私はJavaScriptが好きです
```

**Expected behavior:**
```md
私はJavaScriptが好きです
```

**Actual behavior:**
```md
私は JavaScript が好きです
```

***

For now, Prettier inserts whitespace between latin and Japanese/Chinese on formatting Markdown.

As mentioned in [#5938](https://github.com/prettier/prettier/issues/5938), this is not good behavior for Japanese, but correct for Chinese.

I tried to avoid this problem in [the same way as handling Korean language](https://github.com/prettier/prettier/pull/5040), but it was impossible because Japanese and Chinese uses same Kanji letter, with same char code.

From above reason, I think we should add new option like `add-whitespace-between-latin-and-cj` to determine whether whitespace is inserted between latin and cj.

Of cource it's the best if there is the way to distinguish Japanese and Chinese.

### PR DESCRIPTION
**Pull request by rdrgn**
close #6385
close #5938

- Add an option `cjkSpacing`
  - `always`: same as current behavior for Chinese and Japanese
  - `preserve`: same as current behavior for Korean
- Update the `splitText` function in `src/language-markdown/utils.js` to implement the above option
- Add some tests

While the discussion at #6385 seemed to be inactive, I was annoyed with spaces between CJK characters and non-CJK characters.
Thus, I'm working on this PR.

Before I start working on unfinished tasks (such as writing `changelog_unreleased`), I would like your advice about the direction of implementation. In addition, because I'm not a native English speaker, the namings and the descriptions might be unnatural. 😖 

---

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
I also use Japanese-letters, so I know that this behavior is frustrating..

I opened #6385 but I don't think we should add new option for this now. See https://github.com/prettier/prettier/issues/6385#issuecomment-552484695. I agree the comment. Prettier should simply keep whitespace same as the input. 
However, it is a big breaking change so we cannot add this change in minor and patch release. I think We can do this in next major release.

/cc @ikatyang How do you think?

**Comment by thorn0** [comment]
@sosukesuzuki I think the main problem with that my comment is line breaks. If `--prose-wrap` is set to `always` or `never`, Prettier needs to re-wrap text. If Latin and Japanese or Chinese meet on the line border:
```
.... .... .... .... ... .. ......... ....... <CJK>
<LATIN> .... .... ...... .. ...... .... ..
```
what should Prettier replace the line break with? A space or the empty string?

**Comment by rdrgn** [comment]
Because most plugins that remove between CJK (e.g. [`markdown-it-cjk-breaks`](https://github.com/markdown-it/markdown-it-cjk-breaks)) doesn't treat linebreaks between CJK and non-CJK, in my opinion, it seems like a good idea to leave a space:

```
.... .... .... .... ... .. ......... ....... <CJK> <LATIN> .... .... ...... .. ...... .... ..
```

cf. https://prettier.io/blog/2017/11/07/1.8.0.html

**Comment by uptonking** [comment]
I really want this option merged into prettier and released, because I rely on prettier heavily.    
Now I have to ignore the `.md` files while formatting.

**Comment by thorn0** [comment]
@uptonking We know this is a problem, but we'd like to try to [solve it without adding an option](https://mobile.twitter.com/thorn0/status/1271395033359450114).

**Comment by uptonking** [comment]
@thorn0   
As for Chinese language, it's quite a personal taste about whether to add a whitespace between Chinese and English characters.  
Sometimes it's better, sometimes not. Some people prefer, some people not.  
Someone even writes a guide for [the recommended format for Chinese](https://github.com/ruanyf/document-style-guide/blob/master/docs/text.md) as stated in [issue 6385](https://github.com/prettier/prettier/issues/6385). But I don't agree and won't adopt it.    
So I strongly request an option. Otherwise github issues will always be open.

**Comment by evilebottnawi** [comment]
@uptonking no options, we keep original input as it, if you need ensure one style on all docs you need to use linter

**Comment by sosukesuzuki** [comment]
@@uptonking I agree with evilebottnawi. As [I mentioned on Twitter](https://mobile.twitter.com/__sosukesuzuki/status/1271389954057228289) it is **NOT** Prettier role.

**Comment by rdrgn** [comment]
Sounds good. I am relieved to know that the discussion is continuing. Now I will close this PR because the PR is different from those plans.

**Comment by brodybits** [comment]
It looks to me from <https://github.com/prettier/prettier/pull/7933#issuecomment-682803349> like this change to disable adding spaces is wanted but with no option in the next major release. Considering that these changes seem to simplify `src/language-markdown/utils.js`, should this PR be resurrected with the option removed?

**Pull request closed without merging**
