### PR TITLE
Update release script

### LINKED ISSUE #9954: Release from GitHub Actions
Now Babel uses GitHub Actions for releasing. It is great.

https://twitter.com/NicoloRibaudo/status/1339944122036187141

https://github.com/babel/babel/pull/12526

I want to use the same way for Prettier. Because it is easy for a maintainer who releases.

### LINKED ISSUE #12532: Remove test step from release script?
I just played with the release script, it run tests during release, and the tests may take long time.

Testing source doesn't make sense, we already tested on CI.
Testing bundles maybe make sense, because the build script may have bug.

If we run build script on different platforms on CI to make sure the bundled code are the same, then maybe we can remove that step too.

//cc @sosukesuzuki

### PR DESCRIPTION
**Pull request by fisker**
## Description

This workflow only do `test`+`npm publish` for now, we can move other steps to it in future.

Fixes #9954
Fixes #12532

Ideally, there should be more instructions, but I'm not going to spend more time on these scripts recently.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
I would like to just confirm two things.

1. In this PR, release script is run on the local machine
2. Only test and `npm publish` are executed by `workflow_dispatch` in GitHub Actions

**Comment by sosukesuzuki** [comment]
Thanks for the great work, I hope in the future we can use GitHub Actions to do all the steps for releases!

**Comment by fisker** [comment]
> I would like to just confirm two things.

That's correct.

**Review by sosukesuzuki — COMMENTED** [review]
Looks good to me, but can you check my messages in Discord? I have a concern.

**Review by sosukesuzuki — APPROVED** [review]

**Comment by fisker** [comment]
Let's give this a shot, if it doesn't work as expected, feel free to fix/revert.

**Pull request merged**
