### PR TITLE
Add `Doc[]` as `Doc`

### PR DESCRIPTION
**Pull request by fisker**
~This is a prototype, but seems working, do you think we can do this?~

Adding `Doc[]` as `Doc` to simplify print.

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
:+1: If a `string` can be a `Doc`, I don't see why `Doc[]` can't be.

**Comment by fisker** [comment]
Do we need do this in v3.0.0, if plugin use `mapDoc`/`findInDoc`, it will be broken, but `doc.utils` is private?

**Comment by thorn0** [comment]
I'm sure this can be done in a backwards compatible way, so that plugins will be able to keep using `concat`.

**Comment by fisker** [comment]
I'm done with this one.

We are using array internally, https://github.com/prettier/prettier/pull/9733/commits/d8487da226f8f3aeeb7e456ca1ce0bc1c764e190 to prove this can work, I'll revert it before merging.

I also added a eslint rule to forbind use `concat`, but I'm not going to enable it in this PR, to keep this one clean.

To make `mapDoc`/`traverseDoc` backwards compatible, wrap array into `{type: "concat", parts: doc}` before sending to `onEnter` function https://github.com/prettier/prettier/pull/9733/commits/e706e0bd649d5cc43083129f5acf544df2051d5b

**Comment by thorn0** [comment]
After thinking more about this, I'm not sure the compatibility measures have to be that complicated here. `doc.utils` and `type: 'concat'` aren't documented, so they're indeed should be considered private implementation details. Let's make the `concat` function return an array and let's remove all the mentions of `type === 'concat'` from the code. After all, plugin authors are supposed to use the doc builder functions and not construct doc objects directly, aren't they? Or do you know specific plugins that could get broken?

**Comment by fisker** [comment]
Seems [people use `mapDoc`](https://github.com/search?p=2&q=prettier+mapdoc&type=Code], I think better deprecate it first, give people some time, then remove at somepoint.

**Comment by fisker** [comment]
This plugin seems will be broken https://github.com/NiklasPor/prettier-plugin-go-template/blob/da8244dfac66d6170caa9ad54d06e6eab833b964/src/index.ts#L187

**Comment by thorn0** [comment]
A problem I found in many plugins is that in their `package.json` they depend on Prettier as on a usual dependency, not as on a peer dependency. It means that potentially they can build docs using a different version of Prettier. We have to support this scenario, so yes, we can't remove mentions of `type === 'concat'` from the code. But I'm not sure about the `toConcatIfArray` part. It looks like it might be problematic from the performance point of view (given how often concatenation of docs is used). Also it's not recursive, so the `onEnter` callback that came from an old plugin still gets a doc that might contain nested arrays, right? But if it was made recursive, its performance impact would definitely be really bad.

**Comment by thorn0** [comment]
We probably can add the compatibility overhead only to the exported versions of the doc util functions (`prettier.doc.utils`) and keep their internal versions fast. But I still can't see how this compatibility can be made both reliable and relatively efficient for `traverseDoc` and `mapDoc`.

**Comment by thorn0** [comment]
Looks like the most backwards compatible solution would be to keep the `concat` function as is (returning an object with `type === "concat"`) and to support both concatenation types. `toConcatIfArray` in `traverseDoc` and `cb({ type: "concat", parts })` in `mapDoc` wouldn't be needed then. If a plugin used `concat` to build its doc, it will get the expected format in its traverse and map callbacks. Thoughts?

**Comment by fisker** [comment]
> keep the concat function as is (returning an object with type === "concat") 

Yes, I  was going to keep `concat` that way.

> We are using array internally, d8487da to prove this can work, I'll revert it before merging.

Because we won't use it anymore in core, so the `join` will still be a `{type: "concat"}`, my main purpose is to simply use of `concat`, I guess this part should not care that much.

Without`toConcatIfArray`, there will be no effect when they traverse doc build with `concat`, unless plugin traverse the new doc from core parser,  array will be received.

**Comment by fisker** [comment]
Maybe we can transform array to old `concat` in when they call core parser in multiparsers? Not 100 percent safe  but this is the recommend way to do embed format.

**Comment by thorn0** [comment]
> Maybe we can transform array to old concat when they call core parser in multiparsers?

Are there any known plugins that use multiparser? I think we can skip this part.

**Comment by fisker** [comment]
I don't know any plugin do that, only thinking it's possible.

**Comment by thorn0** [comment]
It's super highly unlikely. Let's skip.

**Comment by thorn0** [comment]
Looks good. Let's revert things in `doc-builders` and merge.

**Comment by fisker** [comment]
Done.

**Comment by thorn0** [comment]
Yes, I'll write it and add to this PR.

**Comment by fisker** [comment]
Thank you @thorn0

**Comment by sosukesuzuki** [comment]
Off topic: I tried using `Doc[]` instead of `concat` and it's so much more comfortable! Thanks!

**Comment by dangmai** [comment]
Hi, I'm trying to understand the impact of this change on my plugin. If I understand correctly, if I use the new syntax `Doc[]` instead of the deprecated `concat`, I will have to bump Prettier `peerDependency` version to `^2.3.0`, is that correct? In that case is it better to keep using `concat` for now so that my users are not forced to upgrade Prettier on their repo?

**Comment by thorn0** [comment]
@dangmai Yes, all you wrote is correct.

**Comment by bbugh** [comment]
Really surprised to see a breaking API change in a minor version release. 😢 

This broke [`prettier-plugin-erb`](https://github.com/adamzapasnik/prettier-plugin-erb) by way of [`prettier-html-templates`](https://github.com/adamzapasnik/prettier-html-templates) (neither are my packages), and the upgrade instructions for plugin authors aren't giving me enough info to make a PR to fix it.

https://github.com/adamzapasnik/prettier-html-templates/blob/8c6674dcd0c0e108c2d64f170bb4e5e12d2b8abd/lib/decoder.js#L10-L18

It seems to imply that `(doc)` is now an array equivalent to `doc.parts` was before, but that does not seem to be the case even when removing instances of `concat`. 

Could we get a more explicitly informative upgrade outline for plugins that used `parts`?

**Comment by fisker** [comment]
Add

```js
doc = Array.isArray(doc) ? {type: "concat", parts: doc} : doc;
```

to the top should work, but better to do `const parts = Array.isArray(doc) : doc : doc.parts` whenever you want to get the parts, and return `Doc[]` instead of `{type: 'concat'}`.


This function also have issues when the doc is not `concat` but `fill`.

**Comment by bbugh** [comment]
Thanks for the reply and info. I was hoping it was something easy like that. Unfortunately, it looks like there's quite a lot more to what changed in this PR. With no changes to the package code, most of the inputs between 2.2.1 and 2.3.0 are quite different.

Given the document

```erb
<% start %><% end %> <br />

<% start %><% end %><br />

<% whatever %><br />
```

Example 1: 

The first `doc` received in 2.2.1 is:

```
doc '<eext1>'
```

In 2.3.0 the same doc seems to be split up:

```
doc ''
doc '<eext1'
doc [ '', '<eext1', [length]: 2 ]
doc '>'
```

Example 2 The first expected `group` is much different

2.2.1

```
    doc {
      type: 'group',
      id: Symbol(element-attr-group-id),
      contents: '<eext1>',
      break: false,
      expandedStates: undefined
    }
```

2.3.0 seems to replace contents with another doc:

```
    doc {
      type: 'group',
      id: Symbol(element-attr-group-id),
      contents: {
        type: 'concat',
        parts: [
          { type: 'concat', parts: [ '', '<eext1', [length]: 2 ] },
          '',
          '>',
          [length]: 3
        ]
      },
      break: false,
      expandedStates: undefined
    }
```

Example 3 the way `br` is extracted is different

2.2.1:

```
doc '<br '
doc {
  type: 'group',
  id: Symbol(element-attr-group-id),
  contents: '<br ',
  break: false,
  expandedStates: undefined
}
```

2.3.0:

```

doc '<br'
doc [ '', '<br', [length]: 2 ]
doc ' '
doc [
  { type: 'concat', parts: [ '', '<br', [length]: 2 ] },
  ' ',
  '',
  [length]: 3
]
doc {
  type: 'group',
  id: Symbol(element-attr-group-id),
  contents: {
    type: 'concat',
    parts: [
      { type: 'concat', parts: [ '', '<br', [length]: 2 ] },
      ' ',
      '',
      [length]: 3
    ]
  },
  break: false,
  expandedStates: undefined
}
```

Just a few examples, almost all of the rest is different too. Unfortunately, I don't know enough about plugins to overhaul this code. 😢

**Comment by fisker** [comment]
Those changes not related to this PR, printer changes the doc all the time. Doc manipulation is not recommended.

**Comment by bbugh** [comment]
Got it. It looked like it was, my apologies. Hopefully the author will update it. Thanks!

**Pull request merged**
