### PR TITLE
fix(range): improve detection of JS source elements

### LINKED ISSUE #6428: --range-start and --range-end don't work as documented
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI
- Runtime: Node 10
- Operating System: MacOS

**Steps to reproduce:**

```
echo "'aaa';\n'bbb';" | prettier --range-start 0 --range-end 1 --parser babel
'aaa';
'bbb';
```

**Expected behavior:**

Following behavior is currently documented:

> The range will extend:
> 
> Backwards to the start of the first line containing the selected statement.
> Forwards to the end of the selected statement.

So it should format only first quotes.

In fact there is no range I can specify so only first quote is formatted.

**Actual behavior:**

It formats both quotes

**Additional notes:**

The first range that results in formatting of both quotes is following:

```
echo "'aaa';\n'bbb';" | prettier --range-start 0 --range-end 14 --parser babel
"aaa";
"bbb";
```

Strangely nothing is formatted when range-start is 1 (again, against what is documented):

```
echo "'aaa';\n'bbb';" | prettier --range-start 1 --range-end 14 --parser babel
'aaa';
'bbb';
```

### PR DESCRIPTION
**Pull request by thorn0**
fixes #6428

Also adds detection for previously not covered types like `ForOfStatement`.

**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAFAAmzzr+YCUAOlKhAE47oBemEqmA2pgG4C6hmwAviADQgIABxgBLaAGdkoAIYUKEAO4AFeQmkpZAGyWyAntMEAjCrLABrODADKw82KgBzZDAoBXOIIAWMALbaAOreYvCS9mBwNhqhYqyh+sjgkkYgjpJwFDAqZk5+ssioOhmCAFaSAB4AQmaW1jayfnAAMo5whcVeIOUVNo5O2nAAiu4Q8B3aJSD2FBkUScayxnDaAtMUjjCBYgAmMN7IABwADILCihmBZsJJ53BzrO2CAI6j8DkimiCykgC0UHA4DsgWsKHBXmIwTlZHkCkgipMuhk-GJXB4kf1BiMxu14Z1BDAlts9gckAAmAlmMTafoAYQgfnySXuAFY1u4MgAVJaaBFTVieACSUGBsBsYA2ogAgiKbDB9IMJlMzM4ooSssgyacQCqnHAAKIi5AAZjJPB4QA)
```sh
--parser babel
--range-end 32
--range-start 20
```

**Input:**
```jsx
f(       fff )
for   (z of [ v]) {}
```

**Output:**
```jsx
f(       fff )
for   (z of [ v]) {}
```

**Prettier pr-8419**
[Playground link](https://deploy-preview-8419--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAzAFAAmzzr+YCUAOlKhAE47oBemEqmA2pgG4C6hmwAviADQgIABxgBLaAGdkoAIYUKEAO4AFeQmkpZAGyWyAntMEAjCrLABrODADKw82KgBzZDAoBXOILgBbY3AATAMCAGVlnd1knOAAxSh9ZGHFnZBBZdxgIARAACxgfbQB1HLF4SXswOBsNUrFWUv1UsEkjEEdJOAoYFTMnBORUHQ7BACtJAA8AITNLaxtZHzgQxzgBoa8QMfGbRydtOABFdwh4Ne1hkHsKDopU41l-bWzhCkcYQrEAmBzkAA4ABkELwgHUKZmEqRecBurFWggAjsd4D0RJo0pIALRQOCBQLZChwRFiAk9KL9JCDc4bDo+MSuDzU3b7I4nVYU9aCGAPD5fH5IABMnLMYm0uwAwhAfOSQNCAKzZdwdAAqD00lIurE8AEkoMFYDYwK9RABBXU2GD6fZnC5mZxVLldZD8wEgW3RACiuuQAGZ+TweEA)

**Output:**
```jsx
f(       fff )
for (z of [v]) {
}
```

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Didn't notice there is a range related PR, need fix snapshots.

**Comment by fisker** [comment]
image

Two buttons...

**Comment by thorn0** [comment]
I updated the snapshots and added more sentence/declaration-like node types to this detection. Now I'm starting to think we should add class/interface members too. Why not? Why [reformat the whole class instead of a single method](https://deploy-preview-8419--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOARugE4AUAlMAL5kXUBejLZzIANCAgAHGAEtomZKFo0IAdwAKtBFJTpU89AE8pgyjXRgA1nBgBlYUbFQA5shg0ArnEFwAtpTgATbz4Ay6HZO6LZwBDTu6DDidsgg6E4wEAIgABYw7qgA6mli8JhWYHDmqvliAG752vFg2Kk2mHA0MIqGtlHIAGYaTYIAVpgAHgBChiZm5ujucP42cN29riCDQ+Y2tqhwAIpOEPCLqH0gVjRNNPHUXqipwjQ2MNli3jBpyAAcAAyCdxBN2YZhPE7nBzhUFoIAI57eBtERqBKYAC0UDgPh8qRocGhYixbVCnSQPSOyya7jEDmcpI2W12+wWRKWghg6EoTxebyQACZmYYxKgNgBhCDuQkgUEAVlSTiaABVWWpiccKi4AJJQPywcxge6iACCGvMMG0W0Ox0MdhKLJayAAjBLBBawgBRDV2gDszGYQA)? Am I missing something?

**Comment by thorn0** [comment]
I forgot how exactly range formatting works. It extracts the range and formats it as if it was a program. Class member on their own can't be parsed as a program, so disregard my previous comment.

**Comment by fisker** [comment]
Similar to 

```json
{
  a: '',
  ^^^^^
}
```

in JSON

**Pull request merged**
