### PR TITLE
website: bigger font for <h5> in blog

### PR DESCRIPTION
**Pull request by thorn0**
## Description

Now it doesn't look like a heading at all:

> image

## Checklist

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Isn't `<h5>` `<h6>` normally just `1em`?

**Comment by thorn0** [comment]
There are some other styles there that change that.

**Comment by fisker** [comment]
I suggested to remove categories in highlights before last version release, so we can use `<h4>`

**Comment by thorn0** [comment]
And I think I supported keeping them as is. Besides, `h5` can be used in non-highlights too.

**Review by fisker — APPROVED** [review]

**Pull request merged**
