### PR TITLE
Increase the image size

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
## Description

Increased the State of JS 2021 Image size.

Before:

before

After:

after

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
So, no.

**Comment by fisker** [comment]
Screenshot_2022-04-01-22-33-23-817_com microsoft emmx canary

So, no.

**Comment by Harry-Hopkinson** [comment]
It is larger than the counter part using phone dimensions though after doing tests on my local machine.

Before:
before

After:
after

**Comment by fisker** [comment]
Sorry, I'm not going to change it.

**Pull request closed without merging**
