### PR TITLE
Enable using custom parser with languages other than JS

### PR DESCRIPTION
**Pull request by adek05**
Currently using custom parser API implies using ASTFormatter "estree".
 
This does not allow for using prettier for simple GraphQL codemodding or using custom GraphQL parser.

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
I like the idea.

**Comment by fisker** [comment]
I'm going to rebase this, and accept it.

**Comment by thorn0** [comment]
> The --parser CLI option may be a path to a node.js module exporting a parse function.

What about this way to specify custom parsers?

**Comment by fisker** [comment]
> What about this way to specify custom parsers? How can be astFormat passed in that case?

You are right, to do this, we have to add `astFormat` option, and I think we won't add it. 

Another problem is if we drop `astFormat` in `normalizeOptions`, this function won't get it.

I didn't think through.

**Comment by thorn0** [comment]
As a probably-good-enough solution we can allow attaching the `astFormat` property directly to the function:
```js
const astFormat = opts.astFormat || opts.parser.astFormat || "estree";
```

**Comment by thorn0** [comment]
Overall, the plugin API can do everything custom parsers can. Custom parsers should have been deprecated long time ago.
See https://github.com/prettier/prettier/issues/3150#issuecomment-392622776

**Comment by fisker** [comment]
I agree, let's close this then.

**Pull request closed without merging**
