### PR TITLE
Add new workflow to prevent updating `users.yml`

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

For https://github.com/prettier/prettier/pull/11752#issuecomment-963080952

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by fisker — APPROVED** [review]

**Comment by sosukesuzuki** [comment]
`GITHUB_TOKEN` does not seem to have enough permissions...

**Review by lipis — APPROVED** [review]

**Comment by fisker** [comment]
> `GITHUB_TOKEN` does not seem to have enough permissions...

Is it used to close PR? We should not auto close it, PR may intend to change it, a comment is good enough.

**Review by fisker — APPROVED** [review]
Feel free to merge when you are ready.

**Comment by fisker** [comment]
@sosukesuzuki [prevent-file-change-action](https://github.com/xalvarez/prevent-file-change-action)

**Comment by sosukesuzuki** [comment]
Ah sorry I didn't notice this, thank you.

**Pull request merged**
