### PR TITLE
Revert #7367 "Fix: remove unnecessary parens when yielding jsx"

### LINKED ISSUE #8999: Add parens back for yielding jsx
`Espree` throws error when yielding JSX without parenthesis.

Related issue 

- https://github.com/eslint/espree/issues/355
- https://github.com/acornjs/acorn-jsx/issues/82

It has been a long time since these issues, and it's still not fixed.

I suggest put parens back.

This will revert #7367 

//cc @cola119 @brainkim

### PR DESCRIPTION
**Pull request by fisker**
Without parens, eslint default parser `espree` can't parse it

Fixes #8999

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
need changelog?

**Review by evilebottnawi — COMMENTED** [review]
I think we need changelog here

**Review by sosukesuzuki — APPROVED** [review]

**Review by evilebottnawi — APPROVED** [review]

**Comment by brainkim** [comment]
Maybe this change can be re-reverted now that https://github.com/acornjs/acorn-jsx/pull/115 has landed? What was the original tooling which caused an error @fisker.

**Comment by fisker** [comment]
I think we should keep it, at least keep it for a  while, because people may have a old version of eslint.

**Comment by brainkim** [comment]
@fisker I am the author of Crank.js, which might be the most well-known library which yields JSX elements. I’m currently stuck on a previous version of prettier because this is the diff I see.
```
diff --git a/examples/async-generator/src/index.tsx b/examples/async-generator/src/index.tsx
index 09d1ba9..b906572 100644
--- a/examples/async-generator/src/index.tsx
+++ b/examples/async-generator/src/index.tsx
@@ -11,7 +11,7 @@ async function* List(
 	for await ({elems} of this) {
 		i++;
 		if (i % 5 === 0) {
-			yield <div>Loading {elems.length} items...</div>;
+			yield (<div>Loading {elems.length} items...</div>);
 			await new Promise((resolve) => setTimeout(resolve, 4000));
 		}
 		yield (
diff --git a/examples/hackernews/src/index.jsx b/examples/hackernews/src/index.jsx
index 8fa5a15..edff153 100644
--- a/examples/hackernews/src/index.jsx
+++ b/examples/hackernews/src/index.jsx
@@ -129,14 +129,14 @@ async function* App() {
 	route();
 	try {
 		for await (const _ of this) {
-			yield <Loading />;
+			yield (<Loading />);
 			switch (data.route) {
 				case "item": {
-					await (yield <Item {...data} />);
+					await (yield (<Item {...data} />));
 					break;
 				}
 				case "top": {
-					await (yield <List {...data} />);
+					await (yield (<List {...data} />));
 					break;
 				}
 			}
diff --git a/package.json b/package.json
index 3924d51..0b402d7 100644
--- a/package.json
+++ b/package.json
@@ -132,7 +132,7 @@
     "jest": "^26.1.0",
     "lint-staged": "^10.2.11",
     "magic-string": "^0.25.7",
-    "prettier": "^2.0.4",
+    "prettier": "^2.1.1",
     "rollup": "^2.18.1",
     "rollup-plugin-typescript2": "^0.27.1",
     "shx": "^0.3.2",
diff --git a/src/__tests__/cascades.tsx b/src/__tests__/cascades.tsx
index a268ba8..08c4d89 100644
--- a/src/__tests__/cascades.tsx
+++ b/src/__tests__/cascades.tsx
@@ -44,7 +44,7 @@ describe("parent-child refresh cascades", () => {
 		function* Component(this: Context) {
 			while (true) {
 				this.refresh();
-				yield <div>Hello</div>;
+				yield (<div>Hello</div>);
 			}
 		}
 
@@ -60,10 +60,10 @@ describe("parent-child refresh cascades", () => {
 
 	test("async generator calls refresh directly", async () => {
 		async function* Component(this: Context) {
-			yield <span>Hello</span>;
+			yield (<span>Hello</span>);
 			this.refresh();
 			for await (const _ of this) {
-				yield <span>Hello again</span>;
+				yield (<span>Hello again</span>);
 			}
 		}
 
@@ -160,7 +160,7 @@ describe("parent-child refresh cascades", () => {
 			function* Child(this: Context) {
 				while (true) {
 					this.dispatchEvent(new Event("test", {bubbles: true}));
-					yield <span>child</span>;
+					yield (<span>child</span>);
 				}
 			}
 
diff --git a/src/__tests__/cleanup.tsx b/src/__tests__/cleanup.tsx
index 5af97cb..c8dcc48 100644
--- a/src/__tests__/cleanup.tsx
+++ b/src/__tests__/cleanup.tsx
@@ -36,7 +36,7 @@ describe("cleanup", () => {
 		function* Component(this: Context): Generator<Element> {
 			this.cleanup(fn);
 			while (true) {
-				yield <span>Hello</span>;
+				yield (<span>Hello</span>);
 			}
 		}
 
@@ -87,7 +87,7 @@ describe("cleanup", () => {
 			this.cleanup(fn);
 			for await (const _ of this) {
 				await new Promise((resolve) => setTimeout(resolve, 1));
-				yield <span>Hello</span>;
+				yield (<span>Hello</span>);
 			}
 		}
 
@@ -115,7 +115,7 @@ describe("cleanup", () => {
 		function* Component(this: Context): Generator<Element> {
 			this.cleanup(fn);
 			while (true) {
-				yield <span>Hello</span>;
+				yield (<span>Hello</span>);
 			}
 		}
 
@@ -143,7 +143,7 @@ describe("cleanup", () => {
 			this.cleanup(fn1);
 			this.cleanup(fn2);
 			while (true) {
-				yield <span>Hello</span>;
+				yield (<span>Hello</span>);
 			}
 		}
 
@@ -175,7 +175,7 @@ describe("cleanup", () => {
 			while (true) {
 				this.cleanup(fn1);
 				this.cleanup(fn2);
-				yield <span>{i++}</span>;
+				yield (<span>{i++}</span>);
 			}
 		}
 
@@ -239,7 +239,7 @@ describe("cleanup", () => {
 		function* Component(this: Context): Generator<Element> {
 			this.cleanup(fn);
 			while (true) {
-				yield <Child />;
+				yield (<Child />);
 			}
 		}
 
@@ -269,7 +269,7 @@ describe("cleanup", () => {
 		function* Component(this: Context): Generator<Element> {
 			this.cleanup(fn);
 			while (true) {
-				yield <Child />;
+				yield (<Child />);
 			}
 		}
 
@@ -331,7 +331,7 @@ describe("cleanup", () => {
 		function* Component(this: Context): Generator<Element> {
 			this.cleanup(fn);
 			while (true) {
-				yield <Hanging />;
+				yield (<Hanging />);
 			}
 		}
 
diff --git a/src/__tests__/components.tsx b/src/__tests__/components.tsx
index 508c1c8..4570ff0 100644
--- a/src/__tests__/components.tsx
+++ b/src/__tests__/components.tsx
@@ -345,7 +345,7 @@ describe("sync generator component", () => {
 					return <span>Final</span>;
 				}
 
-				yield <span>{message}</span>;
+				yield (<span>{message}</span>);
 			}
 		});
 
@@ -379,7 +379,7 @@ describe("sync generator component", () => {
 			ctx = this;
 			let i = 1;
 			while (true) {
-				yield <span>Hello {i++}</span>;
+				yield (<span>Hello {i++}</span>);
 			}
 		}
 
@@ -413,7 +413,7 @@ describe("sync generator component", () => {
 					component = <NestedComponent />;
 				}
 
-				yield <span>{component}</span>;
+				yield (<span>{component}</span>);
 				mounted = true;
 			}
 		}
@@ -446,7 +446,7 @@ describe("sync generator component", () => {
 					component = <NestedComponent />;
 				}
 
-				yield <span>{component}</span>;
+				yield (<span>{component}</span>);
 				mounted = true;
 			}
 		}
@@ -469,9 +469,9 @@ describe("sync generator component", () => {
 		function* Component(this: Context): Generator<Child> {
 			ctx = this;
 			yield null;
-			yield <span>Hello</span>;
+			yield (<span>Hello</span>);
 			yield null;
-			yield <span>Hello again</span>;
+			yield (<span>Hello again</span>);
 		}
 
 		renderer.render(
@@ -495,9 +495,9 @@ describe("sync generator component", () => {
 		let ctx!: Context;
 		function* Component(this: Context): Generator<Child> {
 			ctx = this;
-			yield <span>1</span>;
-			yield <div>2</div>;
-			yield <span>3</span>;
+			yield (<span>1</span>);
+			yield (<div>2</div>);
+			yield (<span>3</span>);
 		}
 
 		renderer.render(
@@ -522,9 +522,9 @@ describe("sync generator component", () => {
 				ctx = this;
 			}
 
-			yield <span>Hello</span>;
-			yield <div>Hello</div>;
-			yield <span>Hello</span>;
+			yield (<span>Hello</span>);
+			yield (<div>Hello</div>);
+			yield (<span>Hello</span>);
 		}
 
 		renderer.render(
@@ -598,7 +598,7 @@ describe("sync generator component", () => {
 			ctx = this;
 			let i = 0;
 			for (const _ of this) {
-				const yielded = yield <Component>Hello {i++}</Component>;
+				const yielded = yield (<Component>Hello {i++}</Component>);
 				mock((yielded as any).outerHTML);
 			}
 		}
@@ -638,7 +638,7 @@ describe("sync generator component", () => {
 			let i = 0;
 			while (true) {
 				i++;
-				yield <div>Hello {i}</div>;
+				yield (<div>Hello {i}</div>);
 			}
 		}
 		renderer.render(
@@ -692,7 +692,7 @@ describe("sync generator component", () => {
 			let i = 0;
 			while (true) {
 				i++;
-				yield <div>Hello {i}</div>;
+				yield (<div>Hello {i}</div>);
 			}
 		}
 
@@ -724,7 +724,7 @@ describe("sync generator component", () => {
 		function* Component(): Generator<Element> {
 			let i = 0;
 			while (true) {
-				const node: any = yield <div id={i}>{i}</div>;
+				const node: any = yield (<div id={i}>{i}</div>);
 				html = node.outerHTML;
 				i++;
 			}
@@ -823,7 +823,7 @@ describe("sync generator component", () => {
 			try {
 				let i = 0;
 				while (true) {
-					yield <div>Hello {i++}</div>;
+					yield (<div>Hello {i++}</div>);
 				}
 			} finally {
 				mock();
@@ -846,7 +846,7 @@ describe("sync generator component", () => {
 			try {
 				let i = 0;
 				while (true) {
-					yield <div>Hello {i++}</div>;
+					yield (<div>Hello {i++}</div>);
 				}
 			} finally {
 				mock();
@@ -919,7 +919,7 @@ describe("async generator component", () => {
 					return <span>Final</span>;
 				}
 
-				yield <span>{message}</span>;
+				yield (<span>{message}</span>);
 			}
 		});
 
@@ -960,9 +960,9 @@ describe("async generator component", () => {
 			{message}: {message: string},
 		): AsyncGenerator<Element> {
 			for await ({message} of this) {
-				yield <span>Loading</span>;
+				yield (<span>Loading</span>);
 				await new Promise((resolve1) => (resolve = resolve1));
-				yield <span>{message}</span>;
+				yield (<span>{message}</span>);
 			}
 		}
 
@@ -1000,8 +1000,8 @@ describe("async generator component", () => {
 			{message}: {message: string},
 		): AsyncGenerator<Element> {
 			for await ({message} of this) {
-				yield <span>Loading</span>;
-				yield <span>{message}</span>;
+				yield (<span>Loading</span>);
+				yield (<span>{message}</span>);
 			}
 		}
 
@@ -1057,7 +1057,7 @@ describe("async generator component", () => {
 		async function* Component(this: Context) {
 			let i = 0;
 			for await (const _ of this) {
-				const node: any = yield <div id={i}>{i}</div>;
+				const node: any = yield (<div id={i}>{i}</div>);
 				html = node.outerHTML;
 				i++;
 			}
@@ -1092,7 +1092,7 @@ describe("async generator component", () => {
 		async function* Component(this: Context) {
 			let i = 0;
 			for await (const _ of this) {
-				const node: any = yield <Async id={i} />;
+				const node: any = yield (<Async id={i} />);
 				html = node.then((node: HTMLElement) => node.outerHTML);
 				await node;
 				i++;
@@ -1117,9 +1117,9 @@ describe("async generator component", () => {
 	test("yield before for await loop", async () => {
 		async function* Component(this: Context) {
 			let i = 0;
-			yield <div>{i++}</div>;
+			yield (<div>{i++}</div>);
 			for await (const _ of this) {
-				yield <div>{i++}</div>;
+				yield (<div>{i++}</div>);
 			}
 		}
 
@@ -1224,7 +1224,7 @@ describe("async generator component", () => {
 			try {
 				let i = 0;
 				for await (const _ of this) {
-					yield <div>Hello {i++}</div>;
+					yield (<div>Hello {i++}</div>);
 				}
 			} finally {
 				mock();
@@ -1253,7 +1253,7 @@ describe("async generator component", () => {
 
 		async function* AsyncGen(this: Context) {
 			for await (const _ of this) {
-				yield <span>true</span>;
+				yield (<span>true</span>);
 			}
 		}
 
diff --git a/src/__tests__/copy.tsx b/src/__tests__/copy.tsx
index 095ac71..a02352f 100644
--- a/src/__tests__/copy.tsx
+++ b/src/__tests__/copy.tsx
@@ -256,7 +256,7 @@ describe("Copy", () => {
 		async function* Component(this: Context) {
 			for await (const _ of this) {
 				await new Promise((resolve) => setTimeout(resolve));
-				yield <span>Hello</span>;
+				yield (<span>Hello</span>);
 			}
 		}
 
diff --git a/src/__tests__/errors.tsx b/src/__tests__/errors.tsx
index 5b0cbf6..f84dece 100644
--- a/src/__tests__/errors.tsx
+++ b/src/__tests__/errors.tsx
@@ -130,7 +130,7 @@ describe("errors", () => {
 		async function* Component(this: Context) {
 			try {
 				for await (const _ of this) {
-					yield <Thrower />;
+					yield (<Thrower />);
 				}
 			} catch (err) {
 				mock();
@@ -161,7 +161,7 @@ describe("errors", () => {
 		async function* Component(this: Context) {
 			try {
 				for await (const _ of this) {
-					yield <Thrower />;
+					yield (<Thrower />);
 				}
 			} catch (err) {
 				mock();
@@ -186,7 +186,7 @@ describe("errors", () => {
 
 		function* Component(): Generator<Child> {
 			try {
-				yield <Thrower />;
+				yield (<Thrower />);
 			} catch (err) {
 				return <span>Error</span>;
 			}
@@ -207,7 +207,7 @@ describe("errors", () => {
 
 		function* Component(): Generator<Child> {
 			try {
-				yield <PassThrough />;
+				yield (<PassThrough />);
 			} catch (err) {
 				return <span>Error</span>;
 			}
@@ -221,7 +221,7 @@ describe("errors", () => {
 		let ctx!: Context;
 		function* Thrower(this: Context): Generator<Child> {
 			ctx = this;
-			yield <div>Hello</div>;
+			yield (<div>Hello</div>);
 			throw new Error("nested functions throw independently");
 		}
 
@@ -232,7 +232,7 @@ describe("errors", () => {
 		function* Component(): Generator<Child> {
 			while (true) {
 				try {
-					yield <PassThrough />;
+					yield (<PassThrough />);
 				} catch (err) {
 					return <span>Error</span>;
 				}
@@ -252,7 +252,7 @@ describe("errors", () => {
 
 		function* Component(): Generator<Child> {
 			try {
-				yield <Thrower />;
+				yield (<Thrower />);
 			} catch (err) {
 				return <span>Error</span>;
 			}
@@ -290,7 +290,7 @@ describe("errors", () => {
 					);
 				} catch (err) {
 					mock(err);
-					yield <div>Restarting</div>;
+					yield (<div>Restarting</div>);
 				}
 			}
 		}
diff --git a/src/__tests__/html.tsx b/src/__tests__/html.tsx
index e5ed4e1..e01503e 100644
--- a/src/__tests__/html.tsx
+++ b/src/__tests__/html.tsx
@@ -162,7 +162,7 @@ describe("render", () => {
 			let i = 0;
 			try {
 				while (true) {
-					yield <div>{i++}</div>;
+					yield (<div>{i++}</div>);
 				}
 			} finally {
 				mock();
@@ -182,7 +182,7 @@ describe("render", () => {
 			// resolve to <div>1</div>
 			try {
 				for await (const _ of this) {
-					yield <div>{i++}</div>;
+					yield (<div>{i++}</div>);
 				}
 			} finally {
 				mock();
@@ -205,7 +205,7 @@ describe("render", () => {
 			let i = 0;
 			try {
 				while (true) {
-					yield <div>{i++}</div>;
+					yield (<div>{i++}</div>);
 				}
 			} finally {
 				mock();
diff --git a/src/__tests__/provisions.tsx b/src/__tests__/provisions.tsx
index d7a9966..798efea 100644
--- a/src/__tests__/provisions.tsx
+++ b/src/__tests__/provisions.tsx
@@ -14,7 +14,7 @@ describe("context", () => {
 		let i = 1;
 		for (const {children, message = "Hello "} of this) {
 			this.provide("greeting", message + i++);
-			yield <Fragment>{children}</Fragment>;
+			yield (<Fragment>{children}</Fragment>);
 		}
 	}
 
diff --git a/src/__tests__/races.tsx b/src/__tests__/races.tsx
index 0c7a754..6e7c11b 100644
--- a/src/__tests__/races.tsx
+++ b/src/__tests__/races.tsx
@@ -165,9 +165,9 @@ describe("races", () => {
 			let i = 0;
 			for await (const _ of this) {
 				if (i % 2 === 0) {
-					yield <Slow />;
+					yield (<Slow />);
 				} else {
-					yield <Fast />;
+					yield (<Fast />);
 				}
 
 				i++;
@@ -211,9 +211,9 @@ describe("races", () => {
 			let i = 0;
 			for await (const _ of this) {
 				if (i % 2 === 0) {
-					yield <Slow />;
+					yield (<Slow />);
 				} else {
-					yield <Fast />;
+					yield (<Fast />);
 				}
 
 				i++;
@@ -300,7 +300,7 @@ describe("races", () => {
 			slowFn();
 			await new Promise((resolve) => setTimeout(resolve, 200));
 			for await (const _ of this) {
-				yield <span>Slow {i}</span>;
+				yield (<span>Slow {i}</span>);
 			}
 		}
 
@@ -349,7 +349,7 @@ describe("races", () => {
 		async function* Fast(this: Context): AsyncGenerator<Element> {
 			await new Promise((resolve) => setTimeout(resolve, 100));
 			for await (const _ of this) {
-				yield <span>Fast</span>;
+				yield (<span>Fast</span>);
 			}
 		}
 
@@ -373,7 +373,7 @@ describe("races", () => {
 		async function* Slow(this: Context): AsyncGenerator<Element> {
 			await new Promise((resolve) => setTimeout(resolve, 200));
 			for await (const _ of this) {
-				yield <span>Slow</span>;
+				yield (<span>Slow</span>);
 			}
 		}
 
@@ -408,7 +408,7 @@ describe("races", () => {
 
 		function* SlowGen(): Generator<Element> {
 			while (true) {
-				yield <Slow />;
+				yield (<Slow />);
 			}
 		}
 
@@ -438,7 +438,7 @@ describe("races", () => {
 
 		function* FastGen(): Generator<Element> {
 			while (true) {
-				yield <Fast />;
+				yield (<Fast />);
 			}
 		}
 
diff --git a/src/__tests__/refs.tsx b/src/__tests__/refs.tsx
index 0306d09..0e41086 100644
--- a/src/__tests__/refs.tsx
+++ b/src/__tests__/refs.tsx
@@ -76,7 +76,7 @@ describe("keys", () => {
 		const fn = jest.fn();
 		function* Component(): Generator<Element> {
 			while (true) {
-				yield <span>Hello</span>;
+				yield (<span>Hello</span>);
 			}
 		}
 
@@ -114,7 +114,7 @@ describe("keys", () => {
 		const fn = jest.fn();
 		async function* Component(this: Context): AsyncGenerator<Element> {
 			for await (const _ of this) {
-				yield <span>Hello</span>;
+				yield (<span>Hello</span>);
 			}
 		}
 
diff --git a/src/__tests__/reuse.tsx b/src/__tests__/reuse.tsx
index 02e6f04..e65e227 100644
--- a/src/__tests__/reuse.tsx
+++ b/src/__tests__/reuse.tsx
@@ -66,7 +66,7 @@ describe("element reuse", () => {
 		function* Component() {
 			fn();
 			while (true) {
-				yield <span>1</span>;
+				yield (<span>1</span>);
 			}
 		}
 
diff --git a/src/__tests__/schedule.tsx b/src/__tests__/schedule.tsx
index 09f8e92..cbb4a5b 100644
--- a/src/__tests__/schedule.tsx
+++ b/src/__tests__/schedule.tsx
@@ -83,7 +83,7 @@ describe("schedule", () => {
 			this.schedule(fn);
 			let i = 0;
 			while (true) {
-				yield <span>{i++}</span>;
+				yield (<span>{i++}</span>);
 			}
 		}
 
@@ -112,7 +112,7 @@ describe("schedule", () => {
 			let i = 0;
 			while (true) {
 				this.schedule(fn);
-				yield <span>{i++}</span>;
+				yield (<span>{i++}</span>);
 			}
 		}
 
@@ -207,7 +207,7 @@ describe("schedule", () => {
 			this.schedule(fn);
 			let i = 0;
 			for await (const _ of this) {
-				yield <span>{i++}</span>;
+				yield (<span>{i++}</span>);
 			}
 		}
 
@@ -236,7 +236,7 @@ describe("schedule", () => {
 			let i = 0;
 			for await (const _ of this) {
 				this.schedule(fn);
-				yield <span>{i++}</span>;
+				yield (<span>{i++}</span>);
 			}
 		}
 
@@ -267,7 +267,7 @@ describe("schedule", () => {
 			this.schedule(fn);
 			this.schedule(fn);
 			while (true) {
-				yield <span>Hello</span>;
+				yield (<span>Hello</span>);
 			}
 		}
 
@@ -291,7 +291,7 @@ describe("schedule", () => {
 			this.schedule(fn1);
 			this.schedule(fn2);
 			while (true) {
-				yield <span>Hello</span>;
+				yield (<span>Hello</span>);
 			}
 		}
 
@@ -317,7 +317,7 @@ describe("schedule", () => {
 				this.schedule(fn1);
 				this.schedule(fn2);
 				this.schedule(fn2);
-				yield <span>{i++}</span>;
+				yield (<span>{i++}</span>);
 			}
 		}
 
@@ -372,7 +372,7 @@ describe("schedule", () => {
 				if (i % 2 === 0) {
 					this.schedule(() => this.refresh());
 				}
-				yield <span>{i++}</span>;
+				yield (<span>{i++}</span>);
 			}
 		}
 
@@ -403,11 +403,11 @@ describe("schedule", () => {
 	test("refresh copy", () => {
 		function* Component(this: Context): Generator<Element> {
 			this.schedule(() => this.refresh());
-			const span = (yield <span />) as HTMLSpanElement;
+			const span = (yield (<span />)) as HTMLSpanElement;
 			while (true) {
 				span.className = "manual";
 				span.textContent = "Hello world";
-				yield <Copy />;
+				yield (<Copy />);
 			}
 		}
 
@@ -429,12 +429,12 @@ describe("schedule", () => {
 			while (true) {
 				if (span === undefined) {
 					this.schedule(() => this.refresh());
-					span = (yield <span />) as HTMLSpanElement;
+					span = (yield (<span />)) as HTMLSpanElement;
 				} else {
 					span.className = "manual";
 					span.textContent = (i++).toString();
 					span = undefined;
-					yield <Copy />;
+					yield (<Copy />);
 				}
 			}
 		}
@@ -460,7 +460,7 @@ describe("schedule", () => {
 		function* Component(this: Context): Generator<Element> {
 			this.schedule(fn);
 			while (true) {
-				yield <Child />;
+				yield (<Child />);
 			}
 		}
 
@@ -519,7 +519,7 @@ describe("schedule", () => {
 		function* Component(this: Context): Generator<Element> {
 			this.schedule(fn);
 			while (true) {
-				yield <Child>async</Child>;
+				yield (<Child>async</Child>);
 			}
 		}
 
@@ -547,7 +547,7 @@ describe("schedule", () => {
 			let i = 0;
 			while (true) {
 				this.schedule(fn);
-				yield <Child>async {i++}</Child>;
+				yield (<Child>async {i++}</Child>);
 			}
 		}
 
@@ -585,7 +585,7 @@ describe("schedule", () => {
 		function* Component(this: Context): Generator<Element> {
 			this.schedule(fn);
 			while (true) {
-				yield <Hanging />;
+				yield (<Hanging />);
 			}
 		}
 
diff --git a/src/__tests__/suspense.tsx b/src/__tests__/suspense.tsx
index b8ed53d..7a68d09 100644
--- a/src/__tests__/suspense.tsx
+++ b/src/__tests__/suspense.tsx
@@ -22,7 +22,7 @@ async function* Suspense(
 	}: {children: Children; fallback: Children; timeout?: number},
 ): AsyncGenerator<Children> {
 	for await ({children, fallback, timeout = 1000} of this) {
-		yield <Fallback timeout={timeout}>{fallback}</Fallback>;
+		yield (<Fallback timeout={timeout}>{fallback}</Fallback>);
 		yield children;
 	}
 }
diff --git a/src/__tests__/types.tsx b/src/__tests__/types.tsx
index 4340f75..4f3407b 100644
--- a/src/__tests__/types.tsx
+++ b/src/__tests__/types.tsx
@@ -130,7 +130,7 @@ describe("types", () => {
 				let newMessage: string = initialProps.message;
 				// @ts-expect-error
 				let newUnexpected = newProps.unexpected;
-				yield <div></div>;
+				yield (<div></div>);
 			}
 
 			return <div></div>;
@@ -152,7 +152,7 @@ describe("types", () => {
 				let newMessage: string = initialProps.message;
 				// @ts-expect-error
 				let newUnexpected = newProps.unexpected;
-				yield <div></div>;
+				yield (<div></div>);
 			}
 
 			return <div></div>;
@@ -194,7 +194,7 @@ describe("types", () => {
 			this,
 			props,
 		) {
-			yield <div></div>;
+			yield (<div></div>);
 		};
 	});
 
@@ -212,7 +212,7 @@ describe("types", () => {
 				let newMessage: string = initialProps.message;
 				// @ts-expect-error
 				let newUnexpected = newProps.unexpected;
-				yield <div></div>;
+				yield (<div></div>);
 			}
 
 			return <div></div>;
@@ -234,7 +234,7 @@ describe("types", () => {
 				let newMessage: string = initialProps.message;
 				// @ts-expect-error
 				let newUnexpected = newProps.unexpected;
-				yield <div></div>;
+				yield (<div></div>);
 			}
 
 			return <div></div>;
@@ -278,7 +278,7 @@ describe("types", () => {
 				let newMessage: string = props.message;
 				// @ts-expect-error
 				let newUnexpected = props.unexpected;
-				yield <div></div>;
+				yield (<div></div>);
 			}
 
 			return <div></div>;
@@ -297,7 +297,7 @@ describe("types", () => {
 				let newMessage: string = props.message;
 				// @ts-expect-error
 				let newUnexpected = props.unexpected;
-				yield <div></div>;
+				yield (<div></div>);
 			}
 
 			return <div></div>;
diff --git a/website/src/playground.tsx b/website/src/playground.tsx
index 1d3a63a..d3b031c 100644
--- a/website/src/playground.tsx
+++ b/website/src/playground.tsx
@@ -8,7 +8,7 @@ import "./index.css";
 
 export function* Editor(this: Context, {value}: {value: string}) {
 	setTimeout(() => this.refresh());
-	const el = yield <div />;
+	const el = yield (<div />);
 	const cm = CodeMirror(el, {
 		value,
 		tabSize: 2,
@@ -29,7 +29,7 @@ export function* Editor(this: Context, {value}: {value: string}) {
 			cm.setValue(newValue);
 		}
 
-		yield <div class="editor" />;
+		yield (<div class="editor" />);
 	}
 }
 
@@ -58,7 +58,7 @@ const babelOptions = {
 async function* Preview(this: Context) {
 	for await (let {id, code} of this) {
 		try {
-			yield <div id={id} class="preview" />;
+			yield (<div id={id} class="preview" />);
 			// TODO: resume async generators only after parent has committed or something
 			await new Promise((resolve) => setTimeout(resolve, 0));
 			code = (Babel.transform(code, babelOptions) as any).code;
diff --git a/website/webpack.tsx b/website/webpack.tsx
index b92d7c5..fcb7c96 100644
--- a/website/webpack.tsx
+++ b/website/webpack.tsx
@@ -206,7 +206,7 @@ export function* Page(this: Context, {storage, children}: PageProps) {
 			storage = nextStorage;
 		}
 
-		yield <Fragment>{children}</Fragment>;
+		yield (<Fragment>{children}</Fragment>);
 	}
 }
```

Given that yielding JSX elements is seldom used, maybe we could defer to my use-case, especially if the tooling which you need can be upgraded?

**Comment by fisker** [comment]
I don't have the problem myself, but people may use a old `ESLint`.

Even if they use the latest version of `ESLint`, but if it was installed before `acorn-jsx@5.3.1` release, they will have `acorn-jsx@5.3.0` installed, it won't auto update because [`espree` use `^5.2.0`](https://github.com/eslint/espree/blob/dbdd5a7c099547c57213e22f2c464e27ab88ae52/package.json#L22)

Anyway, yielding jsx with eslint problem is not reported until #8999, maybe people won't notice this change at all.

**Comment by brainkim** [comment]
> Anyway, yielding jsx with eslint problem is not reported until #8999, maybe people won't notice this change at all.

I don’t understand.

> I don't have the problem myself, but people may use a old ESLint.

Yeah that’s what I’m saying, I’m okay with this change but if you’re not personally experiencing this problem then can we at least determine the point when it’s okay to undo this change, which is disruptive for my framework? Like if you’re the only person who yielded JSX expressions in the first place anyways, maybe we can just upgrade?

**Comment by fisker** [comment]
How about after next ESLint release?

**Comment by brodybits** [comment]
> Without parens, eslint default parser `espree` can't parse it

Do we have this scenario in a test case?

And I suspect we could solve this by adding acorn-jsx@5.3.1 to our own dependencies.

**Comment by fisker** [comment]
@brodybits  see https://github.com/prettier/prettier/pull/9000/commits/ba171519a366e087ef4636bc1b39d2699c274733 from #9000

**Comment by brainkim** [comment]
> How about after next ESLint release?

@fisker If you mean a minor or patch release then sure!

**Comment by fisker** [comment]
@brodybits And you misunderstood the problem here, we don't have `espree` parser yet, so we won't have any problem on ourside, but if you use ESLint(old version) and Prettier together, Prettier will remove parens, and ESLint will fail on parse.

**Comment by fisker** [comment]
@brainkim 

To make it safe, we need change `acorn-jsx` in `espree` to `>=5.3.1`, and change `espree` in `eslint` to `>=___the updated espree version ___`, but this may take too long.

When eslint release a new version(any version), if they don't have any other dependency of `acorn-jsx`, upgrade eslint will update `acorn-jsx`.

**Comment by fisker** [comment]
> I don’t understand. I am experiencing issues because of this change.

Like you said, "you’re the only person who had issues with yielded JSX expressions in the first place", I actually mean, re-revert this, maybe people won't notice the changes.

**Comment by brainkim** [comment]
@fisker
> To make it safe, we need change acorn-jsx in espree to >=5.3.1, and change espree in eslint to >=___the updated espree version ___, but this may take too long.

It seems like the current espree version is ^5.2.0 which should cover 5.3.1, no?

> Like you said, "you’re the only person who had issues with yielded JSX expressions in the first place", I actually mean, re-revert this, maybe people won't notice the changes.

Sorry, I still don’t understand the point you’re trying to make. My bad! What I do notice is that the main reason to revert the change originally was so that you could add a PR with the Espree parser to the codebase (https://github.com/prettier/prettier/pull/9000), which I didn’t understand in the original revert PR, which makes me wonder if I should have agreed so readily. In other words, there was no actual codebase besides prettier where you were experiencing issues, right?

**Comment by fisker** [comment]
> It seems like the current espree version for acorn-jsx is ^5.2.0 which should cover 5.3.1, no?

Yes, but if I have a project with `"dependencies": {"acorn-jsx": "5.2.0"}`, the `acorn-jsx` will never get updated, even if I re-install `eslint`, because `5.2.0` satisfy both my package and `espree`, I'm just saying it's possible.

**Comment by brodybits** [comment]
Couldn't Prettier resolve this by using resolutions?

**Comment by fisker** [comment]
> Couldn't Prettier resolve this by using resolutions?

No, we don't use `espree`, problem is our output.

---

Similar problem,  #8896, check this comment https://github.com/prettier/prettier/pull/8896#issuecomment-678689272

**Pull request merged**
