### PR TITLE
Update single quote option in README 

### PR DESCRIPTION
**Pull request by tdeschryver**
Suggested change for #1947

### CODE REVIEW

**Comment by azz** [comment]
Actually it's only if the number of `'` outweighs the number of `"`.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20arr%20%3D%20%5B%20'%5C%22'%2C%20'%5C%5C''%2C%20'%5C%5C'%5C%22'%2C%20'%5C%5C'%5C%5C'%5C%22'%2C%20'%5C%5C'%5C%22%5C%22'%20%5D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by tdeschryver** [comment]
My bad, I hadn't taken a thorough look at the test cases. I will update the commit later today.
But basically: if the number of quotes outweighs the other quote, the quote with the lowest numbers will be used?
If this is correct, is it OK to put it like that in the README?

**Comment by azz** [comment]
That's correct.

**Comment by vjeux** [comment]
Thanks!

**Pull request merged**
