### PR TITLE
Add --noglob cli option for processing exact the passed files

### PR DESCRIPTION
**Pull request by AzazKamaz**
I faced problem with configuring git hooks with [lint-staged](https://github.com/okonet/lint-staged) on sapper framework. lint-staged starts prettier and passes changed files with arguments, but in [sapper](https://sapper.svelte.dev) there are routes with name `[name].svelte`, and prettier thinks that is is a regexp. So I have added parameter (--noglob) that disables any logic on filenames and just keeps it as you write, so it will process exactly what you have passed

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by AzazKamaz** [comment]
With this option, prettier will work like [eslint](https://eslint.org). There are no such logic with glob)

**Comment by kachkaev** [comment]
This CLI option should be also helpful to those using dynamic routing in Next.js https://github.com/zeit/next.js#dynamic-routing. The PR resolves https://github.com/prettier/prettier/issues/6344.

Instead of tweaking Prettier, the solution might actually come from https://github.com/okonet/lint-staged/pull/698 (see discussion in https://github.com/okonet/lint-staged/issues/676). The benefit in that approach is that we don't need any extra CLI flags in Prettier, which is great.

If this PR gets accepted, it might be worth updating https://prettier.io/docs/en/precommit.html as well.

**Comment by AzazKamaz** [comment]
> Instead of tweaking Prettier, the solution might actually come from [okonet/lint-staged#698](https://github.com/okonet/lint-staged/pull/698) (see discussion in [okonet/lint-staged#676](https://github.com/okonet/lint-staged/issues/676)). The benefit in that approach is that we don't need any extra CLI flags in Prettier, which is great.

If [okonet/lint-staged](https://github.com/okonet/lint-staged) will provide escaped filenames, than [eslint/eslint](https://github.com/eslint/eslint) will not find them, because there are no globbing on [] and it will try to find file like `\[test\].js`

**Comment by alexerhardt** [comment]
I'm using Next.js with a Prettier file watcher and this feature would be a lifesaver for me. As it stands dynamic routes throw errors on save, and I can't see an easy solution to this problem. Thanks for the effort @AzazKamaz - hope it gets accepted.

**Comment by lydell** [comment]
Random thought: Maybe it would even be nice if Prettier didn’t support `[abc]` syntax at all. I’ve never used it. My globs are all `{a,b,c}`, `*.js` and `src/**/*.css`. ¯\\\_(ツ)\_/¯

**Comment by evilebottnawi** [comment]
Same thread in stylelint https://github.com/stylelint/stylelint/pull/4286, here eslint solution https://github.com/eslint/eslint/blob/d08683e3c807f92daf266894093c70f8d5ac6afa/lib/cli-engine/file-enumerator.js#L292, i think we should use it

**Comment by lydell** [comment]
@evilebottnawi Ah – first treat as literal file name, and if no such file exists then treat as glob? Sounds good to me.

(We could potentially end up in the reverse situation – a file on disk prevents someone’s glob to be treated as a glob, but that should be workaround-able by adjusting the glob pattern.)

**Comment by lydell** [comment]
This is now tracked in #6854.

**Pull request closed without merging**
