### PR TITLE
Update `@babel/parser` to 7.22.0

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Updates to https://babel.dev/blog/2023/05/26/7.22.0

I'll create PRs to add support for new syntaxes after this is merged.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
https://github.com/babel/babel/issues/15664

**Comment by sosukesuzuki** [comment]
Thank you, I just created reproducing repo https://github.com/sosukesuzuki-sandbox/babel-7.22-esbuild-warnig-reproducing

**Comment by fisker** [comment]
Can you update @babel/generator too?

**Review by fisker — APPROVED** [review]
Feel free to merge one the bundle issue get fixed.

**Comment by nicolo-ribaudo** [comment]
Fixed and released!

**Pull request merged**
