### PR TITLE
Drop Node.js 4 test on CI

### PR DESCRIPTION
**Pull request by fisker**
As required in https://github.com/prettier/prettier/issues/6888 , drop CI test running on node 4.
It's only two month schedule, the clock is ticking, let's get started

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by lydell** [comment]
Nice!

I wonder if we should do 2.0 items on `master` or in a 2.0 branch. To me, it seems easier to do it on master (we could make a 1.x branch if we need to make another 1.x release).

@j-f1 @evilebottnawi @lipis What do think?

**Comment by fisker** [comment]
I agree

**Comment by lipis** [comment]
my vote is to work on `next` branch instead until we release the version 2. The next branch will always be in sync with master, plus all the new changes.

**Comment by lipis** [comment]
Also all the new updates well be visible here https://github.com/prettier/prettier/pull/6773

**Comment by fisker** [comment]
@lipis one question, default branch set to `master` or `next`?

**Comment by lydell** [comment]
Are there no CI runs? Anyone knows why?

**Comment by j-f1** [comment]
I’m not sure. Could it be that it’s because we’re not targeting the `master` branch?

**Comment by fisker** [comment]
I think its master settings

**Comment by fisker** [comment]
switch base to master  runs , haha

**Comment by fisker** [comment]
still running?

**Comment by fisker** [comment]
someone please change the one in master add  next  branch, Im in bed

**Comment by fisker** [comment]
@j-f1 not here, you need change the azure-pipelines.yml in  master

**Comment by fisker** [comment]
can you try set next as default branch?

**Comment by fisker** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/release/deploy-pull-request-builds?view=azure-devops

there is a target setting

**Comment by j-f1** [comment]
Found it: https://dev.azure.com/prettier/prettier/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=5&view=Tab_Triggers, section “Pull request validation”

**Comment by fisker** [comment]
first move?

**Pull request merged**
