### PR TITLE
Do not break long `describe` calls

### PR DESCRIPTION
**Pull request by karl**
This ensures that `describe` calls in test suites are whitelisted in the same way as `it` and `test` and never break across lines.

As (briefly) discussed with @vjeux in https://github.com/prettier/prettier/issues/159

Before:

```javascript
describe(
  "does something really long and complicated so I have to write a very long name for the describe block",
  () => {
    it("an example test", done => {
      console.log("hello!");
    });
  }
);
```

After:

```javascript
describe("does something really long and complicated so I have to write a very long name for the describe block", () => {
  it("an example test", done => {
    console.log("hello!");
  });
});
```

### CODE REVIEW

**Comment by vjeux** [comment]
Awesome! do you mind rebasing and i'll merge it.

cc @matthewwithanm, we were talking about it during lunch

**Comment by karl** [comment]
Yep, working on the rebasing now!

**Comment by karl** [comment]
OK, that should be good to go! 🤞🏻

I'm heading offline now, please modify/merge as you see fit. If any tweaks are required I should be able to make them tomorrow.

**Comment by vjeux** [comment]
This looks perfect, thanks a lot!

**Pull request merged**
