### PR TITLE
Print trailing comma for rest elements in tuple types

### LINKED ISSUE #12389: Prettier removes trailing comma from multiline type with `trailingComma: all`
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAYgSwCcBnGAFUzgHV8YALANTkLQBloBzAOQEMBbHAF5swADpRs2HkmxQArnwBGzANziAvuPHos2AMpxIUACYUsNekxbso3fkJHjJimfKWqNW2JTz4oPABszalpGZjZOXgFsYQBtJ18SckoLMOtI+wAaBIA6PIMjUxTQqwjbKLhYgF1sqCqVEEyQCAwYfGhiZFAeQkIIAHcABR6ETpRA-p40TqbFQh4wAGs4GD17Vj84ZAAzQOI4Wfmllb0MBb8OZBhCOQOQOHdjYzhjVh5bOR4OOFwIQj4eDA2rZkCAeHIYBBGiA6DA+AEqHRaHBiGcwHADFBiLR8AA3WhoUFgYgzEB+faEGCDeYcAE7PZ3ABWxAAHnoLgE4ABFOQQeD0gL7JpnEjMUE6FFgQj4VrQjDS2A0Yz0ZAADgADMK+vsqPMMKD5SjmLitk0AI68+DUlpjMHEAC0UDgLxe0MIcAtRDg1K+dKQu0Fd32fHwVxuQY53MtW39DKaMB4iiVKqQACZ4-N8AELgBhCB8P1ggIBaFyfZkRNjANCkC424ASRMCFWUplMAAgiY9OhOQL9up1EA)

```sh
# Options:
--parser typescript
--trailingComma all
```

**Input:**

```jsx
type FirstTypeWithVeryLongName = {
  a: number;
}

type SecondTypeWithVeryLongName = {
  b: number;
}

type FinalTypeWithVeryLongName = [
  FirstTypeWithVeryLongName,
  ...SecondTypeWithVeryLongName[],
];
```

**Output:**

```jsx
type FirstTypeWithVeryLongName = {
  a: number;
};

type SecondTypeWithVeryLongName = {
  b: number;
};

type FinalTypeWithVeryLongName = [
  FirstTypeWithVeryLongName,
  ...SecondTypeWithVeryLongName[]
];
```

**Expected behavior:**
Prettier doesn't remove trailing comma from `FinalTypeWithVeryLongName` after `...SecondTypeWithVeryLongName[]` and thus doesn't conflict with `@typescript-eslint/comma-dangle` rule.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #12389

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Did you try to add this before?

**Comment by sosukesuzuki** [comment]
Hmm, I don't remember...

**Comment by fisker** [comment]
https://github.com/prettier/prettier/pull/6172?

**Comment by sosukesuzuki** [comment]
Tailing comma for tuple types are no longer printed by https://github.com/prettier/prettier/pull/7075.

**Review by fisker — APPROVED** [review]

**Pull request merged**
