### PR TITLE
Add Dropbox as a user on the website

### PR DESCRIPTION
**Pull request by matthew-gerstman**
This adds Dropbox to the list of prettier users. We use prettier for all of our JS code internally.

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by matthew-gerstman** [comment]
Thanks! Do you need anything on my end to merge this?

**Comment by j-f1** [comment]
Nope! Just waiting for the CI to pass.

**Comment by PatMyron** [comment]
missing `greyImage` which seems to be required if `pinned: true`:

https://github.com/prettier/prettier/blob/aec3978a134a01e62324db51985b7047cf57d71c/website/pages/en/index.js#L353-L362

https://prettier.io/

Screen Shot 2019-03-21 at 12 45 46 AM

**Comment by lydell** [comment]
@matthew-gerstman Would you be able to fix this?

**Comment by matthew-gerstman** [comment]
So sorry about this, I put up a PR here.

https://github.com/prettier/prettier/pull/5997

**Pull request merged**
