### PR TITLE
Update `execa` to v2

### PR DESCRIPTION
**Pull request by fisker**

### CODE REVIEW

**Comment by fisker** [comment]
requires "node": "^8.12.0 || >=9.7.0"

https://github.com/sindresorhus/execa/blob/a5bce3a6fc2b3f4ba39a069f0564d1dee403d9b3/package.json#L13

**Comment by evilebottnawi** [comment]
@fisker can't be merged, let's close PRs what can't be merged

**Comment by fisker** [comment]
I believe we can still update `execa` to v1.0.0, I will send another PR

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/prettier/prettier/pull/6563

**Pull request closed without merging**
