### PR TITLE
Added image for Estalee and updates users.yml

### PR DESCRIPTION
**Pull request by Flavyoo**
Added a new company entry in the users.yml file for company Estalee.

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [X] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by Flavyoo** [comment]
Ran the SVGO

**Comment by Flavyoo** [comment]
All set!

**Comment by lipis** [comment]
can you also provide the image with ratio 200x100?

**Comment by Flavyoo** [comment]
Why do I need a scale of 200x100 if the file type is svg?

**Comment by Flavyoo** [comment]
I can not make it 200x100 without loosing the aspect ratio, making the logo look really bad.

**Comment by Flavyoo** [comment]
I also don't know why the checks are failing.

**Comment by lipis** [comment]
> Why do I need a scale of 200x100 if the file type is svg?

Because all the other images have this ratio.. :)

**Comment by Flavyoo** [comment]
Will I be added to the users or no? I can’t resize the image to 200x100
cause it ruins the logo,and I don’t know if my changes are causing the
checks to fail. I can close this pull request if necessary.

**Comment by lipis** [comment]
Is it hard to create a new SVG file with 200x100 and add your logo in the middle of it?

**Comment by Flavyoo** [comment]
Is it hard to maybe not be so rude?

**Comment by lipis** [comment]
Rude?! It was an honest question and all the other images are 200x100 :) Also I rerun the checks and it's green now..

**Comment by Flavyoo** [comment]
Excuse me then. I can try when I get home. I have never done it. The png
images are 200x100. The other images, the svg ones are different sizes. You
can see it in the svg source.

**Comment by lipis** [comment]
You are right.. the SVGs are not consistent :/

**Comment by Flavyoo** [comment]
Can I keep the Svg As is? Otherwise I will use isole tool to update it.

**Comment by Flavyoo** [comment]
Is this okay to merge?

**Pull request merged**
