### PR TITLE
Update language support docs

### PR DESCRIPTION
**Pull request by timup**
This commit updates docs language to reflect the change in #4528 that removes the inferred default parser.

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by lydell** [comment]
Hmm, actually, does this file provide any useful information at all? I'd say we remove it.

**Comment by timup** [comment]
Not especially, as the same information is available in [/docs/options.md](https://github.com/prettier/prettier/blob/master/docs/options.md)

**Comment by j-f1** [comment]
Should we keep the part about the Flow test suite somewhere?

**Comment by lydell** [comment]
No, I don't think so. It was important when Prettier was new an untested, but not so much anymore. It's not even entirely true anymore (Prettier supports all Flow features, but `tests/flow` does not contain the _entire_ Flow test suite anymore).

**Comment by lipis** [comment]
So shall we remove it or what?

**Comment by lipis** [comment]
I say we kill it with fire!

**Comment by duailibe** [comment]
@timup Do you want to update the PR removing the file?

**Comment by j-f1** [comment]
IMO the facts that we require a minimum TS version and support all JS proposed features should be kept somewhere.

**Comment by duailibe** [comment]
Thank you @timup!

**Pull request merged**
