### PR TITLE
Update tests so you can run on a certain file type.

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
## Description

Before when running yarn test - it ran checking for all tests, however this proved arduous when one wants to run a test for just a certain file type or folder. With this change you can run a command which just runs the selected file type.

For example if you make a change to the Typescript formatting, instead of running
```shell
yarn test
```
You can run
```shell
yarn test:typescript
```
The latter command saving you time.

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
`yarn test js` or `yarn test format/js/`` That's what I use, should already short enough. Not worth adding those scripts.

**Comment by fisker** [comment]
FYI: you can also run `yarn test vue markdown`(multiple patterns).

**Comment by Harry-Hopkinson** [comment]
@fisker Ah, I did not realise you could do that, thanks for letting me know. Should I close this PR?

**Comment by sosukesuzuki** [comment]
Thanks for the PR! However, we don't need this change, so we close this.

**Pull request closed without merging**
