### PR TITLE
Add content to website

### PR DESCRIPTION
**Pull request by azz**
Added "usage", "options" and "editor integration" from README as separate pages.

Also added some content to the home page.

### CODE REVIEW

**Comment by azz** [comment]
Did a cleanup and created three new files:

* `/website/users.json` - List of projects using prettier.
* `/website/languages.json` - List of programming languages supported by prettier.
* `/website/editors.json` - List of editor integrations.

**Comment by vjeux** [comment]
Awesome! Let's get as much content in and we can do some cleanup in follow ups. Feel free to commit directly to master :)

**Comment by azz** [comment]
Redeployed the website, it's a manual process for now until the CNAME issue (https://github.com/prettier/prettier/pull/2241#issuecomment-312464823) is solved.

**Comment by vjeux** [comment]
I'm getting the person who has admin over the domain to look into it. Thanks for bringing it up

**Pull request merged**
