### PR TITLE
Expand directories in CLI

### LINKED ISSUE #6085: support dot pattern for CLI
**Environments:**
- Prettier Version: 1.17.0
- Running Prettier via: CLI
- Runtime: Node.js
- Operating System: no matter

**Steps to reproduce:**

```shell
node_modules/.bin/prettier . --write
```

**Expected behavior:**

Format all supported files.

**Actual behavior:**

output:
```
[error] No matching files. Patterns tried: . !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
```

**Additional info:**

All popular linters (like `stylelint` and `eslint`) support `.` pattern. I think we should do same. I don't want have list of globs. It is good for DX and 0CJS configuration.

/cc @prettier/core What do you think? I can take care about this and send a PR.

### PR DESCRIPTION
**Pull request by duailibe**
Support folders in Prettier CLI, e.g. `prettier --write .` works

@kachkaev with the update of globby we were using, if `nodeModulesDir` doesn't exist, it crashes. Can you check if my update to the plugin resolution makes sense?

TODO: 
- [ ] add tests: assert it filters by extension, assert extensions provided by plugins are included
- [ ] documentation
- [ ] changelog

Closes #6085

### CODE REVIEW

**Comment by lydell** [comment]
> If an unsupported file exists somewhere, this happens

I don't think the feature is usable if that happens, unfortunately. People won't like it. Could we make it only look at the extensions listed in the support info or whatever it's called, maybe?

**Comment by duailibe** [comment]
Oh I overlooked the extensions and thought it couldn't be done, but looks like it can!

**Comment by lydell** [comment]
Nice!

- So if you want to format all files Prettier is capable of handling in your project you can run just `prettier --write .`?
- If you don't want Prettier to format .html files, you could add `*.html` to .prettierignore.
- If you've taught Prettier how to handle other files/extensions in .prettierrc you have to list them manually. For example: `prettier --write . .prettierrc "**/*.hehe"`. I guess this isn't super common.

<details>
<summary>.prettierrc</summary>

```json
{
  "overrides": [
    {
      "files": ".prettierrc",
      "options": { "parser": "json" }
    },
    {
      "files": "*.hehe",
      "options": {
        "parser": "html"
      }
    }
  ]
}
```

</details>

**Comment by duailibe** [comment]
@lydell I'm not sure those were questions but the answers are:

1. Yes! `prettier --write **/**` will still run in all files, regardless of their extensions
2. Yes. I've thought about this and I think it's worth discussing after this PR lands. This is what #2691 is asking
3. Yes. That could also be fixed with the above (i.e. if we added a `extensions: []` config)

**Comment by duailibe** [comment]
There's still something missing: match files by their filenames instead of their extensions. Luckily globby has an option for that.

I'll see how that goes tomorrow morning.

**Comment by duailibe** [comment]
Memory leak 😔

**Comment by kachkaev** [comment]
Hi @duailibe 👋

I'm quite busy these days so won't be able to dive in, sorry for that. Perhaps @arcanis could help here? The situation when there is no `node_modules` is somewhat related to #5819, which he worked on.

**Comment by arcanis** [comment]
Hey! Unfortunately I'm afraid I won't have much resources to spend on this anytime soon 😕

**Comment by duailibe** [comment]
@kachkaev Actually the change was more related to the fact that if `nodeModulesDir` it will simply ignore instead of throwing an error like before

**Comment by duailibe** [comment]
So I ditched `globby` and wrote a little custom file finder. Obviously this is a breaking change I also included a change that this doesn't support negate patterns anymore, i.e. `prettier --write foo/ !foo/bar/`

We can continue to support it, but it was easier to drop and I judged this suits better in `.prettierignore`.

**Comment by duailibe** [comment]
@lydell what happens now is:

- if you pass `prettier --write 'foo/'` it will only try to format supported files
- if you pass `prettier --write 'foo/**'` it will try to format all files and will show that error on the unsupported files 🤷‍♂

**Comment by evilebottnawi** [comment]
@duailibe what is blocker? I think we should use same behavior as in eslint to better DX, i can investigate and put here information about how it is works in eslint

**Comment by duailibe** [comment]
@evilebottnawi not much.. we just need to iron everything out.

Also we need to coordinate this release, this is a breaking change

**Comment by arcanis** [comment]
Is there a way support for `.` in particular could be added without it being a breaking change, as a special case? Would you consider such a PR for a minor release?

**Comment by lydell** [comment]
By “stretch” I meant “stretch goals.” If we have time we can do it. (Related: I have a new idea for the CLI/API that I’ll make an issue for soon.)

**Comment by evilebottnawi** [comment]
@lydell unfortunately we cannot stretch this issue because it is really a big change and important, i can take care

**Comment by lydell** [comment]
Of course we can wait doing this. Time’s up for making a breaking change. We literally can’t wait any longer because supporting old Node.js undermines the whole project. So we can’t have 2.0 depend on this feature, because it is not super easy to do. But if you manage to do it before January that would of course be super awesome?

**Comment by evilebottnawi** [comment]
@lydell it is easy, i will send a PR at end of month

**Comment by sosukesuzuki** [comment]
Can we release this in 2.0?  postpone to 3.0?

**Comment by evilebottnawi** [comment]
@sosukesuzuki Yes we can, need continue work :smile: You can be champion

**Comment by sosukesuzuki** [comment]
@evilebottnawi Okay, I'll work on this.

**Comment by fisker** [comment]
@evilebottnawi It seems I don't have too  much time in next few days, and this seems a little tricky, may need more time.

Are we going to ship in v2?

**Comment by evilebottnawi** [comment]
@fisker yes, because it is will big breaking change and the next major version (`3.0`) will not be soon, so we should ship it for `2.0`, don't worry, our release will not on this week

**Comment by fisker** [comment]
@evilebottnawi I'm sorry but I'm not be able to work on this, my wife is having a baby. Someone please take over.

**Comment by thorn0** [comment]
@fisker Wow, that sounds like quite a long-term project. Please have a look at #7660 when you have a minute.

**Comment by thorn0** [comment]
Superseded by #7660

**Pull request closed without merging**
