### PR TITLE
Ignore node_modules when running prettier from CLI

### PR DESCRIPTION
**Pull request by thymikee**
**Summary**
Inspired by this comment: https://github.com/prettier/prettier/pull/1048#issuecomment-287824396 I thought it may be a good idea to omit `node_modules` by default when running prettier through CLI. Kinda fixes https://github.com/prettier/prettier/issues/1358.

Notable changes:
* adds new `--with-node-modules` CLI flag to opt-out from default behavior
* adds integration tests inside `tests_integration` directory.
* adds new npm script command to run integration tests: `test-integration`

**Test plan**
Added an integration test suite.

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks, that's going to save a ton of headache to people!

**Comment by vjeux** [comment]
(I'll merge it when it's green)

**Comment by thymikee** [comment]
Cool. I'm just trying to figure out why it's failing on CI and works on my machine 😅

**Comment by vjeux** [comment]
(Feel free to drop the test altogether if you can't make it work :))

**Comment by thymikee** [comment]
No wonder it failed, my nested `node_module` was ignored by git. Took me too long to realize ^^

**Comment by thymikee** [comment]
💚 All green 
Feels good

**Pull request merged**
