### PR TITLE
Docs: Webstorm file watcher screenshot

### PR DESCRIPTION
**Pull request by alexilyaev**

### CODE REVIEW

**Comment by alexilyaev** [comment]
Does the link to the image must be absolute path?

e.g.
```
https://raw.githubusercontent.com/prettier/prettier/master/editors/webstorm/prettier-file-wacther.png
```

**Comment by SimenB** [comment]
>Does the link to the image must be absolute path?

Nope

**Comment by azz** [comment]
`Example` should work.

**Comment by alexilyaev** [comment]
Updated the images paths

**Comment by azz** [comment]
Thanks.

**Pull request merged**
