### PR TITLE
Fix syntax error on JSON range formatting

### LINKED ISSUE #4009: Errors when range does not include curly brackets (via rangeStart and rangeEnd) in json files using node api
Hello Prettier team and thank you for all the hard work you put into this awesome tool. Truly amazing work! 🥇 

I have an issue to report though. When formatting json files using the node api and providing rangeStart and rangeEnd values not including start `{`-sign or end `}` sign it errors. 

I could not recreate it with the playground (unless I missed the rangeStart/rangeEnd options there in which case I am sorry. If it's possible just tell me and I'll put up the repro there instead).

**Prettier 1.10.2**
Reproduction repro: https://github.com/erik-lundgren/prettier-json-range-bug
```js
{
    filepath: filepath,
    rangeStart: 1, // skip start {
    rangeEnd: fileContents.indexOf("}") // skip end }
}
```

**Input:**
```json
{
    "foo": "bar"
}

```

**Output:**
```jsx
SyntaxError: Unexpected token (1:6)
> 1 | "foo": "bar"
    |      ^
    at createError (C:\Projects\prettier-json-range-bug\node_modules\prettier\
parser-babylon.js:1:110)
    at Object.parse (C:\Projects\prettier-json-range-bug\node_modules\prettier
\parser-babylon.js:1:986)
    at Object.parse$4 [as parse] (C:\Projects\prettier-json-range-bug\node_mod
ules\prettier\index.js:24274:19)
    at formatWithCursor (C:\Projects\prettier-json-range-bug\node_modules\pret
tier\index.js:33650:27)
    at format (C:\Projects\prettier-json-range-bug\node_modules\prettier\index
.js:33695:10)
    at formatRange (C:\Projects\prettier-json-range-bug\node_modules\prettier\
index.js:33922:26)
    at formatWithCursor (C:\Projects\prettier-json-range-bug\node_modules\pret
tier\index.js:33654:30)
    at format (C:\Projects\prettier-json-range-bug\node_modules\prettier\index
.js:33695:10)
    at format (C:\Projects\prettier-json-range-bug\node_modules\prettier\index
.js:33945:12)
    at Object.<anonymous> (C:\Projects\prettier-json-range-bug\index.js:8:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
error Command failed with exit code 1.
```

**Expected behavior:**
Output formatted file, exit code 0.

**Additional debug information**
Operating system: Windows 10
yarn version: 1.3.2
node version: 8.9.4

Let me know if I can provide any more details

### LINKED ISSUE #7116: JSON range formatting throws syntax error
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwAEAdEAjLS0BMaAviADQgQAOMAltAM7KgCGATmxAO4AK7CTFCwBuEWgBNyONizABrODADKVWbSgBzZDDYBXOBQAWMALYAbAOqHa8BqrBwlAm7WE2AnsnAMmFdQzg2GB4ZDRMWZAAzFjMAigArBgAPACEZeUUlFhM4ABl1OCiYuJBEpKV1DTM4AEVdCHgi2IMQVTYAti9E6CkqNnUYCwkYQ2QADgAGCj6IAIsZKi8+uA7hQooAR3r4EOpBEBYGAFooODhxc6k2OC3aa5CWMIikaOaKAJNabT0WhkrquoNQovYotGAsbBDcQjZAECg6Fi0MyVADCEBM4S8UGg6xAugCABUIYJXiVhPoAJJQC6wJRgfo0ACC1KUMHc1SaJRkmkc4KCyAArBRuRo4ABRanIACcxGIQA)
```sh
--parser json
--range-end 9
--range-start 5
```

**Input:**
```jsonc
{ "b": 2 }
```

**Output:**
```jsonc
SyntaxError: Unexpected token (1:4)
> 1 | "b": 2
    |    ^
```

**Expected behavior:**
```jsonc
{ "b": 2 }
```

This is the smallest example I could make that causes the parser to fail. It seems like if the range starts with a `:` but doesn't end with a `,` or `}` after the object value, then the parser throws a syntax error.

### PR DESCRIPTION
**Pull request by fisker**
Fixes #4009 [playground](https://deploy-preview-8082--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEwA6UAE3NpAMwgjyVxACMBDAJzwwF8QAaECABxgEtoBnZUGtQgB3AAo0EfFJQBuETgBNmFapTABrODADKbNZygBzZDGoBXOCzgBbcnAUL7AGUpGzlQ3ABiEatcowXEbIIJRmMBDKABYw1gA2AOpRnPA8emBw2pIpnDIpAJ4hYDx8LAY8cNQwoqqG-sj4lHEVLABWPAAeAEKqGlralNZwTgZwDU0tIO0d2gaGcXAAimYQ8OPNliB61BXUIe3QymzUBjAJijBRyAAcAAwsxxAVCapsIcdwuzJjLACOK-AauwpKEeABaKBwez2ZTUOD-ThwmoeepIRobFgVaycEzmTY8OYLZarMZoiabGCUcjnBSXZAAJhYpkonDicwAwhBrKiQFBoD8QGYKgAVKlSdGTGQWACSUEcsG0YBOHAAgnLtDB8gt1pNVEZMpSqsgAIwsPWeACicpN13o9CAA)
Fixes #7116 [playground](https://deploy-preview-8082--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEwAEAdEAjLS0BMaAviADQgQAOMAltAM7KgCGATmxAO4AK7CTFCwBuEWgBNyONizABrODADKVWbSgBzZDDYBXOBQAWMALYAbAOqHa8BqrBwlAm7WE2AnsnAMmFdQzg2GB4ZDRMWZAAzFjMAigArBgAPACEZeUUlFhM4ABl1OCiYuJBEpKV1DTM4AEVdCHgi2IMQVTYAti9E6CkqNnUYCwkYQ2QADgAGCj6IAIsZKi8+uA7hQooAR3r4EOpBEBYGAFooODhxc6k2OC3aa5CWMIikaOaKAJNabT0WhkrquoNQovYotGAsbBDcQjZAECg6Fi0MyVADCEBM4S8UGg6xAugCABUIYJXiVhPoAJJQC6wJRgfo0ACC1KUMHc1SaJRkmkc4KCyAArBRuRo4ABRanIACcxGIQA)

There is only a few tests about this feature, not sure how people use it, some case might different, [old](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwDkBDNSCMAaAHSgAJijTyyTi0AjbAJgF8Q8QIAHGAS2gGdkoDACdhEAO4AFEQgEoMANwjcAJqxC1hGMAGs4MAModt3KAHNkMYQFc4bABYwAtgBsA6ve7w+xsHAOyXtwKXgCeyOB8AmymfHDCMJJaZk4YyABmGC5xbABWfAAeAEJauvoGGE5wADKmcBlZOSD5BQamZi5wAIrWEPAN2XYgxsJxwhH50OocwqYwbqow9sgAHAAMbDMQcW5aHBEzcGMK9WwAjr3wSZxyIBh8ALRQcHAqr+rCcBfcn0kYKWkkJlBmw4k5uJYbEM+O1Oj0+vUgY0hjAMLQFiolsgGGwrBhuC52gBhCBOVIRKDQU4gaxxAAqaLkwKaClsAEkoG9YAYwLMuABBTkGGChToDJpacz+VEJZD4ECSsxwACinOQABYmEwgA) [new](https://deploy-preview-8082--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEwDkBDNSCMAaAHSgAJijTyyTi0AjbAJgF8Q8QIAHGAS2gGdkoDACdhEAO4AFEQgEoMANwjcAJqxC1hGMAGs4MAModt3KAHNkMYQFc4bABYwAtgBsA6ve7w+xsHAOyXtwKXgCeyOB8AmymfHDCMJJaZk4YyABmGC5xbABWfAAeAEJauvoGGE5wADKmcBlZOSD5BQamZi5wAIrWEPAN2XYgxsJxwhH50OocwqYwbqow9sgAHAAMbDMQcW5aHBEzcGMK9WwAjr3wSZxyIBh8ALRQcHAqr+rCcBfcn0kYKWkkJlBmw4k5uJYbEM+O1Oj0+vUgY0hjAMLQFiolsgGGwrBhuC52gBhCBOVIRKDQU4gaxxAAqaLkwKaClsAEkoG9YAYwLMuABBTkGGChToDJpacz+VEJZD4ECSsxwACinOQABYmEwgA)

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
[The way this feature is documented](https://prettier.io/docs/en/options.html#range), it should not be supported for JSON at all because there is no statements in JSON:

> The range will extend:
> Backwards to the start of the first line containing the selected statement.
> Forwards to the end of the selected statement.

Said that, if we want to fix it your way, we should also exclude `NumericLiteral`, `BooleanLiteral`, and `NullLiteral` (see the examples below). Probably it's better to change something in `findSiblingAncestors` instead.

**Prettier pr-8082**
[Playground link](https://deploy-preview-8082--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEwAEAdEAjLS0BMANJuHmgMxoC+IRIEADjAJbQDOyoAhgE68QA7gAU+CTim4AbQdwCenetl7cwAazgwAyo1UsoAc2QxeAVzj04AW2xwAJnfsAZbodPcDcAGIReV7jCshsgg3KYwEHQgABYwVlIA6tEs8Oy6YHBa4iksAG4pciFg7Iog+uxwvDDCKgb+yABm0hX0AFbsAB4AQirqmlrcVnBO+nCNzRYg7R1a+gZScACKphDw41ItILq8Fbwh7dBRjLz6MAksdjDRyAAcAAz0xxAVCSqMIcdwu7lj9ACOK3gNSYElC7AAtFA4PZ7FFeHAASx4TUPPUkE0NpMKlYWMYzFi5gtlqsxuiJvQYNxsOdLtckMQQCZuCwpHMAMIQKxokBQaC-ECmCoAFSpEgxm1y5gAklBHLAtGATswAIKyrQwOQLdabFSGTKUqrIADs9F1ngAorLkABGI3UahAA)
```sh
--parser json
--range-end 17
--range-start 7
--trailing-comma none
```

**Input:**
```jsonc
{ "b": 2, "c": 3 }
```

**Output:**
```jsonc
SyntaxError: Unexpected token (1:4)
> 1 | "b": 2, "c": 3
    |    ^
```

**Prettier pr-8082**
[Playground link](https://deploy-preview-8082--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBtABAHRAI2wGnQCZDswD0BmdAXRHxAgAcYBLaAZ2VAEMAnPhADuABX4IuKHgBshPAJ5cGOPjzABrODADKTNaygBzZDD4BXOAzgBbHHAAm9hwBkeRsz0NwAYhD7WeGDYjZBAeMxgIehAACxhraQB1GNZ4Dj0wOG0JVNYAN1T5ULAOJRADDjg+GBFVQwDkADMZSoYAKw4ADwAhVQ0tbR5rOGcDOCaWyxAOzu0DQ2k4AEUzCHgJ6VaQPT5KvlCO6GimPgMYRNZ7GBjkAA4ABgYTiErE1SZQk7g9vPGGAEdVvBasxJGEOABaKBwBwOaJ8OCA1gI2qeBpIZqbKaVaysEzmbHzRYrNbjDGTBgwHg4C5XG5IEggUw8VjSeYAYQg1nRICg0D+IDMlQAKtTJJitnkLABJKBOWDaMCnFgAQTl2hg8kWGy2qiMWSp1WQAHYGHqvABROXIACMxoAvvagA)
```sh
--parser json
--range-end 17
--range-start 7
--trailing-comma none
```

**Input:**
```jsonc
[ "b", 2, "c", 3 ]
```

**Output:**
```jsonc
[ "b", (2, "c", 3) ]
```

**Comment by thorn0** [comment]
We really should fix this somehow else.

**Prettier pr-8082**
[Playground link](https://deploy-preview-8082--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBtABAHRAI2wGnWGzGyQEYBfQ4kAMzIGZL0BdEfECABxgEtoAZ2SgAhgCdxEAO4AFCQmEpRAG2miAnsM45xosAGs4MAMrd9fKAHNkMcQFc4nOAFsccACYfPAGVHX7USs4ADEIcRdRGH5rZBBRexgIDhAACxgXFQB1VL54QXMwOBNFPL4ANzyNOLBBbRBLQThxGFk9K0jkOlUmzgArQQAPACE9Q2MTURc4H0s4Lp6nEAHBk0srFTgARXsIeAWVXpBzcSbxOIHoFO5xSxgsvg8YVOQADgAGThuIJqy9bjiNzgZ3K804AEddvA2jwlPFBABaKBwTyeFLiOCQvgYtpBTpIbqHJZNFx8WwOYnrTY7PbzAmLTgwUQ4B5PF5IABMjL0fBU6wAwhAXPiQMCAKwpexNAAqzKUhKO5UcAEkoN5YCYwLdeABBNUmGAaTYHI56azFJktZAAdk4ZuCAFE1chyK9KJQgA)
```sh
--parser json
--range-end 18
--range-start 7
```

**Input:**
```jsonc
[ "b", {"c":1}, {"f":3} ]
```

**Output:**
```jsonc
[ "b", ({ "c": 1 }, { "f": 3 }) ]
```

**Prettier pr-8082**
[Playground link](https://deploy-preview-8082--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEwAEAdEAjLS3BZh4CMAvgDSYgCGehIAZngMxlpkgUgQAOMAS2gBnZKBoAnCRADuABUkJRKGgBsZNAJ6ju2CTTABrODADKvAwKgBzZDAkBXONzgBbbHAAmnrwBkaNg401nAAYhASrjQwgjbItA4wEFwgABYwrqoA6qkC8MIWYHCmSnkCAG55mvFgwjogVsJwEjBy+tZRyIxqTdwAVsIAHgBC+kYmpjSucL5WcF09ziADg6ZW1qpwAIoOEPALqr0gFhJNEvED0Cm8ElYwWQKeMKnIABwADNw3EE1Z+rzxG5wM7lebcACOu3gbT4ylowgAtFA4F4vCkJHBIQIMW1gp0kN1Dksmq4BHZHMT1psdnt5gTFtwYDRsA8ni8kAAmRn6ASqdYAYQgrnxIGBAFYUg4mgAVZnKQlHcpOACSUB8sFMYFu-AAgmrTDBNJsDkd9DZikyWsgAOzcM0hACiauQHI5ZDIQA)
```sh
--parser json
--range-end 22
--range-start 7
```

**Input:**
```jsonc
{ "b": {"c":1}, "a":{"f":3} }
```

**Output:**
```jsonc
SyntaxError: Unexpected token (1:4)
> 1 | "b": {"c":1}, "a":{"f":3}
    |    ^
```

**Comment by fisker** [comment]
I think the best result should be: 
- any node as `ObjectExpression.value` 
- any `ArrayExpression` elements

I can't make it work.

Want take a shot?  @thorn0

**Comment by thorn0** [comment]
> Want take a shot?

Maybe, but when I have time, I'd rather focus on more severe bugs, like broken SCSS comments.

**Comment by fisker** [comment]
Close this  now.

**Pull request closed without merging**
