### PR TITLE
build: update editorconfig to resolve a deprecated warning

### PR DESCRIPTION
**Pull request by sibiraj-s**
- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

This resolves a deprecated warning when installing prettier.

screenshot 2018-10-27 at 5 30 37 pm

### CODE REVIEW

**Comment by sibiraj-s** [comment]
@ikatyang Thanks, I thought of doing it after seeing your last commit of `disable integrity migration` I forgot.

**Comment by ikatyang** [comment]
Thanks!

**Comment by sibiraj-s** [comment]
@ikatyang one more thing. What about installing `rennovate` or `greenkeeper`?

**Comment by ikatyang** [comment]
See https://github.com/prettier/prettier/issues/3582#issuecomment-353985045.

**Pull request merged**
