### PR TITLE
Vim readme

### PR DESCRIPTION
**Pull request by Zyst**
Added quite a bit of information on how to use prettier with vim, how to customize it, and a Neoformat approach which was hinted in #658 including a request of sorts in [this comment](https://github.com/prettier/prettier/issues/658#issuecomment-282863788) by @jlongster

### CODE REVIEW

**Comment by vjeux** [comment]
Do you mind putting everything inside of README.md, it's easier to scroll through and see if it's useful or not for you rather than going to an external page.

**Comment by Zyst** [comment]
@vjeux can do, was worried it was a bit too much info so thought I'd kick it up into another folder like the Emacs and IntelliJ sections, but I'll make the edits and push it in a bit

**Comment by Zyst** [comment]
@vjeux your requested changes have been made.

**Comment by vjeux** [comment]
Thanks!

**Pull request merged**
