### PR TITLE
feat(html): tweak printer

### PR DESCRIPTION
**Pull request by ikatyang**
- tweak the ast in the printer.preprocess
  - whitespace-only `text` nodes are removed
    (this does not affect how we print whitespaces, it's an internal change.)
  - add `startLocation` and `endLocation` for nextEmptyLine
- tweak the boundary of printed nodes
  - newlines between siblings are always handled in `printChildren`
- indent the script/style content in multiparser
- [x] no inconsistent output for 2+ attributes ([repro](https://deploy-preview-5119--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAGgPgDpVQei11wwAIBDAXmxAEYac9DGT0Lq6bSAjDgJgYlmxPGyo16IHvy5gOAZkFMiUEABoQEAA4wAltADOyUOQBOpiAHcACmYRGU5AG4RdAE3Uhup8mADWcDAAylq+ulAA5sgwpgCucBrhBnCmMNY+EQC25MgAZuQANskaAFYGAB4AQj7+gUHkmXAAMuFweYXFIKGmyabIXWbJAKyeWqbhMADq7jAAFsgAHAAMGmMQyZM+Wv1jcL1ObRqmcACOsbrH6eRZOUj5RQkgyZm60XGPBuERBXAAirEQeDtB4aGDkbjTNxzZB8UE+XQFL4AYQgmWy-Sg0EOIFiyQAKuCHPdkgBfElAA), [comment 1](https://github.com/prettier/prettier/issues/5098#issuecomment-422936906), [comment 2](https://github.com/prettier/prettier/issues/5098#issuecomment-423036038))
- [x] force break tag if there're multiline attributes ([repro](https://deploy-preview-5105--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeADgAgDpU5sAGwEMBnUgXmxF33wDMIJa6AjYgJxf3YC8XquAHwsAEnEKEImAO4QOhACYBCVACEASgHohmACoALAJalMJzKL0BZADIBWTGohHCcDuhLwAdLlRb0QiAANCAQ6DBG0KTIoJwcEDIACpwI0SjEAG7OisEgrBzEYADWcDAAyuiFRlAA5sgwHACucCHVpG4wiQU1ALbEyPTEhO0hAFakAB5qBcWlZcQ9cDbVcANDIyCVHO0cyJuc7Xa56BzVMADqRoowBsgAHAAMIScQ7ecF6HsncDsZqyEcOAAR0aRkBXWIvX6SEGwxaIHaPSM9Sa8NI1RqrgAio0IPA1nCQjBiKxLtdbkgAExEgouDEAYQgPT6eyg0H+IEa7T0JLSsPaAF8BUA), [comment](https://github.com/prettier/prettier/issues/5098#issuecomment-423671365))

---

**Prettier pr-5134**
[Playground link](https://deploy-preview-5134--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAGgPgDpVQei1wwAIBDAXmxAEZqc9CHTLq6QSAjKkAJnuJNi6cj3Zce-DmB4BmAYyJRiABxK4SJMABsyAZz08NmkgDMIEY5s5kATla5kAXseq4GmgBJxt2iCQB3CFttABMAQlQAIQAlfEwSABUACwBLPRJ0kk9EgFkAGQBWEiiIVO04WxVdeAA6QRVMEAAaEAgVGFToPWRQO1sIAIAFOwQelDIANzLQlpBOWzIwAGs4GABlFSXUqABzZBhbAFc4Vp29Spghxd2AWzJkUzJtC9aAKz0ADyjFlbX1si3OD5HZwR7PV4gLa2C62ZAgZIwW7aOYqWw7GAAdVSoRgyWQAA4AAytNEQC6YxYqeFouCwyZg1q2OAARyOqWZ1zIdweSCeL1OIAut1SB2Ogr0O12FQAikcIPBwQLWjAyJxsbj8UheCrFuUpQBhCC3e7wqDQRkgI4XRJq8b8i4AX0dQA)
```sh
--parser html
```

**Input:**
```html
<X>
</X>
<X a="1">
</X>
<X a="1" b="2">
</X>
<X a="1" b="2" c="3">
</X>

<p 
  class="
    foo
    bar
    baz
  "
>
  Hello world!<BR/> This is HTML5 Boilerplate.
</p>
```

**Output:**
```html
<X></X>
<X a="1"></X>
<X a="1" b="2"></X>
<X a="1" b="2" c="3"></X>

<p
  class="
    foo
    bar
    baz
  "
>
  Hello world!
  <br />
  This is HTML5 Boilerplate.
</p>

```

---

- [x] I’ve added tests to confirm my change works.
- (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by thorn0** [comment]
Whitespaces in HTML are such a PITA. E.g.
```html
<div>200 m<sup>2</sup></div>
```
should not become
```html
<div>
  200 m
  <sup>2</sup>
</div>
```
[repro](https://deploy-preview-5134--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4BMADIQAQC2qAzgK4AOBqA9DfU1niADQgS0ybRKyUAEMATmIgB3AAriEQlCOwRM6LiABGYkWADWcGAGVauzFADmyGGOpxu5ynDEwZOi2RHIAZiIA2TtwAVpQAHgBCOvqGRiJkcAAy5nA+-oEgpmJOYsggABYwZH4atGLmMADqajB5yAAchNylEE4VOrS5pXDZ2CncYnAAjtSYA24iHl5IvgH2IE5kmNa2c5TmFn5wAIrUEPCps9wwIppV6DXI+Ec6mH7rAMIQZJ65UNB9INROAConijNOAC+gKAA)

**Comment by ikatyang** [comment]
@thorn0 That's a known issue and so far we don't know how to fix it without being ugly, see https://github.com/prettier/prettier/pull/4753#issuecomment-400514884 and its following comments for more info.

**Comment by thorn0** [comment]
A rule of thumb might look like following:

1. Never add a whitespace (new line) between nodes if there was no whitespace between them in the input.
2. Never remove whitespaces completely, keep at least one whitespace character like the `conservativeCollapse` [option of `html-minifier`](https://github.com/kangax/html-minifier#options-quick-reference) does.

Overall, it might be useful to have a look at `html-minifier`. Of course, it does the opposite thing of what Prettier does, but still, they have faced similar issues.

**Comment by ikatyang** [comment]
There's not much possible solution for whitespace formatting in HTML, the spec is quite limited. I think I'll try to implement https://github.com/prettier/prettier/pull/4753#issuecomment-400580798 (won't be in this PR), which is the most safe one but a _little_ ugly. Added to the TODO list.

Something like the following cases, though I'm not sure if we should apply the _sophisticated_ rule, CSS makes everything possible.

```html
<!-- before -->
<div> <p> 123 <a href="#something"> First First First First First First First First First First First First First </a> 456 <a> Second Second Second Second Second Second Second Second Second Second Second Second Second </a> 789 </p> </div>

<!-- after -->
<div>
  <p>
    123
    <a href="#something">
      First First First First First First First First First First First First First
    </a>
    456
    <a>
      Second Second Second Second Second Second Second Second Second Second Second Second Second
    </a>
    789
  </p>
</div>
```

```html
<!-- before -->
<div><p>123<a href="#something">First First First First First First First First First First First First First</a>456<a>Second Second Second Second Second Second Second Second Second Second Second Second Second</a>789</p></div>

<!-- after -->
<div
  ><p
    >123<a
      href="#something"
      >First First First First First First First First First First First First First</a
    >456<a
      >Second Second Second Second Second Second Second Second Second Second Second Second Second</a
    >789</p
  ></div
>
```

```html
<!-- before -->
<div> <p> 123 <a href="#something"> First First First First First First First First First First First First First </a>456<a>Second Second Second Second Second Second Second Second Second Second Second Second Second</a>789</p></div>

<!-- after -->
<div>
  <p>
    123
    <a href="#something">
      First First First First First First First First First First First First First
    </a
    >456<a
      >Second Second Second Second Second Second Second Second Second Second Second Second Second</a
    >789</p
  ></div
>
```

```html
<ul
  ><li>First</li
  ><li>Second</li
></ul>

<ul
  >123<li
    >First</li
  ><li>Second</li
></ul>

<ul
  ><li>First</li
  >456<li
    >Second</li
></ul>

<ul
  ><li>First</li
  ><li>Second</li
  >789</ul
>


<ul
  >123<li
    >First</li
  >456<li
    >Second</li
></ul>


<ul
  >123<li
    >First</li
  ><li>Second</li
  >789</ul
>

<ul
  ><li>First</li
  >456<li
    >Second</li
  >789</ul
>

<ul
  >123<li
    >First</li
  >456<li
    >Second</li
  >789</ul
>
```

**Comment by lydell** [comment]
I think we should format as good as we can and document the gotchas and their workarounds.

**Comment by ikatyang** [comment]
IMO, we shouldn't break users' input, at least not by default. Maybe we should introduce an option for this whitespace thing:

- break tags (default, the safest one) ref: https://github.com/prettier/prettier/pull/4753#issuecomment-400580798
  ```html
  <ul
    ><li>First</li
    ><li>Second</li
  ></ul>

  <ul
    >123<li
      >First</li
    >456<li
      >Second</li
    >789</ul
  >
  ```
- add comments (safe if no DOM manipulation) ref: https://github.com/prettier/prettier/pull/4753#issuecomment-400514884
  ```html
  <ul><!--
    --><li>First</li><!--
    --><li>Second</li><!--
  --></ul>

  <ul><!--
    -->123<!--
    --><li>First</li><!--
    -->456<!--
    --><li>Second</li><!--
    -->789<!--
  --></ul>
  ```
- ignore whitespaces, the current behavior. (not safe but pretty)
  ```html
  <ul>
    <li>First</li>
    <li>Second</li>
  </ul>

  <ul>
    123
    <li>First</li>
    456
    <li>Second</li>
    789
  </ul>
  ```

cc @vjeux

**Comment by vjeux** [comment]
While i’m all for safety, it so drastically reduces our options for the common case that I believe it’s okay to make the default not safe. We should provide a reasonable way to find when whitespace would be important (can be hard since it is based on css) and provide a reasonable way to tell prettier not to remove them.

**Comment by claytonrcarter** [comment]
I just found Prettier and I'm **very** excited about HTML support. I think that the the so called "sophisticated rule" is a reasonable default. I would think it safe to assume that most people have not altered the `display` of the standard elements. If they have, then they've already "broken out" of default behavior elsewhere, so it seems reasonable to expect them to use special config/comments to do so here as well.

Furthermore, I would encourage you to use some real world markup as you test.  Things like @thorn0 posted (`<div>200 m<sup>2</sup></div>`) or something like this example from [MDN](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#Document_fragments)

```html
<p>Want to write us a letter? Use our <a href="contacts.html#Mailing_address">mailing address</a>.</p>
```

Some of the examples above (with `First First First` etc) seem contrived and may not represent the bulk of existing HTML content.

My use cases may be unique, but I did a quick check of our HTML templates (several hundred) and I found numerous examples of things like:
```html
<a>Lorem</a>, ispum dolor sit <strong>amet</strong>.
```
In these cases, moving the punctuation onto their own lines would be undesirable.

Thank you for all of your work on this! I'm looking forward to when it lands!

**Comment by ikatyang** [comment]
@michaeljota The formatting there is not safe, for example the before/after:

image

**Comment by ikatyang** [comment]
I'll move this discussion to a new thread later as it's not suitable to discuss in a unrelated thread. (This PR does not change how we print whitespaces but the internal implementation.)

**Comment by ikatyang** [comment]
Closing in favor of #5168

**Pull request closed without merging**
