### PR TITLE
Add issue templates for releasing

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Adds 2 issue templates for releasing:

1. for minor/major (copied from wiki)
2. for patch (please review)

## Checklist

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by duailibe — APPROVED** [review]

**Comment by fisker** [comment]
The issue templates are for users, these not useful for users.

**Comment by fisker** [comment]
Can these only display to the maintainers?

**Comment by sosukesuzuki** [comment]
> Can these only display to the maintainers?

Probably, no.

**Comment by alexander-akait** [comment]
I don't mind if this really helps not to miss something and make the release easier.

**Comment by sosukesuzuki** [comment]
At least it will help me. But, as fisker says, it may not need to be visible to the user.

**Comment by alexander-akait** [comment]
Perhaps it would not be a bad idea and create a request in the github for this feature, it would be convenient, I think

**Comment by fisker** [comment]
Instead of add this, I suggest we can add a manual trigger action to open that issue.

**Pull request closed without merging**
