### PR TITLE
[ImgBot] Optimize images

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
## Beep boop. Your images are optimized!

Your image file size has been reduced!

<details>
<summary>
Details
</summary>

| File | Before | After | Percent reduction |
|:--|:--|:--|:--|
| /website/static/images/get_started_rects.svg | 2.73kb | 2.49kb | 8.70% |
| /website/static/images/editors/editor_atom.svg | 0.88kb | 0.83kb | 4.91% |
| /website/static/images/languages/markdown_small_grey.svg | 0.38kb | 0.37kb | 4.57% |
| /website/static/images/users/used_by_zeit.svg | 0.13kb | 0.12kb | 3.79% |
| /website/static/images/users/used_by_jest.svg | 1.42kb | 1.37kb | 3.64% |
| /website/static/images/users/used_by_react.svg | 1.23kb | 1.19kb | 3.49% |
| /website/static/images/editors/editor_vscode.svg | 0.67kb | 0.64kb | 3.38% |
| /website/static/images/languages/tools_gql.svg | 1.40kb | 1.35kb | 3.35% |
| /website/static/images/languages/graphql_small_grey.svg | 1.41kb | 1.36kb | 3.33% |
| /website/static/images/npm.svg | 0.25kb | 0.24kb | 3.16% |
| /website/static/images/users/heroku.svg | 1.88kb | 1.83kb | 3.16% |
| /website/static/images/npm_grey.svg | 0.27kb | 0.27kb | 2.86% |
| /website/static/images/users/metric-ai-white.svg | 1.72kb | 1.68kb | 2.27% |
| /website/static/images/users/estalee.svg | 1.83kb | 1.80kb | 2.08% |
| /website/static/images/languages/tools_html.svg | 0.25kb | 0.25kb | 1.94% |
| /website/static/images/editors/editor_webstorm.svg | 1.00kb | 0.98kb | 1.77% |
| /website/static/images/languages/python_small_grey.svg | 1.02kb | 1.00kb | 1.73% |
| /website/static/images/editors/editor_vs.svg | 0.31kb | 0.31kb | 1.57% |
| /website/static/images/users/buildcom.svg | 2.10kb | 2.06kb | 1.54% |
| /website/static/images/languages/tools_wip.svg | 1.15kb | 1.13kb | 1.53% |
| /website/static/images/editors/editor_emacs.svg | 1.25kb | 1.23kb | 1.41% |
| /website/static/images/languages/tools_md.svg | 0.36kb | 0.36kb | 1.35% |
| /website/static/images/languages/tools_css.svg | 0.37kb | 0.37kb | 1.31% |
| /website/static/images/languages/css_small_grey.svg | 0.38kb | 0.38kb | 1.28% |
| /website/static/images/users/quip.svg | 2.25kb | 2.22kb | 1.22% |
| /website/static/images/users/3yourmind.svg | 4.22kb | 4.18kb | 1.13% |
| /website/static/images/editors/editor_vim.svg | 1.58kb | 1.56kb | 1.11% |
| /website/static/images/editors/editor_sublime.svg | 0.46kb | 0.46kb | 1.05% |
| /website/static/images/languages/tools_yaml.svg | 0.54kb | 0.53kb | 0.91% |
| /website/static/images/users/used_by_storybook.svg | 0.58kb | 0.58kb | 0.84% |
| /website/static/images/users/used_by_webpack.svg | 0.60kb | 0.59kb | 0.82% |
| /website/static/images/languages/swift_small_grey.svg | 0.68kb | 0.68kb | 0.71% |
| /website/static/images/languages/js_small_grey.svg | 0.71kb | 0.71kb | 0.69% |
| /website/static/images/languages/tools_js.svg | 0.71kb | 0.71kb | 0.68% |
| /website/static/images/github.svg | 0.78kb | 0.77kb | 0.63% |
| /website/static/images/github_grey.svg | 0.79kb | 0.79kb | 0.62% |
| /website/static/images/users/dropbox.svg | 1.47kb | 1.47kb | 0.53% |
| /website/static/prettier-centered-logo-static.svg | 6.20kb | 6.17kb | 0.52% |
| /website/static/images/users/salesforce.svg | 6.93kb | 6.89kb | 0.47% |
| /website/static/images/editors/editor_espresso.svg | 1.18kb | 1.18kb | 0.41% |
| /website/static/images/users/codecarrot.svg | 6.96kb | 6.93kb | 0.41% |
| /website/static/images/users/dropbox_grey.svg | 1.46kb | 1.46kb | 0.33% |
| /website/static/images/users/computerbase.svg | 6.14kb | 6.12kb | 0.33% |
| /website/static/images/users/used_by_yarn.svg | 2.18kb | 2.17kb | 0.22% |
| /website/static/images/users/used_by_facebook.svg | 2.18kb | 2.17kb | 0.22% |
| /website/static/images/users/exponea.svg | 2.26kb | 2.25kb | 0.22% |
| /website/static/images/users/leesa.svg | 3.23kb | 3.23kb | 0.15% |
| /website/static/images/users/used_by_danger.svg | 3.68kb | 3.67kb | 0.13% |
| /website/static/images/users/housinganywhere.svg | 4.56kb | 4.55kb | 0.11% |
| /website/static/images/users/researchanddesign.svg | 4.90kb | 4.89kb | 0.08% |
| /website/static/images/users/used_by_babel.svg | 19.55kb | 19.55kb | 0.02% |
| | | | |
| **Total :** | **111.16kb** | **110.07kb** | **0.99%** |
</details>

---

[📝docs](https://imgbot.net/docs) | [:octocat: repo](https://github.com/dabutvin/ImgBot) | [🙋issues](https://github.com/dabutvin/ImgBot/issues) | [🏅swag](https://goo.gl/forms/1GX7wlhGEX8nkhGO2) | [🏪marketplace](https://github.com/marketplace/imgbot)

### CODE REVIEW

**Comment by MichaelDeBoey** [comment]
If you want, you can install https://imgbot.net in this repo (or in the full organization).
It will automatically send PRs for image optimization 🙂

**Comment by MichaelDeBoey** [comment]
Ping @lydell @lipis

**Comment by lipis** [comment]
Is it possible to run the svgo with `--pretty --indent=2 --precision=1`?

Like in #6939

**Comment by MichaelDeBoey** [comment]
@lipis No that's not possible to configure in ImgBot according to [the docs](https://imgbot.net/docs).

**Comment by MichaelDeBoey** [comment]
Ping @lydell @lipis

**Comment by lipis** [comment]
We will go with the other solution.. sorry

**Comment by MichaelDeBoey** [comment]
No problem at all 🙂

**Comment by lipis** [comment]
I'm thinking of installing this bot after all :)

**Comment by JounQin** [comment]
Here is my thought about this: https://github.com/prettier/prettier/pull/6939#issuecomment-558605839

A bot only targeting images make no sense to me.

**Comment by lipis** [comment]
> A bot only targeting images make no sense to me.

Why not? We don't need to install any dependencies, hooks, or anything.. The bot will from time to time create a PR with a optimized image. Sounds the right way to go, instead of bloating with more dependencies in our package.json

**Comment by JounQin** [comment]
@Lipis If we have `husky + lint-staged`, it can prevent common style or lint issues before CI, CI then makes sure there are on any issue.

I think it makes more senses for contributors and fast development instead of waiting CI response.

**Comment by lipis** [comment]
Images are not the core functionality of Prettier.. so that's why it's better to have it as an external bot. Less dependencies.

As for husky+lint-staged we decided against it in the past.

**Comment by lipis** [comment]
@MichaelDeBoey I installed the bot after all :) #7056! Thanks for the tip.

**Pull request closed without merging**
