### PR TITLE
Build: Fix unexpected `require()`s in `parser-typescript.js`

### LINKED ISSUE #11076: webpack warning: "the request of a dependency is an expression"
When bundling `prettier/parser-typescript` for the browser, Webpack issues 2 warnings "`the request of a dependency is an expression`".

This is a re-opening of https://github.com/prettier/prettier/issues/4959. This warning happens again when bundling recent versions of `prettier/parser-typescript` for the browser.

**Environments:**

- Prettier Version: 2.3.1
- Bundling `prettier/standalone` + `prettier/parser-typescript` via Webpack
- Runtime: Node v15, Webpack 5.38.1
- Operating System: macOS

**Steps to reproduce:**

Clone/check out https://github.com/foxglove/studio/commit/dbe87ed477d370a379da24a8586960bc49bab7a3, run `yarn && yarn serve`.

**Expected behavior:**

Webpack builds without warnings

**Actual behavior:**

Two warnings are produced:

```
  WARNING in ../../node_modules/prettier/parser-typescript.js 22:209490-209500
  Critical dependency: the request of a dependency is an expression
   @ ../../packages/studio-base/src/panels/NodePlayground/prettier.ts 26:29-28:37
   @ ../../packages/studio-base/src/panels/NodePlayground/Editor.tsx 20:0-85 120:40-57
   @ ../../packages/studio-base/src/panels/NodePlayground/index.tsx 36:32-92
   @ ../../packages/studio-base/src/panels/index.ts 6:0-46 40:43-57
   @ ../../packages/studio-base/src/providers/PanelCatalogProvider.tsx 14:0-50 37:19-33 37:38-51 37:56-68 42:23-37 42:42-54 44:19-33
   @ ../../packages/studio-base/src/App.tsx 21:0-88 39:259-279
   @ ../../packages/studio-base/src/index.ts 9:0-39 9:0-39
   @ ./index.tsx 10:0-96 29:0-25 30:0-14 37:10-22

  WARNING in ../../node_modules/prettier/parser-typescript.js 22:295685-295695
  Critical dependency: the request of a dependency is an expression
   @ ../../packages/studio-base/src/panels/NodePlayground/prettier.ts 26:29-28:37
   @ ../../packages/studio-base/src/panels/NodePlayground/Editor.tsx 20:0-85 120:40-57
   @ ../../packages/studio-base/src/panels/NodePlayground/index.tsx 36:32-92
   @ ../../packages/studio-base/src/panels/index.ts 6:0-46 40:43-57
   @ ../../packages/studio-base/src/providers/PanelCatalogProvider.tsx 14:0-50 37:19-33 37:38-51 37:56-68 42:23-37 42:42-54 44:19-33
   @ ../../packages/studio-base/src/App.tsx 21:0-88 39:259-279
   @ ../../packages/studio-base/src/index.ts 9:0-39 9:0-39
   @ ./index.tsx 10:0-96 29:0-25 30:0-14 37:10-22
```

These warnings come from TypeScript code that is bundled as part of the `prettier/parser-typescript` js file. There is an open TypeScript issue on this: https://github.com/microsoft/TypeScript/issues/39436

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #11076

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
@jtbandes @bobbui  Can you donwnload `parser-typescript.js` from https://deploy-preview-11130--prettier.netlify.app/lib/parser-typescript.js and test if this PR solves your problem?

**Comment by steveruizok** [comment]
> @jtbandes @bobbui Can you donwnload `parser-typescript.js` from https://deploy-preview-11130--prettier.netlify.app/lib/parser-typescript.js and test if this PR solves your problem?

Hi @jtbandes, same problem here. I replaced my local prettier/parser-typescript.js and it did not solve the problem.

**Comment by bobbui** [comment]
> @jtbandes @bobbui Can you donwnload `parser-typescript.js` from https://deploy-preview-11130--prettier.netlify.app/lib/parser-typescript.js and test if this PR solves your problem?

Still the same error throws:
```
WARNING in ../../node_modules/prettier/parser-typescript.js 22:261458-261468
Critical dependency: the request of a dependency is an expression
```

**Comment by fisker** [comment]
@jtbandes 

I did

> Clone/check out foxglove/studio@dbe87ed, run yarn && yarn serve.

seems fixed it now. Can you confirm?

@bobbui Can you help test too?

**Comment by jtbandes** [comment]
Confirmed, the fix works, thanks!

**Review by sosukesuzuki — APPROVED** [review]

**Comment by fisker** [comment]
@jtbandes Thank you!

**Comment by YousefED** [comment]
@fisker @jtbandes Has this landed in 2.4.1? Using the file  https://deploy-preview-11130--prettier.netlify.app/lib/parser-typescript.js (as mentioned above) works for me, but with 2.4.1 (latest version), I'm running into the same issue

**Pull request merged**
