### PR TITLE
feat(css): improve svg tags

### PR DESCRIPTION
**Pull request by evilebottnawi**
All tested in browser, all works as expected

### CODE REVIEW

**Comment by lydell** [comment]
I don't think it is safe to do this. Selectors will change from not matching anything to potentially matching.

**Comment by evilebottnawi** [comment]
@lydell do you show example, for me it is very safe, in theory you can use `lInE` and `LiNeArGrAdIeNt` and it is valid

**Comment by lydell** [comment]
See #3304.

Scenario: Somebody has accidentally left behind this piece of broken CSS in their stylesheet:

```css
LinearGradient {
  stop-color: inherit;
}
``

Then they upgrade Prettier, which would change it to:

```css
LinearGradient {
  stop-color: inherit;
}
``

Suddenly the gradient of soms SVG on their site has changed color. Which means that Prettier broke their site. Prettier is supposed to be 100% safe to run.

**Comment by evilebottnawi** [comment]
@lydell for `css` `LinearGradient` === `linearGradient` === `lInEaRgRaDiEnt`

**Comment by evilebottnawi** [comment]
@lydell http://cssdeck.com/labs

```html
<svg>
  <!-- Градиент -->
  <linearGradient id="linear-gradient">
    <stop offset="0%" stop-color="gold"/>
    <stop offset="100%" stop-color="teal"/>
  </linearGradient>

  <!-- Фигура с градиентной заливкой -->
  <rect fill="url(#linear-gradient)"
        width="100%" height="100%"/>
</svg>
```

```css
// Try to change case and look on result
svg LinearGradient stop {
  stop-color: blue;
}
```

**Comment by evilebottnawi** [comment]
@lydell hm you are right, but according spec firefox do not works correctly, yep svg is xml, but when you output all in browsers it is html5. Some svg features don't allowed when you use inline svg in html5 (due to incompatibility). But we can't do here nothing :disappointed:

**Comment by lydell** [comment]
For reference (copied from #3317):

https://www.w3.org/TR/css3-selectors/#casesens

> All Selectors syntax is case-insensitive within the ASCII range (i.e.
> [a-z] and [A-Z] are equivalent), except for parts that are not under the
> control of Selectors. The case sensitivity of document language element
> names, attribute names, and attribute values in selectors depends on the
> document language. For example, in HTML, element names are
> case-insensitive, but in XML, they are case-sensitive.

**Pull request closed without merging**
