### PR TITLE
Fix a failed test on `flow` parser

### PR DESCRIPTION
**Pull request by fisker**
I found a failed test

```js
const foo: ?boolean = true;
const bar = true || (foo || false);
```

This will format to 

```js
const foo: ?boolean = true;
const bar = true || foo || false;
```

AST_COMPARE shows diff

```diff
@@ -67,13 +67,11 @@
                    "source": null,
                  },
                  "type": "Literal",
                  "value": true,
                },
-               "loc": Object {
-                 "source": null,
-               },
+               "loc": Object {},
                "operator": "||",
                "right": Object {
                  "loc": Object {
                    "source": null,
                  },
@@ -81,14 +79,12 @@
                  "optional": false,
                  "type": "Identifier",
                  "typeAnnotation": null,
                },
                "type": "LogicalExpression",
-             },
-             "loc": Object {
-               "source": null,
              },
+             "loc": Object {},
              "operator": "||",
              "right": Object {
                "loc": Object {
                  "source": null,
                },
```

I'm not sure I'm doing this right.

### CODE REVIEW

**Comment by fisker** [comment]
@thorn0 Can you help me with this? Or maybe you want investigate this case?

**Comment by fisker** [comment]
Thanks, if it's not important.  Which one is better?

1.

```js
  if (ast.loc && ast.loc.source === null) {
    delete newObj.loc.source;
  }
```

2.

```js
  if (ast.source === null) {
    delete newObj.source;
  }
```

3.

```js
delete newObj.loc.source;
```

4.

```js
delete newObj.source;
```

4.

```js
delete newObj.loc;
```

**Comment by thorn0** [comment]
The first (current) option looks safest. We don't want to accidentally delete something unrelated.

**Comment by fisker** [comment]
Sure,  if we decide use first one, maybe I should change https://github.com/fisker/prettier/blob/28735c8e7e4bd583966d12aaace887dba3cca683/src/language-js/clean.js#L12-L13

to this style.


Also, merge maybe I should delete this line. https://github.com/prettier/prettier/blob/6c482e2e6c4d771407302fcc999bb3e2b491cbd3/src/common/parser-include-shebang.js#L16

**Comment by thorn0** [comment]
`start` and `end` can stay as is. Babel creates properties with these names directly on AST nodes, so it's safe to presume that these names won't get used for something else (e.g. for a new type of AST node). But we can't be that sure about `source`.

**Comment by thorn0** [comment]
> maybe I should delete this line.

You meant the line 15, not 16, right?

**Comment by fisker** [comment]
Yes, 15, typo

**Pull request merged**
