### PR TITLE
Use JSX style for all nested ternaries

### LINKED ISSUE #5814: Nested ternary formatting - add indents back
Edit: I will no longer be actively participating in this thread - my reasons are explained [in comment below](https://github.com/prettier/prettier/issues/5814#issuecomment-719825938).

Hello,

there are many - including me thinking that change to nested ternary is not best decision.

Eg threads https://github.com/prettier/prettier/issues/5476 https://github.com/prettier/prettier/issues/3018

I know there is some reasoning why nested ternary indent was removed, but it's much harder to read code now.

At least would be good to have option to remain nice formatting (from previous prettier version) - formatting of ternaries with indent and not under each other like:

```
condition
  ? a
  : b
  ? c
  : d
```

instead much easier to understand and read is:

```
condition
  ? a
  : b
    ? c
    : d
```

### PR DESCRIPTION
**Pull request by rattrayalex**
Fixes #5814

This is an alternative to https://github.com/prettier/prettier/pull/9559; **please upvote this PR or https://github.com/prettier/prettier/pull/9559, or a proposal in https://github.com/prettier/prettier/pull/9561**

I think this PR has better behavior since it scales better to long ternary formats, has an extremely clear visual difference between conditionals and consequents, and is easy to refactor. I've also had good experiences and heard good feedback on the JSX style when it is used in JSX.

Headline examples from the tests:

```jsx
const message =
  i % 3 === 0 && i % 5 === 0 ? (
    "fizzbuzz"
  ) : i % 3 === 0 ? (
    "fizz"
  ) : i % 5 === 0 ? (
    "buzz"
  ) : (
    String(i)
  );

const paymentMessage =
  state == "success" ? (
    "Payment completed successfully"
  ) : state == "processing" ? (
    "Payment processing"
  ) : state == "invalid_cvc" ? (
    "There was an issue with your CVC number"
  ) : state == "invalid_expiry" ? (
    "Expiry must be sometime in the past."
  ) : (
    "There was an issue with the payment.  Please contact support."
  );

const StorybookLoader = ({ match }) =>
  match.params.storyId === "button" ? (
    <ButtonStorybook />
  ) : match.params.storyId === "color" ? (
    <ColorBook />
  ) : match.params.storyId === "typography" ? (
    <TypographyBook />
  ) : match.params.storyId === "loading" ? (
    <LoaderStorybook />
  ) : match.params.storyId === "deal-list" ? (
    <DealListStory />
  ) : (
    <Message>
      <Title>{"Missing story book"}</Title>
      <Content>
        <BackButton />
      </Content>
    </Message>
  );
```

and a case I hope to add to the tests:

```jsx
children && !isEmptyChildren(children) ? (
  children
) : props.match ? (
  component ? (
    React.createElement(component, props)
  ) : render ? (
    render(props)
  ) : null
) : null;
```

Note that this PR uses indents for TS Conditional Types, eg:

```ts
type TypeName<T> = T extends string
  ? "string"
  : T extends number
    ? "number"
    : T extends boolean
      ? "boolean"
      : T extends undefined
        ? "undefined"
        : T extends Function
          ? "function"
          : "object";
```
but we could easily back that change out.

I may seek to change TS Conditional Type formatting in a follow-on PR, and am considering this **case-style** format:

```ts
type Animal<T> =
  T extends Quacker ? Duck :
  T extends SuperTall ? Giraffe :
  T extends SingleCelled ? (
    T extends Eukaryotic ? Amoeba :
    Bacteria
  ) :
  T extends Barker ? Dog :
  GenericAnimal;
```

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
Another reason to prefer this style is tabs. "Use tabs for indentation, spaces for alignment" sounds good in theory, but is confusing in practice. I avoid using tabs now because Prettier works best with spaces, specifically because of how it formats ternaries and union types (see #4198).

Also I totally agree that, if the main problem with the current formatting is not the indentation per se but the lack of a clear separation between conditions and results, then this style is a tidier way to achieve this separation than aggressive indentation.

**Comment by DScheglov** [comment]
@rattrayalex , hey

```js
const message =
  i % 3 === 0 && i % 5 === 0 ? (
    "fizzbuzz"
  ) : i % 3 === 0 ? (
    "fizz"
  ) : i % 5 === 0 ? (
    "buzz"
  ) : (
    String(i)
  );
```

it is much more noisy then ts conditional type style:

```js
const message =
  i % 3 === 0 && i % 5 === 0 ? "fizzbuzz" :
  i % 3 === 0 ? "fizz" :
  i % 5 === 0 ? "buzz" :
  String(i);
```

Could "noise" be considered too?

**Comment by askuzminov** [comment]
Original

```ts
const pickBgColor = (colorName: string) =>
  colorName === 'active'
    ? colorName === 'active'
      ? 'var(--blue2)'
      : colorName === 'inactive'
    : colorName === 'inactive'
    ? 'var(--blue1)'
    : colorName === 'success' || colorName === 'abc'
    ? colorName === 'abc'
      ? 'var(--blue2)'
      : 'var(--blue23)'
    : 'var(--red4)';

const message = (i: number) =>
  i % 3 === 0 && i % 5 === 0
    ? 'fizzbuzzfizzbuzzfizzbuzzfizzbuzz'
    : i % 3 === 0
    ? i % 3 === 0
      ? 'ffizzbuzzfizzbuzzfizzbuzzfizzbuzzizz'
      : i % 5 === 0
    : i % 5 === 0
    ? 'fizzbuzzfizzbuzzfizzbuzzfizzbuzz'
    : String(i);
```

current PR
```ts
const pickBgColor = (colorName: string) =>
  colorName === "active" ? (
    colorName === "active" ? (
      "var(--blue2)"
    ) : (
      colorName === "inactive"
    )
  ) : colorName === "inactive" ? (
    "var(--blue1)"
  ) : colorName === "success" || colorName === "abc" ? (
    colorName === "abc" ? (
      "var(--blue2)"
    ) : (
      "var(--blue23)"
    )
  ) : (
    "var(--red4)"
  );

const message = (i: number) =>
  i % 3 === 0 && i % 5 === 0 ? (
    "fizzbuzzfizzbuzzfizzbuzzfizzbuzz"
  ) : i % 3 === 0 ? (
    i % 3 === 0 ? (
      "ffizzbuzzfizzbuzzfizzbuzzfizzbuzzizz"
    ) : (
      i % 5 === 0
    )
  ) : i % 5 === 0 ? (
    "fizzbuzzfizzbuzzfizzbuzzfizzbuzz"
  ) : (
    String(i)
  );
```

The original is much better. The current PR is terrible.

**Comment by rattrayalex** [comment]
Having examples is helpful, thank you – especially when they are more real-world / have sensible code.

I am now convinced that the "JSX style approach" is too simplistic to work well everywhere, so I will close this PR.

I am however still optimistic (possibilistic?) that a solution may exist which truly improves the readability of nested/chained ternaries everywhere.

@DScheglov , I am also starting to think that **case-style** might be a good starting point in general, eg:

```js
const result = 
  children && !isEmptyChildren(children) ? children : 
  props.match ? (
    component ? React.createElement(component, props) : 
    render ? render(props) : 
    null
  ) : 
  null;
```

I'm also interested in the **if-else-style** approach [outlined here](https://github.com/prettier/prettier/issues/737#issuecomment-370202601) by @JAForbes, eg:

```js
const result =
  children && !isEmptyChildren(children)
    ? children
  : props.match
    ? (component
        ? React.createElement(component, props)
      : render
        ? render(props)
        : null)
    : null;
```

I've opened a separate issue to muse about the possibilities at greater length: https://github.com/prettier/prettier/issues/9561

**Comment by lydell** [comment]
@rattrayalex I draw the opposite conclusion from the provided examples (only one of which seems to be real-world code). In my opinion, the JSX style was easier to read in all cases. Longer, yes. More parens, yes. But not noiser than good ol’ if-else.

I think we should reopen and at least give it a chance.

**Comment by rattrayalex** [comment]
@lydell fair, done!

Though I gotta say, I really like the case-style when things are simple, and it naturally turns right into ~JSX-style when they're not:

```jsx
const message =
  i % 3 === 0 && i % 5 === 0 ? "fizzbuzz" :
  i % 3 === 0 ? "fizz" :
  i % 5 === 0 ? "buzz" :
  String(i);

const message =
  i % 3 === 0 && i % 5 === 0 ? (
    // pretend this is big and complex
    "fizz" + "buzz" 
  ) :
  i % 3 === 0 ? (
    // this too
    "fizz" 
  ) :
  i % 5 === 0 ? (
    // such a long line wow
    "buzz" 
  ) : (
    // and this
    String(i)
  );
```

**Comment by rattrayalex** [comment]
@lydell btw, a big part of my motivation in opening #9561 is handling TS Conditional types nicely, which IMO look really bad with JSX-style:

```ts
type TypeName<T> = 
  T extends string ? (
    "string"
  ) : T extends number ? (
    "number"
  ) : T extends boolean ? (
    "boolean"
  ) : T extends undefined ? (
    "undefined"
  ) : T extends Function ? (
    "function"
  ) : (
    "object"
  );

type Unpacked<T> =
  T extends (infer U)[] ? (
    U
  ) : T extends (...args: any[]) => infer U ? (
    SomeVeryLongNameOfSomeKind<U>
  ) : T extends Promise<infer U> ? (
    U
  ) : (
    T
  );
```

if members of the TS community disagree and find this the most readable option, I'd be quite happy to put this back on the table!

**Comment by DScheglov** [comment]
@rattrayalex , I've posted real-world example in the Issue, see the comment:
https://github.com/prettier/prettier/issues/5814#issuecomment-719588547

It is absolutely real.

**Comment by thorn0** [comment]
@rattrayalex WRT conditional types, see #7948 for some good code examples.

**Comment by rattrayalex** [comment]
Just musing aloud, I wonder about an "all-or-nothing" approach to chained ternaries, where if none of the ternaries break, you get this:
```js
const pickBgColor = (colorName) =>
  colorName === 'active' ? 'var(--blue2)' :
  colorName === 'inactive' ? 'var(--blue1)' :
  colorName === 'success' ? 'var(--green4)' :
  'var(--red4)';
```
but if any of them are too long for one line, they all become JSX-style...

**Comment by thorn0** [comment]
@rattrayalex I proposed a similar thing in #7948 for conditional types, but for normal (non-type) conditionals, it might be too diff-unfriendly to reformat an entire multiline expression upon changing only a small part of it.

**Comment by rattrayalex** [comment]
Ah, yes, that's a very good point. Really changes how I think about this to be honest.

**Comment by DScheglov** [comment]
> Ah, yes, that's a very good point. Really changes how I think about this to be honest.

Hey, @rattrayalex , any option we choose (except keeping as is) will be diff-unfriendly, ... 
It seems to be needed an setting.

And one more option -- it is difficult, but possible. Prettier analyzes the source code and defines "current" style and after that checks style-consistency.

**Comment by rattrayalex** [comment]
Sorry, to be clear, the diff changes we are talking about are _while editing code_ once this is released, not "at release of this change". 

Constant large diffs while editing code, in places unrelated to the line you're editing, happen sometimes with prettier but are great to avoid whenever possible.

I appreciate the desire to be helpful, but adding new settings or having prettier "keep existing style" are antithetical to prettier's philosophy. As you can see from countless threads, prettier would rather make some (even many) people unhappy with how their code looks than adopt either approach. I am not a core maintainer; I don't make these rules, I just have to play by them.

**Comment by thorn0** [comment]
Adding a setting also means admitting that all the proposals are equally good/bad, so the whole problem is nothing more but bike shedding, in which case we can as well simply do nothing. I hope it's not the case though.

**Comment by rattrayalex** [comment]
I no longer think this is a good idea, should have closed this a while ago. 

I now believe that postfixed ternaries are the only scalable, readable, consistent alternative, proposed here as "Option B2": https://github.com/prettier/prettier/issues/9561#issuecomment-720262830

**Pull request closed without merging**
