### PR TITLE
Build: Switch to `esbuild`

### PR DESCRIPTION
**Pull request by fisker**
## Description

The cache part is not implemented, `esbuild` is already fast enough, maybe we don't need it.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
Good! But I have some concerns. Can you show me the below data?

- How faster than building with Rollup
- Comparison of the bundle size of the result between Rollup and esbuild
- Comparison of the execution speed of the final JavaScript output between Rollup and esbuild

**Comment by fisker** [comment]
This log should answer your first two questions https://github.com/prettier/prettier/runs/4738823093?check_suite_focus=true#step:8:94

**Comment by sosukesuzuki** [comment]
Copied from the output of the action. Good!

***

**Size Change:** -1.12 MB (-10%) 👏

**Total Size:** 10.5 MB

| Filename | Size | Change |  |
| :--- | :---: | :---: | :---: |
| `dist/bin-prettier.js` | 437 kB | -34.4 kB (-7%) | ✅ |
| `dist/doc.js` | 109 kB | -13.4 kB (-11%) | 👏 |
| `dist/index.js` | 1.59 MB | -70.5 kB (-4%) |  |
| `dist/parser-angular.js` | 91.9 kB | -2.12 kB (-2%) |  |
| `dist/parser-babel.js` | 368 kB | -3.61 kB (-1%) |  |
| `dist/parser-espree.js` | 234 kB | +1.86 kB (+1%) |  |
| `dist/parser-flow.js` | 2.1 MB | -1.12 MB (-35%) | 🎉 |
| `dist/parser-glimmer.js` | 189 kB | +3.51 kB (+2%) |  |
| `dist/parser-graphql.js` | 45 kB | +3.93 kB (+10%) | ⚠️ |
| `dist/parser-html.js` | 160 kB | -4.61 kB (-3%) |  |
| `dist/parser-markdown.js` | 155 kB | -12.4 kB (-7%) | ✅ |
| `dist/parser-meriyah.js` | 236 kB | +816 B (0%) |  |
| `dist/parser-postcss.js` | 230 kB | -16.6 kB (-7%) | ✅ |
| `dist/parser-typescript.js` | 3.59 MB | +150 kB (+4%) |  |
| `dist/parser-yaml.js` | 126 kB | -19.6 kB (-13%) | 👏 |
| `dist/standalone.js` | 532 kB | +715 B (0%) |  |
| `dist/third-party.js` | 307 kB | +19.1 kB (+7%) | 🔍 |

<a href="https://github.com/preactjs/compressed-size-action"><sub>compressed-size-action</sub></a>

**Comment by sosukesuzuki** [comment]
Also extremely fast... I was surprised...

**Review by duailibe — APPROVED** [review]
Looks good to me. Just tested locally on my machine, it is very fast indeed.

And let's remove the cache, it's no longer necessary

**Comment by alexander-akait** [comment]
@sosukesuzuki The size has somehow greatly decreased, this may be suspicious and a signal that something is broken...

**Comment by fisker** [comment]
The file decreased most is `parser-flow.js`, the original `flow_parser.js` file from `flow-parser` package is minified and size is 3m, I think esbuild somehow tree-shaked some code.

I won't worry about this file, as we have most test fixtures for `flow`(`flow-repo` and `flow` dir in `tests/format`), I think we covers everything.

**Review by sosukesuzuki — CHANGES_REQUESTED** [review]
LGTM!!

**Review by sosukesuzuki — APPROVED** [review]
I pressed the Request Change button by mistake...

**Comment by fisker** [comment]
One note: this plugin `@esbuild-plugins/node-globals-polyfill` is not good, it injects code to every file for global `process`, and it supposed to polyfill global `__dirname` and `__filename` too(though we are not using). Maybe I'll build one later.

**Comment by fisker** [comment]
Maybe I should try backport this to main branch? V3 is far to release..

I'm not sure if it can bundle postcss

**Review by alexander-akait — APPROVED** [review]

**Pull request merged**
