### PR TITLE
feat(css): lowercase build-in functions

### PR DESCRIPTION
**Pull request by evilebottnawi**
Two question:
1. Can i create `reference` directory and put all `keywords` and build-in `css` stuff there?
2. In theory it can be break this code (only for scss):
```scss
@function URL($some-number, $another-number){
  @return $some-number + $another-number
}

.my-module {
  padding: URL(10px, 5px);
}
```
But it is very very bad practice (i don't see in popular framework this), maybe better use `prettier-ignore` for this and add docs?

### CODE REVIEW

**Comment by lydell** [comment]
This is probably safe in practice, but not in theory. In SCSS you can define a function like:

```scss
@function ScaleX($x) {
  @return scaleX($x * 0.99);
}
```

If so, it is not correct to change `transform: ScaleX(5);` into `transform: scaleX(5);`.

**Comment by j-f1** [comment]
How about only doing this for vanilla CSS?

**Comment by lydell** [comment]
Personally, I don't think this is worth doing at all. I have never seen anyone use unusual casing for functions in CSS.

**Comment by j-f1** [comment]
Should we fix the conflicts, make the required changes, and merge, or should we close this?

**Comment by lydell** [comment]
I vote for closing, but I don’t feel strongly about this.

**Comment by evilebottnawi** [comment]
@j-f1 we can merge this only for vanilla CSS, it is safe, for less/scss it is not safe, if we accept it for vanilla css i can rebase

**Pull request closed without merging**
