### PR TITLE
Add exit code information to cli docs

### LINKED ISSUE #5896: CLI exit status not documented
Apparently, prettier can terminate with exit status 0, 1 and 2. However, I found no documentation specifying what differs between exit status 1 and 2.

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Closes #5896 

> Add CLI existing status information the the docs.

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@j-f1 Thoughts :thinking:

**Comment by evilebottnawi** [comment]
Please fix linting problems

**Comment by jamesgeorge007** [comment]
@evilebottnawi I'm that sure regarding the one error that still exists :confused:

**Comment by jamesgeorge007** [comment]
@j-f1 Any specific reason for keeping this in hold?

**Comment by j-f1** [comment]
Thanks for contributing to Prettier!

**Pull request merged**
