### PR TITLE
Removed experimental plugins

### PR DESCRIPTION
**Pull request by ntotten**
Removing plugins that abuse the plugin api.

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by lipis — APPROVED** [review]

**Comment by thorn0** [comment]
Somebody has to check other plugins on this page too. E.g. `prettier-plugin-package` is very similar to `prettier-plugin-organize-imports` in how it monkeypatches a built-in parser to reorder things.

**Comment by hosseinmd** [comment]
@thorn0 In this commit [Remove more plugins that use the API in a non-intended way](https://github.com/prettier/prettier/pull/9417/commits/75f5587a9be9871a9f5d5e8d0d9e5f86bbe7ba5f)

I want to know what part of that is non-intended?

**Comment by simonhaenisch** [comment]
lol just found out my plugin got removed from the website a long time ago for some interesting reasons...

- I changed my plugin to be compatible with other plugins that also set `preprocess` in March 2020 already
- Not sure why you'd expose a `preprocess` hook in the plugin API and then call it "abuse" and "unintended" when someone uses it to do some preprocessing with it 🤷🏻‍♂️
- You talk about monkey-patching like it's a bad thing but the whole purpose of Prettier's plugin API is so that Prettier can be [monkey-patched](https://en.wikipedia.org/wiki/Monkey_patch) 🤔 

I mean it's kind of your website so you can put on it whatever you want but it's also more like it's the Prettier community's website so it's kind a lame that one person can just remove whatever from it.

I still think a list of non-official community plugins on the website would be useful for people.

**Comment by thorn0** [comment]
@simonhaenisch The point is that the plugin API is intended for adding support for more languages to Prettier, not to change how the existing formatters work. I have to admit I use your plugin myself and find it practical, but it really should've been implemented as an ESLint rule, not a Prettier plugin. Simply because Prettier is a formatter, not a linter. We don't want to encourage creation of new linter-like plugins by promoting such a plugin on the website. Sorry.

**Comment by simonhaenisch** [comment]
I've used existing implementations for sorting imports via ESLint auto-fix and it also works well, but IMO it's arguable whether this is a linter or a formatter's responsibility, it can fit both. That's the reason for this plugin's existence... I don't always use ESLint but I always use Prettier.

Anyway, thanks for the clarification, makes sense.

**Comment by thorn0** [comment]
Reordering things and especially removing unused things is much closer to ESLint's "auto-fixable" rules than to formatting. Prettier never does that kind of things. See also #2277, https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about

The current plugin API is for adding new parsers and printers to Prettier, not for changing the existing ones. Plugins that change existing parts of Prettier are relying on implementation details. This is not a proper usage of the public API.

**Comment by JounQin** [comment]
@thorn0 

I just notice this PR, this is very interesting.

> The current plugin API is for adding new parsers and printers to Prettier, not for changing the existing ones.

The plugin API is unlimited, or you should forbid current monkey-patched behavior for plugins.

> What Prettier is not concerned about

This is definitely fine for `prettier` core itself, but why it should enforce the 3rd-party plugins? I don't get it.

---

For my own use case, [`prettier-plugin-pkg`](https://github.com/un-ts/prettier/tree/master/packages/pkg) relies on `pretter`'s built-in parser, which `ESLint` does not have by default (there does have a [`jsonc-eslint-parser`](https://github.com/ota-meshi/jsonc-eslint-parser) from community now), that says using `prettier`'s `json` parser is much easier for developers than adding `eslint` + `jsonc-eslint-parser` + [`eslint-plugin-jsonc`](https://github.com/ota-meshi/eslint-plugin-jsonc) + another custom rule.

These plugins are added into document previously, but you suddenly removed them without any discussion, this seems incorrect to me at least. Whether listing here is not a big deal to me, but the statement

> This is not a proper usage of the public API.

is absolutely wrong for me personally.

The public API is just *`public`*.

**Comment by thorn0** [comment]
Monkey patching and the inner workings of the built-in parsers are not public API. If you do it, keep in mind that it's not supported and can break in any version

**Comment by JounQin** [comment]
> Monkey patching and the inner workings of the built-in parsers are not public API. If you do it, keep in mind that it's not supported and can break in any version

It's still the plugin authors' choice. Monkey patching is very commonly used in JavaScript, and it doesn't need to be documented as public API, it **is** public already.

**Comment by thorn0** [comment]
Monkey patching means hacking on undocumented implementation details. A very opposite thing to what "public API" normally means. Anybody is free to hack things however they like, but it doesn't mean Prettier's site should promote these unsupported practices. If we want to let plugins augment the built-in parsers and printers, a proper API should be added for that.

**Comment by JounQin** [comment]
I understand your concern and totally fine with removing them from the official document, but I still think it should not be discouraged to add features for their own or community usage based on current API by your statement.

We, developers, are just making incredible prettier plugins, it should not be considered as abuse.

**Pull request merged**
