### PR TITLE
Refactor: Move `isSourceElement` to languages

### PR DESCRIPTION
**Pull request by fisker**
This should make plugin able to do range format, #7639, but we need update docs to close it.

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by cposture** [comment]
I have also encountered a problem. When will the problem be fixed? @fisker

**Comment by cposture** [comment]
@alexander-akait

**Comment by fisker** [comment]
> I have also encountered a problem. 

What do you mean? Are you writing a Prettier plugin?

**Comment by cposture** [comment]
> > I have also encountered a problem.
> 
> What do you mean? Are you writing a Prettier plugin?

yes, I plan to write a customer thrift plugin to support for vim

**Comment by fisker** [comment]
A recent change in "range format for JSON" shows only expose `isSourceElement` to plugin seems not enough for plugins, we may need to reconsider this.

In #10497 we use a different ancestor logic for the JSON parser.

**Comment by cposture** [comment]
ok，thx. Are there any plans? Recently, using prettier to write custom plugin for thrift  has encountered many problems

**Comment by fisker** [comment]
> Are there any plans?

No, not yet.

**Comment by fisker** [comment]
> has encountered many problems

Are you willing to share?

**Comment by cposture** [comment]
> > has encountered many problems
> 
> Are you willing to share?

I just started to learn the front end recently, and I don’t feel like I’m up to it. 😅

**Comment by fisker** [comment]
Superseded by #11411.

**Pull request closed without merging**
