### PR TITLE
feat: normalize `url` in `@import` directive

### PR DESCRIPTION
**Pull request by evilebottnawi**
:star:

### CODE REVIEW

**Comment by j-f1** [comment]
Would it be possible to break the parens if the file name gets too long?

**Prettier pr-3771**
[Playground link](https://5a6236bea11477263e0cb66b--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEABAlgWwA4QE4wAEArngDYAUAOiAM4SZwC06UYecAJugEZkCeTMtADmTbAEMYACyYwIc6elpMwtFQDN0ZOAHoA7uhlMJTAG5w8gi1aGimUCYwB0a2jQCUAbipRfGHHwiUkpfQkIaekYWNg5uPkFhKDFJY3lFZVV1Ji0dAyNZUxtrS0T7Rxc3Gl9vEAAaEAhsGHRoWmRQCTw8CH0ABS6EdpQJMwh0TnqQCVoYZA0JMlo4Bp48CTAAazgYAGVJMFYRZBg8YhWQTggwecXlhtZlgj71kUwJW6WLgCtaAA8AELrLY7XZOOAAGVYcE+90axBg2ARACZYRdJHgnsg6G4ptg8KwYAB1CYyZAADgADA18RBlkT1thsfi4E8LFMOABHYjoDgvCRvD5IBZfBrLTDoE5nC60I46ACKxAg8DRDRgEh4JM4ZKQyLV620RwAwgx3tioNAYQ1iMsACoa4Yi5YAX2dQA)
```sh
--parser scss
```

**Input:**
```scss
@import url("some-incredibly-long-path-to-this-css-file/with-a-very-very-long-name.css");

@import url(
  "some-incredibly-long-path-to-this-css-file/with-a-very-very-long-name.css"
);
```

**Output:**
```scss
@import url("some-incredibly-long-path-to-this-css-file/with-a-very-very-long-name.css");

@import url("some-incredibly-long-path-to-this-css-file/with-a-very-very-long-name.css");

```

**Comment by evilebottnawi** [comment]
@j-f1 interesting question, from spec:

> The token S in the grammar above stands for white space. Only the characters "space" (U+0020), "tab" (U+0009), "line feed" (U+000A), "carriage return" (U+000D), and "form feed" (U+000C) can occur in white space. Other space-like characters, such as "em-space" (U+2003) and "ideographic space" (U+3000), are never part of white space.

Seems it is allowed, do this in this PR or other?

**Comment by hawkrives** [comment]
@j-f1 I feel like `@import` should kinda behave like `import` or `require`, where the argument is always inlined?

**Comment by evilebottnawi** [comment]
@hampusohlsson I have the same opinion, better inline `import` for best reading

**Comment by j-f1** [comment]
That makes a lot of sense. Relevant code from the JS printer:

https://github.com/prettier/prettier/blob/74d25c37f07fa3898ce400c1ff0b246dded05f04/src/language-js/printer-estree.js#L805-L808

**Comment by hampusohlsson** [comment]
@evilebottnawi not following the context here, what are you referring to?

**Comment by evilebottnawi** [comment]
@hampusohlsson css spec :smile:  then i say about inline import better:
bad:
```css
@import url(
  "some-incredibly-long-path-to-this-css-file/with-a-very-very-long-name.css"
);
```
good:
```css
@import url("some-incredibly-long-path-to-this-css-file/with-a-very-very-long-name.css");
```

**Comment by lydell** [comment]
It's so sad the parsing isn't more granular so we wouldn't have to write code for these things.

**Comment by evilebottnawi** [comment]
@lydell we can fix it, i requested an invite in `postcss-media-query-parser` to allow improve and fix problems faster for `stylelint` and `prettier`

**Comment by azz** [comment]
Status of this PR?

**Comment by evilebottnawi** [comment]
@azz WIP

**Comment by j-f1** [comment]
@evilebottnawi Status of this PR?

**Comment by evilebottnawi** [comment]
@j-f1 not require after https://github.com/prettier/prettier/pull/4435

**Pull request closed without merging**
