### PR TITLE
Website: Add Nova text editor

### PR DESCRIPTION
**Pull request by bdielman**
Adding a link to the Prettier extension and images for the Panic's Nova text editor.

### CODE REVIEW

**Comment by fisker** [comment]
Is this png  file used?

**Comment by bdielman** [comment]
I noticed PNG versions of the other app logos in the repo so I included it here as well. If they are no longer being used I'm happy to remove it.

**Comment by fisker** [comment]
Please remove it.

**Review by fisker — APPROVED** [review]
LGTM , except the unused .png file.Thanks.

**Comment by bdielman** [comment]
PNG removed! Thanks!

**Review by evilebottnawi — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]

**Pull request merged**
