### PR TITLE
Playground: show sidebar by default

### PR DESCRIPTION
**Pull request by thorn0**
## Description

Why do we need that extra click?

## Checklist

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Don't show by default on cellphone 
Screenshot

**Comment by thorn0** [comment]
I thought it's unusable on mobile

**Comment by fisker** [comment]
Hard, but usable.

**Comment by fisker** [comment]
At least can view issue link. 😄

**Review by fisker — APPROVED** [review]

**Pull request merged**
