### PR TITLE
Handlebars: Add tests for `ignore` and `strict` modes (1/3)

### PR DESCRIPTION
**Pull request by dcyriller**
## Description

This PR proposes a refactor of the `whitespace` folder in Handlebars tests.
- it renames the folder from `whitespace` to `mode-default` and does not configure `htmlWhitespaceSensitivity` option
- it copies the `mode-default` folder to `mode-ignore` and configures `htmlWhitespaceSensitivity=ignore`
- it copies the `mode-default` folder to `mode-strict` and configures `htmlWhitespaceSensitivity=strict`

My goal is to propose an implementation of the whitespace sensitive mode in the next PR. I propose to add tests first to have a nice diff. The PR might be reviewed commit by commit.

Step 1 out of 3 of https://github.com/prettier/prettier/issues/9881

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Do you think better add a dir to test for it?

**Comment by dcyriller** [comment]
100% agreed, let me do that

**Comment by dcyriller** [comment]
The PR is updated, as well as the description (as I repurposed it after your suggestion)

**Comment by dcyriller** [comment]
Do you think it’s better @fisker?

**Comment by fisker** [comment]
I don't think we should move other tests, how about a dir named `html-whitespace-sensitivity`, and test both `ignore` and `strict` in one file.

I think still too many files for this option, shouldn't a few cases enough, but if you think all lines are necessary, I'm also okay with it?

**Review by fisker — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
