### PR TITLE
[RFC] Introduce infiniteWidth document

### LINKED ISSUE #616: Braceless if + return + object is not stable
```js
function f() {
  if (position)
    return {name: pair};
  else
    return {name: pair.substring(0, position), value: pair.substring(position + 1)};
}
```

turns into

```js
function f() {
  if (position) return { name: pair };
  else return {
      name: pair.substring(0, position),
      value: pair.substring(position + 1)
    };
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20f()%20%7B%5Cn%20%20if%20(position)%5Cn%20%20%20%20return%20%7Bname%3A%20pair%7D%3B%5Cn%20%20else%5Cn%20%20%20%20return%20%7Bname%3A%20pair.substring(0%2C%20position)%2C%20value%3A%20pair.substring(position%20%2B%201)%7D%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

which then turns into

```js
function f() {
  if (position)
    return { name: pair };
  else
    return {
      name: pair.substring(0, position),
      value: pair.substring(position + 1)
    };
}
```

Notice that return are now indented whereas before they were on the same line.

### LINKED ISSUE #625: Braceless arrow function indentation is not stable
```js
function render() {
  return (
    <View>
      <Image
        onProgress={(e) => this.setState({progress: Math.round(100 * e.nativeEvent.loaded / e.nativeEvent.total)})}
      />
    </View>
  );
}
```

turns into

```js
function render() {
  return (
    <View>
      <Image
        onProgress={e =>
          this.setState({
            progress: Math.round(
              100 * e.nativeEvent.loaded / e.nativeEvent.total,
            ),
          })}
      />
    </View>
  );
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20render()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3CView%3E%5Cn%20%20%20%20%20%20%3CImage%5Cn%20%20%20%20%20%20%20%20onProgress%3D%7B(e)%20%3D%3E%20this.setState(%7Bprogress%3A%20Math.round(100%20*%20e.nativeEvent.loaded%20%2F%20e.nativeEvent.total)%7D)%7D%5Cn%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%3C%2FView%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

which then turns into

```js
function render() {
  return (
    <View>
      <Image
        onProgress={e => this.setState({
          progress: Math.round(
            100 * e.nativeEvent.loaded / e.nativeEvent.total,
          ),
        })}
      />
    </View>
  );
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22function%20render()%20%7B%5Cn%20%20return%20(%5Cn%20%20%20%20%3CView%3E%5Cn%20%20%20%20%20%20%3CImage%5Cn%20%20%20%20%20%20%20%20onProgress%3D%7Be%20%3D%3E%5Cn%20%20%20%20%20%20%20%20%20%20this.setState(%7B%5Cn%20%20%20%20%20%20%20%20%20%20%20%20progress%3A%20Math.round(%5Cn%20%20%20%20%20%20%20%20%20%20%20%20%20%20100%20*%20e.nativeEvent.loaded%20%2F%20e.nativeEvent.total%2C%5Cn%20%20%20%20%20%20%20%20%20%20%20%20)%2C%5Cn%20%20%20%20%20%20%20%20%20%20%7D)%7D%5Cn%20%20%20%20%20%20%2F%3E%5Cn%20%20%20%20%3C%2FView%3E%5Cn%20%20)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

If you look closely, `this.setState({` goes from being on its own line to being on the same line as `=>`.

### PR DESCRIPTION
**Pull request by vjeux**
For some reason I don't understand, breakParent doesn't have the intended effect. But having a document that always puts the remaining with to < 0 does.

I'm pretty sure that we should actually fix the issue with breakParent but wanted to show a solution that would work.

Fixes #625
Fixes #616

### CODE REVIEW

**Comment by jlongster** [comment]
That's strange, I would like to look into this more because it feels like it's working around a bug. Does it involve `conditionalGroup`? Remember that breaks are not propagated across them, so you need to use `willBreak` and manually manage breaking.

**Comment by vjeux** [comment]
Just rebased it

**Comment by jlongster** [comment]
Thanks. I've been very busy recently so sorry I haven't had a chance to look at this yet. Tomorrow is pretty busy as well but I'll try to find time for this. (Usually if I have time I skim through all the other issues/prs :p)

**Comment by jlongster** [comment]
I took a look at this. I don't know the solution yet, but here's what I found:

* The problem is that we forcibly break objects if they were expanded in the original source. That causes these kinds of problems, because if a source has a collapsed object and then we naturally expand it, running prettier on it again will see that it's expanded and forcibly expand it. In case #1, the code does not see any hard breaks, so any checks like `willBreak` will be false, but in case #2, it does see hard breaks, so `willBreak` and friends will be true. This changes how various code interacts and deals with breaks.

I still wish we didn't keep objects expanded. :)

* Your PR happens to fix it, but now for the reason you think. This simple patch makes the problem go away:

```js
diff --git a/src/printer.js b/src/printer.js
index 3a9e6e8..171670c 100644
--- a/src/printer.js
+++ b/src/printer.js
@@ -711,18 +711,17 @@ function genericPrintNoParens(path, options, print) {
             ifBreak(
               canHaveTrailingComma && shouldPrintComma(options) ? "," : ""
             ),
             indent(
               parentIsUnionTypeAnnotation ? 2 : 0,
               concat([options.bracketSpacing ? line : softline, rightBrace])
             ),
             path.call(print, "typeAnnotation")
-          ]),
-          { shouldBreak }
+          ])
         );
       }
 
     case "PropertyPattern":
       return concat([
         path.call(print, "key"),
         ": ",
         path.call(print, "pattern")
```

But that removes the feature of breaking an object if anything inside it is broken, so we obviously can't do that. Your code happens to remove this so it "works", but you don't need `infiniteWidth` at all.

This points to why this is happening: the `shouldBreak` is `false` in the first pass, and `true` in the second pass.

I don't know the right solution yet. I'll come back to this tomorrow!

**Comment by jlongster** [comment]
Overtaken by #1032

**Pull request closed without merging**
