### PR TITLE
Enable flowComments for babel-flow

### PR DESCRIPTION
**Pull request by sosukesuzuki**
https://github.com/prettier/prettier/issues/9062#issuecomment-680856494

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
What  about `babel`? It support `flow`, We'll have  to deal with it too.

I  hate  this , in one hand we are trying to remove`flow` from `babel`, in another hand  we have to add more stuff for it.

**Comment by thorn0** [comment]
> What about babel? It support flow

My opinion is that it's fine to ignore Flow comments in `babel`. Its support for Flow isn't reliable anyway.

**Comment by fisker** [comment]
I talready know it's broken, ignoring the problems seems not good.

How about redirect to `babel-flow` too, if `/*::` found https://github.com/prettier/prettier/pull/9071

**Comment by thorn0** [comment]
These comments are a little-used and little-known feature of Flow. If someone goes to the trouble of using them, it shouldn't be difficult for this person to add `@flow` or switch parsers in Prettier.

**Comment by thorn0** [comment]
This PR misses this part from https://github.com/prettier/prettier/issues/9062#issuecomment-680856494: "and unify the code for `flow` and `babel-flow`".
Code like the `hasFlowShorthandAnnotationComment` and `hasFlowAnnotationComment` functions was added for Babel only because back then Babel didn't have the `flowComments` plugin. Hopefully it should be safe to remove them now.

**Comment by thorn0** [comment]
Superseded by #13687

**Pull request closed without merging**
