### PR TITLE
chore: remove tslib from cspell.json

### PR DESCRIPTION
**Pull request by brodybits**
## Description

see description

discovered while working on: <https://github.com/brodybits/prettierx/pull/569>
## Checklist

- ~~I’ve added tests to confirm my change works.~~
- ~~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).~~
- ~~(If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.~~
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Do you know there is a script to clean it? https://github.com/prettier/prettier/blob/main/scripts/clean-cspell.mjs

**Comment by brodybits** [comment]
Any pointers how I should run it?

**Comment by fisker** [comment]
`node scripts/clean-cspell.mjs`

**Comment by brodybits** [comment]
> node scripts/clean-cspell.mjs

Does not work for me on Node.js 14 or 16.

WIth Node.js 14:

```console
% node scripts/clean-cspell.mjs
Empty words ...
Running spellcheck with empty words ...
Updating words ...
Running spellcheck with new words ...
(node:84878) UnhandledPromiseRejectionWarning: Error: Command failed with ENOENT: yarn lint:spellcheck
spawn yarn lint:spellcheck ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:467:16)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:84878) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:84878) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

On Node.js 16:

```console
% node scripts/clean-cspell.mjs
Empty words ...
Running spellcheck with empty words ...
Updating words ...
Running spellcheck with new words ...
node:internal/errors:456
    ErrorCaptureStackTrace(err);
    ^

Error: Command failed with ENOENT: yarn lint:spellcheck
spawn yarn lint:spellcheck ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn yarn lint:spellcheck',
  path: 'yarn lint:spellcheck',
  spawnargs: [],
  originalMessage: 'spawn yarn lint:spellcheck ENOENT',
  shortMessage: 'Command failed with ENOENT: yarn lint:spellcheck\n' +
    'spawn yarn lint:spellcheck ENOENT',
  command: 'yarn lint:spellcheck',
  escapedCommand: '"yarn lint:spellcheck"',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

I think it may be easier if we can add this to the npm package scripts.

**Comment by fisker** [comment]
> I think it may be easier if we can add this to the npm package scripts.

I don't think this going to help.


The script works on Windows, try change `execa("yarn lint:spellcheck")` to `execa("yarn", ["lint:spellcheck"])` or `execa("npm", ["run", "lint:spellcheck"])` or `execa.command("yarn lint:spellcheck")`

**Comment by fisker** [comment]
Ah, I forgot put `await ` before `updateConfig(config);`(Line 38)

**Comment by brodybits** [comment]
Still not working for me, will try again sometime later. As I said before, I am still thinking it could really help the next person if we can put this in the package scripts. Thanks for your efforts on this.

**Pull request closed without merging**
