### PR TITLE
Fix binary expression comments

### LINKED ISSUE #946: Unstable comment in binary expression
```js
a = (
  // Commment 1
  (Math.random() * (yRange * (1 - minVerticalFraction)))
  + (minVerticalFraction * yRange)
) - offset;
```

```js
a = Math.random() * (yRange * (1 - minVerticalFraction)) +
  minVerticalFraction * yRange// Commment 1
   -
  offset;
```

```js
a = Math.random() * (yRange * (1 - minVerticalFraction)) +
  minVerticalFraction * yRange - // Commment 1
  offset;
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22a%20%3D%20(%5Cn%20%20%2F%2F%20Commment%201%5Cn%20%20(Math.random()%20*%20(yRange%20*%20(1%20-%20minVerticalFraction)))%5Cn%20%20%2B%20(minVerticalFraction%20*%20yRange)%5Cn)%20-%20offset%3B%5Cn%5Cna%20%3D%20Math.random()%20*%20(yRange%20*%20(1%20-%20minVerticalFraction))%20%2B%5Cn%20%20minVerticalFraction%20*%20yRange%2F%2F%20Commment%201%5Cn%20%20%20-%5Cn%20%20offset%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by yamafaktory**
This should fix #946 🤞.

### CODE REVIEW

**Comment by yamafaktory** [comment]
@vjeux your thoughts on this one?

**Comment by vjeux** [comment]
My quick intuition is that you're not solving the problem but just moving it up one level above. But I'm not sure if I'm right.

**Comment by yamafaktory** [comment]
Thanks! Actually not quite sure about what is the expected behavior... At least, this solves the test case you provided in the initial issue.

**Comment by yamafaktory** [comment]
@vjeux what should be cool is to know how it should behave on different test cases.

**Comment by vjeux** [comment]
The solution of just moving the comment without any kind of checks as a leading comment is good enough for nodes that are very rarely used or where you don't really expect comments. But binary expressions are very common and likely to have comments in various shapes. I don't think that we should blindly move them.

In this case, without your changes, the comment is being attached as a leading comment of the binary expression

```js
(Math.random() * (yRange * (1 - minVerticalFraction)))
  + (minVerticalFraction * yRange)
```

so this actually looks correct. But for some reason it isn't printed correctly. We need to figure out why!

**Comment by vjeux** [comment]
Okay, found out the issue ( https://github.com/prettier/prettier/blob/master/src/printer.js#L2893 ):

```js
parts.push(comments.printComments(path, p => "", options));
```

This doesn't print the comments at the correct location. It should instead be:

```js
return comments.printComments(path, p => concat(parts), options)
```

Unfortunately, because we're mutating the parts object and read it later on, this doesn't "just works". We need to refactor this code to avoid the mutation and manage the groups like we do for printMemberChain.

**Comment by vjeux** [comment]
See https://github.com/prettier/prettier/pull/1043 for a fix that doesn't involve a giant refactor but has some trade-offs.

**Comment by yamafaktory** [comment]
Ok, nice catch! Then just close this one and go for your fix 👍.

**Pull request closed without merging**
