### PR TITLE
[RFC DRAFT WIP] automate JavaScript type linting using checkJs, as configured in tsconfig.json

### PR DESCRIPTION
**Pull request by brodybits**
## What

- add `tsconfig.json`, as generated by `tsc -init`
- update `tsconfig.json` to support JavaScript type linting
- other `tsconfig.json` updates & cleanup
- additional devDependencies items to resolve some errors
- add `checkjs` package script entry

This is a followup to PR #6313, enables type checking without needing to port to TypeScript (ref: #6286).

Here is a description of JavaScript type linting, with focus on using VSCode: https://medium.com/@trukrs/javascript-type-linting-5903e9e3625f

## Status

Unfortunately there are many type errors that need to be resolved, as I reported in #6703.

I think we should also look into enabling some of the stricter options, once we resolve most of the errors according to #6703.

Any help with resolving the type errors in #6703 would be much appreciated.

/cc @Shinigami92 @rbiggs

- ~~I’ve added tests to confirm my change works.~~
- ~~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)~~
- ~~(If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.~~
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@brodybits the PR https://github.com/prettier/prettier/pull/6313 already has tsconfig. Can we do it in one PR https://github.com/prettier/prettier/pull/6313?

**Comment by brodybits** [comment]
Closing for now, will discuss in #6313.

**Comment by evilebottnawi** [comment]
@brodybits closing?

**Comment by brodybits** [comment]
Apologies, my bad, should be really closing now.

**Pull request closed without merging**
