### PR TITLE
Fix formatting of empty type parameters

### LINKED ISSUE #13817: [flow] broken code emitted for type annotation with empty type parameters when the value is an arrow function and `arrow-parens: 'avoid'`
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPXf8GFHGFI4kW4A8AfJgLwA6UmmAhgE4DmDdUArgBtBAbhAAaEBAAOMAJbpkoThwgB3AAqcEaZCDYA3CHIAmEkACMObMAGs4MAMpsAtnAAycqHGQAzNoJocJJWNvZO0jZeXMgwHPzBIHAuFnAmJmnubFBc-GxccABiEBwubDDyOXps-DAQ5gAWMC6CAOoNcvBokWBwjjqdcgadAJ56YGi6kl5BHDAa1lxlfgFBkgBWaNiO0YJwAIr8EPArgYmRHLN6voLq5tIcXjCtpjANyAAcAAySDxBBrWs0j0DzgswMPkkAEcjvAFjJdCg2GgALTeNJpcwcOAwuTYhb5ZZIfxnSRBFxyWLxRJoXYHWE+JBxBKSGBsCwvExvZAAJlZ1jkgmiAGEIC4ifphOZ+EEACrsxEktYgAwJACSUAysEcYEesgAgprHDARntTkEAL4WoA)

```sh
--parser flow
--arrow-parens avoid
--trailing-comma all
```

**Input:**

```jsx
const xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: xxxxxxxxxxxxxxxxxxxxxx<> =
  arg => null;
```

**Output:**

```jsx
const xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: xxxxxxxxxxxxxxxxxxxxxx<
  ,
> = arg => null;

```

**Expected behavior:**

Not-broken code. I'd suggest probably:
```jsx
const xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: xxxxxxxxxxxxxxxxxxxxxx<> =
  arg => null;
```

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #13817

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
@thorn0 This is regression introduced in #11515, so I guess we should add `name` check instead of move `.length === 0` out? [`07d8883`](https://github.com/prettier/prettier/pull/14073/commits/07d8883b87837eeceb55c10ae8b550a1bfec680d)

**Comment by thorn0** [comment]
The `name` check shouldn't affect anything as far as I can see. A `VariableDeclarator` node has only two subnodes: `init` and `id`. It's already known that `init` is an arrow function. So an `Identifier` node can only be `id`.

**Review by thorn0 — APPROVED** [review]
This is not ideal but not critical either.

**Prettier pr-14073**
[Playground link](https://deploy-preview-14073--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0DOMAEBZAngYQgFsAHaBGAJiUwCU4BDMGAOgDUIBLAEwDEBXKM07RCpcrAA8AHSiZMAegBUeMWSgVKABQBOEEmiULZAPkwBeTAApgmAB4AaTLkwBfAJQWzwWfMhQMTAYLTH40OABBK3cAbl9MHTgYfh05K3j5SW5OADcTDPl7EOA7VxjnYtwyoOKGVwLJBWy8+NjZMpAHEH0YEQDkUAYdPQB3LSGENGQQBgAbEYZcKa6AIx0mAGskgGUGIjgAGU4NZAAzOfDV9bAtmG2SJmOAc2QYHX44LrgiFbhubj+BwYUCe-AYTzgvAgOiIDBgvRB0wY-BgEE6IAAFjAiLMAOoYzjwNAPMBwbaTQm5Qm4aZgNDLEDHcI6GC6cGws4XT4gABWaDs22eszgAEV+BB4JzZpcQA8dMzpqdZhARuiSDpjjBcTwYBjkAA2ACsXXVEHCuPWJGm6rgzJycHRAEdxfBdPopigGGgALQaP5-dGJZ2cRJsp4cpDnaXc8JETivd4xoWReEalYouBaOA6I4nSNcrpoZNiiUO-PRrowBgrbXcXXISiV9acWbPMQRkC2w3osJwAAq1Y9UZlOQ+AEkoADYNswBqSDAIpPtjBcMKpeFXK4gA)

```sh
--parser flow
--print-width 65
```

**Input:**

```jsx
const MyComponent2: React.VoidFunctionComponent<
  /*MyComponent2Props*/
> = ({ x, y }) => {
  const a = useA();
  return (
    <div>
      x = {x}; y = {y}; a = {a}
    </div>
  );
};
```

**Output:**

```jsx
const MyComponent2: React.VoidFunctionComponent</*MyComponent2Props*/> =
  ({ x, y }) => {
    const a = useA();
    return (
      <div>
        x = {x}; y = {y}; a = {a}
      </div>
    );
  };

```

**Comment by fisker** [comment]
Multi line comment can get ugly.

**Prettier pr-14073**
[Playground link](https://deploy-preview-14073--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0DOMAEBZAngYQgFsAHaBGAJiUwCU4BDMGAOgDUIBLAEwDEBXKM07RCpcrAA8AHSiZMAegBUs+XjFkoFSgAUAThBJpVmJQtkA+TAF5MACmCYAHgBpMuTAF8AlDavATSCgMTAYbTH40OABBO28AbhM9OBh+PTk7E3lJbk4ANwss+Wdw4CdPePdS3ArQ0oZPIskFXIKTBNkKkBcQQxgRYORQBj0DAHcdEYQ0ZBAGABsxhlwZnoAjPSYAaxSAZQYiOAAZTi1kADMFqPXNsB2YXZImU4BzZBg9fjgeuCI1uG43ABRwYUBe-AYLzgvAgeiIDBg-TBswY-BgEG6IAAFjAiPMAOpYzjwNBPMBwXbTYn5Ym4WZgNCrECnKJ6GD6SHwi5Xb4gABWaCcu1e8zgAEV+BB4Nz5tcQE89KzZud5hAxpiSHpTjB8TwYFjkAA2ACsPU1ECi+M2JFmmrgrLycExAEdJfB9IYZigGGgALRaAEAzHJV2cZIcl5cpCXWW8qJETjvT5xkUxRFatZouA6OB6E5naM8npoVMSqVOwuxnowBhrXXcfXISjVzaceavMRRkD242YyJwAAqta9MbleS+AEkoEDYLswFqSDBotPdjBcKKZVFPJ4gA)

```sh
--parser flow
--print-width 65
```

**Input:**

```jsx
const MyComponent2: React.VoidFunctionComponent<
  /*
  MyComponent2Props
  */
> = ({ x, y }) => {
  const a = useA();
  return (
    <div>
      x = {x}; y = {y}; a = {a}
    </div>
  );
};
```

**Output:**

```jsx
const MyComponent2: React.VoidFunctionComponent</*
  MyComponent2Props
  */> = ({ x, y }) => {
  const a = useA();
  return (
    <div>
      x = {x}; y = {y}; a = {a}
    </div>
  );
};

```

**Pull request merged**
