### PR TITLE
Add note about SmartTabs

### PR DESCRIPTION
**Pull request by maximal**
## Description

I think it’s worth noticing for those who search for SmartTab-related tool (as I did, for example).

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by fisker — APPROVED** [review]
Thank you!

**Comment by maximal** [comment]
You’re welcome!

**Review by sosukesuzuki — APPROVED** [review]
Thank you!

**Comment by Deadly0** [comment]
@maximal nice :)

**Pull request merged**
