### PR TITLE
Use native module in test

### PR DESCRIPTION
**Pull request by fisker**
## Description

A small change to use module in `./utils/generate-schema.mjs`, but most important, this opens the door to use native module in tests, we'll be able to start [switch our codebase to esm](https://github.com/prettier/prettier/issues/10157).

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
Why did CI failed? At least tests in my machine(MacOS) don't fail.

**Comment by fisker** [comment]
I don't know, it passes on my windows too. There must be something wrong when running multiple workers. I've tried a lot of ways when [refactoring CI to  use esm](https://github.com/fisker/prettier/pull/1276), unlucky, none of them works.

**Comment by fisker** [comment]
I'll change base to `next` branch, too see if we can make it work without support for Node.js 10.

**Comment by fisker** [comment]
Close in favor of #11891

**Pull request closed without merging**
