### PR TITLE
Indent <script> and <style> tags’ content in *.vue files 

### LINKED ISSUE #3888: Indent script and style tags content in *.vue files
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wB8AOlAAQVlwAeeEWMZAJnAGYCGArgDaPCmVBZALYROsOEwAUASjL9yQpZCjoI3OADpuEAOZSA5AGEIwulASNR4+EwCEBmQKVkAvs4ruoqAPSZcBCRQIAA0IBAEONDoyKDsWFgQAO4ACvEIMSjsAG4QOEyhIOzoMMgc3OhwYQBGWOxgANZwMADKePU4ULrIMFicVSBMEGBl7BUDnZUMKXW6wuyj42EAVujUAEJ1jc0t7MJwADKdcIuVYWIweJwwAEynA+1YU8gg2f2FeLiwAOr5MAAWyAAHAAGMKfCCVb51PAvT5wKbZE5hLBwACOnBwqJm7DmCyQ5TOIEqwhwPT6A3QnV0GgAipwIPB7mEYOxqr8mADkAAWFl1HDcakmYTzF5QaDIkCcSoAFTZmUJcFcriAA)

When I have a Vue.js file:

```vue
<script>
    export default {
        mounted() {
            console.log('Component mounted!')
        }
    }
</script>
```

How do I stop prettier changing the indentation to:

```vue
<script>
export default {
    mounted() {
        console.log("Component mounted!");
    }
};
</script>
```

### PR DESCRIPTION
**Pull request by nakatanakatana**
Fixes #3888

- [x] I’ve added tests to confirm my change works.
-  (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://deploy-preview-5574--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmpaEAqc2+8AzmXgE5xlQQxkBmENhgLwAJmQCecXgDo5pChVQB6aqRWZcBOCSjqmYNgEssMXTmlkAChxgwjcNmQC8-QcN7PCZYJIgBXNhkAKyYACgByGAALAIBzaIiASjIAX3VlA2NTXX0YCQtdGTwocV8wJiYkMhgICDIAQiNsQRgS3nSoFSZ8wpAAGhAIUyNoJmRQdjYIAHcrdgRxlDwANwgjUQGQACM2PDAAa2kAZSx9oyg45Bg2fzhB6JgMHAB1aKNmM7A4Y8WPoxWHwkyHAlS2FyYjhgNjwcWEyD4eBwkMGoQAHgAhPaHE54DBwAAyFzgCKRKJA6OOFziFgAiv4eCSkIjkfcQGc2JC2CCVnctlhjLAXhsYsgABwABkGAogkJeeywIIFcC5KxJgw4AEd-EYODC4XhSazBpCMEZrrc2UxqXSGfAjeS2tthaJRUgAEyDG54Iw4akAYQgGHhKG4UHVIH8kJoeG2SxZkNSqSAA)✨**

### CODE REVIEW

**Comment by Kocal** [comment]
Is it configurable with [`vue/script-indent`](https://vuejs.github.io/eslint-plugin-vue/rules/script-indent.html), or no matter what `<script>` and `<style>` will be indented? 😕

**Comment by j-f1** [comment]
@Kocal `<script>` & `<style>` will always be indented no matter what.

**Comment by Kocal** [comment]
Hum okay.

**Comment by chrisvfritz** [comment]
As a member of the Vue team, I personally don't think this should have anything to do with Vue. There does seem to be a huge split on people who prefer an indent or not for embedded languages, but this isn't a Vue-specific thing. It should behave the same everywhere there's XML.

**Comment by chrisvfritz** [comment]
To end bikeshedding on XML indentation for good, maybe it'd be best to just have an option like:

```js
"htmlNoIndentTags": ["html", "script", "style"]
```

Then indentation behavior could be the same across XML _everywhere_, even `.vue` files, maintaining the default to indent inside every tag since it's the conceptually simplest option.

**Comment by lydell** [comment]
> To end bikeshedding on XML indentation for good, maybe it'd be best to just have an option

No, then we'd just end the bikeshedding in this repo, moving the bikeshedding to every team using Prettier. See our [option philosophy](https://prettier.io/docs/en/option-philosophy.html).

**Comment by chrisvfritz** [comment]
@lydell I'm familiar with the option philosophy and one of the cases when you add new configuration is when there's huge demand. I completely understand having to draw a line, so what would sufficiently demonstrate that demand for this is huge enough? In the past, it looks like configuration requests with 30-100 upvotes have been accepted and the issue to resist adding configuration currently has 426 upvotes.

**Comment by chrisvfritz** [comment]
As an aside, my understanding is that another of Prettier's primary goals is consistency (and like any project, maintainability). As an open source maintainer myself, my worry is that special rules for `.vue` files set a precedent for more file-specific formatting. This would not only be a pain to implement and maintain, but also potentially confusing for users. Something I _really_ don't want is the same languages formatted differently depending on whether the extension is `js`, `jsx`, `ts`, `tsx`, `vue`, `ejs`, `erb`, etc - especially when the same extensions are used by multiple communities.

**Comment by lipis** [comment]
@nakatanakatana are you still around to add the option for this?

**Comment by lipis** [comment]
@prettier/core It looks like @nakatanakatana is not around.. :) Who can take or of that one?

**Comment by duailibe** [comment]
I can do this

**Comment by lipis** [comment]
@duailibe and maybe we can start preparing the blog post and the 1.17 release for that?

**Comment by lydell** [comment]
@azz I agree, I think it makes the most sense to have an option for indent/no-indent for all `<script>` and `<style>` tags in any kind of HTML. I think it should default to indenting. That would keep the current default behavior for .html files, but change it for .vue. That should be fine, though?

Also, I’m closing this PR. I think it’s easier to start from scratch now.

**Pull request closed without merging**
