### PR TITLE
Reduce bundle size of `doc.js`

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Reduce bundle size of `doc.js` by 113.9 kb

Address https://github.com/prettier/prettier/pull/12168#issuecomment-1022946262

**Before:**

```
$ node ./scripts/build/build.mjs --file=doc.js --print-size --report
 Building packages 
doc.js..........................................................178 kB    DONE  
```

**After:**

```
$ node ./scripts/build/build.mjs --file=doc.js --print-size --report
 Building packages 
doc.js.........................................................63.1 kB    DONE  
```

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by fisker — APPROVED** [review]
Great! Thanks!

**Comment by fisker** [comment]
I remember this file was small before, it became bigger when updating rollup or rollup plugin, I guess it was unsafely tree-shaked. Anyway we are not going to bring rollup back, esbuild is much faster.

**Comment by sosukesuzuki** [comment]
I see. In the future, if we migrate our source code to ESM, Tree Shaking will be improved.

**Comment by fisker** [comment]
@sosukesuzuki `parser-html.js` containers `doc.js`, it's used in `language-html/utils.js`, do you think you can fix that?

**Pull request merged**
