### PR TITLE
Enable code coverage in CI

### PR DESCRIPTION
**Pull request by azz**
Ran it locally and found a lot of branches we haven't got jest coverage on. What do you think about adding coverage to CI, @vjeux?

### CODE REVIEW

**Comment by vjeux** [comment]
As long as it doesn't spam every single pull request with a huge comment, i'm fine with it

**Comment by vjeux** [comment]
Yeahhh.... this is using codecov which spams like crazy. I don't think that it's worth it.

**Comment by azz** [comment]
Oh wow, that's a bit much :/

I wonder if we can tune that down a notch...

**Comment by azz** [comment]
Was able to disable the comment, and it didn't seem to have an impact on build-time (which is surprising...)

**Comment by azz** [comment]
Coverage is pretty good though!

94.15% Statements (3137/3332)
93.4% Branches (3369/3607)
95.21% Functions (358/376)
94.14% Lines (3114/3308)

**Comment by azz** [comment]
What is `ModuleDeclaration`? 

image

**Comment by vjeux** [comment]
It has `assert.ok` so it's likely coming from recast and super old. It's likely not used anymore.

**Comment by azz** [comment]
Also found this. Is there some language extension with multiple `catch` blocks?

image

**Comment by vjeux** [comment]
Apparently some JS implementations support it, but I've never seen it in practice: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#Conditional_catch_clauses

**Comment by azz** [comment]
Ah yes, I remember reading about that, it's from Mozilla's JavaScript 1.5. There was lots of funky stuff in there.

**Comment by vjeux** [comment]
Babylon has no results for "handlers" https://github.com/babel/babylon/search?p=1&q=handlers&type=&utf8=%E2%9C%93

**Comment by azz** [comment]
List of nodes never hit:

* Noop
* ParenthesizedExpression
* MetaProperty
* Path
* ModuleDeclaration
* ExportBatchSpecifier
* ExportDeclaration
* PropertyPattern
* ModuleSpecifier
* JSXNamespacedName
* JSXText
* Keyword
* TypeAnnotatedIdentifier
* ClassPropertyDefinition
* DeclareTypeAlias
* NullTypeAnnotation
* TSDecorator
* TSHeritageClause
* TSExpressionWithTypeArguments
* TSAbstractKeyword
* TSAsyncKeyword
* TSProtectedKeyword
* TSPrivateKeyword
* TSPublicKeyword
* TSStaticKeyword

All of the TS ones are from when typescript-eslint-parser forwarded those nodes rather than converting to estree equivalents.

Might be time for a clean up!

**Comment by vjeux** [comment]
`JSXNamespacedName` with the flow parser:

```
<JSX:Namespaced:Name />
```

`JSXText`: we want to keep throwing if it goes there.

We need to be very careful when removing all those and make sure that they can't be written in practice :)

**Comment by vjeux** [comment]
In flow 0.34 ( https://github.com/facebook/flow/blob/0cc64543f1261a3b6a34517af0b8fd9677ffdf87/Changelog.md#v0340 ):

The `NullTypeAnnotation` annotation node is now called `NullLiteralTypeAnnotation` in order to match Babylon.

**Comment by azz** [comment]
Are you happy to merge this in?

We can always revert it if it gets annoying.

**Comment by vjeux** [comment]
I've seen ParenthesizedExpression returned by typescript-eslint-parser.

It's all over the TypeScript codebase
https://github.com/Microsoft/TypeScript/search?utf8=%E2%9C%93&q=ParenthesizedExpression&type=

but their example `const x = (a|b)` doesn't return a ParenthesizedExpression in typescript-eslint-parser.

Best way is to run a tweaked version of prettier on all the big typescript repos we listed and see if it is generated.

**Comment by vjeux** [comment]
Yeah yeah, feel free to merge.

**Comment by vjeux** [comment]
For `DeclareTypeAlias`, babylon outputs it with the following expression:

```js
declare type A = string;
```

**Comment by azz** [comment]
ParenthesizedExpression isn't in https://github.com/eslint/typescript-eslint-parser/blob/master/lib/ast-node-types.js, which means it will be `TSParenthesizedExpression` if it ever makes it to prettier. No mention in flow or babylon repos...

**Comment by vjeux** [comment]
For `ExportBatchSpecifier`, it's renamed in flow 0.34

> Update ExportBatchSpecifier to a ExportNamespaceSpecifier node per the latest ESTree spec.

**Comment by azz** [comment]
`"Keyword"` is a token, not an ast node.

**Comment by vjeux** [comment]
`ClassPropertyDefinition` is not in any of flow, babylon and typescript.

**Comment by azz** [comment]
@JamesHenry Could you confirm that we should never see any of the `TS*` nodes listed in https://github.com/prettier/prettier/pull/2497#issuecomment-315603289 anymore?

**Comment by vjeux** [comment]
@azz: I edited your comment with the latest updates. Lots of cleanup to do indeed :)

**Comment by azz** [comment]
ModuleSpecifier is [abstract](https://github.com/estree/estree/blob/f32646033ed12e6aaa7f5cd496d936a8f8de194e/es2015.md#modulespecifier), used for `(Import|Export)Specifier`

**Comment by azz** [comment]
I couldn't find any references to `Path` in babylon, flow, TypeScript or estree...

**Pull request merged**
