### PR TITLE
Remove parens for type assertions in binary expressions

### LINKED ISSUE #2416: TypeScript excessive parens in binary expression
Input:
```ts
<x>a || {};
```

Output:

```ts
(<x>a) || {};
```

### PR DESCRIPTION
**Pull request by azz**
Fixes #2416

### CODE REVIEW

**Comment by vjeux** [comment]
Since you are looking into parenthesis, could you add ones for a === b === c and a * b % c?

**Comment by azz** [comment]
So print `(a === b) === c` and `(a * b) % c`?

**Comment by vjeux** [comment]
Yes, that's the only two patterns from the big parenthesis issue I could find where it is ambiguous and we should do something about.

**Comment by vjeux** [comment]
https://github.com/prettier/prettier/issues/187

**Pull request merged**
