### PR TITLE
Added a test to verify that #4659 is closed

### PR DESCRIPTION
**Pull request by robert-j-webb**
Initially I wanted to fix the bug described in #4659 but it turns out it's already fixed. So I added a bit of test code to illustrate that and prevent regressions.

- [X] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [X] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

> (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.

If I should do this, I'm more than willing to. I don't know how it works though and I didn't see any reference to it in the Contributing markdown.

### CODE REVIEW

**Comment by fisker** [comment]
Should be  https://github.com/prettier/prettier/pull/6804

**Comment by robert-j-webb** [comment]
@fisker - is the test still a good idea then?

**Comment by fisker** [comment]
Yes

**Pull request merged**
