### PR TITLE
Backport implementation of `satisfies`

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Why not merge #13783 into this one? No wonder I didn't see any `satisfies` tests there.

**Comment by sosukesuzuki** [comment]
> Why not merge https://github.com/prettier/prettier/pull/13783 into this one? No wonder I didn't see any satisfies tests there.

Just for reviewing. #13783 includes changes that are not for satisfies. If the parser changes are not annoying to the reviewer, I can merge this into #13783.

**Comment by fisker** [comment]
They already reviewed. Let's merge them.

**Comment by sosukesuzuki** [comment]
Okay

**Pull request closed without merging**
