### PR TITLE
Exclude `assert` shim

### PR DESCRIPTION
**Pull request by fisker**
## Description

Closes #12145 
Closes #8165

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
@TimvdLippe Can you take a look at this?

**Review by TimvdLippe — APPROVED** [review]
Yes I can confirm that with this PR, the file size becomes 530750, which is a similar improvement compared to #12145, thanks!

**Review by duailibe — APPROVED** [review]

**Comment by duailibe** [comment]
I'm fine with either this or #12145. I do not think one is necessarily a better solution than the other, so feel free to decide on this @fisker 🙂

**Review by sosukesuzuki — APPROVED** [review]
#12145 is great, however it is better to solve this problem at build time. LGTM!

**Pull request merged**
