### PR TITLE
Preserve Whitespace Control For Handlebars

### PR DESCRIPTION
**Pull request by mahirshah**
Previously whitespace strip characters ("~") were omitted after prettier
transformation on handlebars templates becuause the glimmer AST parser
did not expose when whitespace strip characters were used.

Update to the latest glimmer parser which exposes strip flags indicating
when whitespace strip characters are present. Update the glimmer printer
to preserve whitespace strip characters.

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
@mahirshah Try work on `next` branch

**Comment by evilebottnawi** [comment]
Please fix conflicts

**Comment by suchipi** [comment]
Hello; I'm going to remove my review request because I haven't worked on prettier in a long while, and am not familiar with this aspect of handlebars syntax in general.

**Comment by mahirshah** [comment]
@evilebottnawi 	thanks for your patience, fixed the conflicts. Can we merge this PR?

**Pull request merged**
