### PR TITLE
Fix missing parentheses on `async` inside `for..of`

### LINKED ISSUE #10777: Missing parentheses `for ((async) of []);`
This is valid even in [main branch](https://deploy-preview-10775--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAzCAnABAChwQwGcBPKMASiwlSwG0BdcgbhABoQIAHGAS2kOSh8GDBADuABWEIBKfABsx+YgPYAjDPjABrODADKnLTygBzZDAwBXOOzgBbNXAAmzlwBl8Zq-lNwAYpj2+DC8Zsgg+FYwEGwgABYw9vIA6vE88IRGYHD6Mhk8AG4ZxBFghKogJoRwGDASmqbByKgKNewAVoQAHgBCmjp6+vj2cO4mcC1ttiBd3fompvJwAIpWEPBT8u0gRhg1GBFq+E7ycZwYJjApPM4w8cgAHAAM7BcQNSmanBEXcAeFSbsACO63gDS4skihAAtFA4C4XHEMHBQTwUQ1fM0kK1tjMavYeBZrPjFss1htJjjpuwYCcbncHkgAEy0zQ8eSLADCEHs2JA-wArHErDUAConWS4naFGwASSgblg+jAl24AEFFfoYMRllsagBfA1AA), [related babel pr](https://github.com/babel/babel/pull/13208)

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCAnABAChwQwGcBPKMASiwlSwG0BdcgbhABoQIAHGAS2kOSh8GDBADuABWEIBKfABsx+YgPYAjDPjABrODADKnLTygBzZDAwBXOOzgBbNXAAmzlwBl8Zq-lNwAYpj2+DC8Zsgg+FYwEGwgABYw9vIA6vE88IRGYHD6Mhk8AG4ZxBFghKogJoRwGDASmqbByKgKNewAVoQAHgBCmjp6+vj2cO4mcC1ttiBd3fompvJwAIpWEPBT8u0gRhg1GBFq+E7ycZwYJjApPM4w8cgAHAAM7BcQNSmanBEXcAeFSbsACO63gDS4skihAAtFA4C4XHEMHBQTwUQ1fM0kK1tjMavYeBZrPjFss1htJjjpuwYCcbncHkgAEy0zQ8eSLADCEHs2JA-wArHErDUAConWS4naFGwASSgblg+jAl24AEFFfoYMRllsagBfA1AA)

```sh
--parser babel
```

**Input:**

```jsx
for ((async) of []);
```

**Output:**

```jsx
for (async of []);

```

**Second Output:**

```jsx
SyntaxError: Unexpected token, expected "=>" (1:15)
> 1 | for (async of []);
    |               ^
  2 | 
```

**Expected behavior:**

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #10777

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by thorn0 — APPROVED** [review]
Strictly speaking, the parens aren't needed in `for await (async of []);`, but Babel can't parse it without them.

**Review by sosukesuzuki — APPROVED** [review]

**Comment by sosukesuzuki** [comment]
@thorn0 Is it reported to babel/babel or fixed?

**Comment by thorn0** [comment]
@sosukesuzuki I only left a comment in https://github.com/babel/babel/pull/13208, but I didn't report this issue properly. There are also issues with `let` (https://github.com/prettier/prettier/issues/10777#issuecomment-829191658). And there might be more. A good read through the spec is needed.

**Comment by sosukesuzuki** [comment]
@thorn0 Thank you. I'll investigate specs and report to babel/babel and fix, okay?

**Comment by thorn0** [comment]
Sounds good 👍 Probably these changes in the spec are recent.

**Comment by thorn0** [comment]
BTW, here is valid TypeScript that compiles to invalid JS by both the TypeScript compiler and Babel (probably fixed by https://github.com/babel/babel/pull/13208): `for ((async as any) of []);`

**Pull request merged**
