### PR TITLE
Skip folders in CLI pattern

### LINKED ISSUE #3409: Prettier couldn't go through the directories recursively [error] EISDIR: illegal operation on a directory, read
Hi guys. 
I assume that it's not probably connected to the prettier. But I gave up already to fix that somehow, cause it's the only node based tool which doesn't work with GLOB pattern for now.

Mac OS High Sierra
Latest node and npm.
prettier: 1.9.0

```
prettier --write {scripts,config,bin}/**/*
```
throws lot's of errors in my face like:
```
bin/react-scripts.js 58ms
config/custom-react-scripts
[error] Unable to read file: config/custom-react-scripts
[error] EISDIR: illegal operation on a directory, read
config/env.js 26ms
config/jest
[error] Unable to read file: config/jest
[error] EISDIR: illegal operation on a directory, read
config/paths.js 31ms
config/polyfills.js 6ms
config/webpack.config.dev.js 34ms
config/webpack.config.prod.js 44ms
config/webpackDevServer.config.js 9ms
scripts/build.js 17ms
scripts/eject.js 33ms
scripts/init.js 26ms
scripts/start.js 8ms
scripts/test.js 6ms
scripts/utils
[error] Unable to read file: scripts/utils
[error] EISDIR: illegal operation on a directory, read
template/README.md 819ms
```

In the same, this script returns all required files in the deeply nested paths with no arguing.
```javascript
require('glob')('{scripts,config,bin}/**/*', (e, f) => console.log(f));
```

I have prettier of the same version (1.9.0) both installed globally as well as the prettier in the package.json.

I tried to call it with `sudo` and tried to reinstall it etc. not much of a result.
Running it through the npm scripts or directly result in the same output.

Node and npm are the latest and were installed using brew. I'm under administrator profile.

### PR DESCRIPTION
**Pull request by duailibe**
`globby` was returning the directories instead of only files when using a pattern like `folder/**/*` (I believe this is the only one that would raise this issue). Passing `nodir: true` to globby solves the issues + added a regression test.

Fixes #3409

### CODE REVIEW

**Comment by lydell** [comment]
Has this bug always been around? Or has it regressed lately? Do you why? Will `prettier folder/**/*` and `prettier "folder/**/*"` work differently?

**Comment by duailibe** [comment]
I believe it has been around for a long time (at least since 1.7.0), but I can't say for sure. Perhaps running prettier without a `*.[extension]` wasn't very common?

`prettier folder` will output "No matching files" (and so `prettier folder/**/*` will simply skip `folder`). Do you want tests for this?

**Comment by lydell** [comment]
Thanks, that makes sense. 👍 

> Do you want tests for this?

No, then our tests will depend on the shell used. If with and without quotes are equivalent in a sane shell then we're all good.

**Comment by duailibe** [comment]
Yeah we can't add a test for that, but we can write a test for passing the `folder/` explicitly i.e.  `prettier folder/ folder/sub1/a.js folder/sub2/a.js`

**Comment by duailibe** [comment]
I went ahead and added the test :-)

**Comment by duailibe** [comment]
I agree, it's just the current behavior is kind of weird right now.

**Pull request merged**
