### PR TITLE
Use Node.js 12 on netlify build

### PR DESCRIPTION
**Pull request by fisker**
Should faster.

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Previous build

[1](https://app.netlify.com/sites/prettier/deploys/5eb3c60b5f33040007b0f09e)  7m 44s
[2](https://app.netlify.com/sites/prettier/deploys/5eb3c5da3342140006493af8) 7m 3s

---

[1st build](https://app.netlify.com/sites/prettier/deploys/5eb3e410c898370006e6f5a5) 6m 29s
[2nd build](https://app.netlify.com/sites/prettier/deploys/5eb3e5ec76b3030006f3d9a4) ?

**Comment by fisker** [comment]
Can't make the cache work, maybe need do something in netlify web UI.

**Comment by thorn0** [comment]
If you need access there, ask @azz. He's going to need your email.

**Comment by fisker** [comment]
@azz My email lionkay@gmail.com

**Comment by azz** [comment]
> @azz My email lionkay@gmail.com

Sent.

**Comment by fisker** [comment]
Cache isn’t available on PR... https://github.com/netlify/build/issues/1225

**Comment by fisker** [comment]
We [already use Node.js 12 for netlify build](https://github.com/prettier/prettier/blob/e0b766e7f9e9e96078873a481ef4e3ca2ea486d0/netlify.toml#L2), and I can't make the cache work for PRs. Closing.

**Pull request closed without merging**
