### PR TITLE
Switch `parse-srcset` to npm published version

### PR DESCRIPTION
**Pull request by fisker**
## Description

Ref https://github.com/prettier/prettier/pull/13519#issuecomment-1257251731

I published `@fisker/parse-srcset` 2 years ago, when I try to use yarn2 in this repo #9569.

@alexander-akait I heard you've rewritten this module? Have you published it?

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
There is also this issue about that package: https://github.com/prettier/prettier/issues/12560
Apparently, the UMD wrapper causes trouble. Could you remove it?

**Comment by fisker** [comment]
I just forked ikatyang's, if we are going to make changes, I'd like to transform to prettier repo, so you can also make changes. Let me publish under `@prettier` too?

**Comment by thorn0** [comment]
:+1: I wanted to propose the same.

**Comment by fisker** [comment]
BTW: It seems ikatyang is not active on github. I think we should try contact him and ask him to transfer repos like `yaml-unist-parser` https://github.com/ikatyang/yaml-unist-parser/issues/279, `angular-estree-parser` https://github.com/ikatyang/angular-estree-parser/issues/221

**Comment by fisker** [comment]
Do you know what's wrong https://github.com/prettier/prettier/actions/runs/3128719547/jobs/5076912809#step:6:5?

**Comment by thorn0** [comment]
Looks like TS doesn't understand `exports` in `package.json` and doesn't know how to resolve this module. I'll look into this.

**Comment by sosukesuzuki** [comment]
@fisker This is maybe because TypeScript compiler treat `exports` filed in `package.json` correctly. For now, we can avoid the compile error by creating an empty type definition file by executing the following command:

```sh
mkdir ./types/parse-srcset && echo "declare module \"@prettier/parse-srcset\";" > ./types/parse-srcset/index.d.ts
```

I will fix it properly later.

**Comment by thorn0** [comment]
We need to change `tsconfig.json`:

```json
{
    "[compilerOptions](https://www.typescriptlang.org/tsconfig#compilerOptions)": {
        "[module](https://www.typescriptlang.org/tsconfig#module)": "nodenext",
    }
}
```

https://www.typescriptlang.org/docs/handbook/esm-node.html

**Comment by sosukesuzuki** [comment]
> We need to change tsconfig.json:

I've tried to set `"module": "nodenext",`, but errors:

```
yarn lint:typecheck
src/common/load-plugins.js:10:46 - error TS1470: The 'import.meta' meta-property is not allowed in files which will build into CommonJS output.

10 const __dirname = path.dirname(fileURLToPath(import.meta.url));
                                                ~~~~~~~~~~~

src/language-html/syntax-attribute.js:1:25 - error TS2307: Cannot find module '@prettier/parse-srcset' or its corresponding type declarations.

1 import parseSrcset from "@prettier/parse-srcset";
                          ~~~~~~~~~~~~~~~~~~~~~~~~

src/language-js/parse/acorn.js:7:31 - error TS1470: The 'import.meta' meta-property is not allowed in files which will build into CommonJS output.

7 const require = createRequire(import.meta.url);
                                ~~~~~~~~~~~

src/language-js/parse/espree.js:7:31 - error TS1470: The 'import.meta' meta-property is not allowed in files which will build into CommonJS output.

7 const require = createRequire(import.meta.url);
                                ~~~~~~~~~~~

src/main/version.evaluate.js:3:31 - error TS1470: The 'import.meta' meta-property is not allowed in files which will build into CommonJS output.

3 const require = createRequire(import.meta.url);
                                ~~~~~~~~~~~


Found 5 errors in 5 files.

Errors  Files
     1  src/common/load-plugins.js:10
     1  src/language-html/syntax-attribute.js:1
     1  src/language-js/parse/acorn.js:7
     1  src/language-js/parse/espree.js:7
     1  src/main/version.evaluate.js:3
```

**Comment by fisker** [comment]
👍

**Review by sosukesuzuki — APPROVED** [review]

**Comment by alexander-akait** [comment]
Sorry for delay, yeah, rewritten by spec, but it is not published, here is code https://github.com/webpack-contrib/html-loader/blob/master/src/utils.js#L20

If someone publishes it I will be glad and help with fixes and bugs (but I don't think we have it, WPT tests passed + a lot of examples)

**Comment by fisker** [comment]
The original `parse-srcset` seems tested, I'm fixing https://github.com/prettier/parse-srcset/pull/2.

**Pull request merged**
