### PR TITLE
Allow more arrow function print on same line with arrow

### PR DESCRIPTION
**Pull request by fisker**
- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@fisker please focus on issues for `2.0` version, I am very glad that you are helping us and you really contributed a lot problems, but we should hurry in the new release, so let's focus not on issues for v2.0 and bugs. I can’t say what to do, but I would like to ask about it, not all of us have a lot of free time, so if we manage this time wisely we can achieve better results, thanks

**Comment by fisker** [comment]
#5733

This is considered bug

**Comment by evilebottnawi** [comment]
Not high priority unlike the `2.0` version, fixes and improvements do not make sense if we do not release our product on time, developers will not be seen and felt anyway, do you understand that? Almost no one uses the master branch

**Comment by fisker** [comment]
I don't know what are you talking about, I was trying to fix a bug, you are telling me not to do.

I do open source on my interest, stop telling me what to do, what not to do.

Is this blocking the 2.0 release? I did't ask you to wait for this fix.

Is there anything need to do on 2.0? I can't see what I can do on https://github.com/prettier/prettier/milestone/34

At last, this is a draft PR, which means not ready for review!

**Comment by evilebottnawi** [comment]
> I do open source on my interest, stop telling me what to do, what not to do.

**Comment by evilebottnawi** [comment]
> I don't know what are you talking about, I was trying to fix a bug, you are telling me not to do.

What do I want to say?

I want to say that bug fixes and improvements make no sense until we release the 2.0 version and these problems should be prioritized for us.

> I do open source on my interest, stop telling me what to do, what not to do.

Are you seriously ? 

My answer:

I can’t say what to do, but I would like to ask about it, not all of us have a lot of free time, so if we manage this time wisely we can achieve better results, thanks

- Still **WIP** https://github.com/prettier/prettier/pull/6776 by you 
- Still **WIP** https://github.com/prettier/prettier/pull/6794 by you with a lot of reviews and advises


I just asked you no more, did not expect such rudeness to a simple request. I just wanted to say that if we work more coherently we can achieve better results. Thanks for the mood

**Comment by fisker** [comment]
#6776 , I've done all what I can do, mean time, I sit and wait?

#6794 , You said you want take over https://github.com/prettier/prettier/pull/6794#issuecomment-557161730 

> I want to continue development based on your code

and I said that again when reopen that PR https://github.com/prettier/prettier/pull/6794#issuecomment-579783978

> I restored this branch. You can reopen this.
> Maybe you can continue work on it.

**Comment by evilebottnawi** [comment]
For example we can focus on https://github.com/prettier/prettier/issues/6854 and https://github.com/prettier/prettier/pull/6128, it should be not easy and not hard, I ask you to focus on them and not be rude to me, thank you

**Comment by fisker** [comment]
I'm rude to you?  I don't know what to say.

If you want me work on #6854 and #6128 , you can just ask.

Maybe like now, you ask me work on them, I can nicely answer

for #6854 , you said [you are WIP](https://github.com/prettier/prettier/issues/6854#issuecomment-579729721), and we discussed the other day, you want wait for #6776 , and #6776  is blocking by new version of `fast-glob`, so there is nothing I can do.

And #6128 , is that assigned to @sosukesuzuki , as I can see https://github.com/prettier/prettier/pull/6128#issuecomment-581848632 .

One more thing, I didn't mean to "rude", but what is the status of [this](https://github.com/prettier/prettier/pull/6713#issuecomment-551007968) ?

**Comment by evilebottnawi** [comment]
> One more thing, I don't want to be "rude", but what is the status of this ?

Let's focus on work and stop to be rude to each other, I ask you help to us with https://github.com/prettier/prettier/issues/6854 and https://github.com/prettier/prettier/pull/6128

We discuss what https://github.com/prettier/prettier/pull/6776 is not blocker for https://github.com/prettier/prettier/issues/6854 (look discussion). I will want to reduce diff and thought that we could solve the problem with updating faster, but everything turned out to be a little different.

/cc @sosukesuzuki Can @fisker be champion of https://github.com/prettier/prettier/pull/6128?

**Comment by fisker** [comment]
@evilebottnawi I'm not really want work on #6128 now. Because I think we may want more details on https://github.com/prettier/prettier/pull/6639#issuecomment-548949954

**Comment by evilebottnawi** [comment]
@fisker What is questions, yes our behavior should be same like in `eslint`, we don't need extensions, because we known which extension we supported

**Comment by fisker** [comment]
I'll see #6854 first

**Comment by sosukesuzuki** [comment]
@evilebottnawi @fisker Sorry for delay. 
> Can @fisker be champion of #6128?

Yes. Sorry, now  I have no time to enough to work on #6128.
***
@fisker I am always grateful for your contributions.

**Comment by fisker** [comment]
I'll open another PR, since too many off-topic comments here.

**Pull request closed without merging**
