### PR TITLE
Whitelist recovered babel parse errors

### PR DESCRIPTION
**Pull request by fisker**
## Description

Some listed errors still should throw, but we can fix them later.
I believe this may also break some valid case, for example legacy things in non-strict mode, maybe we can try parse as non-strict if find it's necessary.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
@sosukesuzuki We discussed this in #9979. The idea is to allow only specific errors and rethrow anything else. I didn't expect the list to be so long, but it seems to make sense.

> it is annoying to have to update this every time a new error message is added to Babel

It's vice versa. Now we have to monitor when Babel adds new recoverable errors and either add support for them or rethrow them, i.e. update the current blocklist. After this change, the new list will be updated only when we deliberately decide to support some specific case of error recovery.

**Comment by fisker** [comment]
I will also try clean this list later, I want keep this PR small.

**Comment by sosukesuzuki** [comment]
I got it! It makes sense.

Btw, I don't like Babel error messages are hard coded. It may be good to introduce error code for recoverable errors at Babel side. What do you think?

**Comment by fisker** [comment]
Yes, that would be great, but I guess it's not doable... because some messages are from babel plugin.

**Comment by sosukesuzuki** [comment]
The Babel parser plugin isn't external code, so it may be possible. I'll look into it.

**Review by thorn0 — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]

**Pull request merged**
