### PR TITLE
Fixes #5446 Do not convert type parameter to comment type

### LINKED ISSUE #5446: Comment types of Flow makes Prettier confused
**Prettier 1.15.1**

Sorry, I could not reproduce it on v1.15.2 playground. :bow: (solved at 1.15.2 ? :eyes:)
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACACgJwgwGdsBebYAHwB0ptsA6ZgEgFEAPAQzBgB4CRYgHUAljAAWAFQBiUAHwAaOg2aN23XnxYBhLgBt9fdFggAzbAFsuGAMowu8KREElF2AFTuP8pSqasnDz8ugZGJnDmVjYAIqLEGI5gEt7evsr0AepBWgDu4hIASnAJ0MRwjGKSAIoArnD4aK7EfIUQEDB1DWjpdFQAvgDcIIogRDCiZcigXPiEubizCMTIIFwAbhCiACYjIABG+DwA1nAwtolgolAA5sgw+PWjEjCW+sIS4iWXcLbL4qJ1uI0KswMQVqNruV8DACFwbtZkGYDOVRgArYgcABCRzAp3OXEscAAMtc4PdHnB0ZjbNcbvo4HUOuSkMj9KiQIl8NDVmZ9BBcnsMPhrjAxNtJMgABwABlGwog5WERwwq2FJQa63Jo3wcAAjrVRLq4QiuEiUVSQOVLKIKU8rXSGUz4Ob2ZaHPtxZKkAAmUYPLiifR0nQQSyIlBhPa1cpSLj7Fasi39fpAA)

In flow, I can typecast with the following, not type-assertion.

**Input:**
```js
type Props = {|
  ...$Exact<PropsWithTFn>,
  ...$Exact<$Call<typeof mapStateToProps, *, *>>,
  ...$Exact<$Call<typeof mapDispatch, *, *>>,
  ...$Exact<withResponse.WithQueryProps<RootQuery>>,
|};
```

However, this gets error message below in prettier 1.15.1

```sh
Replace `<$Call<typeof·mapDispatch,·*,·*>>` with `/*::·<$Call/*::·<typeof·mapDispatch,·*,·*>·*/>·*/`
```

**Output:**
```js
type Props = {|
  ...$Exact<PropsWithTFn>,
  ...$Exact/*:: <$Call/*:: <typeof·mapStateToProps, *, *>*/> */
  ...$Exact/*:: <$Call/*:: <typeof mapDispatch, *, *>*/> */,
  ...$Exact/*:: <withResponse.WithQueryProps<RootQuery>*/> */,
|};
```

**Expected behavior:**
```js
type Props = {|
  ...$Exact<PropsWithTFn>,
  ...$Exact<$Call<typeof mapStateToProps, *, *>>,
  ...$Exact<$Call<typeof mapDispatch, *, *>>,
  ...$Exact<withResponse.WithQueryProps<RootQuery>>,
|};
```

### PR DESCRIPTION
**Pull request by kogai**
Fixes #5446

When once comment type of Flow occurred at the code, unintentional converting from type parameter like `A<B>` to `A/*:: <B> */` applied.

As commented at [here](https://github.com/prettier/prettier/blob/b38319740af7721873ada5e3b97b0eb34e759b4a/src/language-js/printer-estree.js#L3011), due to lack of information whether the current node declared internal comment type or not, differences this PR proposed to do not fully ideal.

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by kogai** [comment]
Could somebody review or should I close it includes non-ideal solution ❓

**Comment by fisker** [comment]
Did I break it?

**Comment by evilebottnawi** [comment]
@fisker Go ahead

**Comment by thorn0** [comment]
superseded by https://github.com/prettier/prettier/pull/13687

**Pull request closed without merging**
