### PR TITLE
Support `.wxs` &  `.wxss`

### PR DESCRIPTION
**Pull request by fisker**
`miniprogram` is a popular tool in China, by Tencent(one of the biggest IT company in China).

- WXSS 

  It's basic just CSS, except it support a extra `rpx` CSS unit.
  Docs https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxss.html (in Chinese)
  Files on GitHub https://github.com/search?o=desc&p=7&q=extension%3Awxss+color&s=indexed&type=Code

- WXS

  It's just JS
  Docs https://developers.weixin.qq.com/miniprogram/dev/framework/view/wxs/ (in Chinese)
  Files on GitHub https://github.com/search?o=desc&p=7&q=extension%3Awxs+if&s=indexed&type=Code

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]
Just interesting - why it uses other extensions?

**Review by sosukesuzuki — APPROVED** [review]

**Comment by fisker** [comment]
> 在 iOS 设备上小程序内的 WXS 会比 JavaScript 代码快 2 ~ 20 倍

Quote from the website, On ios, wxs is 2~20 faster than javascript.

I don't know if that true. It's like a PWA, but only run in 微信（im software）

**Comment by fisker** [comment]
It has own .wxml(Like html, like vue) but it's not... I didn't add it.

**Comment by fisker** [comment]
@Sichen-Wang You are most recently one mention about miniprogram here, do you think is's safe to format `.wxs` and `.xsss` with babel and css parser?

You might not using them directly, but hope you can help.

**Comment by brodybits** [comment]
They seem to have the documentation in English as well:

- https://developers.weixin.qq.com/miniprogram/en/dev/framework/view/wxss.html
- https://developers.weixin.qq.com/miniprogram/en/dev/framework/view/wxs/

Will this information be linked in the Prettier documentation?

**Comment by fisker** [comment]
No, I don't think that's necessary.

**Comment by fisker** [comment]
... Why thumb down? We don't have link to `mongo`, `ansible`, `home-assistant` ...

**Comment by brodybits** [comment]
Hi this is the first I have ever heard of these extensions, and of the Mini Programs in general, and I did not find anything when I did a search on wxs or miniprogram. I ended up using Google Translate until I found the EN link.

This does look like a really nice concept, similar to the Java applets and WAP applications from the late 90s.

It would be ideal to have open standards somewhere, that people could comment on and contribute to. But if this is not possible, then I think a link to the documentation on the QQ website could help some others understand the meaning and motivation. Thanks:)

**Comment by fisker** [comment]
You know what, Tencent `miniprogram` is the most popular one, all(YES, ALL) leading Chinese IT companies have there own `miniprogram`, Alibaba Baidu etc

**Comment by fisker** [comment]
@brodybits Added links in source https://github.com/prettier/prettier/pull/9081/commits/ffb350b7df8710772ecca557f2f8590fadf36270

**Comment by DouglasdeMoura** [comment]
@fisker that was exactly the thing I was looking for (currently I'm developing a miniprogram for a big Brazilian company). Thanks for this PR.

**Comment by Sichen-Wang** [comment]
> @Sichen-Wang You are the one most recently mention about miniprogram here, do you think is's safe to format `.wxs` and `.wxss` with babel and css parser?
> 
> You might not using them directly, but hope you can help.

Sorry, I don't know.

**Comment by fisker** [comment]
@Sichen-Wang Thanks anyway.

**Comment by oebrab** [comment]
Do you think it's better to create a plugin for all mini programs' formatting things, cause there're too many extensions, such as:

- Markup: `.wxml`, `.axml`, `.ttml`, `.swan`, `.jxml` and so on;
- Style: `.wxss`,  `.acss`, `.ttss`, `.jxss`  and so on;
- Script: `.wxs`, `.sjs`, `.jds` and so on.

**Comment by fisker** [comment]
I don't think it's necessary, people can config parser by themself.
But I'm wondering if [linguist-languages](https://github.com/ikatyang/linguist-languages) want add these extensions, we use it directly.

**Comment by oebrab** [comment]
Yes.
But do you think we need a plugin for formatting these markup files, cause they are a new language.

**Comment by fisker** [comment]
Yes, some of them are, you can do it if you want.

**Pull request merged**
