### PR TITLE
Update cli.md to explain how to fix all files

### PR DESCRIPTION
**Pull request by octogonz**
See this discussion: https://github.com/prettier/prettier/issues/6280

### CODE REVIEW

**Comment by evilebottnawi** [comment]
This solution works for dir files like ".myconfig.js"?

**Comment by kachkaev** [comment]
IMHO suggesting people to use `**` without explaining what should go into `.prettierignore` nearby will cause some confusion and result lots of extra issues in this repo. It took me a while to establish a [sustainable structure for `.prettierignore`](https://github.com/prettier/prettier/issues/6280#issuecomment-509568953) – this task was not trivial. All this glob stuff (`**/*` vs `*.*` vs `*` vs `!*.blah`) is pretty hard-core.

**Comment by octogonz** [comment]
> Also it is necessary to ensure that prettier --write "**" behaves in cmd.exe or PowerShell equally well before advising to use this trick.

The `**` is a itignore expression that I believe is processed by the [ignore](https://www.npmjs.com/package/ignore) library, not by the OS shell.  (The quotes disable shell expansion.)  Thus it should be the same on every platform.

**Comment by kachkaev** [comment]
I believe so too, I'm just saying that it would be cool to manually verify this 🙂

**Comment by octogonz** [comment]
> IMHO suggesting people to use `**` without explaining what should go into `.prettierignore` nearby will cause some confusion and result lots of extra issues in this repo.

@kachkaev I'm going to reopen https://github.com/prettier/prettier/pull/6280, since it sounds like we haven't fully answered the question of **"How do I use the CLI to fix all files?"**  We can resume the discussion there.

**Comment by thorn0** [comment]
Superseded by #7660

**Pull request closed without merging**
