### PR TITLE
chore(deps): upgrade patch-level dependencies

### PR DESCRIPTION
**Pull request by ikatyang**
Context: https://github.com/prettier/prettier/issues/3117#issue-269386287

```
included

cjk-regex                        1.0.1  →          1.0.2
flow-parser                     0.51.0  →         0.51.1
graphql                         0.10.1  →         0.10.5
ignore                           3.3.5  →          3.3.7
jest-docblock            21.3.0-beta.1  →  21.3.0-beta.7
parse5                           3.0.2  →          3.0.3
postcss-scss                     1.0.0  →          1.0.2
cross-env                        5.0.1  →          5.0.5
rimraf                           2.6.1  →          2.6.2
rollup                          0.41.1  →         0.41.6
rollup-plugin-commonjs           7.0.0  →          7.0.2
rollup-plugin-json               2.1.0  →          2.1.1
uglify-es                       3.0.15  →         3.0.28

not included

babel-code-frame        7.0.0-alpha.12  →   7.0.0-beta.3
babylon                  7.0.0-beta.28  →  7.0.0-beta.31
prettier                         1.7.3  →          1.7.4
```

### CODE REVIEW

**Comment by lipis** [comment]
What about updating the rest?

```
$ ncu --semverLevel minor
Using /Users/lipis/work/temp/prettier/package.json
⸨░░░░░░░░░░░░░░░░░░⸩ ⠸ :
 babel-code-frame        7.0.0-alpha.12  →   7.0.0-beta.3
 babylon                  7.0.0-beta.28  →  7.0.0-beta.31
 cjk-regex                        1.0.1  →          1.0.2
 flow-parser                     0.51.0  →         0.51.1
 graphql                         0.10.1  →         0.10.5
 ignore                           3.3.5  →          3.3.7
 jest-docblock            21.3.0-beta.1  →  21.3.0-beta.7
 parse5                           3.0.2  →          3.0.3
 postcss-scss                     1.0.0  →          1.0.2
 cross-env                        5.0.1  →          5.0.5
 prettier                         1.7.3  →          1.7.4
 rimraf                           2.6.1  →          2.6.2
 rollup                          0.41.1  →         0.41.6
 rollup-plugin-commonjs           7.0.0  →          7.0.2
 rollup-plugin-json               2.1.0  →          2.1.1
 uglify-es                       3.0.15  →         3.0.28
```

Using https://github.com/tjunnone/npm-check-updates

**Comment by ikatyang** [comment]
Prerelease-level update may introduce breaking changes, but patch-level should be fine.

**Comment by ikatyang** [comment]
Hmm, it seems the `postcss-scss` patch introduced [a little style change](https://github.com/prettier/prettier/pull/3153/commits/c1d0ec2073f1bd78c7f291cbeb3658085415b489).

The change looks good to me, @lydell can you confirm?

**Comment by azz** [comment]
Codecov is acting very strangely...

**Comment by lydell** [comment]
> Hmm, it seems the postcss-scss patch introduced a little style change.

Yay, they’ve fixed the case insensitive `!important` parsing!

**Pull request merged**
