### PR TITLE
Improve separator between interfaces detection

### PR DESCRIPTION
**Pull request by fisker**
- [stable playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAKpuARmwEsBbDAGzjIRgGdsBBAGmwCEAdKAYm2GwAybNgA8AWnHYASjQgA3HDAAWJRpDK1Y2MMoCGUAOZxG9OBj0AnPTAiXSUbPRh6ARtW7A9SbHoC+3HwAyuZWNnbYANZw5r6MJDCk8Y4qajp6ZtzoWHgEAEykFNRaDMxs7ELYAMJePv4gLCAQGDAk0PTIoFaWEADuAApWCB0oevIQJAAmDSCu1mDRMEEWYCRGyDCWAK5wjcowZJQA6qrw9CtwIVD0CSTyCWjI4PQdjWtmljD91oZkesgAMz0lDMjQAVvQAB7seaLIJ6WgAGTWcEBwNBIAhkKCa0M1AAilsIPA0SDdiALJYPk9DNYMMoAI6UGYYSxrGBHKYqZAADgADI1WRAzEc6U9WSY4JZFDMGUT4N9miMQBlxFAYpM4NNGpY4HKSLrvnpfv8kECyY0zGQSBttuSbkYCfLUWb0eSXK5OZNuUg8o1NnoSJRcVUIJpTSAoNBUY0tmZcG4RuaMfIdgBJKCa2BBMBslpMTNBdDUUlmPx+IA)

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
@thorn0 I make a test case

```graphql
# SOME COMMENT BEFORE, this effects string slice
type AA implements C, D
# { &
# Should separat by \`,\` not \`&\`
```

So this part https://github.com/prettier/prettier/blob/master/src/language-graphql/printer-graphql.js#L291-L294

will substr string to `` type AA implements C, D\n# { &\n# Should separat by `,` not `&` ``

then pass to `determineInterfaceSeparator` function https://github.com/prettier/prettier/blob/617d3d6b1e1504b8c44262e2ebab28f0d367a4b2/src/language-graphql/printer-graphql.js#L672

this line substr will be `implements C, D\n# { &\n# Sh` then check `&`, but `&` in a comment.

I'm not familiar with `graphql`, but this definitely not right.

**Comment by fisker** [comment]
Even use `.slice()` seems still not right,

```graphql
type AA implements C, D
# { &     <-------------------------------------will targeting the wrong `{`
# Should separat by \`,\` not \`&\`
{
...
}
```

Maybe should be `C, D` range, but also maybe comment between them


```graphql
type AA implements C, # &&&&&&&&&&&&&&& <- actually the Separator is `,`
D
&
{
...
}
```

**Comment by thorn0** [comment]
Sure, it's a bug. Include these tests in #7251.

**Comment by fisker** [comment]
I was thinking maybe we can improve detection.

**Comment by fisker** [comment]
@thorn0 I make a improvement, please review.

**Comment by fisker** [comment]
Can we merge this?

**Pull request merged**
