### PR TITLE
Add split jsx text option

### PR DESCRIPTION
**Pull request by yuliaHope**
After changes in v1.14.0 some formatting looks very strange. For example
```js
<div>
  Sales tax estimated using a rate of {salesTax * 100}
  %.
</div>
```
And it would be nice to have an option to manage how it will look.

For example the current version of Prettier process  this code:
```js
x = (
  <div>
    Text<br />
    More text<br />
    And more<br />
  </div>
);

x =
  <div>
    before{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}{stuff}{stuff}after{stuff}after
  </div>

x = <div>
        {title}&nbsp; text here{title}
        <div>Sales tax estimated using a rate of {salesTax * 100}%.</div>
    </div>
```
to [(playground)](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAlgJwM4wAQC8eAFADpR54A8AJugG4B85llAKnAB4xUBGmeAPTMKrALIRMcPPG58BwlqwCCUGngC2kuPKEjKVQXSbkAlAG5y5ToSW0G+1rziptwXAFdUqAL4BDVHhMdxgvXwCgkLD-QLhgz28YyITw2PjQxKjMlKS4rNSguyMHKygbInsTUVZWYBh0GAAbOB8AMihebAAHcxkufAALOLg6huafJRqDY0YAZT9m7Bk-GzhcdA0-eHUPbHQoAHM8PzxMLekIVDx3BbW2FbwAKjwARgAGN58AUgA6QxnJtRikwQAAaEAQLr1aDYZCgPyYTAQADuAAUEQhYSg-PQIOgaGCQPw-GAANZwGCzLok-YHZAwTAeODg-bYOIwVFnA6bZCoBZs8EAK2wnAAQmcyRT5ho4AAZfZwXn85kgak4OLIIl+XgAT0a0EJXUw+xgAHV8TABsgABxvcFGiBs01nLqao1rOL0RXgqQARw8WDgnL83L8SsaApAbI06HpjJVe0OzQAih4IPBw5GYNrzTRLcgAEzghl+dCNWkAYQgGh5KCg0G9IF2cHunUzLR8QA)

```js
x = (
  <div>
    Text
    <br />
    More text
    <br />
    And more
    <br />
  </div>
);

x = (
  <div>
    before
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    {stuff}
    {stuff}
    after
    {stuff}
    after
  </div>
);

x = (
  <div>
    {title}
    &nbsp; text here
    {title}
    <div>
      Sales tax estimated using a rate of {salesTax * 100}
      %.
    </div>
  </div>
);
```

With this pr and option `splitJsxText: false` it will look like: 
```js
x =
  <div>
    Text<br />
    More text<br />
    And more<br />
  </div>

x =
  <div>
    before{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}
    {stuff}
    {stuff}after{stuff}after
  </div>

x = <div>
        {title}&nbsp; text here{title}
        <div>Sales tax estimated using a rate of {salesTax * 100}%.</div>
    </div>
```

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by yuliaHope** [comment]
@j-f1 I found several ways to fix this: 

1.  insert only `softline` in this method `separatorNoWhitespace`
2. add more complex check in this method `separatorNoWhitespace` for inserting `softline`.

In first case we avoid formatting from my example, we skip the following cases:
```js
x = (
  <div>
    Text
    <br />
    More text
    <br />
    And more
    <br />
  </div>
);

x = (
  <div>
    before
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    {stuff}
    {stuff}
    after
    {stuff}
    after
  </div>
);
```
and get 
```js
x =
  <div>
    Text<br />
    More text<br />
    And more<br />
  </div>

x =
  <div>
    before{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}
    {stuff}
    {stuff}after{stuff}after
  </div>
```

**Comment by j-f1** [comment]
> On the one hand It's logical to get this
> ```jsx
> <div>
>   {stuff}after{stuff}
> </div>
> ```
> at the end,but on the other hand to get this result
> ```jsx
> <div>
>   {stuff}
>   after
>   {stuff}
> </div>;
> ```
> logical too. That's why I offer to add option for this case.

This should be printed in the first style if it fits within `printWidth`, and in the second style if it doesn’t.

I feel like we should avoid adding an option in this case because you’re the first person (whom I remember) that’s raised this kind of issue, meaning that there’s not such a huge demand to change this that we need to add an option.

**Comment by yuliaHope** [comment]
@j-f1 Ok, should I create PR with fix or you'll fix it?

**Comment by j-f1** [comment]
Let’s start with an issue and see what the team wants to do before we decide exactly what to do in a PR.

**Pull request closed without merging**
