### PR TITLE
feat(playground): add options

### LINKED ISSUE #2968: Support `--require-pragma` option on playground
From @bguiz https://github.com/prettier/prettier/issues/2962#issuecomment-333706665:

> Note that the "playground link" above does not demonstrate the issue, as it does not support the --require-pragma option... perhaps it should?

### LINKED ISSUE #3218: Support `--no-prose-wrap` option on playground

### PR DESCRIPTION
**Pull request by ikatyang**
- add `--no-prose-wrap`
- add `--insert-pragma`
- add `--require-pragma`
- ~~reorder options~~
---
+ before
  image
+ after
  image
  <details><summary><del>reordered version</del></summary></details>

---
Closes #2968 
Closes #3218

### CODE REVIEW

**Comment by azz** [comment]
Prose wrap won't work until the `website/static/lib` is rebuilt though, right?

**Comment by ikatyang** [comment]
Yeah, this PR should be merged after 1.8.2 release.

**Comment by SimenB** [comment]
Speaking of 1.8.2, anything blocking? it :D The milestone has just closed issues https://github.com/prettier/prettier/milestone/6

**Comment by azz** [comment]
Yeah I'm building it right now :P

**Comment by azz** [comment]
@SimenB when running tests locally I got 

First run:

```
 FAIL  tests/flow/annot/any/jsfmt.spec.js
  ● Test suite failed to run

    ENFILE: file table overflow, open '/Users/azz/code/prettier/tests/flow/annot/any/B.js'

      at Object.fs.openSync (fs.js:648:18)
      at Object.fs.readFileSync (fs.js:553:33)
      at read (tests_config/run_spec.js:129:13)
      at fs.readdirSync.forEach.filename (tests_config/run_spec.js:26:22)
          at Array.forEach (<anonymous>)
      at run_spec (tests_config/run_spec.js:16:27)
      at Object.<anonymous> (tests/flow/annot/any/jsfmt.spec.js:1:90)
```

Second run:
```
Error: Cannot find module 'jest-snapshot'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at _load_jestSnapshot (/Users/azz/code/prettier/node_modules/jest-cli/build/test_scheduler.js:25:78)
    at /Users/azz/code/prettier/node_modules/jest-cli/build/test_scheduler.js:121:44
    at Set.forEach (<anonymous>)
    at updateSnapshotState (/Users/azz/code/prettier/node_modules/jest-cli/build/test_scheduler.js:120:18)
    at /Users/azz/code/prettier/node_modules/jest-cli/build/test_scheduler.js:175:7
    at Generator.next (<anonymous>)
```

`yarn` says everything is up to date... Any ideas?

**Comment by azz** [comment]
Going to try this. https://github.com/meteor/meteor/issues/8057#issuecomment-261011063

**Comment by SimenB** [comment]
Huh, never seen that before. The issue you linked to seems plausible, though

**Pull request merged**
