### PR TITLE
Build: Combine `replace-module` and `replace-text` plugin

### PR DESCRIPTION
**Pull request by fisker**
## Description

This doesn't change the output, just combine them for easier use.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
Personally, I think it is better to have those plugins separate because they do different things.

**Comment by fisker** [comment]
I don't think they are doing different things, you can achieve `replaceModule` result with `replaceText`.

```js
replaceModule: {foo: {contents: “”}}
```

equals

```js
replaceText: [file: foo, find: /.*/s, replacement: ""]
```

----


```js
replaceModule: {foo: {path: bar}}
```

equals

```js
replaceText: [file: "*", find: `require(${foo})`, replacement: `require(${bar})`,]
```

----

```js
replaceModule: {foo: {path: bar, external: true}}
```

equals

```js
replaceText: [file: "*", find: `require(${foo})`, replacement: `require(${bar})`,],
external： [bar]
```

----

Motion behind this change: Some times I want try different solutions, but options for `replaceModule` is an object, options for `replaceText` is an array, hard to switch between them.

**Review by sosukesuzuki — APPROVED** [review]
I got it. Also can you add documentation for this plugin as an another PR? It is getting a little complicated...

**Comment by fisker** [comment]
Sure, I can try.

**Pull request merged**
