### PR TITLE
fix(js): comments after superclass

### LINKED ISSUE #8309: Formatting `class a extends a // comment` breaks the code
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAnTuAD3igBNd8B6SnSAWzoRgB0phWdbpMYAnAVzAwIvABQBKHMAC+rWVBAAaEBAAOMAJbdkodL14QA7gAU9CTMhDpUh9AE8LygEa90YANZwYAZVVuNUADmyHz8cMoAFjB0qADqERrwmH5gcN7miRoAbol2lmDYSiABmHC8MMaugXToyABm1qXKAFaYhABCrh5e3uiMADIBcPWN4SCthN4BgahwAIr8EPAjqE0gfrylvJZO6E5wqEWqvAEwsRqkMBHIABwADMrHEKWxrqqWx3BbWcPKAI6LeCVNQWFBYAC0UDgcFIMKKvDgAI0CMq6GqtSQDVWY1KdA0IQEOOmswWS2GmNGyhge3Ol2uSAATFTXBpUNMAMIQBgYkBfACsRX4pQAKntQVi1lkwgBJMhMbxgE7qACCZG8MDssxWpWk0iAA)
```sh
--parser babel
```

**Input:**
```jsx
class a extends a // comment
{
  constructor() {}
}

```

**Output:**
```jsx
class a extends a // comment {
  constructor() {}
}

```

**Expected behavior:**
```jsx
class a extends a { // comment
  constructor() {}
}

```

### PR DESCRIPTION
**Pull request by thorn0**
fixes #8309

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
But we don't format [like this for `function/if/while`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgBQCU+AOlAPTX6QC2DCMVwAvlVTqvsYaVr0ITFm05QqAdwAWOADZx+guo2axxIADQgIAB1zQAzslCEATuYhSAChYQmUheVMIBPEzoBG5wmADWcDAAynp+OFAA5sgw5uhwOjIwDPIA6nLwRmFgcMEOOLgAbgVuyOBGniARRnDmMDa+kQyEyKjONToAVkYAHgBCvgFBwYTMADIRcK3tCSDdPcERkYoAiugQ8NPyHSBh5jXmZV6EXnDy2rvmETCpOAAmMDLIABwADDp6VjWpvnpln3ADoUpjoAI7reANfSOECEIwAWigcDgdxRF3McHBOAxDUITRaSDa21mNQYOBicRJS1WEKmhJmOhgJ1uDyeSAATIzfAolgBhETNMqAgCsF3QNQAKidHESdoV4gBJKCo2DBMBXAwAQWVwRgbkUWxq7HYQA)

**Comment by thorn0** [comment]
#8309 is a correctness issue, the issues you bring up are something else. I don't think they need to be solved together.

**Comment by fisker** [comment]
But your second format will be the way like others, maybe we can use the logic from other nodes? So these two issue will solve together.

**Prettier pr-8312**
[Playground link](https://deploy-preview-8312--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII4D0hOkAtmQjADpTC044M7oC8AjLQL4gA0IEAA4wAltEzJQ6AE7SIAdwAKMhBJTpU89AE8J-AEbT0YANZwYAZUHGRUAObIY0gK5x+cMvrgATbz4Ay6PbO6HZwAGIQ0mToMKL2yCDozjAQfCAAFjBkqADqGSLwmNZgcBaqhSIAboXaiWDY6baYcNIwikZ2McgAZhot-ABWmAAeAEJGpuYW6JT+tnC9-W4gwyMWtnaocACKzhDwS6gDINbSLdKJ+uheqOmC0rYwuSLeMBnIABwADPwPEC1ckZBIkHnALlVFvwAI77eAdIRqJKYAC0UDgPh86WkcFhIhxHVC3SQfWOKxaZBEjhc5M22z2B0WJOW-BgNxebw+SAATKyjCJUJsAMIQCjoRLggCs6WcLQAKjc1KSTlVXABJKB+WAWMCPYR4TUWGDabZHFpcLhAA)
```sh
--parser babel
```

**Input:**
```jsx
class A // comment
{
  
  a=1
}
```

**Output:**
```jsx
class A { // comment
  a = 1;
}

```

**Second Output:**
```jsx
class A {
  // comment
  a = 1;
}

```

**Comment by thorn0** [comment]
One more case for `isGroupBreakingComment === false`.

**Prettier pr-8312**
[Playground link](https://deploy-preview-8312--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgEFC4APeKAEwGcSB6BwyAW1YRgB0pgfDC-QtggQeAXx4gANCAgAHGKmi1koXJkwQA7gAUNCVSlwAbbbgCeq2QCNM+ANZwYAZXn50Ac2QxMAVzhZOFYbOGpqMIAZXChPP1xPOAAxCExWXBglWOQQXD8YCBkQAAsYVhMAdWLUeFp3AhdDGtQANxqLHLBaazQoWiwYXXtPdOQ8E37ZACtacgAhezAnV1wOSPQ4MdNJkBnyFy8TOABFPwh4LYnAkHdMfswcmAt5OFowTFRFIvkP2ArUagwYrIAAcAAZZD8IP0KvZ5Dkfq8sC1NrIAI5neBDBRGXK0AC0UDgYTCRUwcAxqHJQwSoyQ4x2-VYqB8-mutEOJ0xm3p22uMFwNn+gOBSAATLJfLhUCYvABhCDsXA5V4AViKfn6ABVBUYGdcWgEAJI0Tgud6fGDEGguJ5HS79cTiIA)
```sh
--parser typescript
```

**Input:**
```tsx
interface A extends A// comment
{
  
  foo
}

```

**Output:**
```tsx
interface A
  extends A { // comment
  foo;
}

```

**Comment by fisker** [comment]
Add some logic from try/while here? https://github.com/prettier/prettier/blob/master/src/language-js/comments.js#L433

**Comment by thorn0** [comment]
related: https://github.com/prettier/prettier/issues/7563

**Comment by fisker** [comment]
Done?

**Comment by thorn0** [comment]
done

**Comment by fisker** [comment]
#8313 seems fixed too

**Comment by fisker** [comment]
And #8340

**Comment by thorn0** [comment]
#8313 is in the linked issues. #8340 is about putting the opening brace on a new line after multiline `extends/implements`. I didn't do that in this PR.

**Pull request merged**
