### PR TITLE
fix: comment at end of at-rule with selector

### LINKED ISSUE #5941: Sass directives without blocks can produce invalid code
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAhjAtAJwhGAAgDoAzfAHSgHpqSAjdHK4KwwqgXxABoQIADjACW0AM7JQTPAHcACkwQSU6AG4RhAE14h6OdGADWcGAGUBB4VADmyGDgCucPgAsYAWwA2AdRfD4YhZgcKZK-sKq-gCeyOBiEnxWYnA4MHL61u7oyKTonsl8AFZiAB4AQvpGJqbo7nAAMlZwOXkFIMUlplbWnnAAig4EzUi5+c4gFjjJOLFiYPE6AjhWMN5aMC7IABwADHxLEMne+gKxS3DTqs18OHAAjg7Ct+nomdkjrePJ7sJ2jl-dXoDIYtMZ8GDoehrTQbZAAJnB+mEnm6AGEIO4srEoNBriAHMkACqQ5SjZKcThAA)
```sh
--parser scss
```

**Input:**
```scss
@at-root .foo
// .bar
{
  
}
```

**Output:**
```scss
@at-root .foo
// .bar {
}

```

**Expected behavior:**
Prettier should generate valid Sass code. The output should match the correct formatting that is produced without the `@at-root` directive ([playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AZhCAdKB6PAAlQCMBDAJ12FwF8QAaECABxgEtoBnZUSiiAHcACpQQ8UZAG4R2AE0YgSFMmADWcGAGUWq9lADmyGBQCucJgAsYAWwA2AdUvt4XXWDhbxL9lJcBPZHAuHiZ9LjgKGGEVAxsyZHQyOwimACsuAA8AIRV1TS0yGzgAGX04ROTUkAzMrX0DOzgARVMIeEqUixBdCgiKIK4wEMUWCn0YB3kYS2QADgAGJjGICIcVFiCxuH6pCqYKOABHU3ZDmLI4hKQkrqYIm3ZjM26uBqbW9oqbqu6YMhIUzkM2QACYmCYyOw7A0AMIQGzxIJQaD7ECmCIAFQBEluEVotCAA)):
```scss
.foo
// .bar
 {
}
```

The behavior seems to generally be caused by `@` directives with no associated `{}`-blocks (like `@media` or `@supports` are required to have).

In the example above, any arbitrary `@rule` in place of `@at-root` can cause the incorrect output, for example:

```scss
@qux .foo
// .bar {
}

```

### PR DESCRIPTION
**Pull request by evilebottnawi**
Fixes #5941

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

~partial #5941, still ugly, but don't break code~

### CODE REVIEW

**Comment by thorn0** [comment]
Do you think this isn't worth mentioning in the changelog?

**Comment by evilebottnawi** [comment]
@thorn0 forgot to commit :smile:

**Comment by evilebottnawi** [comment]
@thorn0 Done

**Comment by fisker** [comment]
Need rebase, and there is new `lastLineHasInlineComment`, we can use.

**Comment by evilebottnawi** [comment]
@fisker feel free to send a new PR, don't have time on this right now :disappointed:

**Comment by fisker** [comment]
I fixed the conflicts, let's see what will it be.

**Comment by fisker** [comment]
I changed a little bit, 

```css
@at-root .foo
// .bar
   {
}
```

to

```css
@at-root .foo
// .bar
{
}
```

I think this is better.

**Comment by evilebottnawi** [comment]
@fisker agree

**Comment by fisker** [comment]
Failed cases in #5941,  all fixed.

**Comment by evilebottnawi** [comment]
@fisker :+1: I can't review, because it is my PR :smile:

**Comment by thorn0** [comment]
@evilebottnawi I'm not a member myself :)

**Comment by evilebottnawi** [comment]
@thorn0 I can send a invite :smile:

**Comment by thorn0** [comment]
@evilebottnawi  Okay, now that I'm a member, I'm good with adding Fisker to members. :D

**Comment by thorn0** [comment]
BTW, I'm working on something like https://github.com/prettier/prettier/issues/3905#issuecomment-393621184 that will fix this too. But have I little idea when I finish that.

**Comment by evilebottnawi** [comment]
@thorn0 It is why we should use pure CSS parser for CSS, because pure CSS and SCSS/Less have difference grammar, in an ideal world we should get `SyntaxError` in your case

**Comment by fisker** [comment]
That one should be a parser error.

**Pull request merged**
