### PR TITLE
Upgrade to ts2.5.3-insiders

### LINKED ISSUE #2702: Valid TypeScript has "SyntaxError: '=' expected."
The following code causes a SyntaxError, despite being syntactically/stylistically correct:
```js
const bar = (...varargs:any[]) => {
  console.log(varargs);
};

const foo = (x:string):void => (
  bar(
    x,
    () => {},
    () => {}
  )
);
```

Here is the result:
```js
SyntaxError: '=' expected. (6:6)
  4 | 
  5 | const foo = (x:string):void => (
> 6 |   bar(
    |      ^
  7 |     x,
  8 |     () => {},
  9 |     () => {}
```

[Here is a link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20bar%20%3D%20(...varargs%3Aany%5B%5D)%20%3D%3E%20%7B%5Cn%20%20console.log(varargs)%3B%5Cn%7D%3B%5Cn%5Cnconst%20foo%20%3D%20(x%3Astring)%3Avoid%20%3D%3E%20(%5Cn%20%20bar(%5Cn%20%20%20%20x%2C%5Cn%20%20%20%20()%20%3D%3E%20%7B%7D%2C%5Cn%20%20%20%20()%20%3D%3E%20%7B%7D%5Cn%20%20)%5Cn)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D) to the issue reproduced in the prettier playground. Note that if the parser is changed to babylon then there is no error shown.

Thanks for any assistance!

EDIT: I'm using prettier@1.6.1 and typescript@2.2.2.

### PR DESCRIPTION
**Pull request by azz**
Fixes #2702 

Think we should wait until 2.5.3 is released?

### CODE REVIEW

**Comment by ikatyang** [comment]
[TS v2.5.3 just got published.](https://github.com/Microsoft/TypeScript/releases/tag/v2.5.3)

**Comment by azz** [comment]
I got this error running yarn. 

```
yarn install v1.0.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error Couldn't find match for "af2c80b2bb558a6e7d61540d97f068f9fa162b38" in "_c" for "git://github.com/lydell/postcss-values-parser.git".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

cc @lydell

**Comment by lydell** [comment]
@azz See https://github.com/prettier/prettier/pull/2627#issuecomment-332411202

**Comment by azz** [comment]
Oops I forgot to rename the PR before squash... This PR upgrades TS to `2.5.3`.

**Pull request merged**
