### PR TITLE
Fix switch case spacing

### LINKED ISSUE #814: Inconsistent line spacing in switch cases
Input:

```js
switch (foo) {
  case "baz":
    doThing();
  case "bar":
    doThing();

  case "baz":
    doThing();


  case "qux":
    doThing();

  default:
    doThing();
}
```

Expected output:

```js
switch (foo) {
  case "baz":
    doThing();

  case "bar":
    doThing();

  case "baz":
    doThing();

  case "qux":
    doThing();

  default:
    doThing();
}
```

Actual output:
```js
switch (foo) {
  case "baz":
    doThing();
  case "bar":
    doThing();

  case "baz":
    doThing();

  case "qux":
    doThing();

  default:
    doThing();
}
```

Related https://github.com/prettier/prettier/issues/805

### PR DESCRIPTION
**Pull request by yamafaktory**
This PR fixes #814 & #805. As you can see, it introduces a very opinionated heuristic but I think it's a good way to avoid future issues in switch statements. One future improvement could be to detect enclosed break or return statements in cases in order to apply the same logic, but that involves going through each descendant nodes to find them.

### CODE REVIEW

**Comment by yamafaktory** [comment]
@jlongster in #814, you were talking about *inlined* cases, but even before this PR something like (using current master):

```js
function test () {
  switch (foobar) {
    case foo: return 1;
    case bar: return 2;
  }
}
```

Was turned into:

```js
function test() {
  switch (foobar) {
    case foo:
      return 1;
    case bar:
      return 2;
  }
}
```

IMHO this PR will go further by making it even more readable:

```js
function test() {
  switch (foobar) {
    case foo:
      return 1;

    case bar:
      return 2;
  }
}
```

**Comment by yamafaktory** [comment]
@vjeux your opinion on that one?

**Comment by vjeux** [comment]
Sorry for the long wait. I don't think we should do that. I think we should stick with preserving the \n the way they were entered. If someone added an empty line, we should preserve it, if not we shouldn't.

Otherwise it's going to be very confusing when that happens for body expressions but case do not respect it.

**Comment by yamafaktory** [comment]
@vjeux absolutely no problem, this was very opinionated and the initial issue was leveraging a lot of concerns. Should we close it?

**Comment by vjeux** [comment]
Yeah, I think we shouldn't implement the behavior in #814 and the current one is the right one. But #805 is still an issue that would be nice to be fixed :)

**Pull request closed without merging**
