### PR TITLE
Fix ugly formatting for assignment with closure style type casting

### LINKED ISSUE #9358: Ugly line breaks for variable declarations with JSDoc type comment
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCeIBGAhgE6YC8mA9AFQ2YACMAngA5ybACCJJRzAOgA8uPAOK9xRaTIBeAPgC+mGlUwAKUYWklis2QEl4AWzSYAPuZx4AlAG4AOlEhQM1-BIrU6jFu048fIIi+FKSxDLSCsqqGloRukT6RnCmmADU7vZOLm5a2mSUtPRMbBzcvPzCWmEkUpFJSipqmh46eoYmZpZZmAD87phImBJ2IAA0IBCsMACW6MigpCQQAO4ACqQIaMggRAA2q-w7kwR8YADWcDAAyqxEYLNQAObIMCQArnCTqQRwACb-AEAGSILw+RGecAAYhASMYiDA5i9dkQPjAIBMQAALGDGfYAdWxs3gaHuYDgN22JNmADcScxdmA0CcQE80HASDB1nxngjkNgDhzJgArNAADwAQucrrciMY4MCnnABULviAxeKbk9nvs4ABFD4QeCq-bCkD3Egcki7Yh-fZY1gkJ4wAmzf4wbHIAAcAAZJk6IByCXxWLsnXBrbSVZMAI5G+A86Y7FBENAAWigcABAKxJDg8dm+Z5kP5SEFZvVHOMszenyrOr1huNKvLasmMCIBDdHq9SAATB2+LN9jqAMIQYxlkCRgCsWI+HIAKl2UxXzbSvgYoEDYDcwM6ZlwdzcWHrTRzFIogA)
```sh
--parser babel
```

**Input:**
```jsx
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems || foo);
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems + foo);
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems || foo) ? foo : bar;

```

**Output:**
```jsx
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems ||
  foo);
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems +
  foo);
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems ||
  foo)
  ? foo
  : bar;

```

***Expected:**

```jsx
const foooobar =
  /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems || foo);
const foooobar =
  /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems + foo);
const foooobar =
  /** @type {Array.<fooo.barr.baaaaaaz>} */ (fooobaarbazzItems || foo)
    ? foo
    : bar;

```

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Fixes #9358

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]

**Comment by thorn0** [comment]
These type assertions look and feel like function calls. Wouldn't it make sense to format them the same way? E.g.
```js
const foooobar = /** @type {Array.<fooo.barr.baaaaaaz>} */ (
  fooobaarbazzItems || foo
);
```
?

**Comment by sosukesuzuki** [comment]
@thorn0  Hmmm, I personally don't think that format makes sense. I don't want to format it specifically for type casting comments too much. Let's create a new issue separate from this PR. My company uses Closure Library so I'll ask my colleagues for their opinion.

**Comment by thorn0** [comment]
Sorry, but I'm really not sure that this is an improvement:

**Input:**
```jsx
const foooobar =
  /** @type {Array<{ type: 'file' | 'dir' | 'glob'; glob: string; input: string; }>} */ (fooobaarbazzItems || foo(reallyLongArg(), omgSoManyParameters(), IShouldRefactorThis(), isThereSeriouslyAnotherOne()));
```

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCeIBGAhgE6YC8AOlJpgPQBUDmAAjAJ4AOcmwAgiRJF2AHmCYO3JJgDk2AJYAbODMwAfWQBN5JVRpkBzRYRkBuTEcLSMJeVAPm7nAK4xrMW-fMBfAHzfMBjpMAApcPGJSYgAvaIBJeABbNHUNcJCSOCJFRXYAGWgDAQMQgEoAGkwIRIMAZQgAWSIodgAFUiJEuHgSNDLKuNqACwhnRU0AJThsIjAYCBIAFSH5PorMVeW4TNrt+VG0XL4oCBgh7YB5KDgy0tLTEHKQCE4Yfag0ZFBSEggAd3amQ+yBA2T+wk+TwIQjAAGturVOLM7AZkB5nHAnnBEgQ4JpNHi8s0DM4iAY4AAxBaJIgwN72EFEVwQR4gIYwRKKADqK3gaCRYDguw+8jeADdRewQWA0JCQHY0NsYK0hAYacgZopFU8AFZoAAeACEYfCYLVOnA8nY4BrstqQHr9bUUcoAIrOU42pCa+1I3rbEHEXGKVmcTwwLnyTRnZAADgADE8wxBFVyhJwQWG4IqSGKbU8AI4e+Aql6fFBENAAWmueLxrMyRZ0cBVZPV3rtmJAisS8jRJAxTzQLrg7s9tq1XZgRAIkejQ2QACYnh4iEoUQBhartkDZgCsrOcisWM-LPq7YoxcSgBNgtTAtlex00tQ4ygniu83iAA)

**Output:**
```jsx
const foooobar = /** @type {Array<{ type: 'file' | 'dir' | 'glob'; glob: string; input: string; }>} */ (fooobaarbazzItems ||
  foo(
    reallyLongArg(),
    omgSoManyParameters(),
    IShouldRefactorThis(),
    isThereSeriouslyAnotherOne()
  ));

```

**Prettier pr-9361**
[Playground link](https://deploy-preview-9361--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzCeIBGAhgE6YC8AOlJpgPQBUDmAAjAJ4AOcmwAgiRJF2AHmCYO3JJgDk2AJYAbODMwAfWQBN5JVRpkBzRYRkBuTEcLSMJeVAPm7nAK4xrMW-fMBfAHzfMBjpMAApcPGJSYgAvaIBJeABbNHUNcJCSOCJFRXYAGWgDAQMQgEoAGkwIRIMAZQgAWSIodgAFUiJEuHgSNDLKuNqACwhnRU0AJThsIjAYCBIAFSH5PorMVeW4TNrt+VG0XL4oCBgh7YB5KDgy0tLTEHKQCE4Yfag0ZFBSEggAd3amQ+yBA2T+wk+TwIQjAAGturVOLM7AZkB5nHAnnBEgQ4JpNHi8s0DM4iAY4AAxBaJIgwN72EFEVwQR4gIYwRKKADqK3gaCRYDguw+8jeADdRewQWA0JCQHY0NsYK0hAYacgZopFU8AFZoAAeACEYfCYLVOnA8nY4BrstqQHr9bUUcoAIrOU42pCa+1I3rbEHEXGKVmcTwwLnyTRnZAADgADE8wxBFVyhJwQWG4IqSGKbU8AI4e+Aql6fFBENAAWmueLxrMyRZ0cBVZPV3rtmJAisS8jRJAxTzQLrg7s9tq1XZgRAIkejQ2QACYnh4iEoUQBhartkDZgCsrOcisWM-LPq7YoxcSgBNgtTAtlex00tQ4ygniu83iAA)

**Output:**
```jsx
const foooobar =
  /** @type {Array<{ type: 'file' | 'dir' | 'glob'; glob: string; input: string; }>} */ (fooobaarbazzItems ||
    foo(
      reallyLongArg(),
      omgSoManyParameters(),
      IShouldRefactorThis(),
      isThereSeriouslyAnotherOne()
    ));

```

**Comment by thorn0** [comment]
https://github.com/prettier/prettier/issues/9358 was fixed, so let's close this PR

**Pull request closed without merging**
