### PR TITLE
[playground] fix overflow in safari

### PR DESCRIPTION
**Pull request by johann-sonntagbauer**
fixes problems in safari discussed in https://github.com/prettier/prettier/pull/4394.

Now the options panel will not outgrow editors panel.

### CODE REVIEW

**Comment by duailibe** [comment]
Thank you!! 💯 🎉

**Comment by duailibe** [comment]
I don't think this was the right fix.. I guess we shouldn't mess with the CodeMirror classes, we broke it in another way

screen shot 2018-05-04 at 11 45 37

**Comment by johann-sonntagbauer** [comment]
@duailibe sorry for that, I will try to test even further, what safari os combination do you face that problem?
Tested quite a few combinations without any issues.

**Comment by j-f1** [comment]
@johann-sonntagbauer That’s Chrome, not Safari.

**Comment by duailibe** [comment]
Yeah it's Chrome on macOS

**Comment by johann-sonntagbauer** [comment]
yes you are right, the code mirror gutter styles work as expected, the problem seems to be related only to the placeholder. I will formulate a pr for the revert and dig a little deeper on the placeholder stuff later on.

**Pull request merged**
