### PR TITLE
Add markdown parser to playground

### PR DESCRIPTION
**Pull request by azz**

### CODE REVIEW

**Comment by SimenB** [comment]
This is somewhat buggy. Pasting in some markdown without changing options gives a syntax error (as expected), but changing the parser does nothing. I have to refresh, then it's correct.

Is this expected?

**Comment by azz** [comment]
Probably bad caching? Does it work the next time?

**Comment by SimenB** [comment]
Ah, yes it does. Odd

**Comment by azz** [comment]
Service worker voodoo... https://twitter.com/markdalgleish/status/921519602202316800

**Pull request merged**
