### PR TITLE
[RFC/Strawman] Arrow Function Params always have parens

### PR DESCRIPTION
**Pull request by rattrayalex**
See discussion in https://github.com/prettier/prettier/issues/812

This is clearly uglier in a few cases, but more editable in almost all cases. It is also simple & completely consistent. 

Competes with https://github.com/prettier/prettier/pull/2430

### CODE REVIEW

**Comment by bakkot** [comment]
@rattrayalex, I dispute "in almost all cases" - as I pointed out [in the issue](https://github.com/prettier/prettier/issues/812#issuecomment-313837071), the overwhelming majority of arrows have exactly one parameter which is a single identifier. Indeed, the expectation that this would be the case is exactly why the language allows omitting those parentheses in the first place. It's only useful in the relatively rare case that you want to switch to destructuring, or if you're using a language other than JavaScript.

This feels like requiring the parentheses in `a - (b * c)`. While it's true that this is more editable, in that you don't need to add parentheses yourself if you want to change the `*` to a `-`, and both simple and consistent, it's also redundant to the point of excess.

**Comment by jlongster** [comment]
Thank you for exploring this, but I don't think we should do this. I think we should stick with the current behavior and close the other issue. I'll explain why.

We all need to admit that this is all completely subjective, and in the grand scheme of things a very small issue. If we do this, there will be a lot of people that complain and want it to be switched back. How do I know? I'm involved in enough projects to know that there are a lot of people that prefer the existing style and are silent about it. The only way to ultimately prove that is to make this change and wait to see the response. But do you know how tiring it would be to have to do that for *every single tiny stylistic preference*? As maintainers of the library ultimately we need to make the final decision and just move on.

And yes, that means we are going to be influenced somewhat on what we prefer, there's no denying that. But that is the benefit of being the creator/maintainers of the project. While we try to respect the community as much as possible (there have been *tons* of changes we've made because there was a clear desire from the majority of people) for divisive things like this we can't please everybody, and we are going to make a call. And for me, my call is to stick with what we do now (which I feel fairly represents a lot of the current users).

I can give my reasons, but again they are subjective. Parens adds a lot of noise, and trying a hybrid approach where they are added when a block is used would result in weird things like `foo => bar => (baz) => { ...` for curried styles. We don't believe that adding parens every now and then is really that big of a deal (I saw "we" because I consulted with @vjeux on this and he agrees). Optimize for reading code, not writing. You read code a lot more.

This is an open-source, free project. If you don't like how it works, you do not need to use it. This is especially the case with prettier, which isn't a runtime library or API that you are forced to use at work. Even if a project you work on uses it, you don't have to. Just write code as you would without it (or use a different formatter) and it'll be formatted back with prettier on commit.

The whole point of prettier is to stop having these discussions. We are at the point in this project's life where we've basically hashed out most of the decisions already, and we aren't going to keep spinning our wheels. There are a few things left that I think we should investigate, like nested ternary formatting, but soon we will be working towards a "syntax freeze" where we commit to not changing anything unless it's required by new syntax or something.

There is a fork which implements a lot more options: https://github.com/arijs/prettier-miscellaneous. The cool thing is that you can easily use that locally even if your team isn't using it. Or you can fork prettier yourself and customize it however you want! I think we should encourage that instead of trying to appease every single little style.

Respectfully and with love - jlongster

**Comment by rattrayalex** [comment]
@jlongster you didn't need to write so much, I know all these things and agree :smile: I worry that this kind of stuff is too stressful for you. 

While I certainly appreciate your concern for my feelings, I really I hope I was clear in the other thread (if not here) that I didn't feel a strong personal investment on this issue. And it clearly wasn't very difficult to implement :wink:

It's totally okay to make these calls; don't worry about it so much. 

I do have to say that there are objective tradeoffs at play on this topic, particularly regarding developer workflow - only the question of readability is subjective in this case. But someone has to resolve those tradeoffs, and I'm certainly comfortable having that person be you - it's your project and I think you've done a great job. 

Thanks for weighing in!

**Comment by jlongster** [comment]
@rattrayalex I'm not very stressed about it anymore, you all have done a great job continuing to maintain this while I focused on other things and now I want to start watching it again. :) I have no problem explaining at great length why we reject seemingly tiny changes because we can point back to it in later discussions. They are all points that I wanted to say, and I was in the mood to write.

While there is some objectivity, for things so small as parenthesis there really isn't much to argue. Either you like them or not. Both sides have pros/cons, objective ones even, but it's really subjective when it comes do it. Bigger things like nested ternaries have a lot more legs to stand on.

If I ever sounds stressed it's probably not prettier, but other things I'm working on. I have client work to do and I am also attempting to launch a product, hopefully later this year. This leaves little room for other things but I'd like to work on prettier some again.

**Pull request closed without merging**
