### PR TITLE
Set default parameters for HTML parser options

### LINKED ISSUE #11272: html parser requires options be passed as third option
**Environments:**

- Prettier Version: 2.3.2
- Running Prettier via: API in node
- Runtime: node 16.5.0
- Operating System: Linux
- Prettier plugins (if any): none

**Steps to reproduce:**

Following the API docs: https://prettier.io/docs/en/api.html#custom-parser-api

```
const prettier = require('prettier');
prettier.format(`
    <div></div>
`, {
    parser(text, {html}) {
        return html(text);
    }
});
```

**Expected behavior:**

Returns formatted html similar to `<div></div>`
**Actual behavior:**

An error is thrown:

```
❯ node ./prettier-repro.js 

/d/project/node_modules/prettier/index.js:13704
    throw error.stack;
    ^
TypeError: Cannot read property 'filepath' of undefined
    at qs (/d/project/node_modules/prettier/parser-html.js:132:3682)
    at parse (/d/project/node_modules/prettier/parser-html.js:132:4480)
    at Object.parser [as parse] (/d/project/prettier-repro.js:6:16)
    at Object.parse$a [as parse] (/d/project/node_modules/prettier/index.js:13684:19)
    at coreFormat (/d/project/node_modules/prettier/index.js:15215:16)
    at formatWithCursor$1 (/d/project/node_modules/prettier/index.js:15455:14)
    at /d/project/node_modules/prettier/index.js:60228:12
    at Object.format (/d/project/node_modules/prettier/index.js:60248:12)
    at Object.<anonymous> (/d/project/prettier-repro.js:2:10)
    at Module._compile (node:internal/modules/cjs/loader:1095:14)
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

The fix is to pass `filepath` (`options`) as a third argument to the html formatter.

```
const prettier = require('prettier');
prettier.format(`
    <div></div>
`, {
    parser(text, {html}, options) {
        return html(text, undefined, {filepath: 'test.html'}); // can also pass `options` as third argument if it has filepath; here I am passing an object literal for demonstration purposes
    }
});
```

With the above fix, t fails with a different error which I believe is a separate bug:

```
❯ node ./prettier-repro.js
/d/project/node_modules/prettier/index.js:49122
      throw new Error("unknown type: " + JSON.stringify(node.type));
      ^

Error: unknown type: "root"
    at printPathNoParens (/d/project/node_modules/prettier/index.js:49122:13)
    at Object.genericPrint$6 [as print] (/d/project/node_modules/prettier/index.js:48560:19)
    at callPluginPrintFunction (/d/project/node_modules/prettier/index.js:14958:21)
    at mainPrintInternal (/d/project/node_modules/prettier/index.js:14896:17)
    at mainPrint (/d/project/node_modules/prettier/index.js:14878:14)
    at printAstToDoc (/d/project/node_modules/prettier/index.js:14865:13)
    at coreFormat (/d/project/node_modules/prettier/index.js:15226:15)
    at formatWithCursor$1 (/d/project/node_modules/prettier/index.js:15455:14)
    at /d/project/node_modules/prettier/index.js:60228:12
    at Object.format (/d/project/node_modules/prettier/index.js:60248:12)
```

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #11272 (But the code listed in the issue still doesn't work due to another issue...)

In some special environments, such as custom parser APIs, the options may not be present.

## Checklist

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Isn't the parser private? I think passing the `options` is the right thing to do, if the user wants to use it.

**Comment by sosukesuzuki** [comment]
@fisker 

> Isn't the parser private? I think passing the options is the right thing to do, if the user wants to use it.

Okay. But it is so unfriendly to throw error (`TypeError: Cannot read property 'filepath' of undefined`) when options don't exist. So I've pushed the commit to throw friendly error (`options are required for parsing HTML.`). What do you think?

**Comment by fisker** [comment]
I'm not sure what's the best choice, but [we use `{}` as default value in babel parser](https://github.com/prettier/prettier/blob/b6fd41491856d659e043ac45a3758607f70bb5ba/src/language-js/parse/babel.js#L93). 

This was added by me (I guess maybe about one year ago), it has no default value for very long time, I added it only because we have a test not passing `opts`, [link](https://github.com/prettier/prettier/blob/b6fd41491856d659e043ac45a3758607f70bb5ba/tests/integration/custom-parsers/custom-rename-parser.js#L4).

I don't think we need to do anything.

**Comment by fisker** [comment]
Check this comment too https://github.com/prettier/prettier/pull/8173/files#r422095375

**Pull request closed without merging**
