### PR TITLE
Update `execa` to 3.2.0

### PR DESCRIPTION
**Pull request by fisker**
- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
ready

**Comment by brodybits** [comment]
Looks like dependabot did the same thing in PR #6758, automatically rebased to resolve the conflict.

**Comment by fisker** [comment]
> Sorry to bother you with a nit: I noticed that the commit message has the wrong version number.

this version number is not wrong, I commit this long ago it is v2, then I update to v3 when I rebase

**Comment by lipis** [comment]
merged in #6758

**Pull request closed without merging**
