### PR TITLE
GraphQL: Use spaces instead of commas

### PR DESCRIPTION
**Pull request by vjeux**
"Daniel Schafer: Yeah, that's definitely what I'd describe as the canonical style; anytime you have two "things" on a line, use commas, but if you have a newline it's not needed."

### CODE REVIEW

**Comment by vjeux** [comment]
cc @stubailo, @jnwng

**Comment by dschafer** [comment]
I don't know the prettier code that well, but based on the test cases this looks good to me!

**Comment by jnwng** [comment]
TIL that the commas in the arguments list aren't required, i never even thought about that one

**Comment by dschafer** [comment]
Yep, commas are just whitespace. So we use them for disambiguation when things are on the same line:

```graphql
  field(arg1: 1, arg2: 2)
  field { another, field, if, you, put, them, on, one, line }

**Comment by vjeux** [comment]
Okay, I'm going to merge it, thanks for the insights!

**Pull request merged**
