### PR TITLE
Update `escape-string-regexp` to v2

### PR DESCRIPTION
**Pull request by fisker**
- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
@evilebottnawi you are right,

this should not effect 

https://github.com/prettier/prettier/blob/0cbacd31561f981b7e30972afc09051531c7a7c3/src/utils/front-matter.js#L3 

but for this

https://github.com/prettier/prettier/blob/27ef80d56afecca2a02dfb7349be934209896b9d/src/common/util.js#L4 this is a breaking change, but we don't have any actual test on those utils

https://github.com/prettier/prettier/blob/023a8b78df18a3afd8f82f9c2fc51bae02273d24/tests_integration/__tests__/util-shared.js

**Comment by evilebottnawi** [comment]
@fisker maybe we can add tests?

**Comment by fisker** [comment]
This only public api `sharedUtil.getMaxContinuousCount` using this module is tested on #7262

**Comment by evilebottnawi** [comment]
I think will be better do it in next branch

**Pull request closed without merging**
