### PR TITLE
Adjust `maxWorkers` for `jest`

### PR DESCRIPTION
**Pull request by fisker**
I ran several tests (only the slowest job and a normal windows job) with different `maxWorkers` on my fork

job | duration
:--|--:
[max-workers-1](https://github.com/fisker/prettier/actions/runs/73379503) | 22m 50s 
[max-workers-2](https://github.com/fisker/prettier/actions/runs/73381299) | 14m 10s
[max-workers-3](https://github.com/fisker/prettier/actions/runs/73379954) | 16m 4s
[max-workers-4(current)](https://github.com/fisker/prettier/actions/runs/73388980) | 17m 30s
[max-workers-5](https://github.com/fisker/prettier/actions/runs/73380194) |  22m 56s
[max-workers-6](https://github.com/fisker/prettier/actions/runs/73380357) | 17m 0s
[max-workers-7](https://github.com/fisker/prettier/actions/runs/73393607) | 17m 5s

I also tried increase memory, seems not helping

job | duration
:--|--:
[max-workers-2, --max-old-space-size=6144](https://github.com/fisker/prettier/actions/runs/73400692) | 16m 18s
[max-workers-3, --max-old-space-size=6144](https://github.com/fisker/prettier/actions/runs/73401716) | 17m 38s
[max-workers-4, --max-old-space-size=6144](https://github.com/fisker/prettier/actions/runs/73401171) | 19m 6s 
[max-workers-5, --max-old-space-size=6144](https://github.com/fisker/prettier/actions/runs/73403025) | 15m 28s
[max-workers-6, --max-old-space-size=6144](https://github.com/fisker/prettier/actions/runs/73419518) | 15m 50s

Set `maxWorkers` to `2` seems a little faster, maybe save us about 2 mins :smile: , I ran tests again

job | duration
:--|--:
[max-workers-2(second run)](https://github.com/fisker/prettier/actions/runs/73419069) | 13m 57s 
[max-workers-4(second run)](https://github.com/fisker/prettier/actions/runs/73426505) | 16m 52s

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Why do not remove `--max-workers`, some github actions servers have 32 thread, why we don't use their?

**Comment by SimenB** [comment]
Detecting number of threads cross CI provider is hard (see https://github.com/SimenB/available-cpu where I've tried to get something consistent), so setting something manually when you know your env seems reasonable. It's a slippery slope for Jest to hard code based on which CI it's running in, but if you _just_ use GH actions hardcoding per OS might make sense.

Ideally all CI providers would provide this information in their env, but I don't think any do (https://github.com/pvdlg/env-ci/issues/51)

**Comment by fisker** [comment]
@SimenB Are you suggestion set `2` for `linux`, `4` for `mac` and `1` for `windows`?

**Comment by fisker** [comment]
As we can see `2` makes most jobs faster.

**Comment by SimenB** [comment]
I'd fire GH an email or ask here: https://github.community/t5/GitHub-Actions/bd-p/actions

A platform independent way would be ideal... Easiest for you is probably to use `physical-cpu-count`. Seems it' wrong on Windows (based on https://github.community/t5/GitHub-Actions/NUMBER-OF-PROCESSORS-not-set-on-the-windows-workers/td-p/52562) but still

**Comment by fisker** [comment]
@evilebottnawi I tried to set to 20 workers, not useful https://github.com/fisker/prettier/actions/runs/73361912

**Comment by fisker** [comment]
Indeed macOS: 4, other: 2 seems best.

**Pull request merged**
