### PR TITLE
fix(insertPragma): fix insertPragma breaking comment on invalid docblock (#3269)

### PR DESCRIPTION
**Pull request by gnarmedia**
This commit addresses the issue I raised about pragmas being inserted strangely in invalid docblocks.

**Input:**
```jsx
/* ShippingValidation: 
 * Encapsulates the validation on the payment options page in checkout
 */
```

**Output:**
```jsx
/**
 * /* ShippingValidation:
 * Encapsulates the validation on the payment options page in checkout
 *
 * @format
 */

```

**Expected behavior:**
```jsx
/**
 * ShippingValidation:
 * Encapsulates the validation on the payment options page in checkout
 *
 * @format
 */
```

There are other options for how to handle this:

```jsx
/** @format */

/* ShippingValidation:
 * Encapsulates the validation on the payment options page in checkout
 */
```

or

```jsx
/*
 * ShippingValidation:
 * Encapsulates the validation on the payment options page in checkout
 *
 * @format
 */
```
I chose to have it rebuild the docblock as this was the easiest behavior, and probably most desirable, but if anyone prefers this be handled with a new separate pragma block or anything like that, please let me know and I will revise this PR.  Thank you.

If anyone has any questions or if I didn't do something right, please let me know.  This is my first contribution to Prettier and I am excited to contribute more in the future. :]

### CODE REVIEW

**Comment by SimenB** [comment]
Is it a bug that it's treated as a docblock at all?

**Comment by gnarmedia** [comment]
@SimenB kinda... It's sort of an issue in how Jest parses the block, it actually tests to be sure invalid docblocks can parse.  So I figured this way the data can be retrieved, the docblock can be made, minimal efforts to get it to work.

**Comment by gnarmedia** [comment]
@SimenB I could also check that the block has a comment opening and build a new block based on that condition.

**Comment by gnarmedia** [comment]
I wonder if I should really raise this issue in Jest?

**Comment by azz** [comment]
Sorry this PR was overlooked @gnarmedia.

The expected behaviour for this is actually:

```js
/** @format */

/* ShippingValidation:
 * Encapsulates the validation on the payment options page in checkout
 */ 
```

We shouldn't be treating `/* */` comments as docblocks. This is an issue with `jest-docblock` though, so I've raised an issue there: https://github.com/facebook/jest/issues/5650.

If it is fixed in `jest-docblock` all we'll need to do is upgrade the package here and add a test, so I'll close this PR.

**Comment by CrabDude** [comment]
This doesn't seem to be a jest-specific issue, as the problem occurs with (at least) eslint & flow comments as well:
```
-/* eslint pinterest/no-jquery-outside-of-render:0 */
+/**
+ * /* eslint pinterest/no-jquery-outside-of-render:0
+ *
+ * @format
+ */
```

Is this reported elsewhere?

**Comment by duailibe** [comment]
@CrabDude it's related to the utility we use to parse/extract stuff from docblocks, called [`jest-docblock`](https://yarnpkg.com/en/package/jest-docblock).

It doesn't mean that it happens with jest files or anything.

**Comment by CrabDude** [comment]
🤦

**Comment by tmarkovic** [comment]
Any updates regarding this? I would love to help out since this issue's currently prohibiting me from implementing prettier in our codebase because of eslint-disables(globals 

Example:

`/* globals describe, before, after, it, error */`

Turns into:

```
/**
 * /* globals describe, before, after, it, error
 *
 * @format
 */
```

**Comment by gnarmedia** [comment]
If you simply make that into a proper do block it'll handle it just fine,
or if you add a doc block above it that will work, too. Thet being said, I
haven't heard updates, I was waiting to find out what code to push to fix
this, but haven't heard anything definitive.

**Comment by tmarkovic** [comment]
I'll try my best with some search and replace, It's a very large code though so wish me luck.
Let me know if there's anything I can do to help

**Comment by gnarmedia** [comment]
Perhaps the codemod library might make that easier. Of course fixing this
bug would be even easier, haha.

**Comment by lydell** [comment]
@tmarkovic According to https://github.com/prettier/prettier/pull/3307#issuecomment-368209170 all that needs to be done is upgrading jest-dockblock and adding tests. Interested in making a PR?

**Comment by tmarkovic** [comment]
@lydell Well that doesn't look like to much of a hassle allthough I've never really contributed to any significant OS project before so I guess I have a contributing.md to read somewhere. I'll give writing those tests a shot tomorrow!

**Comment by gnarmedia** [comment]
That's what I thought. I was ready to make all the PRs but I never heard
back.

**Comment by lydell** [comment]
Ah, sorry, I misread the comment.

**Comment by gnarmedia** [comment]
There is more progress on the discussion on jest's comment thread.

https://github.com/facebook/jest/issues/5650#issuecomment-379426068

**Comment by gnarmedia** [comment]
Perhaps just appending a new line with the pragma to each file individually
is easier

**Pull request closed without merging**
