### PR TITLE
fix: nested embeds (JS in HTML in JS)

### PR DESCRIPTION
**Pull request by thorn0**
Currently, if JS code embedded in HTML (via `<script>`) embedded in JS (via a template literal) contains template literals, the inner JS isn't formatted.
```js
const html = /* HTML */ `<script>var a=\`\`</script>`;
```
([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEALGBbAG0wF5MB6AKkwAkAVAWQBlMKzMADAHjTACcBLAA4wAfADcAhr0wTiAHTnsFXMjwHCR7ANwgANCAjD+6ZKCm8IAdwAKUhGmQgJYiPwAmekACNeEsAGs4GABlQT9+KABzZBheAFc4fVxCAHVsfng0MLA4YPsM-jEMgE9HMDQHfQi0OF4Ya19IvAlkADMJAhr9ACs0AA8AIV8AoOCJPDhGCLg2jq6QXr7giMiCOABFOIh4Wc7EkDDeGt5HLwkvOAJPQQFYFPcYbGQADgAGfRuIGpTfQUcbuDHMQzfS8OAARzi-DBDQkTRaSHae30NTw-Bi8X2aBWa022xmiLm+xg53ubkeyAATPpYhJ+AQVgBhCB4ZqOKDQEEgOI1WjnByEvYAXyFQA))

This fix has been extracted from #5993.

- [x] I’ve added tests to confirm my change works.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by duailibe** [comment]
Sorry this was overlooked @thorn0 

Can you add an entry to the CHANGELOG?

**Comment by duailibe** [comment]
FTR this doesn't work (not saying you should fix it)

**Prettier pr-6038**
[Playground link](https://deploy-preview-6038--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEALGBbAG0wF5MB6AKkwAkAVAWQBlMKzMADAHjTACcBLAA4wAfJCgYc+IqUo0GzVpgA6yrjwHCRnMhqGjV7ANw69W4yAA0ICMP7pkoAIa9eEAO4AFFwjTIQTgBuEPwAJlYgAEa8TmAA1nAwAMqCsfxQAObIMLwArnDWuIQA6tj88GipYHBJvuX8geUAnv5gaH7W6WhwvDCeMRl4TsgAZk4E3dYAVmgAHgBCMfGJSU54cIzpcKPjkyAzs0npGQRwAIq5EPA7EwUgqbzdvP6RTpFNBNARggKwxWEwbDIAAcAAZrD8IN1ijFBP4fnAnoFttYAI6XeD9Wx+FBONAAWigcDgoRJEV4cHR-Ap-Scg2GSDGt2s3Tw-GyeTuaGOpwuV22jN2dxgb3+oUByAATNYck5+ARjgBhCB4Ib+KDQFEgXLdWhvHFM7oAXyNQA)
```sh
--parser babylon
```

**Input:**
```jsx
const html = /* HTML */ `<script>const html = /* HTML */ \`<script></script>\`;</script>`;
```

**Output:**
```jsx
SyntaxError: Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:53)
> 1 | <script>const html = /* HTML */ `<script></script>`;</script>
    |                                                     ^
```

**Comment by thorn0** [comment]
I have a bit of "JS in HTML in TS". Not that it's blocking. I'd be happier if I got "JS in JS" though...

As for your snippet, there is nothing to fix there. The result is expected and correct. The first `</script>` closes the script tag in the outer HTML markup. It is more clear if remove the outer JS layer and switch to HTML:

**Prettier pr-6038**
[Playground link](https://deploy-preview-6038--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wB8kU6MABABYwC2ANuQLzkD0AVOQBIAqAsgDLk2LcgAMM2fEVQtMuAoVEBuGXKmEQAGhAQCOaOmSgAhliwQA7gAVTCQymMA3CDgAmWkACMsxsAGs4GABlPF8cKABzZBgsAFc4bWp6AHVKHHh0ULA4ILt0nEd0gE9kcHRDbXD0OCwYKx8ImmNkADNjOmrtACt0AA8AIR9-QKDjGjh+cLhW9s6QHt6g8Ii6OABFWIh4GY6EkFCsaqxSpLoPPFxYZLcYSmQADgAGbQuIauSfPFKLuCPHae0AEdNvB6rp7CBjOgALRQOBwVwIjxYODAnAo+rGRrNJBtXbaao0HDROJ7dDLVYbLbTXGzPYwYyea6uW7IABM2hixhwdGWAGEIDQmqUoNAASBYtVuIz7HjqgBfeVAA)
```sh
--parser html
```

**Input:**
```html
<script>const html = /* HTML */ `<script></script>`;</script>
```

**Output:**
```html
SyntaxError: Unexpected closing tag "script". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (1:53)
> 1 | <script>const html = /* HTML */ `<script></script>`;</script>
    |                                                     ^
```

The inner closing `script` tag simply needs proper escaping:
**Prettier pr-6038**
[Playground link](https://deploy-preview-6038--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAEALGBbAG0wF5MB6AKkwAkAVAWQBlMKzMADAHjTACcBLAA4wAfJCgYc+IqUo0GzVpgA6yrjwHCRnVbuVkNQ0avYBuTgb5GRZkABoQEYf3TJQAQ168IAdwAKnghoyCDuAG4Q-AAm9iAARrzuYADWcDAAyoJJ-FAA5sgwvACucA64hADq2PzwaFlgcOlBNfxhNQCeIWBowQ45aHC8MH6JuXjuyABm7gQDDgBWaAAeAEKJKWnp7nhwjDlwUzNzIItL6Tm5BHAAikUQ8IezpSBZvAO8IXHuce0E0LGCASwCrRGDYZAADgADA5ARABhVEoIQoC4O8wgcHABHO7wEZOYIodxoAC0UDgcCilNivDgOP4tJG7jGEyQ0yeDgGeH4BWKzzQFyut3uBzZR2eMG+IKiYOQACYHIV3PwCBcAMIQPDjEJQaCYkBFAa0b6E9kDAC+5qAA)
```sh
--parser babylon
```

**Input:**
```jsx
const html = /* HTML */ `<script>const html = /* HTML */ \`<script><\\\/script>\`;</script>`;
```

**Output:**
```jsx
const html = /* HTML */ `
  <script>
    const html = /* HTML */ \`
      <script></script>
    \`;
  </script>
`;

```

As for the CHANGELOG, I thought minor bugs aren't reflected there, but okay, I'll do it.

**Comment by duailibe** [comment]
> The result is expected and correct.

Thanks! My bad

> Now, that's a bug.

Yikes, would you open a new issue (or fix it here if you're interested)

> As for the CHANGELOG, I thought minor bugs aren't reflected there

Yeah they are.. we only leave out changes that aren't visible to users

**Comment by thorn0** [comment]
> would you open a new issue (or fix it here if you're interested)

I'll fix it here.

**Comment by duailibe** [comment]
@thorn0 I know we already handle something similar with GraphQL

**Comment by lydell** [comment]
Maybe more relevant edge cases to test: https://stackoverflow.com/questions/41297404/is-it-possible-to-correctly-escape-arbitrary-script-tag-contents

**Comment by thorn0** [comment]
@lydell My two takeaways from that SO question:

1. There is no generic (language-unspecific) way to escape the content of `script` tag.
2. It's recommended to escape HTML comments (the sequence `<!--` ) inside scripts.

As for number one, since it doesn't exist, we probably aren't going to support it. :) Also this issue is specifically about JS in `script` tags, not about generic `script` tags.

As for number two, I never saw unescaped HTML comments in JS cause trouble. I'd be really curious to look at such a case. Looks like unneeded overcautiousness to me.

**Comment by thorn0** [comment]
Found another bug, which also exists on master. Not sure I'll have time to look into it. Most probably I'll open a separate issue.

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUB6AVAAgAkAVAWQBl9dt8ADAHgEIBaZ-AIwEMAnARn1YA+Dj3xNWI7gCYBzQbQCUAbhAAaEBAAOMAJbQAzslA9uEAO4AFHgkMpOANwg6AJmpDtunMAGs4MAMqaXjpQAObIMNwArnDqABYwALYANgDqcTrw+kFgcP42mTr2mQCeyOD6huoh+nDcMBaeoYmcyKicybXqAFb6AB4AQp4+fv6ciXDkIXBtHV0gvX3+IaHJcACKURDws52xIEHctdzlXOwlydBumtwhMKkuMHHIABwADOo3ELWpnprlNzgx3sM3UAEctvBGlpbCBOPpmFA4HBnCi3Nw4BCdBjGpxmq0kO09upaokdBFovt9Cs1pttjNCXN9jBOOwHs4nsgpOpIpwdMkVgBhCCJFrlKDQUEgKK1Yis2xE2oAXyVQA)
```sh
--parser babylon
```

**Input:**
```jsx
foo(/* HTML */ `<!-- bar1 --> bar <!-- bar2 -->`);
```

**Output:**
```jsx
foo(
  /* HTML */ `
    <!-- bar1 -->
    bar
    <!-- bar2 -->
  `
);

```

**Second Output:**
```jsx
foo(/* HTML */ `
  <!-- bar1 -->
  bar
  <!-- bar2 -->
`);

```

**Pull request merged**
