### PR TITLE
Add support for timeouts passed as integers to test functions

### LINKED ISSUE #5061: `it()` calls with a timeout are indented
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLGAKA5ACQIZQAmANnAM4AEeMFpeZNAjAAwDWFArrAE55itxCFAGapSlAO7oAFhA41heMaigBzLABoqZAJ5QwFDAEoKAXgB8FYAB0oFCtLjFiEY7YC+WgEwBWZv6MQDRAIAAcYVGgyZFA8bm4ICQAFOIRolDwANwhUQiCQACNefjgYAGVQvhVVZBhuDjhglTI4bhgk3lUAWzxkRWIW4IArMgAPACFigXK8LrgAGRU4PrwBxpBK7hbuZEK8Ap0XKHzQ7hUYAHVcmGlkAA5mYNOIFoveUN3T8lbM5eDuOAARw4qABHTw3V6SH6gxALS6qFq9XWZGqpAAihwIPAVmtgjB9ldCDdkF58bxlGoAMIQLo9XZQaB-EAcFoAFX26RhcHc7iAA)
```sh
--parser babylon
```

**Input:**
```jsx
it('Handles at least 10k untracked files without failing', async () => {
  hello()
}, 25000)
```

**Output:**
```jsx
it(
  "Handles at least 10k untracked files without failing",
  async () => {
    hello();
  },
  25000
);

```

**Expected behavior:**

Same as input?

Encountered in https://github.com/desktop/desktop/pull/5528.

### PR DESCRIPTION
**Pull request by j-f1**
- [x] I’ve added tests to confirm my change works.
- (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

Fixes #5061

### CODE REVIEW

**Comment by niieani** [comment]
Why was this added? What's the reasoning? There's nothing meaningful in #5051. I much prefer the standard, consistent formatting to the new, custom formatting.

**Comment by duailibe** [comment]
@niieani to keep consistent with how we format other tests

**Before**

```js
it('name of a test', () => {
  // code
});
it(
  'name of another test',
  () => {
    // code
  },
  200
);
```

**Now**

```js
it('name of a test', () => {
  // code
});
it('name of another test', () => {
  // code
}, 200);
```

**Comment by niieani** [comment]
Why do we format tests using a separate logic altogether?
I find default output much more readable. You can see at a glance which argument of the function is being passed into `it`. The new behavior has this odd trailing `}, 200)` is hard to read and looks really ugly.

**Comment by j-f1** [comment]
@niieani IMO that conditional is bad practice — your tests should always be static. Both sides of the ternary will format properly:

**Prettier pr-5366**
[Playground link](https://deploy-preview-5366--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBLGAKAOlABLgcigEMBbOXCAM12KghgAs4AnXeAZxgIBod8MASlwBeAHy5g-fLgD0s3JAAmcaQF8+eXACYADLpyCA3DnQA6DgGtUAB2xaiZCtVr0mrdnC69pQ0RKktfHlFCBV1TXw9AyhjHBAeEAgbGFRoDmRQYhYWCAB3AAVshAyUYgA3CFQlBJAAIxZiMEs4GABlGybUKABzZBgWAFc4RMYYUgAbAHVGdC9OsDg2kvRUcvQAT2RwDgzE7o5WGALGntJiZCpiCcPEgCsOAA8AIUbm1ranABluuEvr24gB6PNrdHoTOAARUGDD+SCuNxGIE6LEOLG2dWIdQ2E2gtRsLG6MCm1SYyAAHLpEgSIIcpo0bNsCV5WOU-okWHAAI6DVCck7EM4XeEApGHUiofpDMVgiHQ2H-RGJGBYklKMlIbTKxqoCZggDCEFI5229Cg7JAg0OABUsaUEYc1GogA)
```sh
--parser babylon
```

**Output:**
```jsx
it("name of another test", () => {
  // code
}, 200);
it.skip("name of another test", () => {
  // code
}, 200);

```

Also, people will typically have many tests, so it’s more important IMO to keep the test code unindented than to have the `() => {` section readable.

**Pull request merged**
