### PR TITLE
feat(markdown): respect tabWidth for list items

### LINKED ISSUE #3459: Markdown: Preserve code blocks within list items
**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgMIAsCGUA5nJjBJgJ4QCuATprhALakAmAlnXGOXZUgA6UYZjHixYNsOEAmLABkOAZxhlcpSLAQxlQkVAkSANsswBaY8JAAaEBAAOMDtGXJQ+OnQgB3AAqeCG4o+ABuEBxstiD4qsgAZvimcHYARnT4YADWcDAAyg6ZHMTIMHQ0KSBsEGAJScqVxQ10MH4ZRMz4dcl2AFbKAB4AQhnZuXn4rEpQcN0NdrQwDjQwsnOVhXTNyCCddFnVPlDRDnTFMADqkTC4yAAcAAx2pxANFxkOO6dwzaGzdtwAI40LhwNr4DpdJCJHogBrMDilcqVZTFIjGOAARRoEHg6zsMHwqSubBuyFkBIyHGMaOwLE6Oyg0H+IBoDQAKkTgjCGgBfXlAA)
```sh
--parser markdown
```

**Input:**

Code blocks may be nested within list items per the original [Markdown syntax for lists](https://daringfireball.net/projects/markdown/syntax#list):

> To put a code block within a list item, the code block needs to be indented twice 
> — 8 spaces or two tabs:

```markdown
1. Change to your home directory:

········cd

2. List the contents:

········ls -l

```

**Output:**

Prettier strips the 8 leading spaces and replaces them with 3 to align with the list item content:

```markdown
1. Change to your home directory:

···cd

2. List the contents:

···ls -l

```

This treats the nested code blocks as subsequent paragraphs in the list items rather than as code blocks:

1. Change to your home directory:

   cd

2. List the contents:

   ls -l

**Expected behavior:**

The original input should either be preserved, indented with tabs or fenced to ensure the nested code blocks are rendered properly:

1. Change to your home directory:

       cd

2. List the contents:

       ls -l

## Subsequent runs change result

If the nested code blocks are indented with 2 tabs (rather than 8 spaces), they are initially converted to 7 spaces. If the same file is saved again, the 7 spaces are converted to 3 spaces.

## Fenced code blocks as workaround

If the nested code blocks are fenced, the input is preserved and output is generated as expected:

~~~markdown

1. Change to your home directory:

   ```sh
   cd
   ```

2. List the contents:

   ```sh
   ls -l
   ```
~~~

### PR DESCRIPTION
**Pull request by ikatyang**
Context: https://github.com/prettier/prettier/issues/3459#issuecomment-366382620

This PR improves the indenting experience in VSCode (probably other editors as well) and also fixes #3459, I'm not sure if this is the proper fix but at least we can see the result and decide if it should be closed/merged.

- align list prefix with `tabWidth`
- it only affect ordered lists if `tabWidth: 2`, otherwise all lists.

vscode indent demo

cc @kachkaev

---

**Prettier pr-3990**
[Playground link](https://deploy-preview-3990--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBGAdAAgMIAsCGUA5nJjBJgJ4QCuATprhALakAmAlnXGOXZUgA6UYZjHixYNsOEAmLABkOAZxhlcpSLAQxlQkVAkSANsswBaYyAA0ICAAcYHaMuSh8dOhADuABQ8Irij4AG4QHGw2IPiqyABm+KZwtgBGdPhgANZwMADK9hkcxMgwdDTJIGwQYPGJyhVF9XQwvulEzPi1SbYAVsoAHgBC6Vk5ufisSlBwXfW2tDD2NDCyJWUVBXRNyCAddJlV3lBR9nRFMADqETC4yAAcAAy2pxD1F+n2O6dwTSEzttwAI40LhwVr4dqdJAJbogerMDhrcq2ZRFIjGOAARRoEHgswqMHwKSubBuyFktlK+A4xjR2BYHR2UGg-xANHqABUiUEYfUAL58oA)
```sh
--parser markdown
```

**Input:**
```markdown
1. Change to your home directory:

        cd

2. List the contents:

        ls -l
```

**Output:**
```markdown
1.  Change to your home directory:

        cd

2.  List the contents:

        ls -l

```

### CODE REVIEW

**Comment by kachkaev** [comment]
Thank you for this PR @ikatyang! I pasted a part of the document I [had problems with](https://github.com/prettier/prettier/issues/3459#issuecomment-366382620) into your playground and the output was much better! No three spaces any more! This means that the preview won't be broken on GitHub/GitHub and that my text editor won't go crazy when I `select` + `tab`!

One last thing I'm not sure how to configure is using `--tab-width=4` for markdowns and `--tab-width=2` for js/ts stuff. But that's minor compared to the problem with three spaces in ordered lists!

**Comment by ikatyang** [comment]
> One last thing I'm not sure how to configure is using `--tab-width=4` for markdowns and `--tab-width=2` for js/ts stuff. But that's minor compared to the problem with three spaces in ordered lists!

See https://prettier.io/docs/en/configuration.html#configuration-overrides, or if you're talking about js/ts code block in markdown, it's currently not supported.

**Comment by kachkaev** [comment]
That's exactly what I needed, thanks! ❤️

**Comment by kachkaev** [comment]
Really looking forward to go for this `prettier.config.js` in my future TypeScript projects!

```js
module.exports = {
  trailingComma: "all",
  arrowParens: "always",
  tabWidth: 2, // default
  overrides: [
    {
      files: "*.md",
      options: {
        tabWidth: 4,
      },
    },
  ],
};
```
As mentioned in https://github.com/prettier/prettier/issues/3459#issuecomment-366382620, a huge bonus of having `tabWidth: 4` in markdown is that unordered lists have the same indent as the ordered ones. This makes it easy to change the type of a list without worrying about getting a huge git diff, just because intents are different!

**Comment by kachkaev** [comment]
@ikatyang who would be the best people to review this? Shall we ping them?

**Comment by ikatyang** [comment]
cc @azz

**Comment by kachkaev** [comment]
Perfect, thank you! Are you planning to fit this change into the upcoming 1.11? That would be awesome, I can't wait 🙌  😃

**Comment by azz** [comment]
Yes it will be in 1.11.

**Comment by suchipi** [comment]
@azz could you add this to my changelog PR?

**Comment by kachkaev** [comment]
Just upgraded to 1.11 and all worked! Thank you so much @ikatyang for responding to my concerns in https://github.com/prettier/prettier/issues/3459#issuecomment-366382620 so quickly and to the rest of the team for such a great work on a new release! To be honest, when I saw three spaces in my markdown after prettier went through it, I thought I'd need to enter a long and hard debate because 2/4 spaces would be a breaking change. However, the ease and the speed with which the change went through ended up beyond my even the most optimistic expectations!

You all rock! 🗿 😄

**Pull request merged**
