### PR TITLE
Support TypeScript 3.7 (using a fork of typescript-estree)

### LINKED ISSUE #6569: [Typescript] Prettier removes question mark from optional computed class property
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAjAhgJ0wF5MByPfUgbgB0owAbXNNTAMQgk2Dsz8wDaFALoB+WlH6CAjGIlSB5XAC9ScugF86IADQgIABxgBLdMlAF8EAO4AFAgjTIQuAG4RjAE10hs+XGAA1nAwAMoGAcZQAObIMPgArnB6ABYwALYMAOopxvBoEWBwoY55xq55AJ7OYCw+UWhw+DC2-tHpuMgAZrgMjXoAVmgAHgBC-kEhobjpcAAyUXDdvf0gQ8OhUdEMcACKCRDwy33JIBH4jfjOMJUGcGhg+MZGPgZPsFleMCnIABwADHo3hBGll-AZnG97k1XEs9ABHA7wVqGJwoZgAWigcDgnlxPnwcERxkJrVw7U6SB6Jz0jXSxjiiVOaC2O32hyWVJWpxguGwn0832QACY9PFcMYGFsAMIQdIdZxQaBwkAJRoAFT5aOpjQ0GiAA)
```sh
--parser typescript
```

**Input:**
```tsx
const bar = 'bar';
class Foo {
    [bar]?;
    [1]?;
    ['baz']?;
}

```

**Output:**
```tsx
const bar = "bar";
class Foo {
  [bar];
  [1]?;
  ["baz"]?;
}

```

**Expected behavior:**
Prettier should preserve ? in output. Expected output:
```tsx
const bar = "bar";

class Foo {
  [bar]?;
  [1]?;
  ["baz"]?;
}

```

This only happens when the computed property is a variable.

### LINKED ISSUE #6574: [TypeScript 3.7] add support for `asserts` keyword
**Prettier 1.18.2**

TypeScript is developing support for [assertions in control flow analysis](https://github.com/microsoft/TypeScript/pull/32695). The functionality is now available in development builds such as [v3.7.0-dev.20190928](https://www.npmjs.com/package/typescript/v/3.7.0-dev.20190928). This ticket requests enabling Prettier support of the new `asserts` keyword.

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAhgM7FwBOMAFAG6EA26cS+mA1lBAO5QCULJMpWL46jOPmAAdKPnwwAFuW74ocLvgCi5ZeSq8ZAXxkgANCAgAHXNGLJQhHdwAKjhHZSEaEHABMzIABG5IRgbHAwAMqWoThQAObIMORM5gowALb0AOoKOPDEMWBwke75ODT5AJ7I4KQBcUIwziHxGYTIqAxk5gBWxAAeAEIhYRGRhBlwADJxcJ3dcH2DkXHx9HAAiugQ8Av0PSAx5EK1MFWWcMRg5DjWAZa3sNl+isgAHAAM5o8QZNkhSy1R5XCg0ebmACOO3gLSsHhAJAAtGo4L40QFyHBoTgsS1CG0OkgugcliAyBkcEkUmTiGsNttdvNiYtzDBCIEXr43kgAExskI4ehrADCEAy7VqnDUAXQZAAKhyPCSyIZDEA)
```sh
--parser typescript
```

**Input:**
```tsx
function assert(value: unknown): asserts value {
  throw new Error()
}
```

**Output:**
```tsx
SyntaxError: '{' or ';' expected. (1:42)
> 1 | function assert(value: unknown): asserts value {
    |                                          ^
  2 |   throw new Error()
  3 | }
  4 | 
```

**Expected behavior:**
```tsx
function assert(value: unknown): asserts value {
  throw new Error()
}
```

### LINKED ISSUE #6595: [TypeScript 3.7] add support for optional chaining
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI

**Steps to reproduce:**
I was able to reproduce in the playground when using the typescript parser, which I guess it's the parser that ends up being used by prettier in typescript files? In my case its happening for both `.ts` and `.tsx` file extensions.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAdAIwPzrCAGhAgAcYBLaAZ2VFQCd6IB3ABQYRpVQDcJyAJoRCZ6qMAGs4MAMolx5KAHNkMegFc4RABYwAtgBsA6tvLwq8sHBmcz5HmYCeycFRpFFVOPRisxSvVRkADNUAy8iACsqAA8AITFJaRlUPTgAGUU4ELCIkGiYmUUlAzgARXUIeBzwrRB5ei96FxhHEjgqMHpyMmESbtgjQRhtZAAOAAYifogvIzESF36O7x5sogBHSvg-Ui40KgBaKDg4ATPhejgt8iu-VACgpFDaoi89clUNOqpi0oqqtlnrk6jBUJghgIRsgAExENSocgGYoAYQgekCLig0HWIHUXgAKuCuC8vABfMlAA

**Expected behavior:** does not throw "Expression expected" syntax error when using optional chaining in typescript files

**Actual behavior:** throw "Expression expected" syntax error when using optional chaining in typescript files

### LINKED ISSUE #6609: [TypeScript 3.7] add support for nullish coalescing operator
**Prettier 1.18.2**

**Input:**
```jsx
const a = null
console.log(a ?? "keque")
```

**Output:**
```
[error] src/index.tsx: SyntaxError: Expression expected. (8:16)
[error]    6 | 
[error]    7 | const a = null
[error] >  8 | console.log(a ?? "keque")
[error]      |                ^
[error]    9 | 
```

**Expected behavior:**
Should understand or at least ignore such expression.

### PR DESCRIPTION
**Pull request by fisker**
Test code is from #6657 (by Cryrivers), replace `@typescript-eslint/typescript-estree` v2.4.0 with my fork version that works for node 4

- Optional Chaining (Fixes #6595)
- Null Coalescing (Fixes #6609)
- `asserts` keyword (Fixes #6574)
- optional computed class property (Fixes  #6569) , was fixed in  #6601 with same solution

I suggest we use my fork until prettier starting v2.0.0(will drop node 6 support https://github.com/prettier/prettier/issues/3919), since many people want Typescript 3.7 support. we can switch back anytime

Yesterday, I saw someone from `typescript-eslint` team says they may try to bring node 6 support back, hope it's true.

My build script can be found on https://github.com/fisker/typescript-estree-for-node-6 , repo is a little mess now

- script: https://github.com/fisker/typescript-estree-for-node-6/blob/9d59ec8e0a8204819d0822b6fac136fda6d3f339/package.json#L14-L16
- rollup config https://github.com/fisker/typescript-estree-for-node-6/blob/master/rollup.config.js
- babel config https://github.com/fisker/typescript-estree-for-node-6/blob/master/babel.config.js
- code replace https://github.com/fisker/typescript-estree-for-node-6/blob/master/scripts/fix-code.js
- package.json build https://github.com/fisker/typescript-estree-for-node-6/blob/master/scripts/sync-version.js

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Playground includes all linked issues

https://deploy-preview-6680--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEB6VACA8gBxgS2gEMAbDAYQAsj8paBzDAYgDYBWATjYB0peiAdACMA-ALC9e6DADkAriTLkIpOAGcwDZixYAGDr0hQ1MDEQwBeDFAUlD0NRBJwBJCPQAU5kSIzcQANZwAI5ycP4AlJJQ0kRqanAATjBqGEEAngDuEIkAJtpsAOwALLwAZnJQYATQZvFJMB4AbqRhSBiVAVAQmVAR7XEJyaktJGEYwLwYGDCUiT3WcJkYAKKJ84keUVAAvtHSEHiEUKQYkAC2OHLw+WAkgxg48zgN6QUsBlUOpkJEiZYYADkv0SgIA3IZ7vEMAAxCAQCZTaYYADaIIAuiIIbsQAAaECHGrGZCgP7zTIABT+CDUyBARCaEHwuTxICEiSIYCCMAAyjhOQxkDBEmF8ZQYOcSAB1Sj4eBqflgOA8mly-BNOXpOlgeKs2hDGAUjn0c5EZBlUgJfEAKzUAA8AEIcrlwXlEc5wAAytDg5stcBt9p5DGcAEU5BB4H6SFaQPzEkM6TB0i8NIl8HhWU9aDApczZsgABy6fFPCAJKUcnB0p7qJJNX340KRuBGw60lBxAC0UDgcFy-dZiRCcnww6NRBNZqQFpjAZACXO+CFIvnahDcHDLejsZgRCEedyBaQACZ8cKaCQGMpzqa6d1e6y5AkACr7juz2NNMIASSgA9gHkwHTPAAEF-x5ZNnB3OAdh2IA

**Comment by lydell** [comment]
I guess I’m fine with using your fork for now. But if so we should make it the top priority to get 2.0 out after 1.19. A non-ambitious 2.0 where we get rid of all unsupported Node.js versions and remove deprecated stuff and other small breaking changes.

**Comment by damiangreen** [comment]
How do i add your fork as a dpendency? 
I tried `yarn add https://github.com/fisker/prettier/tree/typescript-37-attempt-2`
but received 
`error https://github.com/fisker/prettier/tree/typescript-37-attempt-2: Extracting tar content of undefined failed, the file appears to be corrupt: "Invalid tar header. Maybe the tar is corrupted or it needs to be gunzipped?"`

**Comment by thorn0** [comment]
@damiangreen Try [this PR](https://github.com/prettier/prettier/pull/6657) instead. If it's still reproduced, please post a snippet of your code to that PR.

**Comment by thorn0** [comment]
As we're moving forward with #6657, it's time to close this PR.

Thank you for your work and research @fisker!

**Comment by damiangreen** [comment]
@thorn0  that fixed it thanks!

**Pull request closed without merging**
