### PR TITLE
[NotForCommit] Put \n before else

### PR DESCRIPTION
**Pull request by vjeux**
Just to show @vishnevskiy how to fork prettier to let him push prettier on his codebase.

### CODE REVIEW

**Comment by rhengles** [comment]
@vishnevskiy Implemented in https://github.com/arijs/prettier-with-tabs/commit/72df0af615af43f616da7a1b68fa42ed98e43d4d as `breakBeforeElse` option 😊

**Comment by kylpo** [comment]
👍 to a `breakBeforeElse` option! It is the last thing keeping me from really considering prettier. jlongster would also likely appreciate this: https://twitter.com/jlongster/status/834407714965057540.

**Comment by jlongster** [comment]
I'd really like to avoid another configuration option, but I am in favor of adding a newline.

Are there others that really really strongly that `else` should be on the same line as the brace? The only argument I've heard is to save vertical space but that's not a very strong argument, as I think it's much more clear on its own line and it doesn't add much vertical space (it's not like expanding an array or something)

**Comment by vjeux** [comment]
Going to close this one, we can keep talking about it on the issue.

**Pull request closed without merging**
