### PR TITLE
Use `import()` for postcss parsers

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by fisker — APPROVED** [review]

**Comment by fisker** [comment]
Can check all the packages to see if we can import a specific entry instead of whole package?

**Comment by fisker** [comment]
I think this part need update too. https://github.com/prettier/prettier/blob/7d74e821e0c110d20eeb97c4596eb4efd96cfdf3/scripts/build/config.mjs#L220

**Comment by sosukesuzuki** [comment]
We need to check other bundle optimizations still working well after migrating ESM later.

**Review by fisker — APPROVED** [review]
Good job!

**Pull request merged**
