### PR TITLE
markdown: Preserve inline code line breaks if --prose-wrap=preserve

### LINKED ISSUE #11372: --prose-wrap=preserve should preserve line breaks in Markdown inline code spans
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAZCAnOBbABASwAcBnAVzwBMIAbTXY-GXAQ2zhgBpdIpi4x4MUhhYUi+YmHxQA5rjjVGXPhVxV5+UsWwRVAA3jZCmADpRpUsRVKw9uUk2rMARpjjymVWllzZmMqGYWRQBHUmYAOlwAVSYEfDxmVWxpBNwAN3jWLj0wiTMoCGIYDFIKOzgADzgMKRhmGHxoe2onbEhcJ1cMCVxzBnsmZlDSInlK+SDIbB11PR4+MIaIswARUeI7Zgd3fFKfLzppXCxCLAALBAoaxgIoDJpSQnr4DIVbuGI+bnxW8jUaG5cHo4KQzAAzUgyfANOxQUitIKEZg9BrCKIAUUqYDgz1BIgYsFwEDAYGY-Aa3Ce+AoDUphXuZwgNIQnHoNiY0jMYARyNweWJ4PB+CkQWufFKRJ0rVuzHMeBp8mKnRcmHIERAHBAEGeTV4yFAKIwEAA7gAFFEIYjIEDDE3MACe1q1zgwzDAAGt2ABlZFSWTIEqkOBanDOOAUa4UVBymThGRwABimD8MEaAZQ2xgEE1IHOMGw1AA6udGJ8-XBvVbGPh0owHTawF9c9IJTAzW6ZH5kODhnwtQArYiVABCbs9PtYcFQ0jgPb7IZAQ8q3ukMmocAAiqQIPB59R+yBkRgJTa-BgPVQTVBc2dpDAizSYOdkAAOAAMWqZfCLbsINrOT4akyXMwl3OAOx1a1M2IABaKA4AjCNcywPIsA7fxuyQXsD0XPgUkDUo8LXDdt3A-dD3qZxHwoZ9kAAJi1EpmF+NcAGEIBmZgbU+ABWXMtDgAAVFxoJww90mDABJKBrlgb0wB6Z4AEFZO9GAHQ3Ci4AAXx0oA)

```sh
--parser markdown
```

**Input:**

```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod `tempor
incididunt` ut labore et dolore magna aliqua. Ut enim ad minim veniam, `quis
nostrud` exercitation ullamco laboris nisi ut aliquip ex ea commodo `consequat.
Duis` aute irure dolor in reprehenderit in voluptate velit esse cillum dolore `eu
fugiat` nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.
```

**Output:**

```markdown
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod `tempor incididunt` ut labore et dolore magna aliqua. Ut enim ad minim veniam, `quis nostrud` exercitation ullamco laboris nisi ut aliquip ex ea commodo `consequat. Duis` aute irure dolor in reprehenderit in voluptate velit esse cillum dolore `eu fugiat` nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in
culpa qui officia deserunt mollit anim id est laborum.

```

**Expected behavior:**

This input should not be changed. Even though the line breaks are not significant to the output, their removal results in extremely long source lines that make editing unpleasant.

One can of course manually rewrap paragraphs to avoid line breaks inside code spans, but that means fighting against the default behavior of the automatic rewrap function in most editors.

This isn’t an issue when Prettier is given charge of wrapping (`--prose-wrap=always` or `--prose-wrap=never`), but with the default `--prose-wrap=preserve`, Prettier should preserve the existing line breaks inside inline code spans.

### PR DESCRIPTION
**Pull request by andersk**
## Description

Fixes #11372.

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by ulwlu** [comment]
This is very helpful for two reasons. Not only the fact it makes mdfiles easier to see, but also it works well with markdownlint, since markdownlint will consider inline code-blocks as usual line-length.

Hope this gets merged soon.

**Comment by andersk** [comment]
Still waiting for a maintainer to look at this very simple bug fix (3 lines plus tests).

Here’s a sample from the actual buggy change that Prettier wanted to apply to the Zulip documentation, which motivated this fix. Before:

```markdown
(The `--config pull.rebase` option configures Git so that `git pull`
will behave like `git pull --rebase` by default.  Using `git pull
--rebase` to update your changes to resolve merge conflicts is
expected by essentially all of open source projects, including Zulip.
You can also set that option after cloning using `git config --add
pull.rebase true`, or just be careful to always run `git pull
--rebase`, never `git pull`).
```

Prettier 2.7.1:

```markdown
(The `--config pull.rebase` option configures Git so that `git pull`
will behave like `git pull --rebase` by default. Using `git pull --rebase` to update your changes to resolve merge conflicts is
expected by essentially all of open source projects, including Zulip.
You can also set that option after cloning using `git config --add pull.rebase true`, or just be careful to always run `git pull --rebase`, never `git pull`).
```

With this fix:

```markdown
(The `--config pull.rebase` option configures Git so that `git pull`
will behave like `git pull --rebase` by default.  Using `git pull
--rebase` to update your changes to resolve merge conflicts is
expected by essentially all of open source projects, including Zulip.
You can also set that option after cloning using `git config --add
pull.rebase true`, or just be careful to always run `git pull
--rebase`, never `git pull`).
```

**Comment by thorn0** [comment]
```js
return { ...node, value: node.value.replace(/\s+/g, " ") };
```
Turns out this replacement isn't correct at all. See https://github.com/prettier/prettier/issues/13485#issuecomment-1255596695
Your fix is correct, but it fixes only a special case of the incorrect behavior.
Could you also fix this regexp for the `proseWrap !== 'preserve'` case and reflect that in the changelog?

**Review by thorn0 — APPROVED** [review]
Let's do https://github.com/prettier/prettier/pull/11373#issuecomment-1255605458 in another PR

**Review by fisker — APPROVED** [review]
I never saw this PR in my inbox..  

Let's merge this separately, no need wait for #13590

**Comment by thorn0** [comment]
Okay, but there will be a conflict.

**Comment by kachkaev** [comment]
Hmmm this PR has been merged to `main`. What’s the best way to move these changes to the `next` branch?

**Comment by kachkaev** [comment]
Thanks @andersk! I’ve incorporated your change into https://github.com/prettier/prettier/pull/13590 👍

**Pull request merged**
