### PR TITLE
fix(js) Don't break a long nested bin as an argument (#5172)

### PR DESCRIPTION
**Pull request by onurtemizkan**
Fixes: #5172 

This fix applies to `CallExpression` arguments. I haven't figured out the case mentioned in https://github.com/prettier/prettier/issues/5172#issuecomment-528282033 for `SequenceExpression`s yet, because the expected parenthesis-breaking behavior for `SequenceExpression`s seems to be different than `CallExpression`s.

Playground Example: [`CallExpression`](https://prettier.io/playground/#N4Igxg9gdgLgprEAucBDANugFAHSjmAMwFcowYBLaLASgAJgAnOGYxqAXwBo866CSZStXpMWbTnhoBuEFxAQADsKgBnZKFSNGEAO4AFLQnUpUANwgUAJnJAAjRqjABrFgGVFTilADmyGIzEcPIAFjAAtugA6iEU8KqeYHBuxnEUZnEAnsjgqury3qpwjDD6jj7hqMiEGEXyAFaqAB4AQo4u7qjhcAAy3nDVtcEgjU1u3j7ocACKxBDwg+h1IJ6MRYw5dqh2cOi2iozeMFHWMCHIABwADPIHEEVRjoo5B3DrZgPyAI5z8GVKJhAqFUAFooHA4FZIbZmD8KMwyqgKlUkDUlsMiuEKP5AhiJlNZvMBqihvIYNsTlYzsgAExkxwUdATADCEHClRyUGgnxAxCKABVtiY0UUOBwgA), [`SequenceExpression`](
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKAOldMBmBXKMGAS2lQEoACYAJzhjxqgF8AaTSy7fQksq2vUYtM5ANwhWICAAc+UAM7JQAQxo0IAdwAKahEpQqAbhGIATSSABGNFWADW9AMoy7xKAHNkMGnjhSACxgAWwAbAHUA4ngFVzA4J31o4iNogE9kcAUlKXcFOBoYbVsPYJVkHBVQ-KkAKwUADwAhWwdnFWC4ABl3OAqqmpB6hqd3D1C4AEU8CHh+6v8QVxp8mkyrFSs4UMsZGncYcPMYAOQADgAGKT2IfPDbGUy9uFWjPqkARxn4YtkDEBUCgAtFA4HAzODLHQvsQ6MUVKVykhKgspPlgsRvL5FgoxhNprM+siBosYJsjmYTsgAExSHwqYihMYAYQgwTKmSg0HeIDw+QAKpsDCj8sxmEA)

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
Why did you remove the playground link from the PR template?

**Comment by thorn0** [comment]
#5172 is specifically about long expressions, but this PR changes the output for short expressions too. And it's really unclear why exactly `$var ?? "test"` and `$var + "test"` should be treated differently. 

**Prettier pr-6792**
[Playground link](https://deploy-preview-6792--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAucBDANugFAMwK5RgwCW0WAlAATAA6UllATnDHo-QIwDcdAvgDSUAJADdUjSgH5JlGiHgBnGHPI8odMBmz5CJMlVr0mLNpzUDhYiQGpZ8uEpVcQ-EBAAOeqAuShxjCAB3AAVxBB8UVBEIYgATFxAAI0ZUMABrFgBld1TiKABzZBhGPDhXAAsYAFt0AHVy4kUcsDhM8MbiEUaAT2RwBR9XPIU4RhhglPyq1GQcDBHXACsFAA8AIRT0rNQquAAZPLhZ+bKQZZXMvPz0OABFPAh4Y-QFkBzGEcY+mG73BzBGMRPAl3IDYLU4jBysgABwABlcoIgI1qKXcfVBDlGIiOrgAjg94BMPBEQKgFABaKBwOCxWkJZgE4jMCaoKYzJBzF6nEZVYhFEo8q43e6PI6ck6uGCoRIQ2JQ5AAJilKWI6CuAGEIFVpn0oNBcSA8CMACoyiJc14iUoASSgdNgmQBQJgAEF7ZkfjdniNeLwgA)
```sh
--parser typescript
```

**Input:**
```tsx
call(function() {
  return 1;
}, $var ?? "test");

call(function() {
  return 1;
}, $var + "test");
```

**Output:**
```tsx
call(
  function() {
    return 1;
  },
  $var ?? "test"
);

call(function() {
  return 1;
}, $var + "test");

```

**Comment by onurtemizkan** [comment]
Thanks for the review, sorry I added the playground redirect to the post.

> #5172 is specifically about long expressions, but this PR changes the output for short expressions too. And it's really unclear why exactly `$var ?? "test"` and `$var + "test"` should be treated differently.

Working on this now.  My first intention was to make `LogicalExpression`s to behave like `FunctionExpression`s, which seemed to create both issues you mentioned. So just to clarify; is this PR supposed to fix behavior for both long `LogicalExpression`s and `BinaryExpression`s which have similar outputs currently?

[Playground link (master)](https://prettier.io/playground/#N4Igxg9gdgLgprEAucBDANugFAMwK5RgwCW0WAlAATAA6UllATnDHo-QIwDcdAvgDSUAJADdUjSgH5JwsROmzxUmaKULV8lXOWLNunRp00Q8AM4xj5HlDpgM2fIRJkqtekxZtO1gfoDU-oGGAcFB2iHhYUoBxmYWIFZ0IPwgEAAOzlCmyKDijBAA7gAK4gjZKKgiEMQAJskgAEaMqGAA1iwAymktxFAA5sgwjHhwKQAWMAC26ADqY8Rm3WBwHWULxCILAJ7I4KbZKb2mcIwwRc19k6jIOBjHKQBWpgAeAELNbZ2ok3AAMr1wG53UYgJ7PDq9ProOAARTwEHgQPQ9xA3UYx0YuwaqAacHQ9TSjF6MBmtRgY2QAA4AAwpQkQY4zZppXaEuAYkSAlIAR3h8HO6XKIFQpgAtFA4HAalL6sxecRmOdUJdrkhbsiQcdJsRBsNNZDoXCEYC1cCUjAcaSauTkAAmc3NYjoSEAYQgkyuuyg0C5IDwxwAKjjyurjrxeEA)

Also, do you have any comments on the formatting of `SequenceExpressions`? The current output looks weird. For consistency, the `expression`s inside `SequenceExpressions` may be handled equally like `arguments` inside `CallExpressions`. What do you think?

**Comment by thorn0** [comment]
The issue should be fixed for all kinds of binary expressions, but short expressions should not be affected.

**Comment by thorn0** [comment]
Doing a clean up of stale PRs, closing this. It's linked to the issue so we can revive it if necessary.

**Pull request closed without merging**
