### PR TITLE
Remove `index.js` and `standalone.js ` links

### PR DESCRIPTION
**Pull request by fisker**
These two files are created in #5054

> `/index.js` and `/standalone.js` are preserved as links to not break builds that's installed from git.

### `/index.js`

With updating `main` field in `package.json`, removing `/index.js` won't break `require('prettier')`, unless someone use `require('prettier/index')`.

### `/standalone.js`

People use `require('prettier/standalone')` ? If this is considered breaking change, it's good chance to do this in v2.0.0

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by j-f1** [comment]
Using `prettier/standalone` is recommended in [our browser docs](https://prettier.io/docs/en/browser.html).

**Comment by fisker** [comment]
But that's accessing from bundles right? So remove this file won't break it.

**Comment by j-f1** [comment]
Ah, yes. Good point!

**Comment by thorn0** [comment]
What if someone wants to install Prettier from GitHub AND use it for a browser application via a bundler? That's what `standalone.js` in the root is for, I guess. But we can probably just use the `browser` field in `package.json` instead. And overall, we should check if this scenario works and decide if we want to support it.

**Comment by fisker** [comment]
Closing since we support install from github.

**Pull request closed without merging**
