### PR TITLE
CSS: Every selector is now printed in its own line

### LINKED ISSUE #1962: [Prettier CSS] Multi-line comma separated selectors
I think in terms of legibility, multi-lining comma separated selectors is much more readable.  Could this be the default?

## Example of desired effect:
```css
.ball, 
.rabbit,
.wrapper:hover .contents,
.wrapper:active .contents {
  color: red;
}
```

## What prettier currently emits:
```css
.ball, .rabbit, .wrapper:hover .contents, .wrapper:active .contents {
  color: red;
}
```

The single line approach usually ends up creating really long lines that require horizontal scrolling and break n characters per line conventions (usually 80 or 120).

### PR DESCRIPTION
**Pull request by yuchi**
Changes the behaviour for line breaking inside selector lists (those separated by ',') so that every selector is in its own line.

Fixes #1962 and supersedes #2022

### CODE REVIEW

**Comment by yuchi** [comment]
@vjeux Is this ok?

**Comment by vjeux** [comment]
Thanks!

**Comment by dzhytomyrsky** [comment]
Is it now in npm package?

**Comment by GianBe** [comment]
@dzhytomyrsky It should be in version 1.4.4

**Comment by dzhytomyrsky** [comment]
Looks like it is not there, I still get scss-lint red with "SingleLinePerSelector"

**Comment by vjeux** [comment]
It's not in any release yet. You'll have to wait or use master for now, sorry about this.

**Pull request merged**
