### PR TITLE
Playground: Use template string sample

### PR DESCRIPTION
**Pull request by fisker**
## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
Hi, what do you think the about way of https://github.com/sosukesuzuki/prettier/pull/453 (WIP) ? Prepare the code sample as a text file and import it using webpack.

**Comment by fisker** [comment]
I thought about that before, the esm bundle test need read it, need update that part `tests/integration/__tests__/bundle.js`.

**Comment by sosukesuzuki** [comment]
I know. Personally, I don't think it's a good idea to call CodeSamples under website from `tests/integration/__tests__/bundle.js`...

**Comment by fisker** [comment]
Find another way to test it then.

**Comment by sosukesuzuki** [comment]
I can do it, or you want to do it?

**Comment by fisker** [comment]
You do it.

**Comment by fisker** [comment]
Is it possible to use `fs.readFile` in `codeSamples.js` and still work for playground?

**Pull request closed without merging**
