### PR TITLE
Revert breaking changes related to adding pure css parser for minor releasing

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Context: https://github.com/prettier/prettier/issues/9482#issuecomment-715274870. Changes reverted here will be included in the next major version.

**Reverted changes:**
- #9471 https://github.com/prettier/prettier/commit/bc9db85490706fc362f00d2ef13c32af79f4da9c
- #9210 https://github.com/prettier/prettier/commit/9efeb8309e1b1805fe8c8304ee0ab49eead8dede
- #9209 https://github.com/prettier/prettier/commit/b77da32a808e160617dd8fcc578d14fc39d0b439
- #9093 https://github.com/prettier/prettier/commit/01f986bea959927375e1d551844ca7f50ec6fcff
- #9092 https://github.com/prettier/prettier/commit/c0bca1805de45d5f1aab9628cf45af64e4ef00fc
- #7933 https://github.com/prettier/prettier/commit/589ebf670b8db4b21661fb551ff0b4822f8b63d6

I'm not familiar with these changes so please let me know if you notice any unwanted reverts.

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
@fisker Thanks for fixing build script. Can you review this?

**Review by fisker — APPROVED** [review]

**Comment by sosukesuzuki** [comment]
@evilebottnawi Can you review this?

**Review by evilebottnawi — APPROVED** [review]
Looks good

**Comment by fisker** [comment]
Can you add pr numbers(better with commit messages) to the description? So when we revert this one, we  can  easily track them.

**Pull request merged**
