### PR TITLE
Use `lodash/partition`

### PR DESCRIPTION
**Pull request by fisker**
We have `lodash` now from #7235 , but if 

> Maybe we can remove lodash in future? Should be not hard

https://github.com/prettier/prettier/pull/7235#pullrequestreview-340606697

Feel free to close this PR.

@evilebottnawi What do you think?

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
To be honestly I prefer avoid using lodash, but it is a development tool, so size is not matter

**Comment by thorn0** [comment]
I think using popular libraries makes the project more contributor-friendly.

**Comment by evilebottnawi** [comment]
@thorn0 yes, but we don't use a lot of functions/helpers/etc from lodash so we can reduce package size

**Comment by thorn0** [comment]
I guess it's included anyway in Prettier's dependencies.

**Pull request merged**
