### PR TITLE
cleanup: remove extra parent.object conditions

### PR DESCRIPTION
**Pull request by brodybits**
from src/language-js/needs-parens.js

(seems to be not needed)

- ~~I’ve added tests to confirm my change works.~~
- ~~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)~~
- ~~(If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.~~
- ~~I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).~~

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Very bad idea,I'm on cellphone, but I'm almost sure there are needed, just not covered. MemberExpression have `.property` child.

We should add tests.

**Review by thorn0 — APPROVED** [review]

**Comment by fisker** [comment]
@thorn0 You think is not needed?

**Comment by thorn0** [comment]
Yes. `name === "object"` and `parent.object === node` check the same thing.

**Comment by fisker** [comment]
Oh, yes, you're right, I didn't check what name is. 

Sorry about this @brodybits

**Comment by fisker** [comment]
@brodybits How did you notice that it's not needed?

**Review by fisker — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]

**Comment by brodybits** [comment]
I found one case when comparing changes between a couple forks of Prettier, found the other case from a simple search:)

**Pull request merged**
