### PR TITLE
Add test cases about code embedding in markdown that relates to #15909

### PR DESCRIPTION
**Pull request by seiyab**
https://github.com/prettier/prettier/pull/15909#issuecomment-1908724956
Now I'm sure that every diff shown in https://github.com/prettier/prettier-regression-testing/issues/435#issuecomment-1908695983 is bug fix.

## Checklist

- [ ] ~I’ve added tests to confirm my change works.~
- [ ] ~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).~
- [ ] ~(If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.~
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Can you put these code blocks in separate file and make them "ugly" first?

**Comment by seiyab** [comment]
OK. Does "making them ugly" mean make inputs ugly keeping AST? Or emphasize bug in output tweaking AST?

**Comment by fisker** [comment]
> "making them ugly" 

You can just put two extra lines on top, since we silently fail on embed format, it's not clear the code block is formatted or not.

**Comment by seiyab** [comment]
@fisker 
I splitted and uglified them.

**Review by fisker — APPROVED** [review]

**Comment by fisker** [comment]
Great! Thank you!

**Pull request merged**
