### PR TITLE
Revert "[TypeScript] format TSAsExpression with same logic as BinaryExpression"

### LINKED ISSUE #7956: Regression with TypeScript "as const" object literal in 2.0.3
Playground hasn't updated to 2.0.3 yet, so this link was generated on 2.0.2 playground:

**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAVAmgBQFEB9AWQEF9MBeTYAHSk2cwHIwALAQwCcux4PTABM4ANwCWYOKyRs0ABzhgJXADasANIxZtOvfoMyLlqtZgBmEtTLmsTK9Vp0thEnspgQeATztuPAW8fZyYWVg8AcwBXNV5La1s2KxtQ3TQIMABrOBg7DOzctPC0HwBbACMINSlMGqgs2TZ6xu0oAF9MLjRMSCgMAG5GEE0QCAUYCXRkUF4eCAB3fF4ENGQQdQWuHzXRir5CmABlBX4JKEjkGB5ouFGOGDK1AHUOCXhFfjgj1feJSRgPnWYDQuxA5zQcB4MHwfEiZS4yAs6khowAVmgAB4AIQOOWOXDKcAAMuc4EiUXcQBjMUdzpEbABFaIQeAUtSokCnHiQnjrQFKNBgHgSCYjLki2DPCTCGAcZAADgADKMFPNIc8+Ap1mq4LyxOTRgBHFnwWHjNYoboAWigcDgomE4o8JvccFhXHhiKQyI5VMhZQkVxu-vpTNN5J9lNGMC4FWlsvlSAATDG+NZ6QBhCBlBHrPUAVnF0Uh2Djlt9nLEtwAklBRLAjsLRTByPWjoCbOzIe12kA)
```sh
--parser typescript
```

**Input:**
```tsx
const TYPE_MAP = {
    'character device': 'special',
    'character special file': 'special',
    directory: 'directory',
    'regular file': 'file',
    socket: 'socket',
    'symbolic link': 'link',
} as const;
```

**Output:**
```tsx
const TYPE_MAP = {
  "character device": "special",
  "character special file": "special",
  directory: "directory",
  "regular file": "file",
  socket: "socket",
  "symbolic link": "link",
} as const;

```

**Expected behavior:**

The 2.0.2 behavior (above) is expected, but with 2.0.3, I get:

```tsx
export const LOG_LEVEL =
    {
        EMERGENCY: 0,
        ALERT: 1,
        CRITICAL: 2,
        ERROR: 3,
        WARNING: 4,
        NOTICE: 5,
        INFO: 6,
        DEBUG: 7,
    } as const;
```

Only happens with `as const` qualifier. Without it, formatting continues to be like in 2.0.2:

```tsx
export const LOG_LEVEL = {
    EMERGENCY: 0,
    ALERT: 1,
    CRITICAL: 2,
    ERROR: 3,
    WARNING: 4,
    NOTICE: 5,
    INFO: 6,
    DEBUG: 7,
};
```

### LINKED ISSUE #7957: TypeScript `as` regression (2.0.3)
**Prettier 2.0.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqEEAFAJT7AA6U++ATnDOvbdbXYcQDQ2dcRu-PvgC++AIYBnfADEA8vJqiQ3EBAAOuaFOSgJ9ehADuABQMJdKCQBtjEgJ661AI3oSwAayYBlDR5woAHNkGHp0ODUACxgAWxsAdSiceCl-MDgfSxScADcUh2RwKWcQQKk4ehhTdyDYiWRUWwq1ACspAA8AIXcvXwlYuAAZQLhG5siQdo6fQKCbOABFdAh4cZsWkH96CvoimAcNOCkwehwtVS2z2AScABMYKOQADgAGNQ0jCoT3DSLP46VXJjNQARxW8BqmisIGkAFooHA4HdkZdGOCcIwahI6g0kE0NpMKrEcKFwkS5gtlqsxviJmoYBIXLcHk8kAAmBnuHA2OYAYQgsXqRWOAFZLugKgAVJlWAmbXIRACSUBRsB8p3OMAAgqqfAcFusKqJREA)

```sh
# Options (if any):
--single-quote
```

**Input:**

```ts
function foo() {
  return {
    foo,
    foo,    
  } as FOO
}
```

**Output:**

```ts
function foo() {
  return (
    {
      foo,
      foo,
    } as FOO
  );
}
```

**Expected behavior:**

same as input
```ts
function foo() {
  return {
    foo,
    foo,    
  } as FOO
}
```

### PR DESCRIPTION
**Pull request by thorn0**
Reverts prettier/prettier#7869

fixes #7956
fixes #7957 
reopens #6443

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
@thorn0 I'm sorry that the PR I put out caused a regression. Thanks for the revert.

I was surprised that 2.0.3 was released suddenly. Could you tell me about the release cycle? Even if it was a patch version release, we should have used other source code to check for regressions.

**Comment by thorn0** [comment]
@sosukesuzuki The new major version of the VS Code extension was broken because of https://github.com/prettier/prettier/issues/7949 That's why I made this patch release. But I should've tested it more thoroughly, indeed. :(

**Comment by thorn0** [comment]
Hopefully, we're done with 2.0 regressions and there will be no more 2.0.x releases.

**Comment by wincent** [comment]
Thanks for the quick response on this one @thorn0.

**Pull request merged**
