### PR TITLE
Fix binary expression instanceof in arrow function expression

### LINKED ISSUE #912: Omited parentheses for ObjectExpression of BinaryExpression enclosed into ArrowFunctionExpression
It was reported in another PR by @bakkot https://github.com/prettier/prettier/pull/897#issuecomment-284291864.

Something like:

```js
let a = () => ({} instanceof a);
```

Is currently turned into:

```js
let a = () => {} instanceof a;
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20a%20%3D%20()%20%3D%3E%20(%7B%7D%20instanceof%20a)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

I will create a fix in a few minutes.

### PR DESCRIPTION
**Pull request by yamafaktory**
This should fix #912. It was righteously mentioned by @bakkot.

### CODE REVIEW

**Comment by bakkot** [comment]
I don't think this is the right fix.

Sorry, I should have been more specific: It's not just `instanceof`; that was just an example of a binary operation. All binary operations as the body of an arrow expression need parentheses whenever their left operand is an ObjectExpression, or a binary operation whose left operand is an ObjectExpression, or etc.

**Comment by bakkot** [comment]
Here's some test cases where all of the parentheses are necessary:

```js
a = () => ({} && a);
```

```js
a = () => ({}() && a);
```

```js
a = () => ({} && a && b);
```

```js
a = () => ({} + a);
```

For completeness, some more which prettier also gets right, although mostly by accident:

```js
a = () => ({}.b && a);
```

```js
a = () => ({}[b] && a);
```

```js
a = () => ({}`` && a);
```

```js
a = () => ({} = 0);
```

```js
a = () => ({}, a);
```

**Comment by vjeux** [comment]
cc @jlongster, we have the same problem with nosemi. The AST structure is an awkward tool as the parsing rules depend on the token. Ideally, we'd want to know what is the first token of an arbitrary expression and if it is a `{` then add parenthesis.

**Comment by bakkot** [comment]
@vjeux you also need that for e.g. #917, incidentally.

**Comment by yamafaktory** [comment]
@bakkot If you don't mind I'm going to create a new issue out of your great exhaustive test cases 👍.

**Pull request merged**
