### PR TITLE
Add missing parentheses for `throw expression`

### LINKED ISSUE #10411: Better support for the "`throw` expressions" proposal
Found in #10410

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+wAOlPvqTABYBOEA7vgIwA0+ATOQDctAL4geICAAdc0IslABDFm3YAFFQgUolAG3ZKAngskAjFkrABrODADK0qzigBzZDBbo4kuAFszOAATIOCAGSU3dCVXOAAxCBY-JRhcN2QQJXQYCAkQJhg-PQB1JhxiJzA4e21ynAA3cqMMsCJTEBciOBYYdUtXZORUfS7JACsiAA8AIUsbO3slPzgwlzghkZ8QCcn7F1c9OABFdAh4Db1RkCcWLpYMsyVAvTzpFhcYYpwg5mQADgADJI3hAusVLNIMm84Hd6utJABHU7wPoyHSZIgAWigcGCwTyLDgSJwhL6MUGSGGly2XT8OA8Xhp+0OJzO60pm0kMCeXx+TGQ-C5lhwen2AGEIH4KSAYQBWPLoLoAFSeOipV3q3gAklBQrB7GB3rIAIK6+wwIyHC5dUSiIA)

```sh
--parser babel
```

**Input:**

```jsx
function test() {
  (throw 1, 2);
}
```

**Output:**

```jsx
function test() {
  throw 1, 2;
}

```

**Second Output:**

```jsx
function test() {
  throw (1, 2);
}

```

**Expected behavior:**

Should not change AST.

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #10411

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
This don't really need parens, but seems not very clear it's `throw 1` or `throw (1, 2)`, maybe we should always print `0, (throw 1), 2;`?


**Prettier pr-10585**
[Playground link](https://deploy-preview-10585--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAGANAAhgCwE4QDumAjFgEwDcAOlBpgBS4HEkCUFlI6IEADjACW0AM7JQAQzwsAClIRiUEgDaEJATzE8ARnglgA1nBgBlPvsFQA5shh4ArnB5wAttrgATD54AyE6-YSVnAAYhB4LhIwQtbIIBL2MBDcIDgwLsoA6jiC8CLmYHAmCrmCAG656nFgIlogliJweDAyelaRyABmKo08AFYiAB4AQnqGxiYSLnA+lnBdPU4gA4MmllbKcACK9hDwC8q9IOZ4jXhx2hLuyil8eJYwmYIeuMgAHBjHBI2ZenxxdzgZzK8x4AEddvBWvxFPERABaKBwTyeFJ4OAQwTo1pBDpIbqHJaNFyCWwOInrTY7PbzfGLHgwK5PF44ZDkBl6QTKdYAYQgLjxICBAFYUvZGgAVK6KAlHMqOACSUG8sBMYHuAgAgsqTDB1JsDo0AL5GoA)

```sh
--parser babel
```

**Input:**

```jsx
0, throw 1, 2;
0, (throw 1), 2;
```

**Output:**

```jsx
0, throw 1, 2;
0, throw 1, 2;

```

**Comment by thorn0** [comment]
> maybe we should always print

:+1:

**Comment by thorn0** [comment]
This is also a problem for other operators. E.g. ` (throw 1 + 2);`

**Comment by thorn0** [comment]
This seems to have been solved correctly for `do` expressions. I assume `throw` expressions just should use the same logic.

**Comment by fisker** [comment]
> This is also a problem for other operators. E.g. ` (throw 1 + 2);`

I thought about this too.


It seems the proposal is not active https://github.com/tc39/proposal-throw-expressions, and no one has opened any issue about them (both `SequenceExpression` and your example), maybe it not worth to worry about it? I'm going to close this and ignore the problem.

**Comment by thorn0** [comment]
Okay, let's get back to this if the proposal shows signs of life.

**Pull request closed without merging**
