### PR TITLE
JSDocs for comments.js and dependend scripts

### PR DESCRIPTION
**Pull request by Shinigami92**
- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by lydell** [comment]
Looks like you made some mistake with git. This PR now has a lot of diff in it that shouldn’t be there.

**Comment by Shinigami92** [comment]
> Looks like you made some mistake with git. This PR now has a lot of diff in it that shouldn’t be there.

Oh damnd :/

**Comment by Shinigami92** [comment]
Arrrg damnd, I messed up, I will open a new PR
I'm not very well with special git things like making clean sync to branch in forks
I tried to squash-merge and then after that didn't worked, I tried rebase on master

**Comment by Shinigami92** [comment]
@lydell  ->  #6898

**Pull request closed without merging**
