### PR TITLE
[typescript, flow]: double indent for unions inside of tuples

### LINKED ISSUE #4794: Incorrect formatting for union types within tuple types
Prettier adds first one and then second empty line when formatting nested union of tuples.

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAcnAZ3gBMAeAFQD5sBebcgbgB0oX0tsAhAVwHNa8hEqRbZsAH2wBtJiACGsgDTYiAJwCWUXgF1RE6bIBGSlTA1bdUMZJngTazTr03Zxe2ceXrBkHHfmnK30ZILExWQAzJT0wsMlZAEYk5JTU1NkY2P1ZACY8-ILCoryM0Kz4kABmaprauvrq0tjLSgYQRRAIDBh1aAJkUDlVVQgAdwAFIYR+lDkANwh1YnaQQ1U5MABrOBgAZQwNx2QzbjgOzQI4VRhx9d4AWzlkCLkAG0uOgCsCAA9Oda2O12cnucAAMpo4M83h8QAdVJdVMhUJhCGANN0VhhzDAAOpLGAAC2QAA4AAwdbEQS649YYZHYwhXOZQjqqOAAR246nZtzkDyeSBe7zOIEu93Ux1Upw6BEcrzgAEVuBB4NCRR0YHJDPjiETkDlNet1K9HABhCD3R7IqDQVkgbiXcjambCy4AX3dQA)
```sh
--parser typescript
```

**Input:**
```tsx
type Nested<T> = T;

type Bug = Nested<
  | ["a", string]
  | ["b", string]
  | ["c", string]
  | ["d", string]
  | ["e", string]
  | [
      "f",
        | "11111111111111111111"
        | "22222222222222222222222"
        | "33333333333333333333333"
    ]
>;
```

**Output:**
```tsx
type Nested<T> = T;

type Bug = Nested<
  | ["a", string]
  | ["b", string]
  | ["c", string]
  | ["d", string]
  | ["e", string]
  | [
      "f",

        | "11111111111111111111"
        | "22222222222222222222222"
        | "33333333333333333333333"
    ]
>;

```

**Second Output:**
```tsx
type Nested<T> = T;

type Bug = Nested<
  | ["a", string]
  | ["b", string]
  | ["c", string]
  | ["d", string]
  | ["e", string]
  | [
      "f",


        | "11111111111111111111"
        | "22222222222222222222222"
        | "33333333333333333333333"
    ]
>;

```

**Expected behavior:**
```tsx
type Nested<T> = T;

type Bug = Nested<
  | ["a", string]
  | ["b", string]
  | ["c", string]
  | ["d", string]
  | ["e", string]
  | [
      "f",
        | "11111111111111111111"
        | "22222222222222222222222"
        | "33333333333333333333333"
    ]
>;

```

### PR DESCRIPTION
**Pull request by squidfunk**
This PR fixes indentation of multi-line union types inside of TypeScript/Flow tuples.

__Input:__

``` ts
type B = [
  | AAAAAAAAAAAAAAAAAAAAAA
  | BBBBBBBBBBBBBBBBBBBBBB
  | CCCCCCCCCCCCCCCCCCCCCC
  | DDDDDDDDDDDDDDDDDDDDDD
]

type C = [
  | [AAAAAAAAAAAAAAAAAAAAAA | BBBBBBBBBBBBBBBBBBBBBB | CCCCCCCCCCCCCCCCCCCCCC | DDDDDDDDDDDDDDDDDDDDDD]
  | [AAAAAAAAAAAAAAAAAAAAAA | BBBBBBBBBBBBBBBBBBBBBB | CCCCCCCCCCCCCCCCCCCCCC | DDDDDDDDDDDDDDDDDDDDDD]
]
```

__Output (before fix)__:

``` ts
type B = [

    | AAAAAAAAAAAAAAAAAAAAAA
    | BBBBBBBBBBBBBBBBBBBBBB
    | CCCCCCCCCCCCCCCCCCCCCC
    | DDDDDDDDDDDDDDDDDDDDDD
];

type C = [

    | [

          | AAAAAAAAAAAAAAAAAAAAAA
          | BBBBBBBBBBBBBBBBBBBBBB
          | CCCCCCCCCCCCCCCCCCCCCC
          | DDDDDDDDDDDDDDDDDDDDDD
    ]
    | [

          | AAAAAAAAAAAAAAAAAAAAAA
          | BBBBBBBBBBBBBBBBBBBBBB
          | CCCCCCCCCCCCCCCCCCCCCC
          | DDDDDDDDDDDDDDDDDDDDDD
    ]
];
```

__Output (after fix)__:

``` ts
type B = [
  | AAAAAAAAAAAAAAAAAAAAAA
  | BBBBBBBBBBBBBBBBBBBBBB
  | CCCCCCCCCCCCCCCCCCCCCC
  | DDDDDDDDDDDDDDDDDDDDDD
];

type C = [
  | [
      | AAAAAAAAAAAAAAAAAAAAAA
      | BBBBBBBBBBBBBBBBBBBBBB
      | CCCCCCCCCCCCCCCCCCCCCC
      | DDDDDDDDDDDDDDDDDDDDDD
    ]
  | [
      | AAAAAAAAAAAAAAAAAAAAAA
      | BBBBBBBBBBBBBBBBBBBBBB
      | CCCCCCCCCCCCCCCCCCCCCC
      | DDDDDDDDDDDDDDDDDDDDDD
    ]
];
```

Fixes #4794

- [x] I’ve added tests to confirm my change works.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by squidfunk** [comment]
@evilebottnawi shall I add some notes to `CHANGELOG.unreleased.md`?

**Comment by evilebottnawi** [comment]
@squidfunk yes, please use template as do this for other problems, thanks

**Comment by squidfunk** [comment]
Done!

**Comment by bakkot** [comment]
Hm, this ends up a little confusing [when there's multiple types in the tuple](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAgtgXmwG0AdKbbAZxgCcBLKAcwBpzKAfPXH3v-ge2xcAQmPETJUkUK4BhBYqXKVcthWHYAIjt179BrbOwBRM+YuWrJ4wDF7Dx0+e31lKAFcAtgCM4tcgBdEBYQCAwYemgqZFAAQ1paCAB3AAUEhBiUOIA3CHoAExCQH1o4sABrOBgAZQxyxiZkOg84UIALGC8AGwB1dvp4KnqwOBrMwfocwbRkcCoY0MYqfxhUsqYvOOQAMzjuldCAKyoADxEyyuqauK84ABlGOF39w5AT05rG7rgARQ8IPAXgc2iB6rQVrQ5j44j40N1oMUMAxYL1CjB2sgAGwABlCyIgK16ZQwc2RcEhOWeoQAjgD4OtwlkQHEqABaKBwOAFbnFWhwOn0fnrOKbbZIPYg0IrLz0Zq0VrS75-enPCWvUEwWFogoY5AAJlCdDi9G6jTkEC8WzmUGg1JAHhWABVYVlJSsAL4eoA):

```ts
type A = [
  string,
  | AAAAAAAAAAAAAAAAAAAAAA
  | BBBBBBBBBBBBBBBBBBBBBB
  | CCCCCCCCCCCCCCCCCCCCCC,
  | DDDDDDDDDDDDDDDDDDDDDD
  | EEEEEEEEEEEEEEEEEEEEEE
  | FFFFFFFFFFFFFFFFFFFFFF,
  number,
];
```
I assume that's why its formatted [on master](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAgtgXmwG0AdKbbAZxgCcBLKAcwBpzKAfPXH3v-ge2xcAQmPETJUkUK4BhBYqXKVcthWHYAIjt179BrbOwBRM+YuWrJ4wDF7Dx0+e31lKAFcAtgCM4tdQBdAG5yEBYQCAwYemgqZFAAQ1paCAB3AAVkhHiURIA3CHoAE3CQH1pEsABrOBgAZQwqxiZkOg84CIALGC8AGwB1Lvp4KiawOHqckfp8kbRkcCp4iMYqfxgMyqYvROQAM0S+9YiAKyoADxFKmrr6xK84ABlGOAOjk5Bzi-qWvrgAIoeCDwd7HTogJq0da0RY+RI+NB9aBlDAMWADEowLrIABsAAYImiIOsBpUMIs0XAYfk3hEAI7A+BbKK5ECJKgAWigcDgxT5ZVocEZ9CFW0SOz2SEO4Ii6y89DatA6cr+gKZb2lHwhMARmOK2OQACYInREvQ+i05BAvLtFkc+mUPOsACoI3Iy9YAXy9QA) as

```ts
type A = [
  string,

    | AAAAAAAAAAAAAAAAAAAAAA
    | BBBBBBBBBBBBBBBBBBBBBB
    | CCCCCCCCCCCCCCCCCCCCCC,

    | DDDDDDDDDDDDDDDDDDDDDD
    | EEEEEEEEEEEEEEEEEEEEEE
    | FFFFFFFFFFFFFFFFFFFFFF,
  number,
];
```

which is at least unambiguous at a glance.

**Comment by evilebottnawi** [comment]
@bakkot new output https://deploy-preview-6381--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAgtgXmwG0AdKbbAZxgCcBLKAcwBpzKAfPXH3v-ge2xcAQmPETJUkUK4BhBYqXKVcthWHYAIjt179BrbOwBRM+YuWrJ4wDF7Dx0+e31lKAFcAtgCM4tcgBdEBYQCAwYemgqZFAAQ1paCAB3AAUEhBiUOIA3CHoAExCQH1o4sABrOBgAZQxyxiZkOg84UIALGC8AGwB1dvp4KnqwOBrMwfocwbRkcCoY0MYqfxhUsqYvOOQAMzjuldCAKyoADxEyyuqauK84ABlGOF39w5AT05rG7rgARQ8IPAXgc2iB6rQVrQ5j44j40N1oMUMAxYL1CjB2sgABwABlCyIgK16ZQwc2RcEhOWeoQAjgD4OtwlkQHEqABaKBwOAFbnFWhwOn0fnrOKbbZIPYg0IrLz0Zq0VrS75-enPCWvUEwWFogoY5AAJlCdDi9G6jTkEC8WzmUGg1JAHhWABVYVlJW8cq0AJJQHmwGpgBgRXC+mroH7AlYAXyjQA

**Comment by bakkot** [comment]
@evilebottnawi I messed up the first link; fixed. The code in the comment was still correct (with print-width 60, anyway.)

**Comment by squidfunk** [comment]
@bakkot I see your concerns. Can we somehow detect if there're multiple types in the tuple? If there are multiple entries, we could add newlines before and after unions, without indenting them:

``` ts
type A = [
  string,

  | AAAAAAAAAAAAAAAAAAAAAA
  | BBBBBBBBBBBBBBBBBBBBBB
  | CCCCCCCCCCCCCCCCCCCCCC,

  | DDDDDDDDDDDDDDDDDDDDDD
  | EEEEEEEEEEEEEEEEEEEEEE
  | FFFFFFFFFFFFFFFFFFFFFF,

  number,
];
```

However, I don't know whether that's easily possible with the current architecture.

**Comment by bakkot** [comment]
@squidfunk Yeah, you can probably do that in [the tuple printing code](https://github.com/prettier/prettier/blob/b9cbca9eceea28968096b5a80a41be0f1089a62c/src/language-js/printer-estree.js#L2494-L2512).

**Comment by squidfunk** [comment]
Done. Haven't had the time to work on the remaining issue, though.

**Comment by lipis** [comment]
What else is left here?

**Comment by thorn0** [comment]
It doesn't seem to have been rebased correctly.

**Comment by squidfunk** [comment]
Sorry, then it's my mistake. Haven't rebased a PR before. I followed the directions GitHub gave me, but obviously made an error. Any directions?

**Comment by evilebottnawi** [comment]
@squidfunk looks you do something wrong, if it is difficult for, maybe you can send a new PR?

**Comment by squidfunk** [comment]
@evilebottnawi fixed it!

**Comment by thorn0** [comment]
BTW, I'd prefer the input over the output in these examples where a tuple or generic has more than one entry, otherwise it's not clear how many entries it has. But this can be done in another PR.

**Prettier pr-6381**
[Playground link](https://deploy-preview-6381--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEMCeAHOACAhgJ31zWwF5sBtAHSm2wGcZ8BLKAcwBoa6AKbu7AB9sVEADc4+EgBtobbM3gBbbNBwALSThgRsAMwj4wOXNihwA7tNZxR-OsNESp2WewXLsAJju0Bj8UkZOQ84FQBmXzoASi4-Pj8HEUCXN3lFMNVzbE18bV0DIxMzS2tzKP9k52D3DJUfEHshKqDXELrsSMa-aJoAXQBuGhp0LH0IXXIAMQmAHn5GFnY43iaA6rbazzUcrWwdcaK8EqsbCqSnVrTQ+vPmy9T2zy7+WP4EgXuUmvTt7Nz8odjMdzKdyt1Pusrk9Mg01i1HltMi8ejQAHxDKAgDggCAYGDMaD0ZCgAj4CAWAAKBAQxJQuDEEGYABNsSAAEZEMAAazgMAAyhhcGBWGxkEwAK5wHHqGBKaQAdXUGXoQuM-NpimYYkUaGQ4HoxJxrHokhglKIbCUuGQelw0lNOIAVvQAB4AIS5vIFuCUcAAMjZbfbHSAXa7+aLpHAAIoSiDwYMO6UgIX4U34fXs3DstBuNkYJYwBUsmDqZAADgADDjCxBTQqiBh9YW4BmJGyAI7x+AWvF0kC4egAWnMcGZ47ZeW7zDyFtwVptSDtyZxpqUzHF+Cla6jsZ7cCToZgOZLzLLyC8OKYuGYZTYAGEIEprfqoGo2RLTQAVHN0lehmIUoAJJQBOsD8mALD4gAgmB-LoNGR5wAAvihQA)
```sh
--parser babylon
```

**Input:**
```jsx
type array = [
  string,
  (
    | "very long item one here to force a newline"
    | "very long item 2"
    | "very long item 3"
  ),
  (
    | "very long item one here to force a newline"
    | "very long item 2"
    | "very long item 3"
  )
];

type foo = Foo<
  string,
  (
    | "very long item one here to force a newline"
    | "very long item 2"
    | "very long item 3"
  ),
  (
    | "very long item one here to force a newline"
    | "very long item 2"
    | "very long item 3"
  )
>;

```

**Output:**
```jsx
type array = [
  string,
  | "very long item one here to force a newline"
  | "very long item 2"
  | "very long item 3",
  | "very long item one here to force a newline"
  | "very long item 2"
  | "very long item 3"
];

type foo = Foo<
  string,
  | "very long item one here to force a newline"
  | "very long item 2"
  | "very long item 3",
  | "very long item one here to force a newline"
  | "very long item 2"
  | "very long item 3"
>;

```

**Comment by squidfunk** [comment]
@thorn0 I have the fix for tuple typings in TypeScript that are wrapped in a parenthesized expression. The result is the following:

Input:

```
type D = [
  (AAAAAAAAAAAAAAAAAAAAAA | BBBBBBBBBBBBBBBBBBBBBB | CCCCCCCCCCCCCCCCCCCCCC | DDDDDDDDDDDDDDDDDDDDDD),
  (AAAAAAAAAAAAAAAAAAAAAA | BBBBBBBBBBBBBBBBBBBBBB | CCCCCCCCCCCCCCCCCCCCCC | DDDDDDDDDDDDDDDDDDDDDD)
]

type E = [
  (
    | AAAAAAAAAAAAAAAAAAAAAA
    | BBBBBBBBBBBBBBBBBBBBBB
    | CCCCCCCCCCCCCCCCCCCCCC
    | DDDDDDDDDDDDDDDDDDDDDD
  ),
  (
    | AAAAAAAAAAAAAAAAAAAAAA
    | BBBBBBBBBBBBBBBBBBBBBB
    | CCCCCCCCCCCCCCCCCCCCCC
    | DDDDDDDDDDDDDDDDDDDDDD
  )
]
```

Output

```
type D = [
  (
    | AAAAAAAAAAAAAAAAAAAAAA
    | BBBBBBBBBBBBBBBBBBBBBB
    | CCCCCCCCCCCCCCCCCCCCCC
    | DDDDDDDDDDDDDDDDDDDDDD
  ),
  (
    | AAAAAAAAAAAAAAAAAAAAAA
    | BBBBBBBBBBBBBBBBBBBBBB
    | CCCCCCCCCCCCCCCCCCCCCC
    | DDDDDDDDDDDDDDDDDDDDDD
  )
];

type E = [
  (
    | AAAAAAAAAAAAAAAAAAAAAA
    | BBBBBBBBBBBBBBBBBBBBBB
    | CCCCCCCCCCCCCCCCCCCCCC
    | DDDDDDDDDDDDDDDDDDDDDD
  ),
  (
    | AAAAAAAAAAAAAAAAAAAAAA
    | BBBBBBBBBBBBBBBBBBBBBB
    | CCCCCCCCCCCCCCCCCCCCCC
    | DDDDDDDDDDDDDDDDDDDDDD
  )
];
```

Should I add them to this PR or create a new one? It's just one line of code, the tests are green.

**Comment by lipis** [comment]
Maybe add it here since it's a small change.

**Comment by squidfunk** [comment]
Added the change. Interestingly codecov now fails in a completely different part.

**Comment by thorn0** [comment]
What's been done is not exactly what I meant. Let's remember that in the AST of usual JS expressions, there is no such thing as "parenthesized expression". Parens are considered formatting, not part of AST. Prettier itself decides where to add parens, just like it does with spaces and line breaks. I'd expect it to do the same with types. But for some reason, `TSParenthesizedType` expression is a thing in TS type expressions. Why do we need these nodes?

**Comment by thorn0** [comment]
This PR is good to merge. I'm going to catch and polish inconsistencies (if I find them) in #6605.

**Comment by evilebottnawi** [comment]
@thorn0 looks @duailibe is unavailable, maybe setup minimum reviews help to use moving faster

**Comment by thorn0** [comment]
It's been my observation that the more comments a PR has the longer it takes for it to get merged. We should probably chat less in comments or just hide/delete outdated and irrelevant comments, so that it is easier for reviewers to follow.

**Comment by evilebottnawi** [comment]
I think we can safely merge, if somebody from developers thinks that we missed something or did something wrong, he can safely open issue and we fix it too

**Pull request merged**
