### PR TITLE
Also infer parser when using `--list-different`

### LINKED ISSUE #1971: --list-different is reporting files are different (when they aren't)
I've run `prettier --write '**/*.{css,ts}'` on my code base and committed the changes. Using `prettier -l '**/*.{css,ts}'` afterwards returns a `1` exit code causing my CI to fail.

Both `ts` and `css` files are being reporting as being incorrectly formatted - but running prettier on them again results in no diff.

Adding the write flag changes the output, in that no files get listed - but the exit code is still non-zero. `prettier --write --list-different '**/*.{ts,css}'`

Reproduction can be found [here](https://github.com/wayneashleyberry/prettier-test-repo).

---

Running `--debug-check` shows the following, which interestingly enough reports unexpected tokens for the problematic files.

```sh
~/prettier-test-repo master
❯ prettier --debug-check '**/*.{ts,css}'
color.directive.ts
color.directive.ts: SyntaxError: Unexpected token (17:11)
  15 | })
  16 | export class ColorPickerDirective implements AfterViewInit, OnChanges {
> 17 |   private _element: any;
     |           ^
  18 |
  19 |   @Input() colorValue: string;
  20 |   @Output() colorValueChanged: EventEmitter<any> = new EventEmitter();
index.ts
lib/foo.ts
public/style.css
public/style.css: SyntaxError: Unexpected token, expected ; (1:6)
> 1 | body {
    |      ^
  2 |   font-family: sans-serif;
  3 | }
  4 |
```

---

This screenshot might help as well :)

screen shot 2017-06-05 at 12 28 21 pm

### PR DESCRIPTION
**Pull request by philipp-spiess**
Fixes #1971

### CODE REVIEW

**Comment by azz** [comment]
Thanks for the fix!

Would you be able to add a simple test [here](https://github.com/prettier/prettier/tree/master/tests_integration/__tests__) to make sure we don't regress?

**Comment by philipp-spiess** [comment]
@azz I've added the test you were asking for. I also verified that it fails when I undo my fix.

**Comment by vjeux** [comment]
Thanks!

**Comment by wayneashleyberry** [comment]
This is great! Thank you @philipp-spiess and @vjeux :)

**Pull request merged**
