### PR TITLE
Make `options` argument in parsers optional

### LINKED ISSUE #11888: "TypeError: Cannot set property 'originalText' of undefined" from TypeScript Jest inline snapshot
After upgrading from Prettier 2.4.x to 2.5.0, a Jest inline snapshot test in a TypeScript file throws the following error when Jest tries to update the snapshot:

```
    TypeError: Cannot set property 'originalText' of undefined

      at Object.<anonymous> (node_modules/prettier/parser-typescript.js:13:3304772)
      at Object.parse$d [as parse] (node_modules/prettier/index.js:12975:19)
      at coreFormat (node_modules/prettier/index.js:14525:16)
      at formatWithCursor$1 (node_modules/prettier/index.js:14765:14)
      at node_modules/prettier/index.js:60955:12
      at Object.format (node_modules/prettier/index.js:60975:12)
```

I'm not sure if this is a bug within Prettier or within how Jest is using Prettier; if I should file this with the Jest project, please let me know.

**Environments:**

- Prettier Version: 2.5.0
- Running Prettier via: CLI (via Jest)
- Runtime: Node.js 14.17.1
- Operating System: Windows and Linux
- Prettier plugins (if any): None

**Steps to reproduce:**

Clone https://github.com/joshkel/prettier-test-case and run `npm i; npm test`

**Expected behavior:**

The snapshot is correctly written and Prettier formats the file.

**Actual behavior:**

Abort with a stack trace.

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #11888

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by duailibe — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]
Thank you!

**Comment by sosukesuzuki** [comment]
Sorry after mergeed, it might be better to have a changelog for this change.

**Comment by fisker** [comment]
I think we should not encourage people use the parsers directly, but make sense to add changelog says we fixed the jest issue, is it fine?

**Comment by sosukesuzuki** [comment]
Yes, It would be better for users to know that this fixes the problem with jest. ((Of course, I don't want a user to use the parser directly...))

**Pull request merged**
