### PR TITLE
Remove badges for GitHub Actions

### PR DESCRIPTION
**Pull request by fisker**
## Description

GitHub already show the status in the UI.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by kachkaev** [comment]
By UI you mean this?

Screenshot 2021-01-04 at 13 10 49

What about npm? Not saying that build status badges are that useful for projects with PR merge policies, just trying to be the devil's advocate 😁

**Comment by fisker** [comment]
Actually, I mean this, but seems it's not a github feature? Maybe some plugin I installed.

image

**Comment by kachkaev** [comment]
Hmmm interesting, that green tick does not show up for me.

Screenshot 2021-01-05 at 09 09 08

**Comment by fisker** [comment]
It's a ["Refined Github"](https://github.com/sindresorhus/refined-github/blob/master/source/features/ci-link.tsx) feature, I thought it's native :smile:

image

**Pull request closed without merging**
