### PR TITLE
Allow `lang` attribute of `<template>` to be empty

### LINKED ISSUE #12388: </template> in VS code breaks prettier
**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gLwA6I1AfJVIYagG4C0eWWbARngE71GTZuwwIAroQgAzGQGc4MNgE8hIkejjZ88WqgD0mXATjrNBsZPOH2nbn0ENDx3WYYgANCAhYYAS2h5ZFABfggAdwAFAQRglDwcCLwVYO8efjwwAGslAGU8cQAZfyg4ZBlExXTMnPysLNLSZBh+CThvbR44ABMe3qK8Mgk8UjgAMQh+DAIAsmQQPAkYCC8QAAsYDBwAdXX-eHkGsDg8uIP-FgOVBbB5NJBSxX4YKMzSGYqqjpAAK3kAB55Jo4OAARQkEHgXxw1RADX4zwWfG6ODWWH4pRgO38PRg62QAA4AAzeDEQRQ7TJYBYYuDPFjlbwAR0h8Devnii3kbDKvV6a34cFZ-iFb1GnyQlVhP0UGH8LTaspB4LZ5SQrXa3hgeB4OLxBKQACZtZl-DgmgBhCAYSUgekAVjWEkUABVdfFNT8WO0AJJQfqwPJgTF+ACCAbyMBUoJhigAvvGgA)

```sh
--parser babel
--use-tabs
--single-quote
```

**Input:**

```jsx
<template lang="">
  <v-app-bar>
    <v-menu offset-y>
      <template></template>
    </v-menu>
  </v-app-bar>
</template>

```

**Output:**

```jsx
<template lang="">
	<v-app-bar>
		<v-menu offset-y>
			<template></template>
		</v-menu>
	</v-app-bar>
</template>;

```

**Expected behavior:**
The expected behavior in the playground is correct, however in my environment, it seems to recognize the first </template> tag it finds as the end of the vue template and creates this error:

```
SyntaxError: Unexpected closing tag "v-menu". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (5:5)
  3 |     <v-menu offset-y>
  4 |       <template></template>
> 5 |     </v-menu>
    |     ^^^^^^^^^
  6 |   </v-app-bar>
  7 | </template>
  8 | <script>
	at y (m:\source\bandzintranet\node_modules\prettier\parser-html.js:40:2906)
	at Vl (m:\source\bandzintranet\node_modules\prettier\parser-html.js:111:2567)
	at Xl (m:\source\bandzintranet\node_modules\prettier\parser-html.js:111:4116)
	at Object.parse (m:\source\bandzintranet\node_modules\prettier\parser-html.js:111:4885)
	at Object.parse$d [as parse] (m:\source\bandzintranet\node_modules\prettier\index.js:12975:19)
	at coreFormat (m:\source\bandzintranet\node_modules\prettier\index.js:14525:16)
	at formatWithCursor$1 (m:\source\bandzintranet\node_modules\prettier\index.js:14765:14)
	at m:\source\bandzintranet\node_modules\prettier\index.js:60959:12
	at Object.format (m:\source\bandzintranet\node_modules\prettier\index.js:60979:12)
	at t.default.format (c:\Users\jmarshall\.vscode\extensions\esbenp.prettier-vscode-9.3.0\dist\extension.js:1:13219)
	at async t.PrettierEditProvider.provideEdits (c:\Users\jmarshall\.vscode\extensions\esbenp.prettier-vscode-9.3.0\dist\extension.js:1:10196)
	at async g.provideDocumentFormattingEdits (c:\Users\jmarshall\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:93:98509)
["INFO" - 11:59:23 AM] Formatting completed in 0.007ms.
```

### PR DESCRIPTION
**Pull request by HallvardMM**
## Description

Allow the lang attribute to be empty string in template. Solves Vue issue #12388.

Fixes #12388

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Let's fix this too

**Prettier pr-12394**
[Playground link](https://deploy-preview-12394--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwAE+UA5gHwA6UhhqAbgLR5ZaMBGeATlTbXUwwIAroQgAzcQGc4MRgE9e-fujjZ88cqgD0mXAThKV2wSKM6mLNpx7UdejYcIgANCAhYYAS2hTkobi4IAHcABW4EPxQ8HGC8eT83di48MABrWQBlPCEAGS8oOGRxGJkklPSsrFSC0mQYLmE4NzV2OAATdo7cvDJhPFI4ADEILgwCbzJkEDxhGAhXEAALGAwcAHUlr3gparA4TMjtr3pt+WmwKUSQApkuGFCU0nHi0uaQACspAA9M2pw4ABFYQQeCvHBlEDVLh3ab0JqLLBcAowdZedowJbIAAcAAY3EiIDJ1iksNMkXA7vQim4AI4g+CPDxRGZSRiFDodRZcOD0rw8x4DF5IEoQ94yDBeeqNcX-IEMooit5uGB4dhojFYpAAJhVKS8OFqAGEIBhhSBKQBWRbCGQAFTVUVFkPhcAAklAurBMmBkZ4AIKezIweQA8EyAC+EaAA)

```sh
--parser vue
```

**Input:**

```vue
<template lang>
  <v-app-bar>
    <v-menu offset-y>
      <template></template>
    </v-menu>
  </v-app-bar>
</template> 
```

**Output:**

```vue
SyntaxError: Unexpected closing tag "v-menu". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (5:5)
  3 |     <v-menu offset-y>
  4 |       <template></template>
> 5 |     </v-menu>
    |     ^^^^^^^^^
  6 |   </v-app-bar>
  7 | </template> 
```

**Comment by HallvardMM** [comment]
Should I check for just lang=undefined or could I do something like !value which accepts:
lang=null, undefined, NaN,"",0,false?

**Comment by fisker** [comment]
I'm not near a laptop, don't know the parse result, but let's check what the parser pased as.

**Comment by HallvardMM** [comment]
Okay so I checked and it seems like lang="" or lang="und" should be used when the language is undefined [link](https://stackoverflow.com/questions/15416683/is-lang-unknown-attribute-valid). However <template lang> will give the same as <template lang=""> so it is okay that Prettier accepts that :)

**Review by fisker — APPROVED** [review]
LGTM. Thank you!

**Review by sosukesuzuki — APPROVED** [review]

**Pull request merged**
