### PR TITLE
feat: add support for PartialApplication

### PR DESCRIPTION
**Pull request by JounQin**
- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

Waiting for #6386

### CODE REVIEW

**Comment by fisker** [comment]
@JounQin #6386 merged

**Comment by JounQin** [comment]
> @JounQin #6386 merged

Thx, I will rebase tonight.

**Comment by fisker** [comment]
```js
// partial template strings
const Diagnostics = {
  unexpected_token: `Unexpected token: ${?}`,
  name_not_found: `'${?}' not found.`
};
Diagnostics.name_not_found("foo"); // "'foo' not found."
```

https://github.com/tc39/proposal-partial-application/blob/master/README.md#proposal

is this supported?

**Comment by fisker** [comment]
@lipis Should this included in 1.19?

**Comment by evilebottnawi** [comment]
@fisker we can

/cc @JounQin friendly ping, need rebase

**Comment by JounQin** [comment]
@evilebottnawi Done.

**Pull request merged**
