### PR TITLE
Upgrade Docusaurus to a stable version

### PR DESCRIPTION
**Pull request by lipis**
https://deploy-preview-3874--prettier.netlify.com

### CODE REVIEW

**Comment by azz** [comment]
Are there breaking changes?

**Comment by lipis** [comment]
There shouldn't be and I tested the website thoroughly locally.. everything works as expected.

**Comment by lipis** [comment]
Can anyone else verify this?

**Comment by suchipi** [comment]
When clicking through the netlify preview, I sometimes got this when navigating to the playground:
screen shot 2018-02-06 at 1 07 14 am
Not sure if it docusaurus related or netlify related or what.

**Comment by lipis** [comment]
Can't reproduce that one (locally/netlify)

**Comment by lipis** [comment]
@suchipi do you still have this issue? or it was random incident..?

**Comment by suchipi** [comment]
It's not happening anymore, so it must have been something weird/random

**Comment by lipis** [comment]
merging?

**Comment by suchipi** [comment]
Go for it

**Pull request merged**
