### PR TITLE
Markdown: preserve non-ASCII whitespaces at the end of the line and beginning of the next line

### PR DESCRIPTION
**Pull request by tats-u**
## Description

The safest part of #15081 

Prettier removes non-ASCII whitespaces at the end of the line and beginning of the next line in Markdown, which violates the CommonMark spec.

The space (U+3000) in the following should be kept:

```markdown
# 例

　全角スペース全形空白
```

https://spec.commonmark.org/0.31.2/#soft-line-breaks

> Spaces at the end of the line and beginning of the next line are removed:

https://spec.commonmark.org/0.31.2/#unicode-whitespace-character

> A [Unicode whitespace character](https://spec.commonmark.org/0.31.2/#unicode-whitespace-character) is a character in the Unicode Zs general category, or a tab (U+0009), line feed (U+000A), form feed (U+000C), or carriage return (U+000D).
>
> [Unicode whitespace](https://spec.commonmark.org/0.31.2/#unicode-whitespace) is a sequence of one or more [Unicode whitespace characters](https://spec.commonmark.org/0.31.2/#unicode-whitespace-character).
>
> A [space](https://spec.commonmark.org/0.31.2/#space) is U+0020.

The CommonMark spec doesn't mention non-ASCII spaces here, so they should be reserved.

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by tats-u** [comment]
https://spec.commonmark.org/dingus/?text=%E3%80%80%E5%85%A8%E8%A7%92%E7%A9%BA%E7%99%BD%E3%80%80%0A

Hm, the official dingus removes such spaces.
I'll have to ask the spec maintainers a question.

**Comment by tats-u** [comment]
https://github.com/commonmark/commonmark.js/issues/261

**Comment by tats-u** [comment]
https://github.com/commonmark/commonmark.js/pull/289

It's proven to be a commonmark.js's bug.

**Review by fisker — APPROVED** [review]

**Review by fisker — APPROVED** [review]

**Comment by fisker** [comment]
`\u{xx}` notation seems more readable. We can ignore `\\u\{[0-9a-f]+\}` in https://github.com/prettier/prettier/blob/69f419213ecae370fc0499bbf5ddeeeafcbc5d23/cspell.json#L328

**Comment by tats-u** [comment]
> `\u{xx}` notation seems more readable

I agree with you, and I was able to shut cspell up by adding a regex.

**Review by fisker — APPROVED** [review]

**Pull request merged**
