### PR TITLE
[WIP]JavaScript: Fix ugly formatting on destructuring assignment with binary operators

### LINKED ISSUE #6396: Potential bug: Ugly code example when breaking line
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgII7AA6URMAtnDABYQAmAFBAA4wCW0mAlISTvwIGQomGIRxwAHszhh4dHAF4cUAK6pUAGhyY2UAObr0AJyUr1WnM1Srj6VGbUbtbTHmN2AnmYBm9zHDaosZ6+mw+3spODgC+ZizsnDgAPsmEMQDcfAIxJLlQ-CRgGNg4AEK8pBRUtIwJHCI8xAWCgsKi4lIycnAKURZBoUam-c5WNnYOo5au7l6+-oE6MCEG4ZHmGjhxyvWcWS38+TEgmiB7IsigJsYQAO4ACiYImMgg6ABuEGx0pyAARnYwABrKgAZWY6DAoWQK1UgRA1AoqAA6tQ2PBMJCwHAwS8MWwPhjPG8wNg-noAsYYA87PpyOhkH5UAEzgArTCSMpA0EwMHoSgAGT0cCZi3ZnLBoVQcAAiqoIPAxSyEZDjFS3v90P84Kg-sxVjAUT8aMgAIwABgtZwNEACKLszDeBrgVI+orOAEcFfBaSxXigsABaKBwXq9P7GODethR2noemMpDM1kgALkNiw4zws66Awy+WK0XJ8UgGDa410U1IABMZxW6DYqFCAGEIOQGW8oNAPSBVAEACragMpuAxGJAA)
```sh
--parser babel
--print-width 100
```

**Input:**
```jsx
class A {
	method(options) {
         const { expected = null, singular = null, plural = null, isArray = false, stringify = null } = options || {};
    }
}
  
class B {
	method(options) {
         const { expected = null, singular = null, plural = null, isArray = false, stringify = null } = options;
    }
}
```

**Output:**
```jsx
class A {
  method(options) {
    const { expected = null, singular = null, plural = null, isArray = false, stringify = null } =
      options || {};
  }
}

class B {
  method(options) {
    const {
      expected = null,
      singular = null,
      plural = null,
      isArray = false,
      stringify = null
    } = options;
  }
}

```

**Expected behavior:**
```js
class A {
  method(options) {
    const {
      expected = null,
      singular = null,
      plural = null,
      isArray = false,
      stringify = null
    } = options || {};
  }
}

class B {
  method(options) {
    const {
      expected = null,
      singular = null,
      plural = null,
      isArray = false,
      stringify = null
    } = options;
  }
}

```

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Fix #6396 

```js
// Input
const { expected = null, singular = null, plural = null, isArray = false } = options || {};

 // Prettier (stable)
const { expected = null, singular = null, plural = null, isArray = false } =
  options || {};

 // Prettier (master)
const {
  expected = null,
  singular = null,
  plural = null,
  isArray = false
} = options || {};
```

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
**Prettier pr-6439**
[Playground link](https://deploy-preview-6439--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuc0DOMAExNwB4AOcY8AJpgLyZQCuANnZgL6WYBGAlgGYQBOUAYV4coAczi8AshDQALOKQAKEgnXwBlAIYB3UhMwBqTJrQBrACq8IANwSaAQnDsAROESik0AJQjbNUNENMAB0oTExROg4AWzQ4AHE6AE8CWTQACU0AL01eUgA5CAgCNHMOODK4EAAaEGKYDnRkUFyrbUVchDRkEE1rCA5SGpA2Xk0wUzgYdQJxkVFkGF4aOFrZGGi6AHVZDng0WbA4dS69jms9pJ6wNG7akTjeGEUx0WjNZC5NOjjagCs0Hh7GMJlMtNE4AAZERVJBfH6rEAAvDqeZqACKNAg8E+31+IFmvEePTYmjYSTo0GGBGEsC2gxgsmQAA4AAy1GkyOBbMYEHo0uCPWzDACOWPgL2K3RQJgAtFAnHohrVeHAxRxVS9NG8PnC8Yi4tEOItlga0XBMdjYfD8TAyfTSIzkAAmWpLTQcKJiAQQaLvHpQaBVWo0OLmMnSm2I6wrACSHgQ0zAwgIMAAgh51DAKdb9UwmEA)
```sh
--parser babylon
```

**Input:**
```jsx
const { expected = null } = bifornCringerMoshedPerplexSawder + askTrovenaBeenaDependsRowans + 
  glimseGlyphsHazardNoopsTieTie
```

**Output:**
```jsx
const { expected = null } = bifornCringerMoshedPerplexSawder +
askTrovenaBeenaDependsRowans +
glimseGlyphsHazardNoopsTieTie;

```

**Comment by sosukesuzuki** [comment]
@evilebottnawi This is WIP. I haven't been able to fix the pointed out by thorn0 yet. you can close this pr. if you do it,  I re-open the pr when I fixed the bug.

**Comment by lipis** [comment]
Is this still WIP?

**Comment by sosukesuzuki** [comment]
yes, this is wip. Also, to fix the issue essensialy is hard for me.
I'll close this pr. If I find the solution, I'll open this pr again.

**Pull request closed without merging**
