### PR TITLE
Migrate to native dependabot

### PR DESCRIPTION
**Pull request by fisker**
Ref: https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/
Syntax: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#about-the-dependabotyml-file

Adding this file will enable [this page](https://github.com/prettier/prettier/network/updates)

image

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Why? What is wrong with default configuration?

**Comment by fisker** [comment]
This is not config for the old dependabot, it's migrate to native github  bot, we don't need go to dependabot.com, there will be logs and `update` button on the github page I post in the description. Consider there are two bots have similar names.

**Comment by fisker** [comment]
I read the docs again, about [`allow`](https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#allow), should we only check direct dependencies? There might too many indirect dependencies PR.

@evilebottnawi What do you think?

**Comment by evilebottnawi** [comment]
Updating `transient dependencies` is good practice, because you can have regressions in vendor packages, very few projects uses it, but I found it very good and useful, it is my opinion

**Comment by fisker** [comment]
Just afraid it  will be  annoying. Let's keep  it  this  way  and  see?

**Comment by evilebottnawi** [comment]
Yep, let's keep it this way, anyway will be great to hear other opinion here too

**Comment by fisker** [comment]
Checkout this page https://github.com/prettier/prettier/network/updates

**Pull request merged**
