### PR TITLE
Update steps for running Prettier on save in WebStorm

### PR DESCRIPTION
**Pull request by prigara**
WebStorm 2020.1 makes it easier to configure Prettier to [run on save](https://www.jetbrains.com/webstorm/whatsnew/#running-prettier-on-save).

I've updated the docs accordingly. 

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by prigara** [comment]
Sorry about having all the previous commits I've made visible in the PR. They should have been all merged back in 2018.

**Comment by thorn0** [comment]
What about the WebStorm link on the main page of prettier.io? Should we update it too?

**Comment by prigara** [comment]
@thorn0 the support for Prettier in WebStorm is about out-of-the-box. No changes here.
Do you suggest adding a link to https://prettier.io/docs/en/webstorm.html?

**Comment by thorn0** [comment]
>  support for Prettier in WebStorm is about out-of-the-box

Whereas the link leads to a plugin. Is that okay?

> Do you suggest adding a link to https://prettier.io/docs/en/webstorm.html?

Probably. Or we can put multiple links there. There are multiple links for other editors. You decide what would work best for WebStorm users.

**Comment by prigara** [comment]
Yeah, let's point the link to https://prettier.io/docs/en/webstorm.html. Will push a change to this branch.

**Pull request merged**
