### PR TITLE
Add pure css parser

### LINKED ISSUE #7740: Throw on Less syntax when the `css` parser is used
Not really sure this is really needed, but evilebottnawi asked to open this issue [here](https://github.com/prettier/prettier/pull/6981/files#r371918167).

### PR DESCRIPTION
**Pull request by fisker**
Fixes #7740

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
The initial idea behind the current solution was to support [non-standard CSS syntax](https://github.com/postcss/postcss/blob/master/docs/plugins.md#language-extensions) people use via PostCSS plugins. The idea was that there is a good chance that syntax can be parsed by the Less or SCSS parser (e.g. [postcss-nested](https://github.com/postcss/postcss-nested)). If Prettier switches `--parser css`  to a pure CSS parser, we'll break that use case. Not sure what to do about this mess. :(

**Comment by fisker** [comment]
Bad  idea, but I guess they can still use `scss`/`less` as parser for `.css` file? They work  same  as  before.

**Comment by evilebottnawi** [comment]
@thorn0 postcss pure parser works fine with nested constructions and other non standard stuff (otherwise they don't work :smile: ), so I don't think we break something (yes, we can have regressions, but we will fix it)

**Comment by fisker** [comment]
Strange, why this `less` parser broken on [playground](https://deploy-preview-7933--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEB6AVAAgDJwM56YDKAnrAIYAemA7gJYwAWmABgLRsAO5ATnnDwC8YAi0zpUAHSjlMwAHQAjCDwAmAuKoAUASgDcAXxAAaEBE4w60PMlC8eEGgAVeCGynIAbGuRI3TijzkYADWcDBE3GB0UADmyDA8AK5wpowwALaeAOqMDPhRcERuDHQAbgwkyOAEJiAx-DwwTkGxGeTIAGZe-KYAVniUAEJBoeFE5Blw2DFwXT2pIAOURDGxnnAAikkQ8POevSDcfALVG7WmnDwxMNl0qkzIABwADJcO-NlBnNVX+AJlOamACOO3gLXM7hA5DwbCgcE0mjqPDgoLoKJa5DaHSQ3QOi34GToCWSBLWG22uzmuIWphg5EUdwejGQACY6UE6J41gBhCAZdrVfAAVjqSX4ABUGe48YcyikAJJQdSwIhga4WACCyqIMBIG32-AMBiAA)?

**Comment by fisker** [comment]
I  can't locate the playground problem, the  parser for  `less` is  actual `css`.

**Comment by fisker** [comment]
Found the problem https://github.com/prettier/prettier/pull/7933/commits/4240ab6a3f164470d45121adc5796e48c0ade498 , we really should get this internal parsers automatically somehow.

**Comment by fisker** [comment]
Stable: [Formatting `less` syntax with `scss` parser](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABMAdAIwgJwBM585CAKASgG4BfAHShABoQIAHGAS2gGdlQqfPggB3AApCE-FKgA2o1AE9+rHPlRgA1nBgBldpq5QA5shj4ArnFYALGAFs5AdVtd4vQ2Dh7p7rgBu7krI4LyqIMa8JDDiGiYOqMgAZvLRrABWvAAeAEIa2rp6qA5wADLGcClpNiBZ2XrGJnJwAIqWEPDVcukghvjR+KG8YOEsffjGMM5chDC2yAAcAAys7CLRzhrsoetwgwFVrACOHfBxHDJovAC0UHBkZOOkp1ykcagJSUipPbXRDi45is-yaLXanSqPxqrBgqBwMzmCyQACZYRouHImgBhCAORKhfYAVnGlmiABV4TJfr0AtYAJJQYiwPRgSacACCTL0MCULW60VotCAA) :)

**Comment by fisker** [comment]
@evilebottnawi Do you think we should enable `postcss-safe-parser`?

**Comment by evilebottnawi** [comment]
@fisker I prefer to avoid recovered mode for formatting, it can potential create unsafe situations for us

**Comment by evilebottnawi** [comment]
@fisker it is breaking change, I don't think we no work on `prettier@3`

**Comment by evilebottnawi** [comment]
But maybe you should not use non standard syntax in pure CSS files

**Comment by fisker** [comment]
Maybe we can release 3.0?

**Comment by evilebottnawi** [comment]
@thorn0 What do you think?

**Comment by fisker** [comment]
IMHO, we are too slow, 5 month `v2.0.0` -> `v2.1.0`, 4 month `v2.0.5` -> `v2.1.0`.

**Comment by evilebottnawi** [comment]
@fisker agree, we can do release more often

**Comment by evilebottnawi** [comment]
We can open discussion about it, for example eslint makes releases every 2 week, we can choose the strategy that suits us

**Comment by evilebottnawi** [comment]
> But is it really a breaking change? Nobody promised --parser css should work for SCSS and LESS. It was an undocumented Easter egg.

Yes, that's what I'm talking about, on the one hand it's breaking change, on the other hand you should not use less/sass syntax for pure css or using `css` parser for formatting less/sass

**Comment by fisker** [comment]
The old docs says `autodetects which to use`, kind of telling people use `css` for  all

**Comment by thorn0** [comment]
This is indeed a breaking change then. IDK. Somehow releasing 3.0 just because of this change doesn't feel right.

**Comment by fisker** [comment]
I say, we should do this, don't postpone, world changing so quickly. We can't wait another six month or even longer...

Major release is not a big deal, IMO. We are code formatter, we break someone's code on most every release, we should do more breaking changes.

Let's introduce `espree` and break `css`, release `v3`!

**Comment by sosukesuzuki** [comment]
Although not absolutely necessary, I want to fix #6385 by the next major release.

**Comment by brodybits** [comment]
And can we add the ignore@5 update(#8546)?

**Pull request merged**
