### PR TITLE
Add Knip

### PR DESCRIPTION
**Pull request by fisker**
## Description

https://knip.dev/

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Thanks!

**Review by kachkaev — APPROVED** [review]
Great tool!

**Comment by webpro** [comment]
Thanks @kachkaev! Very cool to perhaps be a tiny part of this majestic project. In the event this PR will be merged I'll make sure to add Prettier to the [integration test suite](https://github.com/webpro-nl/knip/blob/main/.github/workflows/integration.yml) to minimize surprises/breakage going forward.

**Comment by webpro** [comment]
https://github.com/webpro-nl/knip/actions/runs/10926100754/job/30329210127#step:7:162

**Comment by fisker** [comment]
We need update knip, right?

**Comment by fisker** [comment]
Forgot to run knip on CI...

**Comment by fisker** [comment]
[`dcbba34` (#16679)](https://github.com/prettier/prettier/pull/16679/commits/dcbba34d481bb7ef764798244681e24104cae6a5)

**Comment by webpro** [comment]
> We need update knip, right?

Sorry for not being clear, it was just a follow-up because I said I was going to add Prettier to Knip's integration test suite.

No need to update Knip (I think you should see the configuration hints already, but they're just warnings).

**Comment by fisker** [comment]
I thought the warning was cause by new version, it seems it not appears because I didn't run `yarn` install on local.

**Comment by fisker** [comment]
Maybe `docusaurus-build` and `docusaurus-version` can analyzed from `yarn.lock`, so the subdirs don't need really installed?

**Comment by fisker** [comment]
Aren't binaries already in `yarn.lock`? Why the workspace need to be installed?

**Comment by fisker** [comment]
https://github.com/prettier/prettier/blob/73b0de69cfe66a22ebd4c4f0383b86b1fa2d1ab5/website/yarn.lock#L3942-L3949

**Comment by webpro** [comment]
Oops tbh I didn't even know that. Yet Knip also checks for optional peer dependencies, and whether `types`/`typings` is set (i.e. if types are included then `@types/..` aren't needed). Last but not least Knip works with any package manager so would need a parser for each lockfile version/format. Still, good to know so thanks for sharing!

**Pull request merged**
