### PR TITLE
handlebars: Add prettier-ignore

### PR DESCRIPTION
**Pull request by chadian**
This pull request adds the ability to use `{{! prettier-ignore }}` in  glimmer/handlebars

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by lipis** [comment]
Maybe updating the docs to reflect this change?

**Comment by chadian** [comment]
@lipis That sounds like a good idea. Can you point me in the right direction of which docs to update?

**Comment by lipis** [comment]
https://github.com/prettier/prettier/blob/master/docs/ignore.md

**Comment by chadian** [comment]
@lipis Thanks! I've included an example in the ignore docs.

**Comment by lipis** [comment]
Linter is complaining.

**Comment by chadian** [comment]
Thanks @thorn0!

**Pull request merged**
