### PR TITLE
fix(html): preserve case-sensitive tag names

### PR DESCRIPTION
**Pull request by ikatyang**
Non-HTML tag names are considered case-sensitive.

- [x] I’ve added tests to confirm my change works.
- (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by ikatyang** [comment]
It seems the fork does not work in the case where `html`, `head`, `body`, `script`, etc. are not lowercased. I guess there must be some hardcoded tag names in parse5, cc @StarpTech.

```html
<!DOCTYPE html>
<HTML CLASS="no-js mY-ClAsS">
  <HEAD>
    <META CHARSET="utf-8">
    <TITLE>My tITlE</TITLE>
    <META NAME="description" content="My CoNtEnT">
  </HEAD>
  <body>
    <P>Hello world!<BR> This is HTML5 Boilerplate.</P>
    <SCRIPT>
      window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
      ga('create', 'UA-XXXXX-Y', 'auto'); ga('send', 'pageview')
    </SCRIPT>
    <SCRIPT src="https://www.google-analytics.com/analytics.js" ASYNC DEFER></SCRIPT>
  </body>
</HTML>
```

image

**Comment by StarpTech** [comment]
@ikatyang I don't understand your issue. What's your input and output and how looks your code?

**Comment by StarpTech** [comment]
@ikatyang there are two modes in parse5

* fragment
* document

in order to check which modes should be used, I'm searching for `head`, `body` tags. I don't respect case-sensitive. I have never seen such a scenario in practice but the fix is an easy one. Your content is nested in a separate page because the `document` mode is enabled.

**Comment by ikatyang** [comment]
I thought the mode was determined by `parse`/`parseFragment`, isn't it?

Here's the repo steps:

```js
const text = `
<!DOCTYPE html>
<HTML CLASS="no-js mY-ClAsS">
  <HEAD>
    <META CHARSET="utf-8">
    <TITLE>My tITlE</TITLE>
    <META NAME="description" content="My CoNtEnT">
  </HEAD>
  <body>
    <P>Hello world!<BR> This is HTML5 Boilerplate.</P>
    <SCRIPT>
      window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
      ga('create', 'UA-XXXXX-Y', 'auto'); ga('send', 'pageview')
    </SCRIPT>
    <SCRIPT src="https://www.google-analytics.com/analytics.js" ASYNC DEFER></SCRIPT>
  </body>
</HTML>
`;

const parse5 = require("@starptech/prettyhtml-parse");
const htmlparser2TreeAdapter = require("parse5-htmlparser2-tree-adapter");

const ast = parse5.parse(text, {
  treeAdapter: htmlparser2TreeAdapter,
  sourceCodeLocationInfo: true,
  preserveCaseSensitiveTags: true
});
```

Issues:

- the `HTML`/`HEAD`/`BODY` tags are not recognized
- the `SCRIPT` tags are parsed as `type: "tag"` instead of `type: "script"`

**Comment by ikatyang** [comment]
I think we could switch to the fork in future PRs when the issue is fixed, I'd like to merge this PR first to continue the work.

(@StarpTech Could you enable the `issues` in your fork? otherwise I don't know how to report bugs other than ping you.)

**Comment by StarpTech** [comment]
@ikatyang I enabled issues.

**Comment by StarpTech** [comment]
@ikatyang this is actually no issue. You have to parse it with `parse5.parseFragment`. `parse5.parse` will wrap it into a separate document.

**Pull request merged**
