### PR TITLE
CLI: Don't use `logger` to print information

### PR DESCRIPTION
**Pull request by fisker**
## Description

Should not use `logger.log` to print information, for example

```js
prettier -v --loglevel silent
```

Should still print the version.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
What do you think about to add `logger.info(message)` method instead of using `console.log` directly?

**Comment by fisker** [comment]
I don't think this information is related to logger, it's just a `print()`.

**Review by sosukesuzuki — APPROVED** [review]

**Comment by fisker** [comment]
Maybe define a function `printToScreen()`? @sosukesuzuki

**Comment by sosukesuzuki** [comment]
Thanks. I prefer that, but I have no strong opionion

**Pull request merged**
