### PR TITLE
Fix ternary format in function call

### LINKED ISSUE #4338: Ternary expressions as call arguments can be difficult to read
I'm not sure whether it is by design or a bug, but it can be really difficult to see how many arguments the `fn` function is called with in the code below.

**Prettier 1.13.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzKAKAOlABLgIwEtUIAnKAYTKKgHM4yBZCAZwAs4ATABUYAcANnAAeAZQCGAdy6MANDnwTWAawAqZCADcEEgEJxdAETj8EXVgCUIUiVFYK8uOoKIBbVnADiggJ792VgAJCQAvCTIuADkICH5WNSI4RLhcAF4M3AkdMjJuPQkYTjJWPQgRTQg3PQBXOjpfKJqyQXwAMjbFfCyoCC5fKDhKaC42JglBQrgAeRypyzgYWghWru7cAH4eqBrJsmGIQy4xISIwOFYAdQmVK4lfa99cNe6kXBUIMHYJAgOkrwkbhmUGmBBWcAAqlApHBsqkcABKADcOBAchAcSW0FYyFAEU0Uh4EQQOJQ2QgRC4aJAyhgyFQE086IIZAkYBUixObNodGQMDINTg6NGYHpjKFIFonjIMB4rLobgkYsETJAACtWCI9Kz2ZzAXAADK0ODK1UQGowfgWgBMpol-Ai0uQIAIP18gmg1P4NFgl0pRWQAA4AAzo71sOCXVn8Z3ei6MHTUvIARxqRDycokCqVSAZKolnjcRD5AoLPOEAEUahB4Hb0TAfn6uAGkNb66yiK56MM3Irnb1BtSap41D9SXnPABfSdAA)
```sh
--parser babylon
```

**Input:**
```jsx
fn(
  bifornCringerMoshedPerplexSawder,
  askTrovenaBeenaDependsRowans,
  glimseGlyphsHazardNoopsTieTie === averredBathersBoxroomBuggyNurl  &&
    anodyneCondosMalateOverateRetinol 
      ? annularCooeedSplicesWalksWayWay 
      : kochabCooieGameOnOboleUnweave 
);

```

**Output:**
```jsx
fn(
  bifornCringerMoshedPerplexSawder,
  askTrovenaBeenaDependsRowans,
  glimseGlyphsHazardNoopsTieTie === averredBathersBoxroomBuggyNurl &&
  anodyneCondosMalateOverateRetinol
    ? annularCooeedSplicesWalksWayWay
    : kochabCooieGameOnOboleUnweave
);

```

**Expected behavior:**

Same as the input, probably.

### PR DESCRIPTION
**Pull request by malcolmsgroves**
This fixes #4338. The formatting of conditional expression in functional calls was hard to read. This PR results in the following format:
```javascript
fn(
  bifornCringerMoshedPerplexSawder,
  askTrovenaBeenaDependsRowans,
  glimseGlyphsHazardNoopsTieTie === averredBathersBoxroomBuggyNurl &&
    anodyneCondosMalateOverateRetinol
    ? annularCooeedSplicesWalksWayWay
    : kochabCooieGameOnOboleUnweave
);
```
While it would be preferable to indent the last two operands of the ternary expression, it seemed to me like that would require substantial refactoring of the printer because the last two operands are not in the scope of the test operand and therefore do not inherit the indentation level. At least this makes it easier to see how many args there are.

This is my first Prettier PR, so apologies for any oversights. Happy to try to get those last two lines to indent if anyone has any ideas for how to proceed.

### CODE REVIEW

**Comment by suchipi** [comment]
I think this is only halfway there; we need to indent the last two lines in this case, too (as you noted). I don't think we should merge a change until it does that as well.

**Comment by malcolmsgroves** [comment]
makes sense. I'm stuck on this one right now, so someone else can feel free to take up the issue or provide suggestions for how to proceed

**Comment by j-f1** [comment]
I propose merging this as-is since it’s strictly better than the current behavior, but leaving the issue open to figure out a better solution. How does that sound?

**Comment by suchipi** [comment]
@j-f1 sounds good to me

**Comment by j-f1** [comment]
Thank you for contributing @malcolmsgroves!

**Comment by thorn0** [comment]
@j-f1 You were going to keep #4338 open, but GitHub closed it automatically.

**Comment by j-f1** [comment]
Thanks for pointing that out! Fixed.

**Pull request merged**
