### PR TITLE
GraphQL: Directives

### PR DESCRIPTION
**Pull request by stubailo**

### CODE REVIEW

**Comment by vjeux** [comment]
If you fix the checks i'll merge it :)

**Comment by stubailo** [comment]
Hmm, maybe the GitHub being down means my newest stuff didn't get pushed, trying to push again.

**Comment by stubailo** [comment]
Odd, it still seems to pass locally and fail remotely.

**Comment by stubailo** [comment]
screenshot 2017-06-06 17 26 24

Can you tell me what this parser test failure means?

**Comment by vjeux** [comment]
Oh, this is running with AST_COMPARE=1 yarn test

**Comment by stubailo** [comment]
OK I see the problem now! I guess it also compares the output of the snapshot, and caught a real error.

**Comment by stubailo** [comment]
Yay! Thanks for the help, I will always run with that flag now.

**Comment by vjeux** [comment]
The ast tests are significantly slower and catch bugs once in a blue moon so I don't think it's worth doing it all the time. But if it puts your mind at rest, feel free to.

**Pull request merged**
