### PR TITLE
docs: add two plugins `pkg` and `sh`

### PR DESCRIPTION
**Pull request by JounQin**
`prettier-plugin-pkg` for `package.json`
`prettier-plugin-sh` for shell scripts

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
I think  we  should add some  descriptors to  these plugins.

@thorn0 @evilebottnawi

**Comment by thorn0** [comment]
@fisker Agree. This list probably needs to be turned into a table.

**Comment by kachkaev** [comment]
Should the plugins be inserted so that the list remained alphabetical?

**Comment by lipis** [comment]
Yes I agree that we have to turn this thing into a table.. but in a separate PR.. 

Some suggestions for the columns:

- Name
- Description
- AST (if it's changing the AST or not)
- Additional options
- (Anything else?)

**Pull request merged**
