### PR TITLE
Use `try/finally` in `AstPath`

### PR DESCRIPTION
**Pull request by fisker**
## Description

Use `try/finally` in `AstPath`, make them `try/catch` friendly.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
This definitely needs thorough benchmarking

**Comment by fisker** [comment]
I never thought this will cause permeance issue.

anyway, 

Before: 

```text
[debug] '--debug-benchmark' option found, measuring formatWithCursor with 'benchmark' module.
[debug] '--debug-benchmark' measurements for formatWithCursor: {
[debug]   "benchmark": "format x 0.13 ops/sec ±40.51% (5 runs sampled)",
[debug]   "hz": 0.1279763236020376,
[debug]   "ms": 7813.94536
[debug] }
```

After:

```text
[debug] '--debug-benchmark' option found, measuring formatWithCursor with 'benchmark' module.
[debug] '--debug-benchmark' measurements for formatWithCursor: {
[debug]   "benchmark": "format x 0.13 ops/sec ±39.04% (5 runs sampled)",
[debug]   "hz": 0.13366986736401562,
[debug]   "ms": 7481.117619999999
[debug] }
```

I don't know if I can trust those numbers, the same version result quite differently on small files. So I find a bigger one.

**Comment by thorn0** [comment]
Try-catch blocks were known to cause deoptimizations in old Node versions. Maybe it's not something to worry about anymore

**Comment by fisker** [comment]
I ran many times on https://gitpod.io/#https://github.com/prettier/prettier/pull/13216 with this

```sh
PRETTIER_PERF_REPEAT=1000 yarn perf:benchmark CHANGELOG.md
```

The result is very unstable, maybe our benchmark script can be trust?

**Review by thorn0 — APPROVED** [review]
```
Benchmark 1: node ./bench.mjs ast-path-try-catch serial
  Time (mean ± σ):     52.371 s ±  0.219 s    [User: 64.481 s, System: 3.545 s]
  Range (min … max):   52.127 s … 52.783 s    10 runs

Benchmark 2: node ./bench.mjs ast-path-try-catch parallel
  Time (mean ± σ):     52.813 s ±  0.369 s    [User: 62.492 s, System: 5.370 s]
  Range (min … max):   51.978 s … 53.233 s    10 runs

Benchmark 3: node ./bench.mjs next serial
  Time (mean ± σ):     51.750 s ±  0.269 s    [User: 63.739 s, System: 3.431 s]
  Range (min … max):   51.326 s … 52.067 s    10 runs

Benchmark 4: node ./bench.mjs next parallel
  Time (mean ± σ):     53.110 s ±  0.150 s    [User: 63.534 s, System: 5.411 s]
  Range (min … max):   52.831 s … 53.298 s    10 runs

Summary
  'node ./bench.mjs next serial' ran
    1.01 ± 0.01 times faster than 'node ./bench.mjs ast-path-try-catch serial'
    1.02 ± 0.01 times faster than 'node ./bench.mjs ast-path-try-catch parallel'
    1.03 ± 0.01 times faster than 'node ./bench.mjs next parallel'
```
I've run this benchmark 3 times and the results are consistently like this. 1% is not much, but it's real, not a measurement error.

I guess we can merge this. BTW you can remove the `try` method of `AstPath` now.

**Comment by fisker** [comment]
> BTW you can remove the try method of AstPath now.

No, we can't.
`AstPath#try` backup the whole stack, so whatever happened inside, the stack still correct.
Those methds don't work if error happens when call `.callParent()`.

**Comment by thorn0** [comment]
I don't see what you mean. You have added `finally` in `callParent`.

**Comment by fisker** [comment]
`.match` `.findAncestor` not `try/finnally`, we assume they won't throw.

**Comment by thorn0** [comment]
> `.match` `.findAncestor` not `try/finally`, we assume they won't throw.

They don't change the stack, so it doesn't matter.

**Pull request merged**
