### PR TITLE
Add docs for pnpm

### LINKED ISSUE #14433: Add docs support for Prettier usage with pnpm package manager
Include Docs of prettier with pnpm package manager

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #14433

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by kachkaev — APPROVED** [review]
Thanks for working on this! I tried `pnpm` [in a side project](https://github.com/kachkaev/website) recently and quite liked it actually!

**Review by fisker — APPROVED** [review]
Better copy changes to website/versioned_docs/version-stable

**Comment by sosukesuzuki** [comment]
@fisker Other docs changes in `next` hasn't been copied to `versioned_docs`, so I've skip copying in this PR.

**Comment by fisker** [comment]
I thought we are changing main branch.

**Pull request merged**
