### PR TITLE
Improved object-break heuristic

### PR DESCRIPTION
**Pull request by j-f1**
This changes the heuristic from breaking the object if it contains a newline somewhere inside it to only breaking if the newline is between the `{` and the first key. This allows users to easily collapse objects by deleting that linebreak without having to manually move the object onto one line.

- [x] I’ve added tests to confirm my change works.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by j-f1** [comment]
Ref #5170.

**Comment by lydell** [comment]
I kind of like the shortcut aspect of it, but I'm afraid this will be harder to explain/teach.

I think it's pretty easy to select the object and press the "join lines" keyboard shortcut most editors have (such as `ctrl+j`, or `J` in Vim).

**Comment by suchipi** [comment]
I'm in favor of this change, better DX for sure :+1:

**Comment by zackkrida** [comment]
Could this heuristic also be used for _destructuring_ objects? Makes sense to have that consistent to me. 

Would help deal with issues like the discussion at #4267

**Comment by j-f1** [comment]
@zackkrida since we don’t have any heuristic for destructured objects, it’s unlikely ATM.

**Comment by j-f1** [comment]
Actually, this might happen: https://github.com/prettier/prettier/issues/2550#issuecomment-437397749

**Pull request merged**
