### PR TITLE
playground: add (s)css examples

### PR DESCRIPTION
**Pull request by Haroenv**
see #3667

These are derived from Bootstrap, should there be a license comment?

### CODE REVIEW

**Comment by Haroenv** [comment]
It's MIT, so I'm not 100% sure if this is allowed without license text. It's such a small block that it doesn't matter I guess though 🤔  https://getbootstrap.com/docs/4.0/about/license/

**Comment by azz** [comment]
Yeah I really don't think it matters for tiny extracts. I guess you could put a comment in the code linking to bootstrap?

**Comment by j-f1** [comment]
What about putting something like this in the JS?

```js
// Excerpted from the Bootstrap source, which is licensed under the MIT license:
// https://github.com/twbs/bootstrap/blob/v4.0.0-beta.3/LICENSE
```

**Comment by Haroenv** [comment]
done now (sorry for earlier mistakes, commited on GitHub so didn't see the linting errors)

**Comment by Haroenv** [comment]
awesome 👌

**Pull request merged**
