### PR TITLE
Add an option to enable empty/self-closing tags conversion in JSX

### PR DESCRIPTION
**Pull request by MattiaMalonni**
- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by MattiaMalonni** [comment]
@evilebottnawi May I ask why?

**Comment by MattiaMalonni** [comment]
According to this #6452, seems like a lot of people are asking for that.

**Comment by evilebottnawi** [comment]
Answer is simple - https://prettier.io/docs/en/option-philosophy.html

**Comment by kachkaev** [comment]
See ESLint this rule from [eslint-plugin-react](https://www.npmjs.com/package/eslint-plugin-react): [self-closing-comp](https://github.com/yannickcr/eslint-plugin-react/blob/97a9f397d2a8a3ce3b2af893bdbb86bb2c1d4480/docs/rules/self-closing-comp.md)

I'm using it at work and in home projects, all works well. Switching to self-closing tags changes AST, which would be out of Prettier’s scope even if it still accepted options.

**Comment by MattiaMalonni** [comment]
@kachkaev TY.

@evilebottnawi Oh well, ok then. Should have read that post first..

**Pull request closed without merging**
