### PR TITLE
Fix tests for Windows and add Azure Pipelines for cross platform CI

### PR DESCRIPTION
**Pull request by damccorm**
**Issue**
I recently did a clean clone and tried to run tests, and a bunch of them failed. As I investigated, I realized that it was because I was using a Windows machine that has CRLF default line endings while all of the test snapshots were generated with LF default line endings. Basically there's 2 issues here:

1. Tests are failing for Windows because of line endings. This is especially alarming because it means that line endings weren't really being tested in the way we thought they were, a topic which has been a significant development area recently: see #5393 and #5327 for reference
2. These weren't caught by the current CI

**My solution**
To address (1), I set the default eol setting to LF in most tests. I also got rid of some recently added tests that rely on the default setting being eol and tried to make platform specific versions of these (see eol-crlf.js and eol-lf.js).

To address (2), I added Azure Pipelines which can natively build/test cross platform. Right now, appVeyor isn't catching this because it uses Unix line endings, but Pipelines runs natively on Windows so it has the default CRLF line endings. 

Full disclosure, I work at Microsoft on Pipelines, but I also think its the best solution to this problem - it has big advantages in the form of unlimited minutes, 10 parallel jobs, and the ability to build/test for all platforms with one service.

**Additional Info**
[Here](https://dev.azure.com/prettier/prettier/_build?definitionId=3) is the pipeline I tested this with on my fork. You can see its [failing 36 tests on its first build](https://dev.azure.com/prettier/prettier/_build/results?buildId=58&view=ms.vss-test-web.test-result-details), those are the tests it was failing before I changed any tests.
image

After my updates, it [passes all tests](https://dev.azure.com/prettier/prettier/_build/results?buildId=70&view=logs) across all platforms. This replicates all of the current CI in this project.
image

- [x] I’ve added tests to confirm my change works.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by damccorm** [comment]
AppVeyor failing on this PR kinda demonstrates the CI issue here. You can see in the logs that it was expecting a snapshot with CRLF line endings (which was generated from my local Windows box), but instead it received a snapshot with LF endings (generated by AppVeyor).

**Comment by ikatyang** [comment]
Wow, I didn't know that Azure pipeline is free for open source and supports all platform. This looks good to me, AppVeyor is somehow slow and its permission management is weird IMO. (Do people with write access automatically get the permission on Azure pipeline, just like Travis?)

@prettier/core what do you think?

**Comment by willsmythe** [comment]
@ikatyang - I am a product manager at Microsoft on Azure Pipelines and can help with these and other questions.

Currently Azure Pipelines permissions are managed separately from GitHub's, but we have plans to improve this. Until this ships you would need to add other users to your Pipelines project and give them the necessary permissions. It's pretty easy to add users using their @gmail.com address (or other), but I agree it will be nice when this "just works".

[Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) being free for open source projects (with unlimited build minutes and up to 10 parallel build jobs) was just announced in September, so it's fairly new news. And, yah, having a single CI service build/test across Linux, macOS, and Windows is definitely one of the top reasons other projects are moving to Azure Pipelines.

Let us know if we can help with other questions!

**Comment by duailibe** [comment]
Wow thanks for opening this.

This looks strictly better than AppVeyor, so I think we can merge this, and test the Mac/Linux integration for a bit and then change to use only one service?

**Comment by damccorm** [comment]
@j-f1 it should be pretty straightforward, just need the following steps:
1. Merge this PR in. You probably want to disable AppVeyor here too since it fails some of the tests I added.
2. I'll transfer access of the pipelines organization I've been using to you. You can also create your own, but I figured you'd like the org name Prettier.
3. You can create a pipeline pointing at master of this repo. To do this, just go to the [Pipelines tab](https://dev.azure.com/prettier/prettier/_build?definitionId=3), click New->New Build Pipeline and follow the prompts. It should automatically detect the Yaml from this PR, so no additional work should be needed there.

At that point, it should automatically queue builds on PRs and for CI. You can add badges/checks as appropriate.

**Comment by willsmythe** [comment]
@j-f1 - regardless of whether you create a new Azure Pipelines org or @damccorm transfers the https://dev.azure.com/prettier org over (recommended), follow the steps to [install the Azure Pipelines app](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=vsts#integrate-using-the-github-app) into the prettier GitHub org (or just this repo). This process also steps you through creating the pipeline for your main repo.

**Comment by j-f1** [comment]
I’ve disabled access to Appveyor in the Prettier settings. Is that enough to stop it from running?

**Comment by j-f1** [comment]
@ikatyang Done!

**Comment by ikatyang** [comment]
Weird, it's still running. Should we remove the project from AppVeyor?

**Comment by damccorm** [comment]
@j-f1 @ikatyang @duailibe I just sent you email invitations to join the org as administrators. Once one of you confirms access I'll transfer ownership of the org.

**Comment by j-f1** [comment]
I only deleted the webhooks after that commit, so it probably still picked it up.

> Should we remove the project from AppVeyor?

I don’t want to do that since it would remove the logs from previous builds, which  might have value.

**Comment by ikatyang** [comment]
I guess I just joined the org? I can access https://dev.azure.com/prettier now.

**Comment by damccorm** [comment]
Great! I just made you the org owner, you should be able to [create the Pipeline](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=vsts#integrate-using-the-github-app) in the prettier project now.

**Comment by j-f1** [comment]
Should I disable boards and repos for the Azure project? Also, how can I set avatars for the org and project @damccorm?

**Comment by damccorm** [comment]
@j-f1 disabling boards/repos makes sense to me. Concerning avatars, unfortunately we don't currently support updating avatars for orgs/projects. I agree it would be nice though, hopefully that will change soon.

**Comment by ikatyang** [comment]
Not quite sure how to create the pipeline, I clicked the <kbd>install our app from the GitHub Marketplace</kbd>.

<details>
<summary>image: install our app from the GitHub Marketplace</summary>

image

</details>

<br />

It navigated me to the GitHub App settings, I clicked <kbd>Save</kbd>.

<details>
<summary>image: GitHub App settings - save</summary>

image

</details>

<br />

There's no prettier org in the list.

<details>
<summary>image: setup your azure pipelines project</summary>

image

</details>

<br />

It seems I have two accounts but I cannot choose which one to use, I'm confused.

<details>
<summary>image: two account</summary>

image

</details>

---

@j-f1 Are you able to create the pipeline?

**Comment by j-f1** [comment]
I can’t seem to create it either; any suggestions @damccorm?

**Comment by damccorm** [comment]
Whoops, I think this was my mistake - I forgot to disconnect the org from the Microsoft user directory. Would you be able to temporarily add me back as an administrator so I can do that? Here are the steps to do that, sorry for the inconvenience.

1. Go to https://dev.azure.com/prettier/_settings/security?_a=members
2. Select the "Project Collection Administrators" group and then select the "Members" tab
3. Click Add, enter "damccorm@microsoft.com", click Save changes

Note: it may take a few seconds for the list of members to be updated.

**Comment by j-f1** [comment]
Looks like @ikatyang has to do that.

**Comment by ikatyang** [comment]
I logout and login several times but still got this error:

image

I made you the owner again so you should be able to do those things?

**Comment by dannymccormick3** [comment]
Ok, I disconnected it from the Microsoft directory and added @ikatyang back as the project owner, it should be good to go. I'm going to stay in the project as an administrator until its clear this fixed it if that's ok - I'll remove myself once we have a working pipeline. Sorry for the delay on this.

**Comment by damccorm** [comment]
Ok, I disconnected it from the Microsoft directory and added @ikatyang back as the project owner, it should be good to go. I'm going to stay in the project as an administrator until its clear this fixed it if that's ok - I'll remove myself once we have a working pipeline. Sorry for the delay on this.

**Comment by ikatyang** [comment]
It works, @damccorm thank you!

https://dev.azure.com/prettier/prettier/_build/results?buildId=72&view=logs

**Comment by damccorm** [comment]
Awesome! I went ahead and removed myself from the org.

One additional note, it looks like somewhere in this process the webhooks got messed up so I don't think it will automatically queue builds. Fortunately, the fix for this is really easy, @ikatyang since you created the pipeline just follow this link and click restore: https://dev.azure.com/prettier/prettier/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=5&view=Tab_Triggers

Other than that, I think the only remaining steps are:
1. Add Azure Pipelines as a check for the PR
2. (optionally) [Add a badge](https://docs.microsoft.com/en-us/azure/devops/pipelines/get-started-yaml?view=vsts#get-the-status-badge) to the Readme
3. (optionally) Switch to just use one service once Pipelines is confirmed to be working for a while

If you run into any issues/have any Pipelines questions, feel free to ping either me (damccorm@microsoft.com) or Will (wismythe@microsoft.com) or just follow up in this thread.

**Comment by ikatyang** [comment]
It seems we don't need to <kbd>restore</kbd>? I didn't see it.

image

**Comment by ikatyang** [comment]
Not quite sure why #5491 worked but #5490 did not. 🤔

**Comment by dannymccormick3** [comment]
Not 100% sure, but I think it might be because I tried to create a PR with the exact same code I used in this PR which has been merged, so it didn't recognize that it was actually distinct. I think if it worked for #5491 its probably fine, I must have just gotten my wires crossed. We can continue to monitor it, but I think it should be good to go.

**Comment by damccorm** [comment]
Not 100% sure, but I think it might be because I tried to create a PR with the exact same code I used in this PR which has been merged, so it didn't recognize that it was actually distinct. I think if it worked for #5491 its probably fine, I must have just gotten my wires crossed. We can continue to monitor it, but I think it should be good to go.

**Comment by damccorm** [comment]
@ikatyang @j-f1 @duailibe just wanted to follow up and see how things are going with Pipelines! Do you feel like its working as well as CircleCI and Travis/have you run into any problems with it that I could help out with?

**Comment by j-f1** [comment]
It’s been working pretty well from my viewpoint, but @ikatyang probably has more knowledge about this. Thanks for getting us set up!

**Comment by ikatyang** [comment]
It works great! Though there're still some missing features; they're not that critical for us but it'd be better if we could have them. I'm not sure if there's a repo that we can send feature requests to, so I wrote them down here:

Missing features:

- one status/check per job (it's possible to use one status/check per pipeline but it looks overcomplicated to me.)
  image
- Azure Pipelines does not support cache, though it's fast enough that the build time is still acceptable, it'd be better to be faster.
- CircleCI can store artifacts in the previous job and pass them to the next job. From what I understand from the docs on Azure Pipelines, it seems it only supports executing job depends on the previous job, but the artifacts can not be passed to the next job.
  image


Feature requests:

- I saw Azure Pipelines also supports coverage, and somebody even built a badge for it (`Azure DevOps coverage` on https://shields.io/). I wonder if it's possible to have something like `codecov` in Azure Pipelines.
  image

**Comment by ikatyang** [comment]
@damccorm Thanks for the detailed explanation!

> You could add a seperate "linting pipeline", add the line `condition: variables.linting_job` to the YAML file, and only set that true in the linting pipeline.

I just [tried to split out those jobs into multiple pipelines][azure-pipelines-on-my-fork] on my fork, it works but there're some confusing things happened:

- some pipelines are still marked as pending on GitHub even if it's passed on Azure Pipelines:
  <details><summary>image: commit status on my fork (<a href="https://github.com/ikatyang/prettier/commits/chore/azure-pipelines">url</a>)</summary>
  
  
  </details>

- the start time of the [last pipeline] is slower than the [first pipeline] about 2 min.
  - this may be caused by the fact that I created a lot of [reusable step templates], I wonder if it's possible to have inline templates to reduce the I/O time.
- it's hard to navigate the same commit between different pipelines on the Azure Pipelines website, we need to:
  1. go back to the Builds page
  1. select the pipeline
  1. select the commit (this can be hard if there're a lot of different PR builds)
  1. select the job
     <details><summary>(and also the jobs view here looks confusing since there're a lot of <i>skipped</i>)</summary></details>

  comparing to the current single pipeline approach:

  1. select the job
  1. done!

[first pipeline]: https://dev.azure.com/ikatyang/prettier/_build?definitionId=1
[last pipeline]: https://dev.azure.com/ikatyang/prettier/_build?definitionId=5
[reusable step templates]: https://github.com/ikatyang/prettier/tree/chore/azure-pipelines/.azure-pipelines/steps
[azure-pipelines-on-my-fork]: https://dev.azure.com/ikatyang/prettier/_build

---

Summaries from my recent experiments: (pros: ⭕️, cons: ❌)

Single pipeline:

- ❌only one status/check
- ❌only one badge
- ⭕️navigation between jobs is easy
- ⭕️no need to configure on the Azure Pipelines website, everything is controlled by the yaml config
- ⭕️no need to think about the pipeline start time

Multiple pipelines:

- ⭕️can have multiple status/check, we can observe the entire status at a glance
- ⭕️can have multiple badges (e.g., one for Windows, one for Linux, etc.)
- ❌navigation between jobs (across pipelines) can be hard
- ❌need to configure on the Azure Pipelines website, which means it's a global setting and it's not possible to only enable it in the specific PR (for experiments)
- ❌the pipeline start time may be slow

Though I'd love to have multiple status/check, the pros for single pipeline look more important to me.

**Comment by damccorm** [comment]
> some pipelines are still marked as pending on GitHub even if it's passed on Azure Pipelines

Thanks for the heads up, that looks like a bug. I'll file that internally and hopefully we can get that behavior fixed.

> the start time of the last pipeline is slower than the first pipeline about 2 min. this may be caused by the fact that I created a lot of reusable step templates, I wonder if it's possible to have inline templates to reduce the I/O time.

I'm not totally sure why this is happening, I haven't seen broken out step templates slow things down, but that is possible.

> It's hard to navigate the same commit between different pipelines on the Azure Pipelines website, we need to

Agreed, it would be nice to have a view of all the pipeline builds for a commit

> Though I'd love to have multiple status/check, the pros for single pipeline look more important to me.

That makes sense to me for now, hopefully we can reach a point where some or all of those cons can be reduced/eliminated

@willsmythe do you have better ideas for any of the above challenges (or a better way to get multiple status checks)?

**Pull request merged**
