### PR TITLE
Fix/ts interface heritage

### PR DESCRIPTION
**Pull request by despairblue**
This also contains #1599 and #1600

### CODE REVIEW

**Comment by vjeux** [comment]
Sorry for the slow review on the other one. If you split the other one, I can ship the part without the comments and you can push this one then

**Comment by vjeux** [comment]
This needs to be rebased

**Comment by despairblue** [comment]
Yep, I also need to spent some time to get the comments printed.

**Comment by vjeux** [comment]
Random guess about the comment: the code that attaches comments iterates through ast nodes via ast types, maybe the type is missing from there so it attaches to the parent.

**Comment by despairblue** [comment]
Woah, you're a genius, never thought of that. I'll check that tomorrow.

**Comment by despairblue** [comment]
Ok, the culprit was that field names where missing or incorrect in `typescript-ast-nodes.js`.

I also fixed the rest of the TypeScript tests except for the ones waiting for https://github.com/eslint/typescript-eslint-parser/pull/270.

But I also broke some flow tests, which I need to figure out later this week. I guess I changed some `join(...)` calls to `path.call(print, ...)` since the typescript-eslint-parser AST contains specific nodes wrapping things like type parameter whereas the flow AST just uses an array.

**Comment by despairblue** [comment]
@vjeux done, all tests pass. :)

**Comment by vjeux** [comment]
Yay!

**Pull request merged**
