### PR TITLE
Use yarn 3

### PR DESCRIPTION
**Pull request by fisker**
## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by kachkaev** [comment]
Do we need to keep multiple `yarn.lock` files? Yarn 3 has an improved ‘focus mode’ for workspaces, if I remember correctly. In theory, there can be just one `yarn.lock` at the top of the repo.

**Comment by fisker** [comment]
> Do we need to keep multiple yarn.lock files?

I think we do, we run release script from `scripts/release` and during the release it removes the one in root. But I'm not sure.

**Comment by fisker** [comment]
> Before we decide to use Yarn 3 in the main branch

Unfortunately, the CI log is telling us we can't, it seems yarn 3 don't support Node.js 10.

**Comment by kachkaev** [comment]
> Yarn 3 don't support Node.js 10

Yeah, that's a shame. We can probably finish this PR after Prettier v3 is out then. We'll have an opportunity to drop Node 10 and 12 I guess.

**Pull request merged**
