### PR TITLE
Fix some issues from melpa PR

### PR DESCRIPTION
**Pull request by rcoedo**
This PR addresses some issues that @purcell commented in https://github.com/melpa/melpa/pull/4765

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks!

**Comment by rcoedo** [comment]
That was fast!

Thank you 😄

**Comment by vjeux** [comment]
I know nothing about this emacs mode, so I prefer to trust you :p

By the way, I've considered moving this into its own repo `prettier/prettier-emacs` or something. Would you be interested in helping with this?

**Comment by rcoedo** [comment]
My elisp skills are limited but you can count with my help 👍

**Comment by vjeux** [comment]
I'll set this up tonight, thanks!

**Comment by vjeux** [comment]
I just created https://github.com/prettier/prettier-emacs and gave you admin access, feel free to move everything over :)

**Pull request merged**
