### PR TITLE
Test: Skip install for standalone test

### PR DESCRIPTION
**Pull request by fisker**
## Description

standalone test eval from code, no need install, just read file from `dist/`

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
Why do we need the install for non-standalone production tests?

**Comment by fisker** [comment]
I don't have an answer, I thought about this before, maybe prevent unexpected things like plugin searching?

Sometimes I even disable install when I run production test on my machine.

**Review by thorn0 — APPROVED** [review]

**Review by duailibe — APPROVED** [review]

**Comment by duailibe** [comment]
> Why do we need the install for non-standalone production tests?

We had a bug that after the "bundle everything into a single file" step, there were some `require("../../file")` left, that would still work when running inside the Prettier folder. So we started to test the production build this way (install the final package, in a tmp folder)

**Comment by fisker** [comment]
> there were some require("../../file") left, that would still work when running inside the Prettier folder.

Wow, yes, this make sense.

**Pull request merged**
