### PR TITLE
Add alias and null value

### PR DESCRIPTION
**Pull request by stubailo**
Also, this means we pass the kitchen sink test case! 🎉 

I think that means the only thing we need to add is comments and we are good to go for an initial release!

### CODE REVIEW

**Comment by vjeux** [comment]
The next step is to get your hand on as much graphql as possible and run --debug-check on it to make sure that it outputs correct code. And look at the output to make sure that it looks good.

The bar for announcing a language support is really high. I want to make sure that the first impression is awesome and "it just works".

There are a ton of "pretty printers" out there. The reason why prettier is successful is that we spent a huge amount of time getting all the edge cases right.

The good news is that GraphQL is simpler so that shouldn't take as long, but just having printed things is not enough. That's just the first step :)

**Comment by vjeux** [comment]
Also don't you need union types?

https://github.com/prettier/prettier/pull/2014

**Comment by stubailo** [comment]
@vjeux that PR is for the schema language, I'm mostly concerned with the query language at the moment.

Is there something in particular I can look at to figure out how to get comments working?

**Comment by stubailo** [comment]
@leebyron if you have a moment, can you check my style preferences in the kitchen sink example? Curious if you have some opinions there.

**Comment by leebyron** [comment]
There seem to be inconsistency between spacing in List and Object literals.

It would be helpful to see tests that cover edge cases like when alias is used on a >80c line

**Comment by stubailo** [comment]
@leebyron this is intentionally adding spaces inside Object literals, but not inside List literals, to match the behavior of prettier for JavaScript.

**Comment by vjeux** [comment]
@stubailo There's a setting to tweak that: `bracketSpacing`. Does it respect the setting?

**Pull request merged**
