### PR TITLE
Remove `lodash`

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Based on #12604

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
@fisker I tried to fix type errors, but it is hard. Some type errors are solved by `@ts-expect-error` and casting to `any`.

**Comment by fisker** [comment]
Good job, Thanks! Shouldn't we try to add types to the new functions to solve problems?

**Comment by sosukesuzuki** [comment]
I've added types for lodash-like functions! But it does not solve type errors.

**Comment by fisker** [comment]
I don't know about types. I'm fine with whatever you think the best.

**Review by fisker — APPROVED** [review]

**Pull request merged**
