### PR TITLE
Fix yaml comment in non-singleline items missing space before `#`

### LINKED ISSUE #16443: Incorrect YAML formatting produces invalid YAML.
**Prettier 3.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDARmJACAxBsAHSmzwFpsAGSgRmJABoQIAHGAS2gGdlRUAnfhADuABQEIeKVABthqAJ48m6fqjABrODADKqALZwAMuyhxkAM1lc4KtZu06W60wHNkMfgFdbIG-vYPb184AA8WOH52Q1hZABVIqAF2OCkrGRsmLjcZOABFLwh4S2tfACsuUJ0c-MLipHTMkABHOrhRIRYpNC4yMzgAE0HGEE9Udhk3AGEIfX1UZDQZGRHsqFdcgEEYT3Z0L3hRSJMzEozfAAsYfRkAdQv2eC5nMDgdSUf2ADdHhUWwLjKEBfHwASSgQ1gOjAUTYmwhOhgClyZyaLCENluahYi3RqUiX3MTFMNn4MA6qFc81Rvmc-FJiwUBhWTHRphgt3YAxgF2QAA5KEx+HBWuxhRSqQsGqUmDAMJzubykAAmJheGxxDBpGUgOD6dCDIYDIyodZeSlwABiEH48x2bkWqAOEBAAF9XUA)

```sh
--parser yaml
```

**Input:**

```yaml
abc: #abc
  #- 001

```

**Output:**

```yaml
abc:#abc
  #- 001

```

**Expected output:**

```yaml
abc: #abc
  #- 001
```

**Why?**
The output removes the space between `abc:` and `#abc` resulting in a bad YAML

### PR DESCRIPTION
**Pull request by fyc09**
## Description

Fix #16443. I added an if statement to insert a space before the comment when `MappingValue` has a `trailingComment`.

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Please add changelog https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md#pull-requests

**Comment by fyc09** [comment]
Normally, log of “Install dependencies” ends with "Done with warnings in ?s ?ms", but those [failing actions](https://github.com/prettier/prettier/actions/runs/10017628927/job/27692196602?pr=16489) seem to start testing before dependencies are installed, and complains “Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)”. How can I solve this?

**Comment by fisker** [comment]
#16491

**Comment by fisker** [comment]
Close/re-open to apply #16491

**Review by fisker — APPROVED** [review]

**Comment by fyc09** [comment]
@fisker Review please and give feedback or merge this PR.

**Comment by fyc09** [comment]
@fisker Review please and give feedback or merge this PR.

**Comment by fisker** [comment]
I've approved, waiting for other reviews.

**Comment by fyc09** [comment]
@sosukesuzuki Review please and give feedback or merge this PR.

**Review by sosukesuzuki — APPROVED** [review]

**Pull request merged**
