### PR TITLE
CSS: New option «CSS Selector List on Same Line» and changed default behaviour

### PR DESCRIPTION
**Pull request by yuchi**
Following #1962 this PR changes the behaviour of the CSS Printer so that every selector in a selector list will be printed in its own line. A new option enables the previous behaviour.

This new behaviour is the one followed by
- Bootstrap ([see example][twbs-example], but [not enforced][twbs-lint]);
- Foundation for Sites ([see example][zurb-example], but [not enforced][zurb-lint]);
- Pure CSS ([see example][pure-example], but not enforced because using CSS Lint ¹)
- Semantic UI ([see example][sem-example], but not enforced because using CSS Lint ²)
- Many other

( <sup>1, 2</sup>: CSS Lint doesn’t have formatting linting rules. )

[twbs-example]: https://github.com/twbs/bootstrap/blob/2d8789508937c98782cba39bd74dc8f145050d97/scss/_button-group.scss#L20
[twbs-lint]: https://github.com/twbs/bootstrap/blob/2d8789508937c98782cba39bd74dc8f145050d97/.scss-lint.yml#L464
[zurb-example]: https://github.com/zurb/foundation-sites/blob/b6a8255d4e44e5c19f63b1c9f8387918bfb60883/scss/components/_tabs.scss#L105
[zurb-lint]: https://github.com/zurb/foundation-sites/blob/b6a8255d4e44e5c19f63b1c9f8387918bfb60883/.sass-lint.yml#L370
[pure-example]: https://github.com/yahoo/pure/blob/master/src/menus/css/menus-skin.css#L35
[sem-example]: https://github.com/Semantic-Org/Semantic-UI/blob/d9ac759e7eb480dc896988ac5d6fe4e0553a4cbb/src/definitions/elements/list.less#L24

## Example

Given this input:

```css
.a,.b,.c {
  color: red;
}
```

New output:

```css
.a,
.b,
.c {
  color: red;
}
```

Previous behaviour (can be enabled with option):

```css
.a, .b, .c {
  color: red;
}
```

## New option

To revert back to the previous behaviour we created the `cssSelectorListSameLine` option, which defaults to `false`.

From the CLI can be used as `--css-selector-list-same-line`.

The name of the option comes from the Style lint rule: [`selector-list-comma-newline-after`](https://stylelint.io/user-guide/rules/selector-list-comma-newline-after/).

### CODE REVIEW

**Comment by yuchi** [comment]
.cc @evilebottnawi for their work on [`stylelint-plugin-prettier`](https://github.com/vjeux/stylelint-plugin-prettier)

**Comment by vjeux** [comment]
Hey. I've been thinking about it some more and I believe that you are right. This should be the way we print CSS. If you remove the option, I'll merge it in! Thanks

**Comment by yuchi** [comment]
Thank you. This is the main stopper to adopt it in a lot of our projects.

We'll report other minor issues over the time.

Glad to help!

**Comment by yuchi** [comment]
@vjeux I didn’t update all failing snapshots but I can do that in another commit. Do you want me to do that and probably also rebase?

**Comment by SimenB** [comment]
Snapshots should be updated. https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md

**Comment by yuchi** [comment]
Thanks @SimenB, updated them. Should I rebase to master also?

**Comment by yuchi** [comment]
@vjeux Totally missed «If you remove the option, I'll merge it in!»

**Comment by yuchi** [comment]
Close in favor of #2047

**Pull request closed without merging**
