### PR TITLE
Add indentation back to nested ternaries

### PR DESCRIPTION
**Pull request by rattrayalex**
Reverts https://github.com/prettier/prettier/pull/5039/commits/a7580eb53b3f6983acaa713cb8843439b4a6c61f, which was intended to address https://github.com/prettier/prettier/issues/737

Fixes https://github.com/prettier/prettier/issues/5814

Alternative/complementary approaches were proposed in https://github.com/prettier/prettier/issues/9561, with https://github.com/prettier/prettier/pull/13183 emerging as the intended successor, as it addresses several of the shortcomings of this approach.

Headline examples, pulled from [the tests](https://github.com/rattrayalex/prettier/pull/12/commits/2a127d39970fba3a63c40d434d15d71f55e0c090#diff-6755425a75ca1290cf0caf067010b27eaad4bdfb8202c94bb2a21b55737ba02bL2340-R2389):

```jsx
const message =
  i % 3 === 0 && i % 5 === 0
    ? "fizzbuzz"
    : i % 3 === 0
      ? "fizz"
      : i % 5 === 0
        ? "buzz"
        : String(i);

const paymentMessage =
  state == "success"
    ? "Payment completed successfully"
    : state == "processing"
      ? "Payment processing"
      : state == "invalid_cvc"
        ? "There was an issue with your CVC number"
        : state == "invalid_expiry"
          ? "Expiry must be sometime in the past."
          : "There was an issue with the payment.  Please contact support.";

children && !isEmptyChildren(children)
  ? children
  : props.match
    ? component
      ? React.createElement(component, props)
      : render
        ? render(props)
        : null
    : null;

// Note that JSX stays the same, eg:
const StorybookLoader = ({ match }) =>
  match.params.storyId === "button" ? (
    <ButtonStorybook />
  ) : match.params.storyId === "color" ? (
    <ColorBook />
  ) : match.params.storyId === "typography" ? (
    <TypographyBook />
  ) : match.params.storyId === "loading" ? (
    <LoaderStorybook />
  ) : match.params.storyId === "deal-list" ? (
    <DealListStory />
  ) : (
    <Message>
      <Title>{"Missing story book"}</Title>
      <Content>
        <BackButton />
      </Content>
    </Message>
  );
```

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by askuzminov** [comment]
Original

```ts
const pickBgColor = (colorName: string) =>
  colorName === "active"
    ? colorName === "active"
      ? "var(--blue2)"
      : colorName === "inactive"
    : colorName === "inactive"
      ? "var(--blue1)"
      : colorName === "success" || colorName === "abc"
        ? colorName === "abc"
          ? "var(--blue2)"
          : "var(--blue23)"
        : "var(--red4)";

const message = (i: number) =>
  i % 3 === 0 && i % 5 === 0
    ? "fizzbuzzfizzbuzzfizzbuzzfizzbuzz"
    : i % 3 === 0
      ? i % 3 === 0
        ? "ffizzbuzzfizzbuzzfizzbuzzfizzbuzzizz"
        : i % 5 === 0
      : i % 5 === 0
        ? "fizzbuzzfizzbuzzfizzbuzzfizzbuzz"
        : String(i);
```

Current RP

```ts
const pickBgColor = (colorName: string) =>
  colorName === "active"
    ? colorName === "active"
      ? "var(--blue2)"
      : colorName === "inactive"
    : colorName === "inactive"
      ? "var(--blue1)"
      : colorName === "success" || colorName === "abc"
        ? colorName === "abc"
          ? "var(--blue2)"
          : "var(--blue23)"
        : "var(--red4)";

const message = (i: number) =>
  i % 3 === 0 && i % 5 === 0
    ? "fizzbuzzfizzbuzzfizzbuzzfizzbuzz"
    : i % 3 === 0
      ? i % 3 === 0
        ? "ffizzbuzzfizzbuzzfizzbuzzfizzbuzzizz"
        : i % 5 === 0
      : i % 5 === 0
        ? "fizzbuzzfizzbuzzfizzbuzzfizzbuzz"
        : String(i);
```

This is a good change as the tree of conditions is visible. It is easier to navigate and refactor using it (for example, move too large branches into separate variables to simplify the logic).

**Comment by thorn0** [comment]
How about keeping nested ternaries flat (like now) only if all the nesting happens in the else-branches?

**Comment by troglotit** [comment]
@thorn0 as I said in original issue, it will create noise in falsy branch when you add or remove in truthy branch.

**Comment by thorn0** [comment]
@troglotit But how often is that going to happen? Not too often, isn't it? So this might be a good enough trade-off.

**Comment by troglotit** [comment]
@thorn0 yeah... but the idea of alternating styles based on an arbitrary "looks good" is what irks me here.

**Comment by mike-marcacci** [comment]
I'd like to cross-post [this comment of mine](https://github.com/prettier/prettier/issues/9561#issuecomment-720602459) because I believe it introduces a strategy for putting format specification in the hands of the developer, without the addition of an option to prettier (which is obviously out of the question):

> @rattrayalex thanks for testing out using my example. I have a couple follow-up comments based on the results and a bit more thought here. Instead of just announcing my preferences here, I think it might be more useful to explain my priorities and criteria for whatever a "good" solution here would exhibit. Maybe other folks agree or disagree:
> 
> 1. HIGH PRIORITY: All paths within the same ternary MUST be formatted under the same rules; otherwise the continuous context switching makes the logic exceedingly difficult to follow.
> 2. HIGH PRIORITY: Perhaps with the exception of inlining a short, single-branch expression, ternary formatting should not change dramatically with the addition, removal, or reordering of paths; otherwise the large changes make it difficult to write (when auto-formatting is used) and difficult to review (as file diffs hide the logical change).
> 3. MEDIUM PRIORITY: The total number of different formats should be small; otherwise, a developer or reviewer will have to context switch repeatedly even within the same file.
> 
> Adding a new configuration option is obviously out. However, there is precedent in prettier for applying different rules based on the _manually-formatted context_. For example, prettier is perfectly happy to leave both of these alone, assuming they don't break the max column width:
> 
> ```js
> const a = { a: "a", b: "b" };
> 
> const b = {
>   a: "a",
>   b: "b"
> };
> ```
> 
> Said a different way, prettier uses the existing formatting to decide whether the object's field definitions will be inline or on distinct lines.
> 
> Could we do the same for ternaries? **If we use the ternary root as a cue, we could apply the "chosen" formatting to all child paths.** This would allow the best format to be "chosen" by the developer and enforced by prettier without the need for arbitrary heuristics. This would satisfy my 2 biggest criteria, and leave the third in the hands of me and my team.

**Comment by mike-marcacci** [comment]
This would also have the benefit of reducing "diff trauma" caused by changing the "default format" (assuming no valid root-level format can be inferred) back to the classic tree-like indentation, or to some new "compromise" format.

I would also argue that this would generally remove the need for these "compromise" formats and allow us to support a minimal number of existing "tried and true" ones.

**Comment by mike-marcacci** [comment]
🤦 I meant to add these previous comments to the issue, not the PR. Will delete from GH momentarily (sorry for the duplicate notifications to those following both).

**Comment by rattrayalex** [comment]
I think it's best to keep this PR a straight up-and-down, one-line revert to previous behavior.

**Comment by thorn0** [comment]
It can't remain a one-liner. If only because turning TS conditional chains into pyramids is not an option. As you already know, the current formatting for TS conditional gets its share of criticism, but those complaints have nothing to do with "bring the indentation back".

**Comment by fisker** [comment]
We are close to v3 release, @rattrayalex want push this forward? Personally, I'm 👍 for this change.

**Comment by rattrayalex** [comment]
Yeah I really do. I've just been blocked on writing an extensive PR description / blog post justifying the change, and any merge conflicts or corner case bugs that may be lurking. 

I'd love help getting it over the line!

I might be able to devote some time to it this weekend...

**Comment by rattrayalex** [comment]
(thanks for the words of support btw)

**Comment by rattrayalex** [comment]
@fisker would you mind taking a look at https://github.com/prettier/prettier/pull/13183 instead, which supersedes this?

**Review by sosukesuzuki — APPROVED** [review]

**Comment by sosukesuzuki** [comment]
Wait for @fisker review before merging

**Comment by ADTC** [comment]
My support goes 100% to this, and 0% to #13183 😄

**Comment by rattrayalex** [comment]
gentle bump @fisker (this is blocked on you, and you'd previously given it a thumbs-up)

**Review by fisker — APPROVED** [review]

**Comment by u3u** [comment]
Unbelievable! It's been 3 years! It finally merged!

**Comment by ADTC** [comment]
At least, we finally have this, until it gets superseded by #13183 (which will probably happen, whether we like it or not).

Regardless, **thank you so much for the merge.** This should have been there in the first place.

**Pull request merged**
