### PR TITLE
Fix Chained Call Wrapping Error #12433

### PR DESCRIPTION
**Pull request by Harry-Hopkinson**
## Description

Fixed the Chained Call wrapping error, in which Prettier was putting an array on a new line instead of the function.
Fix for https://github.com/prettier/prettier/issues/12433

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
If you want work on this, you may want learn more about estree.

**Comment by fisker** [comment]
Can you stop wasting your time? None of your code make sense,

**Comment by fisker** [comment]
You are not even close to the solution.

**Comment by fisker** [comment]
I appreciate your passion, do you know something about AST or EStree?

**Comment by Harry-Hopkinson** [comment]
I did some research as you suggested.

**Comment by fisker** [comment]
I don't want to hurt your feeling, but I don't want you to waste your time either. `foo[bar]` is not an array, it's computed `MemberExpression`. If you still want to work on this, send a PR on your own fork, feel free to ping me or ask me questions. This is much more trick than you thought.

**Comment by Harry-Hopkinson** [comment]
Okay

**Pull request closed without merging**
