### PR TITLE
Print end-of-line comment for `continue`/`break` statements

### LINKED ISSUE #12073: Prettier [error] -> Comment "' + comment.value.trim() + '" was not printed..."
[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBuABAWwgEwK4A2cAdHAB4AOEATjAM7F0AWcBBAomXGOgLzoAzPFDAwAltHTNWHLmAAUkTJgCGUHAEoAOlHTpg6AG4rq6AmKhw6fKSzak5iiMrU4ANMDpiisJDGp4cAC+GsQQeDAUEYwU5jDyAPRaOgnauugYBBAA5vIARhAEOE4u6hppehgCNOjyxqZi6BZmFlYVevotlnQA2mIAusT+Ypg6HRlNArUAhObdff0a6JCwFoHoCQlSANZiFOh5BGrbXVZjHZk58nNWC+16QeePUCBuIBAU4tB0yKAm1BAAO4ABRMCB+KBUBEBKgAnj83nlqCowNs4DAAMoqTBwAAyrWQAihdDgiORqPRGIoKIs2WQ-kCbzgmDycBwODZuLU2TwKmycAAYjRVDBxFA6ZCIhBXiAmDBMAQAOpMMTwOjUsBwDHg1ViQyq2HIcB0BEgCwk2jA5HZVSE4mkkAAKzoZAxtKIAEU8BB4HaCCS3tTqBajXkVKyCDKKNQLDBFWIcDAmMgABwABkDAJJiuRFCN0ascGohjgMoAjt74FaPhCQCo6ABaSxstky6hwCtidtWvm2pBE-0OkmYMT0gJD91wL0+0v9+1vGDh+OJ5NIABMC+R3lpAGFnH2QFYAKwyvAkgAq4YhA4DIEMgQAkuoEJiwDHPgBBdQYmCwoh+kkgiCIA)

**Input**
```
$ prettier someScript.js --check
```
`someScript.js`
```
; module.exports.shellExec = function shellExec(command)
  { var lines = shell.exec(command,{silent:true}).output.split(/\n/)
  ; log(bold(command))
  ; for (var i in lines)
    { lines[i].trim
    ; if (!lines[i]) continue // skip blank lines
    ; log(lines[i])
    }
  }
```

**Output**

```
Checking formatting...
someScript.js [error] someScript.js: Error: Comment "skip blank lines" was not printed. Please report this error!
[error]     at Object.ensureAllCommentsPrinted (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/index.js:13824:13)
[error]     at coreFormat (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/index.js:14538:14)
[error]     at formatWithCursor$1 (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/index.js:14765:14)
[error]     at Object.formatWithCursor (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/index.js:60959:12)
[error]     at format$1 (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/bin-prettier.js:18001:21)
[error]     at Object.formatFiles$1 [as formatFiles] (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/bin-prettier.js:18115:16)
[error]     at async main (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/bin-prettier.js:20216:5)
[error]     at async Object.run (/usr/local/Cellar/prettier/2.5.1/libexec/lib/node_modules/prettier/bin-prettier.js:20159:5)
All matched files use Prettier code style!
```

**Expected Behavior**

```
[warn] someScript.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```

On prettier version 2.5.1.

This is my first issue in this repo, so please let me know if there's something missing from this bug report.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #12073

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by kachkaev** [comment]
How about adding this test case for extra robustness? It does not work in 2.5.1 as well.

```js
for (;;) continue /* comment */
;
```

**Comment by fisker** [comment]
'WhileStatement', 'DoWhileStatement', 'ForStatement', 'ForOfStatement', 'ForInStatement' all can have `continue` and `break`.  'SwitchCase` can  also have `break`. Let's test them all?

**Comment by fisker** [comment]
Have you noticed the output is unstable?

**Comment by XYShaoKang** [comment]
These test cases fail

[Playground link](https://deploy-preview-12075--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAzCAnABACgNx4CUWARhnAIYDWWAOlAPQBUWkAtmwjFkw-XiAA0ICAAcYAS2gBnZKAoYMEAO4AFBQlkoKAG2UUAnrOFkKYKnBgBlCpwAyEqHGSpd0uCYxmL10WccA5sgwGACuHiBwbCRwACaxcXYUUAGhFAFwAGKYbBQwkinIIBShMBBCIAAWMGw6AOqVEvDSfmBwVppNEgBuTQZFYNLGII7uGDCqXgG5Lm4RAFbSAB5WgTpwAIqhEPCzOu7CfhhjRSQUMToVohiOMHUSsTCVyAAcAAyHSu51XqJF13Axt1nMIAI7beCTMRaYrSAC0TjicQq5HBEnIk3SMyQrn2EXcbAkwTC+LWmwhzhxc2EMHO90ezyQACYaV4JDpAgBhCAcChFQEAVgqoXcABVzlpcQcQN1wgBJKAJWBWMA3cQAQUVVhgBnWe3cAF8DUA)

```js
for (;;) break 
/* comment */
;
```

[Playground link](https://deploy-preview-12075--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAzCAnABACgNx4CUWARhnAIYDWWAOlAPQNaQC2rCM9eIANCBAAOMAJbQAzslAUMGCAHcACjISSUFADbyKAT0n8yFMFTgwAyhQ4AZEVDjJUm8XAMYjJ84KO2A5shgYAK4uIHCsJHAAJpFRVhRQPoEUPnAAYpisFDCiCcggFIEwEHwgABYwrBoA6qUi8OJeYHBmqnUiAG51Onlg4vogts4YMIpuPpkOTiEAVuIAHma+GnAAioEQ8JMazvxeGEN5JBQRGiWCGLYwVSKRMKXIABwADLtyzlVugnnncEPt9vwAI7reCjIRqfLiAC0diiURK5GBInIo2SEyQjm2IWcrBE-iC2KWqxB9gxU34MGO11u9yQACYKW4RBpfABhCDsCh5X4AVhKgWcABVjmpMTsQO1ggBJKAxWBmMAXYQAQVlZhgOmWW2cAF8dUA)

```js
for (;;) break 
// comment
;
```

**Comment by sosukesuzuki** [comment]
@fisker

> Have you noticed the output is unstable?

No, but we have same issue for non-for and non-continue/break. So we should treat this unstable formatting as an other issue. I don't think this is in the scope of this PR.

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwE4CucAlJuhBJgPRWaQC29CMAOlANwgA0IEADjFTQAzslABDPHggB3AAqSEolOIA2M8QE9RPAEZ5xYANZwYAZXFMAMqihxk6NcLh6Dx02b6HbAc2T4iHjh6XTgAEzDwq3EoHwJxHzgAMQg8enEYQVjkEHECGAhuEAALGHpVAHVi1HhhLzA4MyUa1AA3Gs0csGEdNChnPBg5Ax90hycXEAArYQAPM19VOABFAgh4cdVnHi88AZzdcVDVIr48WxgK1DCYYuQADgAGHelnCoM+HLO4Adb7HgAjmt4MN+MpcsIALR2cLhIp4OBA1AI4YJMZIRxbSbOeiofyEbGLFbA+wYiY8GBHK43O5IABMFIMqFUvgAwhBGOIcj8AKxFAjOAAqR2UmO2IFaRAAklBIrAzGBzgIAIKyswwTRLTbOAC+OqAA)

```sh
--parser babel
```

**Input:**

```jsx
if (true) foo // comment
;
```

**Output:**

```jsx
if (true)
  foo; // comment

```

**Second Output:**


```jsx
if (true) foo; // comment

```

**Comment by fisker** [comment]
> So we should treat this unstable formatting as an other issue.

Add it here then https://github.com/prettier/prettier/blob/53da86c34dd1c1e1241e85c57469100f2467fcec/tests/config/format-test.js#L24

**Comment by sosukesuzuki** [comment]
Woops, sorry thanks.

**Comment by fisker** [comment]
Why are we testing the first output instead of adding it to `unstableTests`?

**Review by fisker — APPROVED** [review]

**Pull request merged**
