### PR TITLE
Update some dependencies

### PR DESCRIPTION
**Pull request by brodybits**
This is a proposal to update some dependencies.

I have already verified that these updates give me a green build on Azure Pipelines is green.

I would be happy to split these into separate PRs if needed.

- ~~I’ve added tests to confirm my change works.~~
- ~~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)~~
- ~~(If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.~~
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by lydell** [comment]
Sounds reasonable! Out of curiosity, how did you choose these three dependencies?

**Comment by brodybits** [comment]
These are the 3 that I can remember updating without encountering any build issues. (I remember encountering build issues with some other Babel, Jest, Rollup, and Webpack dependencies.)

I would be happy to try updating a few others.

**Comment by duailibe** [comment]
Rollup (and its plugins) can't be updated without lots of changes in the build script. And even then, it's not guaranteed the final bundle will work. 

I eventually gave up after a few tries after I realized there wasn't any real benefit in updating it anyway :P

**Comment by thorn0** [comment]
Could you please update the dependencies in the `website` folder too?

They aren't compatible with Node.js v10:

```console
$ yarn install
yarn install v1.13.0
[1/4] Resolving packages...
[2/4] Fetching packages...
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9". Got "10.15.0"
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
$ node -v
v10.15.0
```

**Comment by brodybits** [comment]
> Could you please update the dependencies in the `website` folder too?

@thorn0 I think that should be done in a separate PR. Maybe we should raise an issue first?

**Comment by brodybits** [comment]
I have updated a number of dependencies in this PR and raised separate PRs for some of the more tricky dependencies. I am now looking forward to a more formal review of my work.

There are still a few more to look at someday, such as postcss-* dependencies.

@thorn0 I am getting to raise another PR to resolve the issue with `website`.

**Comment by brodybits** [comment]
I just rebased this one with a few of the trickier updates removed:
- `cosmiconfig`
- `editorconfig`
- `graphql`
- `leven`
- `mem`
- `semver`
- `string-width`
- `typescript` (seems to be superseded by some recent changes)

I will try to make these updates in separate PRs.

It looks like something went wrong with the build, looks like some kind of an issue between Pipelines config and GitHub.

I hope these changes will be reviewed sometime. I would be happy to split them out if needed.

**Comment by brodybits** [comment]
Closing as I think all of the proposed changes are now covered by PR #6224.

**Pull request closed without merging**
