### PR TITLE
Allow breaking for logical expressions in member chains

### LINKED ISSUE #822: Unnecessary break for conditional inside of member expression
```js
const values = (response.tickets || e).map(tickets =>
      TicketRecord.createFromSomeLongString(tickets));
```

outputs

```js
const values = (response.tickets ||
  e).map(tickets => TicketRecord.createFromSomeLongString(tickets));
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20values%20%3D%20(response.tickets%20%7C%7C%20e).map(tickets%20%3D%3E%5Cn%20%20%20%20%20%20TicketRecord.createFromSomeLongString(tickets))%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by vjeux**
I'm not really sure what a general rule is for those, but starting with LogicalExpressions should be good. Outside of identifiers, function calls and logical expressions, there aren't a lot of things you'd put there in real code anyway.

Fixes #822

### CODE REVIEW

**Comment by jlongster** [comment]
This seems like a very specific exception and I'm worried about adding ones this specific to the code.

We haven't really though much about sequence expressions (or whatever they're called), meaning a list of expressions inside parens. My gut says we could try a general rule where to try to break what's after a sequence expression before trying break it. I feel like it would be easy to come up with other code where we want this behavior but it won't apply because your fix is so specific.

**Comment by vjeux** [comment]
> We haven't really though much about sequence expressions (or whatever they're called), meaning a list of expressions inside parens.

I haven't seen them used much in real code. I'm not sure we should worry about them until people complain that they do not behave the way they expect.

> I feel like it would be easy to come up with other code where we want this behavior but it won't apply because your fix is so specific.

Game on ;) On a more serious note, I can't think of other places where we'd want the same thing happening. This is only an issue for the first element of a member chain where we want to control when we use the long form or not.

The member chain logic is pretty complex but it's starting to get really good. The two pull requests I just sent today are super small edge cases and the only crazy things from a really big codebase that people noticed.

**Comment by jlongster** [comment]
Ok, thinking about it more, I think you're right, this is a pretty specific case. I was thinking of something like `(sideEffect(), obj).map(...)` but I think that's extremely rare, and I can't think of many other scenarios. We can do this and if we need to, generalize it later.

**Comment by jlongster** [comment]
Rebase needed though!

**Pull request merged**
