### PR TITLE
feat(json): add jsonc to aliases and use it to find parser in markdown embed 

### LINKED ISSUE #4611: json5 embedded in markdown gets treated as js (quotes removed)
**Prettier 1.13.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAztArAHSmEIAIT8QoBDAWzgqXJACMrm4AbAWkgCd6QAGlJNIUMFXjV4AEwBytAYwqt2HPgOFQyFGRADuUDhCoysAGSpYYAZgAMAESoBPLAxIBGOwE4A7AA5fABZvLR0QPUNjUywAJUkASwh3OwA6O38bLwA2XA9s-wAmAtx-bI8wpgALAFcaKigHAyMTM0treydXdwoPDxoKSooABwhhmo4qXncYXhq4IZAANzheLCSoHpBs1OL0wcIAX0J0VCEQMZgNrGRQKd4DAAUphBuUKiWIBJlz5l4qMAAazgMAAysMAQkoABzZCzeaCEBQrCrGCPf7Q+rIABmVA4KMR2AAHgAhf5AkGgxTmKFwHF4gkgCFrVbIED1XiAyJQc7DXhQmAAdW+MCqyH8dkRfIgKMF-2GbL5cBRvBW534AEcagl+OiqJiqPT8QsQCiaAk4XMTesYRw4ABFGoQeBGxkwNjCmSi5CFRGzKgJDhQ6EAYQgNCxKCg0DpiJqKIAKmw3rjjYdDkA)
```sh
--parser markdown
```

**Input:**
````markdown
```json5
{
  "name": "babel-core",
  "concatenatedName": "babelcore",
  "downloadsLast30Days": 10978749,
  "downloadsRatio": 0.08310651682685861,
  "humanDownloadsLast30Days": "11m",
  "popular": true,
  "version": "6.26.0",
}
```
````

**Output:**
````markdown
```json5
{
  name: "babel-core",
  concatenatedName: "babelcore",
  downloadsLast30Days: 10978749,
  downloadsRatio: 0.08310651682685861,
  humanDownloadsLast30Days: "11m",
  popular: true,
  version: "6.26.0"
}
```

````

**Expected behavior:**

### PR DESCRIPTION
**Pull request by ikatyang**
~~`JSON` and `JSON with Comments` are different languages in `linguist`, but I think it's fine to just add `.jsonc` to `JSON`'s `extensions` here since we treat them the same, thoughts?~~

~~(Actually I think we should remove those unrelated fields since it's hard to maintain, for example: `JSON` and `JSON with Comments` have different `linguistLanguageId`.)~~ -> #4741

Closes #4611

- [x] waiting for github/linguist#4171

### CODE REVIEW

**Comment by j-f1** [comment]
Can you add a test with a `.jsonc` file (as opposed to a Markdown code block)?

**Comment by ikatyang** [comment]
`.jsonc` is not an extension now 😅, see https://github.com/github/linguist/pull/4171/commits/05682395d579e9f3bef8b0f93ec61a44ec884de5.

**Comment by j-f1** [comment]
Can you fix the merge conflicts?

**Comment by ikatyang** [comment]
I'm still waiting for github/linguist#4171 so that I can update linguist-languages then use it here.

**Comment by ikatyang** [comment]
Updated to use `JSON with Comments` from the latest linguist-languages, ready for the second round review.

**Pull request merged**
