### PR TITLE
Fix angular unstable expression binding

### PR DESCRIPTION
**Pull request by fisker**
- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Seems coverage upload still fails ?

**Comment by fisker** [comment]
What happened here? Nobody did anything, the result turns green...

**Comment by evilebottnawi** [comment]
:confused:

**Comment by thorn0** [comment]
I wanted to answer that maybe somebody pushed something to `master` as the tests are run against the merge result not against the PR branch, but no: the last commit in `master` is 15h old. 🤔

**Comment by fisker** [comment]
checkout the [log](https://github.com/prettier/prettier/pull/7924/checks?check_run_id=554760892#step:6:35), and the job is finished 1h ago

**Pull request merged**
