### PR TITLE
Refactor: Simplify `getSortedChildNodes`

### PR DESCRIPTION
**Pull request by fisker**
## Description

- Simplify logic

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
The changes don't look safe, and the function became more difficult to follow IMHO.

**Comment by fisker** [comment]
Which part do you think is not safe?

I think this great improvement.

Run format on `src/index.js` file, let's see how many times related functions are called

```
Master
┌──────────────────────┬────────┐
│       (index)        │ Values │
├──────────────────────┼────────┤
│ getSortedChildNodes  │  196   │
│ getCommentChildNodes │  126   │
│   canAttachComment   │  160   │
│       locStart       │  140   │
│        locEnd        │  140   │
└──────────────────────┴────────┘
```

```
This PR
┌──────────────────────┬────────┐
│       (index)        │ Values │
├──────────────────────┼────────┤
│ getSortedChildNodes  │  151   │
│ getCommentChildNodes │   94   │
│   canAttachComment   │  128   │
│       locStart       │  149   │
│        locEnd        │  149   │
└──────────────────────┴────────┘
```

And here `getCommentChildNodes` function was called with argument without `type` property

```
┌─────────┬────────┐
│ (index) │ Values │
├─────────┼────────┤
│ string  │   11   │
│  array  │   15   │
│ number  │   64   │
│ object  │   27   │
└─────────┴────────┘
```

**Comment by fisker** [comment]
I pushed some new changes, it should be much easier to understand the logic.

**Comment by thorn0** [comment]
I'm reluctant to change the sorting algorithm without any benchmarks. And I have trouble with understanding the function you pass to `sort`:

```js
    .sort(
      (aNode, bNode) =>
        locStart(aNode) - locStart(bNode) || locEnd(aNode) - locEnd(bNode)
    );
```

Are you sure that's what you meant? Maybe I need to have another look at it...

Also you changed the behavior of the function a little. Previously, if `printer.canAttachComment(node)` returned `false`, the function was called recursively and the children of the `node` were added to the list. Now they aren't. This doesn't break the built-in languages, but might break plugins. The removed behavior can be a useful way for excluding certain nodes from comment attaching without excluding their children, so I'd prefer to keep it.

**Comment by fisker** [comment]
> Are you sure that's what you meant? 

Yes, it is. Why this hard to understand?

```js
 (aNode, bNode) =>
        locStart(aNode) - locStart(bNode) || locEnd(aNode) - locEnd(bNode)
//      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ If locStart(aNode) < locStart(bNode), aNode first
//                                        If same, will be `0`, sort by `locEnd`
```

> Also you changed the behavior of the function a little. 

Seems you're right, I forgot to consider that `canAttachComment` returns false, I only considered that branch hit `canAttachComment` be `undefined`, my bad.

**Comment by fisker** [comment]
It seems I finally got the logic right in https://github.com/prettier/prettier/pull/13255, it #13255 didn't get merge, I may move code to this one.

**Comment by fisker** [comment]
> if printer.canAttachComment(node) returned false, the function was called recursively and the children of the node were added to the list. Now they aren't.

Somehow, I missed this, I have to read the code again to understand how it works in #13255 😢

**Comment by fisker** [comment]
Included in 13255

**Pull request closed without merging**
