### PR TITLE
replace mem dependency

### PR DESCRIPTION
**Pull request by 43081j**
## Description

`mem` pulls in 2-3 levels deep of dependencies for what should be much, much simpler.

here i've replaced it with [nano-memoize](https://github.com/anywhichway/nano-memoize) which is dependency-free and much faster. there's also [fast-memoize](https://github.com/caiogondim/fast-memoize.js) if you'd rather have that. or we could just throw a `WeakMap` together ourselves, any of these solutions are an improvement.

## Checklist

- [ ] I’ve added tests to confirm my change works (existing tests should be enough)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Two things I don't like about this module,

1. It uses a global `this`, not `globalThis`(https://github.com/anywhichway/nano-memoize/blob/72cffee317de30bcfea4a0e68822955f3015bf9b/src/nano-memoize.js#L101), which may cause problems when bundling, see https://github.com/prettier/prettier/blob/5f0ee39fa03532c85bd1c35291450fe7ac3667b3/scripts/build/config.mjs#L32.

2. I don't see the point [shimming `Object.assign`](https://github.com/anywhichway/nano-memoize/blob/72cffee317de30bcfea4a0e68822955f3015bf9b/src/nano-memoize.js#L4), it already uses `WeakMap` inside, they both require ES2015 environment.

**Comment by 43081j** [comment]
thats fair, like i said there's a couple of options. happy to switch it to fast-memoize instead, or just keep our own weak map.

let me know and ill update

**Comment by fisker** [comment]
Personally, I think `mem` is already small enough, it's about 350 lines in the bundle.

https://unpkg.com/browse/prettier@2.3.2/index.js  Line 16668 - Line 17024

**Comment by 43081j** [comment]
meanwhile it unnecessarily pulls in multiple levels deep of dependencies, as is standard with these micro-packages.

it really isn't difficult to cache the loaded plugins in prettier, it shouldn't need a chain of dependencies to achieve that. something with no dependencies or just using a weak map directly would make a lot more sense. 

less dependencies in this case is a win from what i can see. if the source is the same size or smaller, and you have less dependencies, and it is faster, why would you keep the cruft?

**Comment by sosukesuzuki** [comment]
Thank you for the PR. I agree with @fisker, we don't have any problem in using mem now. I don't think there is much benefit in terms of performance or maintainability by using nano-memoize.

**Comment by 43081j** [comment]
the benefit is dropping an unnecessary cluster of dependencies you never actually needed. what you're pulling 4-5 packages in for, you could've achieved with a weakmap yourself in a couple of lines. 

it would be good to understand where you think the loss is here @sosukesuzuki. 

you'd be increasing CI install speeds (the more of these bloated micro-packages you throw away, the better), reducing the size of your built code and simplifying your logic.

if you could let me know what the downside is of changing it, that'd be super helpful.

**Review by alexander-akait — COMMENTED** [review]
We memorize they simple things, maybe we can recreate own memorize function or just remove it...

**Comment by 43081j** [comment]
yes its incredibly simple and its slightly absurd a package that provides the functionality somehow has its own dependency chain. we could implement our own cache with a weakmap or similar, just cache the plugins to their resolved values.

i don't see any benefit in keeping the bloated package, so i really would like to understand what im missing and what the benefit is. there must be one im not aware of, im sure

**Comment by alexander-akait** [comment]
> i don't see any benefit in keeping the bloated package, so i really would like to understand what im missing and what the benefit is. there must be one im not aware of, im sure

Agree, less deps - less problems

**Pull request closed without merging**
