### PR TITLE
Markdown: Fix missing blank lines in fenced code block

### PR DESCRIPTION
**Pull request by fisker**
- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Problem in this PR:

For Value of code block without end mark, there are difference between CommonMark and Remark.

In this case.

````markdown
```
a
````

If we add line breaks to the end.

CommonMark:

node.value didn't count the final `\n`.

Remark:

node.value include all `\n`s to EOF.

And `remark` believe the remark AST is right.

More details https://github.com/remarkjs/remark/issues/512

Which one should we follow?

**Comment by fisker** [comment]
Let's keep current behavior (the  CommonMark way)?

**Comment by evilebottnawi** [comment]
I think it is safe to change

**Comment by fisker** [comment]
The real question is "Do we want to change"?

Github also render

````markdown
<!-- end with 1 blank line -->
```
a


````

with no blank line,

and

````markdown
<!-- end with two blank lines -->
```
a



````

with one blank line

**Comment by evilebottnawi** [comment]
To be honest, I have no strong opinion here

**Comment by fisker** [comment]
Me too, so let's follow CommonMark  and GitHub!

**Comment by evilebottnawi** [comment]
:+1:

**Review by evilebottnawi — APPROVED** [review]

**Review by sosukesuzuki — APPROVED** [review]

**Pull request merged**
