### PR TITLE
Add plugin section in the readme

### PR DESCRIPTION
**Pull request by lipis**
I think it would be nice to link to the upcoming plugins for better visibility to attract more people to test/contribute.. :)

Maybe adding a few words or something..?

### CODE REVIEW

**Comment by lipis** [comment]
Am I missing any other language?

**Comment by lipis** [comment]
I just noticed that there is a [plugin](https://prettier.io/docs/en/plugins.html) section in the docs, but maybe it's still a good idea to have something here as well.. wdyt?

**Comment by azz** [comment]
We deleted all the duplication a while ago so the README is intentionally bare. I don't think we want to be adding this here. (we don't even have install instructions)

**Comment by lipis** [comment]
maybe we could do in a less prominent way.. but the plugins section is not the most visited page in the docs.. but from here i thought that we could get more attention.. just an idea

**Comment by azz** [comment]
We don't _want_ it to be the most visited page in the docs, especially since none of the plugins have been released yet.    #3762 should be fine

**Comment by lipis** [comment]
fair enough

**Pull request closed without merging**
