### PR TITLE
Get tests passing on Windows

### LINKED ISSUE #4564: Get AppVeyor Passing
I just set up windows builds on AppVeyor, here's a link to the failing tests: https://ci.appveyor.com/project/azz/prettier/build/5#L1359

Also should add an `appveyor.yml` rather than using the web UI.

### PR DESCRIPTION
**Pull request by azz**
Closes #4564

### CODE REVIEW

**Comment by azz** [comment]
First try!

**Comment by azz** [comment]
Finishes faster than CircleCI, which is nice. Plus it runs and passes on Node 6 (where travis currently segfaults)

**Comment by duailibe** [comment]
> Finishes faster than CircleCI, which is nice.

CircleCI also runs the build script.

It's nice if it finishes faster than travis though =)

**Comment by azz** [comment]
> CircleCI also runs the build script.

I know, but I was expecting it to be super slow on Windows.

**Pull request merged**
