### PR TITLE
Add proseWrap docs

### PR DESCRIPTION
**Pull request by azz**

### CODE REVIEW

**Comment by ikatyang** [comment]
Forgot to add docs 😅 , maybe also add note for CJK user? https://github.com/prettier/prettier/issues/3183#issuecomment-342454466

**Comment by azz** [comment]
Not sure I completely understand that comment.

**Comment by ikatyang** [comment]
Similar to our release note but another solution, no-prose-wrap won't cause additional spaces for unsupported renderer.

> Note for CJK users: If your markdown renderer does not support CJK line ending, you'll have to use plugin like [markdown-it-perfect-newline-for-cjk](https://www.npmjs.com/package/markdown-it-perfect-newline-for-cjk), [hexo-filter-fix-cjk-spacing](https://www.npmjs.com/package/hexo-filter-fix-cjk-spacing), etc. to remove additional spaces.
> 
> ```
> // Source
> 一二三
> 四五六
> 七八九
> 
> // Rendered content with unsupported renderer
> 一二三 四五六 七八九
>
> // Rendered content with supported renderer or via plugin
> 一二三四五六七八九
> ```

**Comment by azz** [comment]
```
$ ./bin/prettier.js --parser markdown <<EOF
→ 一二三
→ 四五六
→ 七八九
→ EOF
一二三四五六七八九
```

Wait, how does this work? I was expecting spaces between 3-4 and 6-7.

**Comment by ikatyang** [comment]
Uh, the source I meant is the output from prettier (suppose the printWidth is really short):

```
一二三
四五六
七八九
```

or

`一二三四五六七八九` with printWidth=6

Rendered content from unsupported will be

```
一二三 四五六 七八九
```

**Pull request merged**
