### PR TITLE
Updating cosmiconfig to not cache .js config files when told not to

### PR DESCRIPTION
**Pull request by wuweiweiwu**
fixes: #5311 

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by ikatyang** [comment]
It seems Jest uses its own `require` (facebook/jest#5120) which we're not able to test `require`'s cache using Jest. I guess we could just update `cosmiconfig` without adding a test in this case.

**Comment by SimenB** [comment]
You can run `jest.resetModules()`, but I'm now sure how cosmiconfig caches. If it's just `delete require.cache[thing]` then it's always empty when running through Jest, so a `resetModules` should work

**Comment by SimenB** [comment]
Ah, indeed.

I have some nefarious plans at some point to add support for `require.cache` properly (including `delete`, `Proxy` makes it quite straight forward), but it's super low pri at the moment

**Comment by wuweiweiwu** [comment]
removed the test!

**Comment by ikatyang** [comment]
Thanks!

**Pull request merged**
