### PR TITLE
Fix row break in arrow func with default argument value

### PR DESCRIPTION
**Pull request by GlebDolzhikov**
## Description

fixes https://github.com/prettier/prettier/issues/12597

## Checklist

- [X] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [X] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
What you changed is intended behavior and doesn't fix the issue.

**Comment by GlebDolzhikov** [comment]
if you agree with this [behavior](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzKBGTAXkwAoBDIzAJgEoiA+TABgG4AdKSKDHKKy8kTx1CjEgCMRjAMztO6LLmkCKxWg1KSNJMFMyyOXHrgAsKvRIu7tAEz0H53RVACs57eOLDt10aTvacPZyRs4AbO5+lj6E0hYBUUHaAObBhgq8AOyRYlpRvmI2sRZJUana2MEgADQgEAAOMACW6MigZABOHRAA7gAKnQhoyCBkADY9ZACew7XiHWRgANZwMADKZAC2cAAyTVBwyNjjaHBzC8ura-WL+8nIMB0ArmcgcJvicDY2XztkUMknmRknAAGIQDqbMgwZoAkZkJ4wCA1EAACxgmzGAHVUU14GgbmA4GshnimgA3PFTEZgNCzED7U4dGB9BbJKFHE6vABWaAAHms7mM4ABFJ4QeCcsanWo3DpMkbiMifMYo+odfYwLFNGwwVHIAAcTFl3VOWIW9RG6rgTPJh1qAEdxfBWQ1higyGgALQHL5fFEdOBOpqB1nAjlIY7S16nTZNB7PGNC0XOw6Rrm1GDK7W6-VIKiZhZNMZ3ADCEE2EbeaBcKKepwAKsr3VGZSByS8AJJQH6wNZgDWNACCPbWMCmwqlpwAvtOgA), let's close this PR

**Comment by thorn0** [comment]
Your examples are contrived. If you find real world code that looks bad because of the current heuristics, let's change this. But the condition should be stricter than just "allow assignments patterns". E.g. "allow assignments patterns if there is only one parameter and the right-hand side of the assignment is a simple (whatever that means) expression".

**Comment by thorn0** [comment]
BTW, you can use https://github.com/prettier/prettier-regression-testing to check the potential impact of your changes.

**Pull request closed without merging**
