### PR TITLE
chore: Check for updates every Sunday

### PR DESCRIPTION
**Pull request by lipis**
## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
It was @fisker who set it to "daily". I guess he likes its being this way, so why not let it be? On the other hand, I see how the stream of bot notifications can deter contributors.

**Comment by lipis** [comment]
> I see how the stream of bot notifications can deter contributors.

That's the main reason.. we can give it a try and if @fisker agrees we can merge :)

**Comment by fisker** [comment]
Personaly I prefer deps update ASAP so the change will be small.

If you feel it's annoying, I'm fine with this change.

One question, does dependabot work on weekend? As far as I know , it doesn't work on weekend if we set to "daily".

**Comment by lipis** [comment]
I think it's also going to work better for you, as this way it might skip a few versions if the release cycle is faster than a week for some libraries.. Yes it works on Sundays if you say so.. not sure when set to daily though. My vote is to give it a shot!

**Review by fisker — APPROVED** [review]

**Pull request merged**
