### PR TITLE
chore(doc-printer): Fixed minor typo

### PR DESCRIPTION
**Pull request by jamesgeorge007**
`coping` -> `copying`

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
@fisker doesn't that make sense to you?

**Comment by fisker** [comment]
We have  tool called `cspell` do spell check, why didn't it catch it.

**Comment by jamesgeorge007** [comment]
It seems `cspell` isn't catching it.

**Comment by jamesgeorge007** [comment]
Hope this one's good to land :rocket:

**Pull request merged**
