### PR TITLE
Initial GraphQL implementation

### PR DESCRIPTION
**Pull request by vjeux**
This is the bare minimum amount of code to make graphql work. Turns out it's pretty easy to add support for other languages :)

### CODE REVIEW

**Comment by lydell** [comment]
I wonder if people want `` gql`...` `` tagged template literals in JS to be formatted.

Also, somewhat related here, perhaps the CLI should choose parser based on file extension:

- .js → babylon
- .css → postcss
- .graphql → graphql

**Comment by k15a** [comment]
@lydell we could do this for styled-components and other CSS in JS libraries as well.

**Comment by azz** [comment]
@lydell 
> I wonder if people want gql\`...\` tagged template literals in JS to be formatted.

I think this could be done with editor extensions + #1609

**Comment by vjeux** [comment]
We have both .graphql files and js files with Relay.QL template literals inside of fb, so would be nice to enable both usecases.

The CSS in JS community is also eager to have a way to autoformat css from prettier.

I'd also love prettier to work with vue where you have a html file that contains both js and css.

At first I was thinking like @azz about having editor plugins but the more I look into it, the more it looks like all those languages are very intertwined and it would be best handled inside of prettier itself.

**Comment by vjeux** [comment]
Closing this as this was an experiment and I'm not going to pursue it for now, but I'd love to see it inside of prettier :)

**Pull request closed without merging**
