### PR TITLE
Drop Node.js 12 support for development "build"

### PR DESCRIPTION
**Pull request by fisker**
## Description

The production build still support v10

Like #10842

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by Harry-Hopkinson — APPROVED** [review]

**Comment by fisker** [comment]
@Harry-Hopkinson Please stop approving PRs, it's not helping, leave comments instead.

**Comment by fisker** [comment]
@Harry-Hopkinson Please stop approving PRs, it's not helping, leave comments instead.

**Comment by fisker** [comment]
Prettier v2.6.2 should fix the lint script.

**Comment by fisker** [comment]
@sosukesuzuki Fine with this?

**Review by sosukesuzuki — APPROVED** [review]

**Pull request merged**
