### PR TITLE
feat(html): preserve surrounding linebreaks

### LINKED ISSUE #5472: Preserve line-breaks on multiline HTML content
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UABMagEYQAmAnoSaWVQJYBuxzVAvASPAM4xe9RowCGYoqNQB6FqxFkZlWvVmZceEABoQEAA4xm0fslBiAThYgB3AAqWEplGNYROOkOQtiwAazgYAGV9X2YoAHNkGAsAVzhdDRwAdXRmAVCwOCCndLZ0mmRwflNdcP44Cxg7HwisMWQAMzEcCt0AK34ADwAhH39AoLEsOAAZcLgmlraQTq6g8IicOABFWIh4KdaEkFCLCosipM99C3CYZM4YdGQADgAGXVOICuSffSLTuAPWSd0LOAAR1izABNTEdQaSGa210FSwzGicR2-EWyzWG0m0OmOxgYnIlyo12QACZdDExMwcIsAMIQLD1IpQaB-ECxCoAFXxzhhFQAvnygA)

**Input:**
```html
<html>
  <body>
    <div id="test">
      aa
    </div>
  </body>
</html>
```

**Output:**
```html
<html>
  <body>
    <div id="test">aa</div>
  </body>
</html>
```

**Expected behavior:**
Preserve line-break before and after "aa".
```html
<html>
  <body>
    <div id="test">
      aa
    </div>
  </body>
</html>
```
This situation is similar to preserve multiline array notation of JavaScript.

### LINKED ISSUE #5595: Weird behavior with HTML elements with children and long `print-width` (parser Vue and HTML)
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoDOWe5AbgLQCWAZgLzEgwBOArnDLthZXgK4lyFSszJh8VKpxCs8ZVYx5xWWqgAt1eRjWZQuZAPSTpMuQqVdVhzdt0GNJsyEvXpqWfJ4ispOGlo6cPrOnuZWpBSoFjR0vvGUACbM9GRMbMpigsLsovxwEmkJAfYhamGuke5GMd5xUomZ9KltOLJMrBA8yrKmOcxUzABGOHAACngA5pHmSADWcACeQ8uBwVzAmVR4U3DpSGSyRWSMAIxkAD53ZLSLQiLMAL7lUglquRxcsgAhCIbuY9OFlABicwAAXkzDAKwAdFgtPQEDBlFQ4NMwDAABTMACUXxsFGAwHOZHen2+lAseF8CWSDEYOOxTL8VBwEBgZCgeAwcGUOJ6WHGVAkADI9KLmFgANyJbm8znK2hQXyJHqSRKYXAEOCSEAAGhAECwMGY0CoyFAeB4PAgAHc5looLaUHh6BBmOlTSAJjw8Ii4DAAMq0MCmebIApmvQwDA4ADqemY8GSYDg4YQ4yt9Az62Q4EUAdM2J4MBmwfmGDwyFUOGxZoAVlQAB4AIWDoYjgrgABlTHBG3hm3A253wzHpgBFPi80dIJstkC0HiVkv0AQB1EQbEp4NYEuoyJwHjogNaACOfGYWhrC3rY4nZuxGGYcdK79ncAXS6vmuMBHCmfowHoyAAExmrweDMD0UDzAAwhAGAvigUDQKOZp8NiAAqRyequk7rjwpgwGB6QQcg1wABwAAw0kAA)
```sh
--parser vue
--print-width 180
```

**Input:**
```vue
<template>
  <span v-if="true === true">
    <i class="fa fa-refresh fa-spin" />
    <i class="fa fa-refresh fa-spin" />
    <i class="fa fa-refresh fa-spin" />
  </span>
  
  <div v-if="true === true">
    <i class="fa fa-refresh fa-spin" />
  </div>
  
  <li v-for="i in visiblePages" :key="i" :class="{disabled: i === -1 || page === i}">
    <a v-if="i !== -1" href="#" @click.prevent="select(i)">
      {{ i }}
    </a>
    <span v-else>
      <slot name="ellipsis">&hellip;</slot>
    </span>
  </li>
</template>

```

**Output:**
```vue
<template>
  <span v-if="true === true"> <i class="fa fa-refresh fa-spin" /> <i class="fa fa-refresh fa-spin" /> <i class="fa fa-refresh fa-spin" /> </span>

  <div v-if="true === true"><i class="fa fa-refresh fa-spin" /></div>

  <li v-for="i in visiblePages" :key="i" :class="{ disabled: i === -1 || page === i }">
    <a v-if="i !== -1" href="#" @click.prevent="select(i)"> {{ i }} </a> <span v-else> <slot name="ellipsis">&hellip;</slot> </span>
  </li>
</template>

```

**Expected behavior:**

The expected behavior may not be strictly equals to the input, but `v-if` and `v-else` should not be in a single line. 
Also, tags with one or multiple children already correctly indented (like the first `<span>` with the three `<i>` should not be modified I think :thinking: :  

```vue
<template>
  <span v-if="true === true">
    <i class="fa fa-refresh fa-spin" />
    <i class="fa fa-refresh fa-spin" />
    <i class="fa fa-refresh fa-spin" />
  </span>
  
  <div v-if="true === true">
    <i class="fa fa-refresh fa-spin" />
  </div>
  
  <li v-for="i in visiblePages" :key="i" :class="{disabled: i === -1 || page === i}">
    <a v-if="i !== -1" href="#" @click.prevent="select(i)">
      {{ i }}
    </a>
    <span v-else>
      <slot name="ellipsis">&hellip;</slot>
    </span>
  </li>
</template>

```

Maybe related to #5385 and #5441? 
This issue is present in 1.15.3, 1.15.2, 1.15.1 and 1.15.0, but not in 1.14.3. 

I don't think this is really expected since actually output is not prettier than input (IMO). I tried to change `--html-whitespace-sensitivity` but nope.

Thanks!

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #5472
Fixes #5595

I feel like this is the best choice we can come up with since HTML is too customizable that any tag can be used as `if-else`-like node (e.g., `*ngIf`, `v-if`, and other variants) or lists (e.g., `class="list"`), people would like to align their contents in these situations and it's indeed more readable, but it's nearly impossible to figure out what's their intent.

- surrounding linebreaks for node with no sibling (i.e., it's the only child) are controlled by the leading linebreak.
- surrounding linebreaks for node with siblings are preserved if both leading linebreak and trailing linebreak exist.
---
- [x] I’ve added tests to confirm my change works.
- (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by Kocal** [comment]
Thanks, this is perfect! :smile:

**Comment by yanni4night** [comment]
Great indeed!

**Comment by sheikalthaf** [comment]
@ikatyang Considering prettier for our projects and succesfully tested in other file formats except `html`. We are using angular. faced this problem and waiting for this to be merged. Nice work

**Comment by chrisvfritz** [comment]
Just want to add as a member of the Vue team that this is definitely necessary before Prettier will be usable for our templates. Reformatting this:

```html
<h1>Hi</h1> 
<img src="foo">
<p>test</p>
```

to: 

```html
<h1>Hi</h1> <img src="foo"> <p>test</p>
```

is essentially equivalent to changing:

```js
foo()
bar()
baz()
```

to:

```js
foo(); bar(); baz()
```

This PR also makes HTML formatting more consistent with the current JSX formatting, which I think makes sense as a goal.

**Comment by ikatyang** [comment]
@sheikalthaf The `class` formatting is tracked in #5482.

**Comment by ikatyang** [comment]
@chrisvfritz 

- Elements with `display: block` would not be treated as inline elements.

  **Prettier 1.15.3**
  [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFgRgHwAkCWqA9FtgAQA6Uq+AtgOZkDOATmALwUgBmEEX2KqgAO2eExjFRIADQgIwmPmhNkoAIYsWEAO4AFTQlUp1ANwj4AJrJAAjFurABrODADKwx-ij1kMFgCucHLoMLQANgDq6PjinmBwbkax+KaxAJ7I4Eyqct5McCwweg70tOrI3OrhBXIAVkwAHgBCDs6ubuq0cAAy3nCV1bUgDY1u3vThcACKARDwgzXBIJ4sBSxZoRE2wizeMJFWMOjIABwADHK7EAWRDsJZu3DrpgNyLHAAjgH4HyXqZQqSCqSzkBVo+D8gWWTAmU1m8wGwKGyxg6lsh0sx2QACY5P51PhwhMAMIQWjlLJQaBvEABAoAFXRxhBBQAvmygA)
  ```sh
  --parser html
  ```
  
  **Input:**
  ```html
  <h1>Hi</h1> 
  <img src="foo">
  <p>test</p>
  ```
  
  **Output:**
  ```html
  <h1>Hi</h1>
  <img src="foo" />
  <p>test</p>
  
  ```

- This PR is mainly for `if-else`/list-like elements, for example:

  **Prettier 1.15.3**
  [Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlKgCYCWAbgARj4DOjAvMSDpYzOyVLQNoUa9Jq3aVMvAFJ4yAeirU+qRTT6lUeWtQC0lAGZsQlWgEIWLWroCM7WgAsATnCPsAxPYACDSmADWAHRYLtQIMMaMcDhwYDAAFJQAlLykAsDAtKYAvtma8ngqjFhyOrrRUXwCqIw4EDC0UHgYcMbRnFiMXLwAZA7tlFgA3Kq19SryxXITmLgEcHwgADQgEFgwlNCMyKB4Tk4QAO4ACnsI2yh41BCU5MsgAEZOeAFwMADKJWCUUADmyDAnABXOArBwwDA4ADqDkkcCmYDg73OkhokgAnshwMx7j8ok4YMdnr8MHhkAY8DgoisAFaMAAeACFnq8Ps04AAZH5wcmU6kgOn094-X4xACKQPqPKQFKpoJAJSc+Kx1BB9xCPxgUNuMAcyAAHAAGFYhCBRKHPLBYkLwuBOML3FwARyBlBcRLwJLJMr58qiGEoAOBfpF4sl8F5cpWMDwD215F1yAATNHnpROH8AMIQDCkrFQaA8lZAqIAFVjF1lUVyQA)
  ```sh
  --parser vue
  ```
  
  **Input:**
  ```vue
  <template>
  <div class="list">
      <div class="item">Jan</div>
  </div>
  
  <a v-if="i !== -1" href="#" @click.prevent="select(i)">
    {{ i }}
  </a>
  <span v-else>
    <slot name="ellipsis">&hellip;</slot>
  </span>
  </template>
  
  ```
  
  **Output:**
  ```vue
  <template>
    <div class="list"><div class="item">Jan</div></div>
  
    <a v-if="i !== -1" href="#" @click.prevent="select(i)"> {{ i }} </a>
    <span v-else> <slot name="ellipsis">&hellip;</slot> </span>
  </template>
  
  ```
    
  Their surrounding linebreaks will be preserved:
    
  **Prettier pr-5596**
  [Playground link](https://deploy-preview-5596--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlKgCYCWAbgARj4DOjAvMSDpYzOyVLQNoUa9Jq3aVMvAFJ4yAeirU+qRTT6lUeWtQC0lAGZsQlWgEIWLWroCM7WgAsATnCPsAxPYACDSmADWAHRYLtQIMMaMcDhwYDAAFJQAlLykAsDAtKYAvtma8ngqjFhyOrrRUXwCqIw4EDC0UHgYcMbRnFiMXLwAZA7tlFgA3Kq19SryxXITmLgEcHwgADQgEFgwlNCMyKB4Tk4QAO4ACnsI2yh41BCU5MsgAEZOeAFwMADKJWCUUADmyDAnABXOArBwwDA4ADqDkkcCmYDg73OkhokgAnshwMx7j8ok4YMdnr8MHhkAY8DgoisAFaMAAeACFnq8Ps04AAZH5wcmU6kgOn094-X4xACKQPqPKQFKpoJAJSc+Kx1BB9xCPxgUNuMAcyAAHAAGFYhCBRKHPLBYkLwuBOML3FwARyBlBcRLwJLJMr58qiGEoAOBfpF4sl8F5cpWMDwD215F1yAATNHnpROH8AMIQDCkrFQaA8lZAqIAFVjF1lUVyQA)
  ```sh
  --parser vue
  ```
  
  **Input:**
  ```vue
  <template>
  <div class="list">
      <div class="item">Jan</div>
  </div>
  
  <a v-if="i !== -1" href="#" @click.prevent="select(i)">
    {{ i }}
  </a>
  <span v-else>
    <slot name="ellipsis">&hellip;</slot>
  </span>
  </template>
  
  ```
  
  **Output:**
  ```vue
  <template>
    <div class="list">
      <div class="item">Jan</div>
    </div>
  
    <a v-if="i !== -1" href="#" @click.prevent="select(i)">
      {{ i }}
    </a>
    <span v-else>
      <slot name="ellipsis">&hellip;</slot>
    </span>
  </template>
  
  ```

**Pull request merged**
