### PR TITLE
Improve wrapping for codeblock in markdown and jsx in mdx

### LINKED ISSUE #9503: Inline React components in MDX cause line lengths to exceed print-width
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAogD3gJygQwBsAZASygGsACACxzgDMBeAHRBphgAckB6X-AHcAzgDp8AW3wAvaKMgTekACZwupLnELk4vNgD4AggHUAylQDCEVQAUNWnal5ZcBEuQr6qpYVXxVIWHIAVwhg31VtADc4HABPPyhlKnpCOHxhOD9gmAgpGFJoKkycKNIwLJgafBg-UmVfYQkICCqqVS5CCDiJBBgxKgBNMID8KG9YOABzHBqsgGYcZK58HBgE3IhCX3JcxITheC4qCAYqOLCcFK10zKouHAgK4V8IK4vg0fHwrKtbe20UCyGUSVAQygAtLkIeDilscoUoAAaCZgQjBZTkKZUADiNAghyoAEkoMJNGBcld4IdfGNksJgqRqaIQEiQBAuAVoMJkKBVo9BDZVggeSgiIJ8HEeWyAEazMAUOAwUwrMBY5AwHDBOBsuASGVwZSqZTEMZTYL4KZwABib3yBSgU2QIHwOQgrPYMAkhGMNCZcDJ+AqphFTNIZXWzrALw95BKMBssymUmQDCImTZACthJgAELyxXKyRwMhA1PpnUgbOYUxYtIARVC8HL20rKxwJWdEmUmA9DwJcGMsy4zoeAdiMQ9AEcm3BExzRS7hBCgYbDR76DPSPRE5aU0g0622ZkJKQNVrK8I63BG604C2MyAYPgZcZ6lVkAAmNma-CkQFTFYEj7iAAYAKwej8AAqL6ioej5RNqJKqLAphgDgGgwIYSSmOsaQPm2GGwG+ygfkgACMAAMlEAL40UAA)
```sh
--parser mdx
--print-width 100
```

**Input:**
```mdx
<ExternalLink href="http://aws.amazon.com/codepipeline/">AWS CodePipeline</ExternalLink> is a continuous delivery and release automation service that aids smooth deployments. You can integrate 3rd party tools into any step of your release process or you can use CodePipeline as an end-to-end solution, including Ghost Inspector tests and suites.
```

**Output:**
```mdx
<ExternalLink href="http://aws.amazon.com/codepipeline/">AWS CodePipeline</ExternalLink> is a continuous
delivery and release automation service that aids smooth deployments. You can integrate 3rd party tools
into any step of your release process or you can use CodePipeline as an end-to-end solution, including
Ghost Inspector tests and suites.

```

**Expected behavior:**

Here the output optically looks correct, however if you view it in the playground or any editor that has a line length “ruler” you can see that each line is actually longer than 100 characters.

```
❯ echo '<ExternalLink href="http://aws.amazon.com/codepipeline/">AWS CodePipeline</ExternalLink> is a continuous' | wc
       1       6     105
```

This causes a bit of a problem if you have word wrapping on in your editor.

Screen Shot 2020-10-26 at 1 58 54 PM

If I remove the inline component it works fine, so the bug seems to have something to do with inline React components.

Thanks!

### PR DESCRIPTION
**Pull request by seiyab**
## Description
First step of https://github.com/prettier/prettier/pull/15909.
Narrowing the scope of `normalizeDoc()` that yields invalid `fill()`, this PR
- fixes #9503 
- make codeblock consistent with pure code format (CSS it most significant).
- Closes #9847

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] ~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).~
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
I totally forgot  https://github.com/prettier/prettier/pull/9847... I'll take a deeper look soon.

**Comment by fisker** [comment]
Calling `cleanDoc` on root seems useless, removed and tests still pass https://github.com/prettier/prettier/pull/15993/commits/bee898ac12b1c68fda81b68de83a36f64916fbcc

**Comment by fisker** [comment]
From what I can see is that we fix these test cases by removing the `normalizeDoc` call on root.
The result looks great!

**Review by fisker — APPROVED** [review]

**Comment by fisker** [comment]
Took another look at #9847, these two PRs are doing the samething 😄  We'll address https://github.com/prettier/prettier/pull/9847#issuecomment-770451578 in https://github.com/prettier/prettier/pull/15909.

**Comment by seiyab** [comment]
@fisker 
To fix word wrapping in paragraph, just `flattenFill()` is not sufficient. `flattenFill()` requires internal `fill()`s to be valid form but some `fill()`s like sentence yield invalid ones. https://github.com/seiyab/prettier/commit/842f0b5364bcb99c6c7d5d6f182d29fd24feee54 should result same as #15909.
Does this answer https://github.com/prettier/prettier/pull/15993#issuecomment-1925420991 well?

**Comment by seiyab** [comment]
I resolve conflict with https://github.com/prettier/prettier/pull/16032.

**Comment by seiyab** [comment]
@sosukesuzuki 
Don't you miss this PR?
There's no hurry. Just worrying that it's forgotten.

**Review by sosukesuzuki — APPROVED** [review]
Thank you for working on this

**Pull request merged**
