### PR TITLE
Fix printing of exact object flow type annotations

### LINKED ISSUE #1089: Empty exact object flow type is changed as non-exact
Prettier turns this:

```js
type Props = {||};
```

into this:

```js
type Props = {};
```

...which changes the type. This feels like a bug.

This means different things in Flow: https://flowtype.org/try/#0C4TwDgpgBAogHgQwMbAPICMBWUC8UDeAPoQL4DcAUKJFAJIB2EiKG2e+5FFAZgK70oAlgHt6UJsmAAKYQC5YzNFgCUBEj35DRUQY0Uz5DCSxVqux6fijdhcqAHJ0CAE72oJZZV0WpVm3ccXNw9KIA

Here's the prettier run: https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Props%20%3D%20%7B%7C%7C%7D%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

### PR DESCRIPTION
**Pull request by lydell**
Fixes #1089.

Where do you want me to add a test?

### CODE REVIEW

**Comment by vjeux** [comment]
@lydell thanks! The location doesn't matter much as long as there is a test for it.

**Comment by lydell** [comment]
Test added! While doing so, I noticed that there are no tests at all for exact objects (I ran `git grep '{|' tests`). Perhaps it is time to sync `tests/flow/` with `tests/` in the flow repo? I just checked there, and it does contain two `{||}` so that would have caught this bug :)

**Comment by vjeux** [comment]
I should have cleanly split the flow tests apart from our own, so it should just be a matter of cp -R the flow ones inside of prettier. If you are interested in doing it, that would be awesome :)

**Comment by lydell** [comment]
I started looking into it, but I ran into a problem and now I'm so confused that I'll have to take a break before continuing :)

Here's what I did: Removed `node_modules/` and then ran `yarn`. The I ran `jest`. Here the end of its output:

```
Snapshot Summary
 › 34 snapshot tests failed in 20 test suites. Inspect your code changes or re-run with `-u` to update them.

Test Suites: 21 failed, 436 passed, 457 total
Tests:       34 failed, 1420 passed, 1454 total
Snapshots:   34 failed, 1271 passed, 1305 total
Time:        31.579s
Ran all test suites.
```

Am I doing something wrong, or are a bunch of snapshots out of date?

**Comment by vjeux** [comment]
I have a brand new machine and master works fine for me

```js
git clone https://github.com/prettier/prettier.git
cd prettier/
yarn
yarn test

Test Suites: 457 passed, 457 total
Tests:       1464 passed, 1464 total
Snapshots:   1315 passed, 1315 total
Time:        27.944s
```

**Comment by lydell** [comment]
Thanks, you're right. Turns out I had accidentally committed some tests without noticing!

When copying over files from the flow repo, I see a lot of deletions in the diffs. Tests seem to have been added to some files since they were copied. My plan is:

1. Find the additions by us and split them out.
2. Write a script that syncs with the flow repo, and commit that script.
3. Run that script and commit the new tests.
4. Document.

It might take a few days for me to get around doing that. Stay tuned!

**Comment by vjeux** [comment]
Omg, you're the best!

**Pull request merged**
