### PR TITLE
Markdown: fix HTML formatting broken if the beginning tag starts after a list item

### LINKED ISSUE #5907: Markdown: HTML formatting broken if the beginning tag starts after a list item
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBaABAQXQGwJYDOM6e8AtgHQA6UAPACZwwCGeOBAfLQQK5lnMATgE8OAZT4CRtAPS9+Q0TVoAHDjRoZs+IiXLUoymWqOMWbTjRAAaEBBUw80AslBDBEAO4AFIQhcozABuEHj0NiAARoLMYADWTGIqsXhQAObIMII8cLYAFjBkOADqeaRwBMlgcGL+pHhBpMLI4AQutqkEcIIw3jFpAsgAZszsuSAAVgQAHgBCMfGJzGRwADKpcMOjXbZT02KpaThwAIo8EPBbY7bJgl2CLVJx9F5QESqCqTDFYTB5yAAOAAMNw8XWKMRULQ+FW6QU2tkEcAAjjw8Ei+swBswrjsQF0yHhMtlxgRDsczhdNkgRtcQCxIj96H9kAAmWxZVj4dIAYQgChaUGgCJAPC6ABVmJEArSugBfOVAA)
```sh
# Options (if any):
None
```

**Input:**
```md
- A list item.
<details><summary>Summary</summary>
<p>

- A list item.

</p>
</details>
```

**Output:**
```md
- A list item.

  <details><summary>Summary</summary>
  <p>

- A list item.

</p>
</details>
```

**Expected behavior:**
I'd expect output like:
```md
- A list item.

<details><summary>Summary</summary>
<p>

- A list item.

</p>
</details>
```
If I enter such Markdown manually, Prettier doesn't touch it.

The output Prettier produces for the initial input is broken; the original file defines proper HTML with list items inside of the `details`; the output Prettier produces takes the list item outside of the `details` element. Compare on GitHub:

Before:

-----

- A list item.
<details><summary>Summary</summary>
<p>

- A list item.

</p>
</details>

-----

After:

-----

- A list item.

  <details><summary>Summary</summary>
  <p>

- A list item.

</p>
</details>

-----

### PR DESCRIPTION
**Pull request by sasurau4**
fix #5907

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

## Note

I apologize for making mistakes creating a lot of troublesome PRs (#7182 - #7201) and sending unnecessary notifications to repository watchers and maintainers :bowing_man:

### CODE REVIEW

**Comment by sasurau4** [comment]
@evilebottnawi  Thanks! I added another test and updated changelog.
Do you have any other test cases?

**Comment by thorn0** [comment]
What if the HTML block is supposed to be inside the list item? This PR breaks this case.

**Prettier pr-7181**
[Playground link](https://deploy-preview-7181--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBaABAQXQGwJYDOM6e8AtgDpTroA8ARjhGANYCOArhPAHwCGBACYAzWgHpGzdl14gANCAgAHGHmgFkoPgCdtEAO4AFHQg0o+ANwh5B8kPW19WcGAGUlTvFADmyGNo44BQALGDIcAHVg0jgCDzA4V1NSPAtSAE9kcAINBS8COG0YQ0dvMj5kYT4cAoUAKwIADwAhR2c3PjI4ABkvOErq2pAGxtcvbxw4AEUZfqQqmqCQD20C7Szy7RZBAyg7JW0vGAibGGDkAA4ABgUDiAKIxyUsg9jCi36FTm44EuUzEACVBQOBwQRguzaOCcPBQkp8MoVeaDJYFMh4PwBVHjSYzH4DRYKGB8egnQRnZAAJiJjjw+B8AGEIGRylkoNBPiAOAUACokswLIYWQIASSg4NgrjAhxUmHFrhg6UmBIKAF9VUA)
```sh
--parser markdown
```

**Input:**
```markdown
- A list item
  <blockquote>asdf</blockquote>
```

**Output:**
```markdown
- A list item
<blockquote>asdf</blockquote>
```

**Expected:**
```markdown
- A list item
  <blockquote>asdf</blockquote>
```

**Comment by evilebottnawi** [comment]
@thorn0 Can you open issue?

**Comment by thorn0** [comment]
@evilebottnawi done https://github.com/prettier/prettier/issues/7218

**Pull request merged**
