### PR TITLE
[WIP] Update `remark-parse` to v7

### PR DESCRIPTION
**Pull request by fisker**
Update `remark-parse` to v7

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
@evilebottnawi I `Draft` and `[WIP]` means not ready for review

**Comment by evilebottnawi** [comment]
@fisker i see so I ask what status, since I thought to do it and I would not want us to spend time on the same work

**Comment by fisker** [comment]
@evilebottnawi forgot about the progress, you can do it

**Pull request closed without merging**
