### PR TITLE
Add new lint rule `prefer-path-get-value`

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Adds new rule for #13447

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Should prefer getters #13448.

**Comment by sosukesuzuki** [comment]
I've noticed https://github.com/prettier/prettier/pull/13448 now! It is a great.

**Comment by sosukesuzuki** [comment]
We need `prefer-path-getters` new rule?

**Comment by fisker** [comment]
The `.key` is different than `.getName()`, I think we should do it manually. But `.getValue()` can do automaticlly.

**Pull request closed without merging**
