### PR TITLE
fix: add jsdoc plugin for prettier source

### PR DESCRIPTION
**Pull request by hosseinmd**
I added prettier-plugin-jsdoc and resolved some jsdoc issues.

For some reason, some docs shouldn't format so for ignoring them I added them to commentLine.

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by hosseinmd** [comment]
@fisker I have trouble with tests. I don't know what exactly happened.

**Comment by fisker** [comment]
The tests seems running with the plugin, but I'm not sure how to fix it.

Try add `{"plugins": []}` to `.prettierrc`?

**Comment by hosseinmd** [comment]
> The tests seems running with the plugin, but I'm not sure how to fix it.
> 
> Try add `{"plugins": []}` to `.prettierrc`?

That does not work. This plugin doesn't need to be added to the plugins list (I think this is a bug). When installed in a project it is in prettier plugins.

**Comment by hosseinmd** [comment]
But `"plugins": []` doesn't work. Needed another way to prevent prettier search for it

**Pull request closed without merging**
