### PR TITLE
Initial CSS support

### PR DESCRIPTION
**Pull request by vjeux**
I wanted to see how hard it would be to add support for CSS inside of prettier. Turns out, it's not that hard. I spent a few hours printing post-css values and getting all the stylefmt unit tests to not throw.

### CODE REVIEW

**Comment by azz** [comment]
Pretty-print the planet!

**Comment by vjeux** [comment]
I migrated over to https://github.com/shellscape/postcss-values-parser (from https://github.com/TrySound/postcss-value-parser ) and had to send a PR to fix nested function parsing ( https://github.com/shellscape/postcss-values-parser/pull/27 ).

Except for media queries (I need to start using https://github.com/dryoma/postcss-media-query-parser ) and crazy sass functions, the output of all the stylefmt tests look good at first glance. This is extremely promising :)

The big thing that's going to block real adoption is to port the comment handling logic we have in JS to CSS. Right now most of the CSS parsers just drop all the comments, which is not acceptable!

I did a quick look at all the stylefmt outstanding bugs and most of them are already fixed in this PR. It's great to be able to use a solid foundation!

**Comment by vjeux** [comment]
I now prefix all the nodes and added media query parsing

**Comment by mathieudutour** [comment]
Seems broken here: https://gist.github.com/vjeux/e1d1b286d87dabddd7740fed1c7d213d#file-nuclide-diff-L125-L128

**Comment by vjeux** [comment]
@mathieudutour yeah, need to add an indentation in this case, so it's obvious it belongs to the same rule. Note that this is valid css :)

**Comment by lydell** [comment]
Would it make sense to have a separate printer.js file for every non-JS-y language?

**Comment by vjeux** [comment]
Yes, most likely. Also there's a lot of cleanup to do, the printer file could be split into more meaningful pieces.

**Comment by andreypopp** [comment]
Pinging @lahmatiy with his [csstree/csstree](https://github.com/csstree/csstree) parser which might do better work at handling comments.

**Comment by vjeux** [comment]
The ast of csstree seems to be much cleaner than postcss.

It doesn't seem to be outputting any comment: https://astexplorer.net/#/gist/244e2fb4da940df52bf0f4b94277db44/f9011cd86adfea73546ab352ae6b74b403cef20d

I don't see it supporting less and sass?

**Comment by ai** [comment]
It has fork API to create Sass and Less parsers, but right not csstree parses only valid CSS (I am not sure about parsing CSS Modules or PreCSS extensions).

BTW, right now we are discussing of merging Sass, PostCSS and csstree parses together. But it could takes a months, so you can start from PostCSS.

**Comment by vjeux** [comment]
I'm merging it as is as I want to spend the day refactoring the codebase a bit.

**Pull request merged**
