### PR TITLE
Add Eye Square to users

### PR DESCRIPTION
**Pull request by montogeek**
Thanks for prettier!

### CODE REVIEW

**Comment by duailibe** [comment]
Thanks for the PR!

Two requests to be consistent with the other logos:
- Can you change the height of the image to be 100px?
- Can you rename the file to `eyesquare-200x100` ?

**Comment by montogeek** [comment]
@duailibe Done

**Comment by duailibe** [comment]
I'm sorry, I wasn't clear. I meant to change the height to 100px but preserving the 200px width.

**Comment by montogeek** [comment]
@duailibe that would skew the logo, I could change the canvas size though.

**Comment by duailibe** [comment]
@montogeek Yeah, I meant the filling the rest with empty space. Like this:
image

You can use this one if I didn't screw anything up :)

**Comment by montogeek** [comment]
@duailibe Oh thank you, sorry I was updating it as well.

**Comment by duailibe** [comment]
Thanks ❤️ 

Sorry for the confusion!

**Comment by montogeek** [comment]
@duailibe To you!

**Pull request merged**
