### PR TITLE
Badge maintenance

### PR DESCRIPTION
**Pull request by j-f1**

### CODE REVIEW

**Comment by j-f1** [comment]
Looks like we’re trying to install with npm on Circle and npm seems to be unhappy.

**Comment by duailibe** [comment]
I don't know why your PR made CircleCI run an old config for this.. it used the correct config for #4501

**Comment by ikatyang** [comment]
I guess this PR is based on an old branch, rebasing should fix it.

**Comment by duailibe** [comment]
Thanks @ikatyang didn't notice that

**Comment by j-f1** [comment]
I did this PR from the web editor so I couldn’t update my fork’s `master` before creating this branch.

**Pull request merged**
