### PR TITLE
Mention `@prettier/sync` in changelog

### PR DESCRIPTION
**Pull request by fisker**
## Description

I built a sync version of Prettier APIs. Just in case people need.

[`prettier-sync`](https://github.com/fisker/prettier-sync)

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
What do you think move `prettier-sync` to Prettier org?

**Comment by fisker** [comment]
I can, should we release as `@prettier/sync`?

**Comment by fisker** [comment]
Done https://github.com/prettier/sync

**Comment by sosukesuzuki** [comment]
I prefer `prettier/prettier-sync`

**Comment by fisker** [comment]
I think it's fine to use `sync`. I've unpublished `prettier-sync`, will release as `@prettier/sync`.

**Comment by kachkaev** [comment]
Out of curiosity, why is it https://github.com/prettier/prettier-synchronized and not https://github.com/prettier/prettier-sync?

**Comment by kachkaev** [comment]
Side suggestion: register `prettier-sync` on NPM to avoid its hijacking.

**Comment by fisker** [comment]
> why is it https://github.com/prettier/prettier-synchronized

Inspired by [babel-synchronized](https://www.npmjs.com/package/babel-synchronized)

> register prettier-sync on NPM to avoid its hijacking.

Don't think that's nessary, I gave that name up, when we decide to publish under `@prettier/`

**Pull request merged**
