### PR TITLE
Add Google Site Verification file

### PR DESCRIPTION
**Pull request by lipis**
In order to enable the [webmaster tools](https://www.google.com/webmasters/) we need this file.

screen shot 2018-02-21 at 14 56 47

Once verified I can add owners to the project.

### CODE REVIEW

**Comment by lipis** [comment]
Send me your emails if you want to have access via DM from https://twitter.com/lipis :)

**Comment by j-f1** [comment]
I don’t have Twitter, but my email address is  [hit edit to see it].

**Comment by lipis** [comment]
@j-f1 added :)

**Comment by j-f1** [comment]
@lipis I can’t see it on my dashboard. Can you double-check please?

**Comment by lipis** [comment]
If I remember correctly you have to add it manually `https://prettier.io` and since you are whitelisted it will appear then.

**Comment by j-f1** [comment]
That doesn’t work :(

screen shot 2018-02-21 at 09 12 45

**Comment by lipis** [comment]
`httpS`

**Comment by j-f1** [comment]
That explains it. Thanks! 🎉

**Comment by lipis** [comment]
We need to wait a couple of days though for the data to arrive..

**Pull request merged**
