### PR TITLE
Fix parser inference

### PR DESCRIPTION
**Pull request by fisker**
## Description

Should infer parser by filenames first, then by extensions.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — APPROVED** [review]

**Comment by HolgerJeromin** [comment]
Just as a reference:
This makes tools like jsonlint (linting `*.json` in my project) and visual studio intellisense unhappy. :-(

**Comment by henrikvolmer** [comment]
Does not work with `.eslintrc.json` files (and maybe many other files, which aren't support `jsonc`). 

https://github.com/prettier/prettier/issues/15946

Please revert.

**Comment by erikbrgn** [comment]
Absolutely breaks`jest` if you have trailing commas enabled in `prettier` and import your `tsconfig.json` in your `jest` config. The tsconfig can no longer be parsed because of that. I guess a temporary solution would be to ignore formatting the tsconfig.

**Comment by gaby** [comment]
I don't understand why this was added, even less as a patch release. Our CI's are now failing because of conflicts between prettier and jsonlint, jq, etc

**Pull request merged**
