### PR TITLE
Add parser check to flow-comment related checks

### PR DESCRIPTION
**Pull request by fisker**
Make related part little safer for other parsers.

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
This code path is intended only for `--parser flow`. Babel, the way it's configured now, doesn't parse Flow comments into AST nodes.

**Comment by fisker** [comment]
Are you sure about this? Let me try.

**Comment by fisker** [comment]
No, not only `flow`,

https://github.com/prettier/prettier/blob/357196cf3c0ae248a135ea1268219c4744e16dbb/src/language-js/printer-estree.js#L1008-L1010

This line definitely for `babel`, because with `--parser=flow`, there will be no comment there

**Comment by thorn0** [comment]
I said nothing about that code path. I mean the one that this PR modifies.

**Comment by fisker** [comment]
I added it to it too.

**Comment by thorn0** [comment]
Sorry, overlooked that. I meant the `"case "TypeParameterDeclaration": case "TypeParameterInstantiation"` part. It's intended for `flow` only whereas the other one is for the other parsers, not only for Babel as the original purpose of Flow comments is to keep code JS-compatible:

> Flow supports a comment-based syntax, which makes it possible to use Flow without having to compile your files.

-- https://flow.org/en/docs/types/comments/

**Review by thorn0 — APPROVED** [review]

**Review by evilebottnawi — APPROVED** [review]

**Pull request merged**
