### PR TITLE
Revert #7889

### PR DESCRIPTION
**Pull request by sosukesuzuki**
context: https://github.com/prettier/prettier/issues/8776#issuecomment-660358745
Revert #7889. We should reopne #3594 and #3621 after this PR is merged.

- [x] I’ve added tests to confirm my change works.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
@fisker @evilebottnawi Could you review this? This is a blocker of 2.1.

**Comment by evilebottnawi** [comment]
What is status of typescript@4, because I think we will need to do release for this too?

**Comment by thorn0** [comment]
I'll try to find time to get back to #8063 this week. If I don't make it, then let's do this revert.

**Comment by sosukesuzuki** [comment]
Can we merge this?

**Comment by evilebottnawi** [comment]
Yes, let's merge and continue working on 2.1 release

**Comment by fisker** [comment]
Related issue not reopened

**Comment by rattrayalex** [comment]
Hey @thorn0 @fisker , been a while! Was this revert supposed to be temporary? Should #7889 come back? It seems like a great change to me! (I was going to come to advocate for something like that, but looks like @thorn0 already did the work!)

**Pull request merged**
