### PR TITLE
Avoid printing attribute per line in Vue SFC blocks

### LINKED ISSUE #12787: Avoid tags for the singleAttributePerLine rule
Is it possible to specify a list of tags to avoid for this rule? I'm working with Vue 3 and I would LOVE to keep both of this tags in one line:

```
<script
  setup
  lang="ts"
>
  ...
</script>
```

```
<style
  scoped
  lang="scss"
>
  ...
</style>
```

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #12787 

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
I don't see the point to treat it differently.

**Comment by jd-solanki** [comment]
> 

It will be more readable to don't add new lines for `script` and `style` in vue. Recently PR #5501 merged after lots of requests. We had to wait long for it. This PR is targeting a user who uses TypeScript and even without TypeScript vue devs sometimes need `lang="scss" scoped`.

If we don't consider TypeScript, `<style lang="scss" scoped>` is a basic need in any vue project. Making it multiline is the same case as indenting the script and style block.

I request you to please approve this 🙏🏻 

This is already breaking the syntax highlighting for vue extension Volar and I submitted the issue as well https://github.com/johnsoncodehk/volar/issues/1258

Thanks to the team we got #5501 PR in prettier but this is still holding us back 😢 

I hope the team consider this PR for the upcoming release.

Thank you :)

**Comment by ronaklalwaniii** [comment]
Yes. This is also holding us back.

It will be great if we can get this in the next release.

**Comment by fisker** [comment]
If someone use `<a id=xx></a>` inside template.  
Or `<body class=foo>` in html file.
Should we treat them differently too? If the answer is true, what's the boundary then?

**Comment by fisker** [comment]
Vue also support [`<script setup="{/* this can be long */}">`](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md#template-binding-optimization), how should we format this?

**Comment by jd-solanki** [comment]
> If someone use `<a id=xx></a>` inside template. Or `<body class=foo>` in html file. Should we treat them differently too? If the answer is true, what's the boundary then?

Only vue's script and style block will get omitted because both are SFC blocks, not markup content.

> Vue also support [`<script setup="{/* this can be long */}">`](https://github.com/vuejs/rfcs/blob/master/active-rfcs/0040-script-setup.md#template-binding-optimization), how should we format this?

As per above, `script` is not markup content we can just omit the single attr per line for it and keep it as it is for this rule.

Regards.

**Comment by fisker** [comment]
I guess I can stay neutral. Anyway, if we want merge, the following cases should be tested.


```vue
<script lang="ts" src="./long_long_long_long_long_long_file_path.ts">
</script>

<script lang="ts" src="./long_long_long_long_long_long_long_file_path.ts">
</script>

<script lang="ts" src="./short">
</script>

<template lang="pug" src="./long_long_long_long_long_long_file_path.pug">
</template>

<template lang="pug" src="./long_long_long_long_long_long_long_long_file_path.pug">
</template>

<template lang="pug" src="./short">
</template>

<unknown-block foo bar="bar" baz long_long_long_long_attribute></unknown-block>
```

Are we missing `singleAttributePerLine` option on playground? I didn't see it.

**Comment by jd-solanki** [comment]
It can't see that as well 👀

**Comment by sosukesuzuki** [comment]
I use Vue occasionally and found this formatting in current Prettier unacceptable. Since top-level SFC blocks are special to Vue SFC, I see no problem in applying different formatting rules to them than to other tags.

**Review by fisker — APPROVED** [review]
Just for the record, I really don't like the idea, but won't block either, I don't use `singleAttributePerLine`.

**Pull request merged**
