### PR TITLE
Build: Add `--no-babel` flag

### PR DESCRIPTION
**Pull request by fisker**
## Description

Add `--no-babel` flag for debugging purposes.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
Looks good to me except CI failed

**Comment by fisker** [comment]
Do you think we should use this flag for playground? We don't need to support old browsers, at least not for PR.

**Comment by sosukesuzuki** [comment]
> Do you think we should use this flag for playground? We don't need to support old browsers, at least not for PR.

Sounds good!

**Comment by fisker** [comment]
@sosukesuzuki I saw `buildPrettier` in `scripts/build-website.mjs` only called if it's PR, do you know how the stable version build those files?

**Comment by fisker** [comment]
Ah found it 

```js
const PRETTIER_DIR = IS_PULL_REQUEST
  ? DIST_DIR
  : path.dirname(require.resolve("prettier"));
```

**Pull request merged**
