### PR TITLE
Update users.yml

### PR DESCRIPTION
**Pull request by ndonovic**
The new logo can be found in this article: https://www.toptal.com/designers/logo/toptal-new-brand-and-logo

I added Toptal as a resource as a company that uses Prettier - followed what all the others looked like. I'm not sure if you have a Toptal logo on hand so I just put that in there as a placeholder - you can find that image in the blog post I posted above. 

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
You need commit the logo here https://github.com/prettier/prettier/tree/master/website/static/images/users

**Comment by ndonovic** [comment]
Thank you, I have done so. Please do let me know if dimensions/formatting is correct or if there's anything I need to change. Thank you.

**Comment by lipis** [comment]
You didn't upload the logo :)

**Comment by lipis** [comment]
Check the changed files.. it seems that you updated only the users

**Comment by ndonovic** [comment]
Thank you for your reply. So I created a new pull request with the uploaded logo. This is my first time using Github like this, so I am very new to this world. See new pull request here: https://github.com/ndonovic/prettier/pull/2 - I dragged and dropped the image when I clicked upload file, then for good measure I put it in the description there. :)

**Comment by thorn0** [comment]
No need to open a new pull request. You need to add the file to the branch `patch-1` associated with this pull request: https://github.com/ndonovic/prettier/tree/patch-1/website/static/images/users

You can probably use the same <kbd>Upload</kbd> button there, but I don't promise this will work as I never used it. Most people don't use GitHub's web UI for this kind of operations. Changes are made using [Git](https://help.github.com/en/github/getting-started-with-github/set-up-git).

**Comment by thorn0** [comment]
BTW, this company, Toptal, how do you know they use Prettier? You aren't a developer, right?

**Comment by ndonovic** [comment]
@thorn0 Thank you, I did as you recommended. 

And you're correct, I am not a developer, but a developer colleague told me that he used Prettier :)

**Pull request merged**
