### PR TITLE
fix formatting of pseudo-elements and pseudo-classes in styled-component

### PR DESCRIPTION
**Pull request by thorn0**
fixes https://github.com/prettier/prettier/issues/7826

The solution is pretty dirty, but hopefully it will do for now.

- [x] I’ve added tests to confirm my change works.
- (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
@fisker This is the first PR without Azure Pipelines checks. Could you please check that everything works as expected here?

**Comment by fisker** [comment]
#6794 can also fix it, and many styled-component issues.

**Comment by thorn0** [comment]
#7826 is a regression that I'd like to fix quickly and release 2.0.2.

**Comment by fisker** [comment]
Sure, I'll let you know if something missing.

**Comment by fisker** [comment]
This is taking forever.... Still `Queued`, this is why I prefer keep both for a while.

**Comment by thorn0** [comment]
We might have exceeded some limitations. After I merged #7431, existing PRs went crazy like this:

image

**Comment by fisker** [comment]
This is because github actions don't clear previous build status on force push.

**Comment by thorn0** [comment]
Is this fixable?

**Comment by thorn0** [comment]
The CI fail is related to coverage (`The coverage upload was rejected because the workflow run is either not in-progress or finished a while ago.`). All the tests pass.

**Pull request merged**
