### PR TITLE
Correct `standalone test` environment variable

### PR DESCRIPTION
**Pull request by fisker**
refs:
- [old azure pipeline settings](https://github.com/prettier/prettier/commit/34115cbd3c7101a6be733e8d3288fe46d0eb10f5#diff-fec826feae04e51c0d94076385408bdcL90)
- [mistake](https://github.com/prettier/prettier/pull/7431/files#diff-2d1d1197987e7769ed317c9ef37ea11dR110)

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
How do I know it's correct or not? I guess have to check locally.

**Comment by thorn0** [comment]
> How do I know it's correct or not? I guess have to check locally.

One way is to add a test that standalone doesn't have methods like `getFileInfo` and `clearConfigCache`.

**Comment by fisker** [comment]
Problem is  I don't even know if it's running standalone test.

**Comment by thorn0** [comment]
Right. So we can add a test that would check  `prettier.getFileInfo` should be `undefined` if and only if this env variable is set.

**Comment by fisker** [comment]
But if I set the variable name  wrong again, jest will run the default tests, still get pass.

**Comment by thorn0** [comment]
The default test should assert the opposite: `prettier.getFileInfo` should be defined.

**Comment by thorn0** [comment]
Also we could add some kind of report to which each test run would add something (only on CI) and in the end a separate step will check that this report is correct.

**Pull request merged**
