### PR TITLE
Added support for the graph ql comment tag

### PR DESCRIPTION
**Pull request by tjallingt**
As described in the issue https://github.com/prettier/prettier/issues/4360
Prettier still adds a space in between the comment tag and the template literal.

### CODE REVIEW

**Comment by duailibe** [comment]
After reading https://github.com/prettier/prettier/pull/4395#commitcomment-28780404 I don't think we should do this. Feels really hack-ish. The suggestion in https://github.com/prettier/prettier/issues/4360#issuecomment-385070286 seems like a better solution

```js
const gql = String.raw;

gql`query MyQuery {}`;
```

**Comment by tjallingt** [comment]
@duailibe well I mean this is the way those other tools do this as well so its not more or less hacky than those other tools ("would you jump off a bridge if your friends did" fallacy i know...) additionally 
```javascript
const gql = String.raw;

gql`query MyQuery {}`;
```
also feels kinda hacky...

but its your call, I understand your hesitation to merge this 😕

**Comment by tjallingt** [comment]
Actually after thinking about it, the `String.raw` workaround doesn't work if you are using the actual `gql` tag in the same file. (Which i guess you could fix by using one of the other template tags prettier formats as graph ql but thats a workaround ontop of a workaround...)

Additionally I dislike it as a workaround because of someone sees ```gql`...```` but doesn't see the `const gql = String.raw` part they might get a completely wrong idea of what the code is doing only because prettier doesnt handle formatting arbitraty template literals as graph ql...

**Comment by jaydenseric** [comment]
@duailibe https://github.com/prettier/prettier/issues/4360#issuecomment-385218271

**Comment by suchipi** [comment]
@duailibe could you expound on why you think we shouldn't do this?

**Comment by duailibe** [comment]
@suchipi Just feels like we already have a pretty consistent way to format non-JS stuff in JS, that is using template literals or `<style>` tags and it's been working really well.

Comments is an area of Prettier that works good enough for the effort we've put in but we still get reports of it's behavior so it seems a fragile strategy to rely on them for this kind of stuff.

That said, I changed my mind and I don't oppose to it. If other maintainers are comfortable with adding this functionality, I'm on board.

**Comment by tjallingt** [comment]
So what is the status of this discussion?
Are you willing to merge this provided I fix the failing test?

**Comment by j-f1** [comment]
I’m 👍 on the change, and @duailibe seems have changed their mind and is also 👍 (or at least not 👎).

**Comment by duailibe** [comment]
@tjallingt to fix the test, you probably need to skip the check of the AST here: https://github.com/prettier/prettier/blob/master/src/language-js/clean.js

**Comment by tjallingt** [comment]
That should fix the failing test 👍 

I really don't like that i had to duplicate the hasGraphQLComment stuff so maybe that should be exported to clean? (don't know what your stance on this is)

**Comment by suchipi** [comment]
@tjallingt let's not worry about the space between the comment and the template literal tag for now. Also, I'm not sure we have a consistent approach with duplicated logic in clean; do whatever you feel is best.

**Comment by tjallingt** [comment]
The it's ready for review and merge I think

**Comment by lydell** [comment]
@tjallingt There are some merge conflicts to fix before merging, though

**Comment by suchipi** [comment]
Fixed the conflicts

**Comment by tjallingt** [comment]
oh mb didn't see them 😕 
Thanks for fixing @suchipi 👍

**Pull request merged**
