### PR TITLE
Refactor angular control flow block

### PR DESCRIPTION
**Pull request by fisker**
## Description

- Change node type from 'block' to 'angularControlFlowBlock'
- Add an wrapper "angularControlFlowBlockParameters“ for parameters

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — APPROVED** [review]

**Comment by fisker** [comment]
Yes, please wait.

**Comment by sosukesuzuki** [comment]
>  Yes, please wait.

Okay, thank you.

**Comment by fisker** [comment]
Do you think we are not respecting whitespace? But I don't think I have time for it...

**Comment by fisker** [comment]
```
<span>@if(foo){A}</span>
```

Should be

```
<span>A</span>
```

Not

```
<span> A </span>
```

**Comment by sosukesuzuki** [comment]
I tried that case in this PR's playground and it seems more broken...

**Prettier pr-15614**
[Playground link](https://deploy-preview-15614--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQHwACAlgGYAUJEEAlMAIIC+qA9FrngDpQgA0IEmGEWjpkobACcJEAO4AFSQlEpsAGxnYAnqL4AjCdjABrODADK2ALZwAMkShxkJNejh6Dx02Zxh7Ac2QYCQBXNxBXSyJAkLD0f1U4AEVgiHgnFzCAK3QADzN4pJS0pGdVVz4ARyK4OWlMZRBsdABaBzgAEw7eECDsIlV-AGEIS0tsZEbVVW64qD8Euhggol1g+Dk4CTsHdLKwgAsYS1UAdX2ieDYwODMlC6IANwvNCbB0HRAH0IBJKE7YMxgCREQR0P5mGCaBK7cogTDSVwnAyYCbwuCuCQPRx8ewYmC1bB+MYwsI4CQYia4PzBVSSbrw+wwE5EdowfbIAAcAAY+BI4FUiHyCUTxiUMnwYNhdMzWeykAAmPjBVwAFSlylKsLgll0HU67RsVOChLgADEIBIxkt-JS1hAQAwGEA)

```sh
--parser angular
```

**Input:**

```html
<span>@if(foo){A}</span>

```

**Output:**

```html
<span
  @if (foo) {
    A
  }
>

```

**Comment by sosukesuzuki** [comment]
> Do you think we are not respecting whitespace? But I don't think I have time for it...

Ah I see. Would you like to create an issue as a known issue?

**Comment by fisker** [comment]
Let's wait for community to report? :smile:

**Comment by sosukesuzuki** [comment]
:+1:

**Pull request merged**
