### PR TITLE
Update `jest-watch-typeahead` to v0.4.0

### PR DESCRIPTION
**Pull request by fisker**

### CODE REVIEW

**Comment by fisker** [comment]
rebased

**Comment by evilebottnawi** [comment]
Can't be merged https://github.com/jest-community/jest-watch-typeahead/releases/tag/v0.4.0

**Comment by fisker** [comment]
@evilebottnawi add a tag ? we can merge when we start v2.0

**Comment by evilebottnawi** [comment]
@fisker I'm sure it will require rebase and you can unavailable so the PR will be stale, also before release 2.0.0 we update all deps too so i think better close this

**Pull request closed without merging**
