### PR TITLE
feat: use `postcss-values-parser` for `@namespace` at rule

### PR DESCRIPTION
**Pull request by evilebottnawi**
Part of https://github.com/prettier/prettier/pull/4181. `postcss-value-parser` is abadoned and bad parser many bleeding edge in `at-rules`

### CODE REVIEW

**Comment by lydell** [comment]
No snapshots changed?

**Comment by evilebottnawi** [comment]
@lydell yes

**Comment by evilebottnawi** [comment]
@lydell yep, `postcss-media-query-parser` is don't respect css spec. According css spec all values in at-rules and value in properties have same syntax. Look https://www.w3.org/TR/css-syntax-3/#parser-diagrams on At-rule and Declaration - one algorithm for get tokens - i.e. ast very same, only except keywords.

**Comment by evilebottnawi** [comment]
Example `cssnano` also use value parser for at rules and all works very very good. Maybe in future postcss implement basic support value parser and at-rule and we can remove some workaround, but it is don't break anything in theory :smile:

**Pull request merged**
