### PR TITLE
Print HTML5 `doctype` in lowercase

### PR DESCRIPTION
**Pull request by fisker**
Please DO NOT MERGE until we have consensus that this should be accepted. 

Fixes: #6502

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by lipis** [comment]
I'm down!

**Comment by thorn0** [comment]
It would be another incompatibility with XML. Why introduce it without a reason?

**Comment by fisker** [comment]
@thorn0 https://github.com/prettier/prettier/issues/6502#issuecomment-533840708

**Comment by lipis** [comment]
xml requires uppercase?

**Comment by thorn0** [comment]
@lipis yep https://www.w3.org/TR/xml/#NT-doctypedecl

**Comment by evilebottnawi** [comment]
I think we should discuss about supporting xhtml (xml)

**Comment by thorn0** [comment]
How about lowercasing it only if it's the HTML5 doctype (`<!doctype html>`)?

**Comment by evilebottnawi** [comment]
@thorn0 Problem what some developers can use not fully html template (with doctype) and we can potential break code

**Comment by thorn0** [comment]
I mean lowercasing only in this one case, when doctype is `<!doctype html>`. If it contains something else (e.g. after html`), it should be uppercase.

**Comment by thorn0** [comment]
As far as I understand, `<!DOCTYPE html>` is meaningless from the XML point of view, so lowercasing it should affect anything. Probably... :)

**Comment by kydesnic** [comment]
I understand the concerns about merging this as is. This is the explicit change of the current behaviour.
But couldn't this be done with a new configuration option? If the default configuration value will produce the current result, the existing users will not be affected. But those, who want to change the behaviour, will be able to tune it.

**Comment by fisker** [comment]
@kydesnic  We don't add options.

**Comment by fisker** [comment]
Can we include this in V3?

**Review by thorn0 — APPROVED** [review]

**Comment by JounQin** [comment]
AFAIK, prettier does not change the inputs but only prints, why it is changed here?

**Comment by JounQin** [comment]
AFAIK, prettier does not change the inputs but only prints, why it is changed here?

**Review by JounQin — CHANGES_REQUESTED** [review]
AFAIK, prettier does not change the inputs but only prints, why it is changed here?

**Comment by fisker** [comment]
> prettier does not change the inputs but only print

We change html tags to lowercase.

> why it is changed here

Check original issue https://github.com/prettier/prettier/issues/6502

**Comment by JounQin** [comment]
> We change html tags to lowercase.

So the correct change to me should be keeping the input as-is instead.

**Comment by JounQin** [comment]
@fisker It seems disagree with my opinion here which follows https://prettier.io/docs/en/rationale.html#what-prettier-is-_not_-concerned-about and it is mentioned a lot of times by @thorn0 elsewhere.

Maybe I ask why we are not consistent here?

**Comment by fisker** [comment]
I don't talk.

**Comment by thorn0** [comment]
Prettier usually normalizes case-insensitive things: CSS property names, HTML tag names, JS hex numbers, etc. Often it's done by the parser. When something is syntactically case-insensitive, it means case is styling/formatting, which is what Prettier deals with. Of course, there aren't strict definitions of what "formatting", "linting", "transform", etc. are, so the debates about this stuff can be endless.

**Comment by JounQin** [comment]
> Of course, there aren't strict definitions of what "formatting", "linting", "transform", etc. are, so the debates about this stuff can be endless.

@thorn0 

It makes sense to me. And then can we define what are considering as formatting into the policy on prettier's side in details? Otherwise it could still be confusing in the future.

For example, when the content is case-insensitive we usually print them in lowercase.

**Comment by thorn0** [comment]
> can we define what are considering as formatting into the policy on prettier's side in details

I don't believe it's possible to come up with clear and satisfying definitions. It's all too complicated and full of tradeoffs. E.g., what are numeric separators in JS? Syntax or formatting? Are the two ways to make a code block in Markdown (fenced and indented) just two different styles for the same syntactic thing, so they should be normalized to one style? The general idea is kind of simple: "preserve the syntax and regenerate formatting from scratch (keeping some elements of the original formatting when practical)", but when it comes to defining the line between syntax and formatting, things become tricky. I don't think this boundary is formalizable. Decisions should be made on the case-by-case basis. 🤷‍♂️

> Otherwise it could still be confusing in the future

I'd say it gets confusing mostly in bikesheddy cases like this doctype issue, where the practical value of doing it one way or another is really questionable.

**Comment by yoyo837** [comment]
https://github.com/prettier/prettier/issues/15096 Personally I want it to stay uppercase regardless of the standard, how do I control it from being converted to lowercase by prettier?

**Comment by eligrey** [comment]
DOCTYPE is case sensitive in XML contexts. With this change, prettier no longer supports my XHTML.

**Comment by eligrey** [comment]
Re: @thorn0 https://github.com/prettier/prettier/pull/7391#issuecomment-577099818

> As far as I understand, <!DOCTYPE html> is meaningless from the XML point of view anyway because it doesn't include a link to DTD. It's only [needed for the browser not to switch to a legacy mode](https://html.spec.whatwg.org/multipage/syntax.html#the-doctype), and browsers don't care about its case. So lowercasing it should not affect anything. Probably... :)
> 
> But also there is (or was, it's "no longer in active maintenance") a thing called [Polyglot markup](https://www.w3.org/TR/html-polyglot/#dfn-polyglot-markup), a way to write markup compatible with both syntaxes at the same time, and it [requires](https://www.w3.org/TR/html-polyglot/#doctype) the doctype to be uppercase.

The ['polyglot' markup](https://blog.whatwg.org/xhtml5-in-a-nutshell) is and has been supported by all major browsers (even IE & EdgeHTML) for over a decade. It has rare use in some sites and frameworks (including many of my own).

**Comment by yoyo837** [comment]
[Polyglot markup](https://www.w3.org/TR/html-polyglot/#dfn-polyglot-markup), doctype doc https://www.w3.org/TR/html-polyglot/#doctype Uppercase needed.

**Comment by Rock-n-Roll-CRC** [comment]
Are W3C standards a joke to you? _If something works, why would you ever want to ruin it?_ Revert the changes concerning the `<!DOCTYPE html>` casing.

**Comment by atesgoral** [comment]
DOCTYPE is not an HTML tag. It's a preamble. "We lowercase all HTML tags" shouldn't have applied here.

**Comment by ProximaB** [comment]
How to change that behavior?

**Comment by ptu14** [comment]
From: https://html.spec.whatwg.org/multipage/syntax.html#the-doctype

> A DOCTYPE must consist of the following components, in this order:
> 
> - A string that is an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for the string "<!DOCTYPE".
> - One or more [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace).
> - A string that is an [ASCII case-insensitive](https://infra.spec.whatwg.org/#ascii-case-insensitive) match for the string "html".
> - Optionally, a [DOCTYPE legacy string](https://html.spec.whatwg.org/multipage/syntax.html#doctype-legacy-string).
> - Zero or more [ASCII whitespace](https://infra.spec.whatwg.org/#ascii-whitespace).
> - A U+003E GREATER-THAN SIGN character (>).

> In other words, `<!DOCTYPE html>`, case-insensitively.

**Pull request merged**
