### PR TITLE
website: add State of JS 2020

### PR DESCRIPTION
**Pull request by thorn0**
## Description

see https://2020.stateofjs.com/en-US/other-tools/utilities

## Checklist

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by lipis — APPROVED** [review]

**Comment by lipis** [comment]
While we at it.. more than 2.5M deps: https://github.com/prettier/prettier/network/dependents and more than (almost) 7.5K on NPM: https://www.npmjs.com/package/prettier

**Comment by thorn0** [comment]
@lipis Those will be updated by the release script when the next release happens. See https://github.com/prettier/prettier/blob/main/scripts/release/steps/update-dependents-count.js

**Comment by lipis** [comment]
> @lipis Those will be updated by the release script when the next release happens. See [https://github.com/prettier/prettier/blob/main/scripts/release/steps/update-dependents-count.js](https://github.com/prettier/prettier/blob/main/scripts/release/steps/update-dependents-count.js?rgh-link-date=2021-02-14T21%3A09%3A56Z)

Nice..! Missed it :)

**Review by sosukesuzuki — APPROVED** [review]

**Comment by thorn0** [comment]
@lipis Do we still need this line in `website/README.md`

> Please run <code>yarn svgo _path/to/image.svg_</code> before committing a new SVG to the repository.

? Looks like ImgBot will override what svgo does anyway.

**Comment by lipis** [comment]
> @lipis Do we still need this line in `website/README.md`

Yeah I think we can get rid of that..

**Pull request merged**
