### PR TITLE
Update cspell.json

### PR DESCRIPTION
**Pull request by fisker**
- Ignore urls in `()`
- Ignore `png` file (It's matched by cspell)
- Update `test.*` to `test*.*`

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by evilebottnawi — APPROVED** [review]

**Comment by thorn0** [comment]
Why ignore URLs? Why not let cspell catch typos in URLs?

**Comment by fisker** [comment]
It's either right or wrong, why should we care about misspell in it?

**Comment by thorn0** [comment]
We should care about our own typos that can happen in URLs.

**Comment by fisker** [comment]
We use this  "\\/.*?\\/" to ignore regexp, so we  can't really catch a thing except `namee` in `https://github.com/namee`. the only part cspell reportted a lot, and nothing we can do.

**Review by thorn0 — APPROVED** [review]

**Pull request merged**
