### PR TITLE
Handle JSX whitespace separately from fbt whitespace

### PR DESCRIPTION
**Pull request by karl**
This is partial progress towards https://github.com/prettier/prettier/issues/2279

With this PR we now detect Facebook `fbt` tags and handle whitespace for them differently from other JSX tags.

This lets us tweak how we format whitespace in JSX tags without breaking the Facebook translation pipeline. This means we can now fix up some small JSX formatting edge cases that have always bugged me 😀

The main benefit here is improved consistency across different but equivalent inputs.

For example the current version of Prettier leaves these unchanged ([Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzAlgJwM4wAQC8eAFADpR54A8AJugG4B85llAKnAB4xUBGmeAPTMKrALIRMcPPG58BwlqwCCUGngC2kuPKEjKVQXSbkAlAG5y5bHEhrCJJbQb7WHOfz0SpMrj0-CqupaUrqKoobGIhZWsAAWWOpEZBFRSux+6dQBrpTe0rIwWWG5eEGa2sU5TkYuZuYgADQgEAAOMOjQ2MigAIaYmBAA7gAK-QjdKL30EOg0TSD8vWAA1nAwAMqty+hQAObIMJgArnDNuzaYMCOYvXsavciovQA2Ns0AVticAEK3q+sNr0NHAADK7OBPV7vEDbHBwTDIRa9XgATxe0AWrUwuxgAHU5jA4sgABwABma2IgNjxt1aSOxcEu9EhzSkAEdjlg4Dc7g8oW8ziAbBp0IcTkLsLs9i84ABFY4QeACmEwFEEmhE5AAJmaR166Be0oAwhANPyUFBoKyQMcbGwUZNnoKAL4uoA)):

```jsx
first = (
  <div>
    Text<br />
    More text<br />
    And more<br />
  </div>
);

second = (
  <div>
    Text<br />More text<br />And more<br />
  </div>
);

third = (
  <div>
    Text
    <br />
    More text
    <br />
    And more
    <br />
  </div>
);
```

And with this PR they become:

```jsx
first = (
  <div>
    Text
    <br />
    More text
    <br />
    And more
    <br />
  </div>
);

second = (
  <div>
    Text
    <br />
    More text
    <br />
    And more
    <br />
  </div>
);

third = (
  <div>
    Text
    <br />
    More text
    <br />
    And more
    <br />
  </div>
);
```

When the text separating tags or expressions is just a single character we display it on a single line where possible.

With the current version of Prettier ([Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPABAXnQCgDpTroA8AJgJYBuAfAUUcABYQCuATgL5LAC25ULeF2ABnOJCikOdEgHoKNAgEoA3AQIZs+QiQW0dDZu2kH0SGQz4ChFs7dHjoUmcXlV9q9VE24Xe+0ac5qa8-IJwXPZiEs46rv5QqiAANCAQAA4w5NAiyKAAhmxsEADuAAqFCLko+ZQQ5KQpIABGbPlgANZwMADK6e38AObIMGwscKn8YmwwZW2DPPnIAGb5ADZiqQBWIqgAQm2d3T35PHAAMvxwK+ubIP1s08gt+c0AnmvQTels-DAA6g0YIxkAAOAAMqR+EDE-za6WePzg00o11SbDgAEcWOQMXN8gslkhVhsJiAxHwRmMySIhms4ABFFgQeA3UmpGCvQGkYHIABMHLa5DWQwAwhAeItnlBoGiQCwxAAVV7VEliDgcIA)):

```jsx
x = (
  <div>
    {hour}:{minute}:{second}
  </div>
);

x = (
  <div>
    {hour}
    :
    {minute}
    :
    {second}
  </div>
);

x = (
  <div>
    {hour}:
    {minute}:
    {second}
  </div>
);
```

With this PR:

```jsx
x = (
  <div>
    {hour}:{minute}:{second}
  </div>
);

x = (
  <div>
    {hour}:{minute}:{second}
  </div>
);

x = (
  <div>
    {hour}:{minute}:{second}
  </div>
);
```

And finally I feel this PR improves the output of edges cases like this:

Input:

```jsx
this_really_should_split_across_lines =
  <div>
    before{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after
  </div>
```

Output in current version of Prettier ([Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgfQE5wCGANsQJ45ZoQCuxAJpQA7EYw6Fh4Ra6tRwsAAgC8AHShChAHnoYAbgD4JUqQCM4AMwgFgWGDU2aAvoU3w8eg0dPm4l-YZNmLVp7deObL+2+92Ha2cAv2DPII9fLzCoiJ9A93jQyIT-CxUZAHo5JQkQABoQCCYYDGgsZFBCPG4AdwAFaoQKlEJ5CAx6ApA1PE4AazgYAGUmTgwoAHNkGDwaOEKJrHsYer7JgFtCZE0SZcKAKywADwAhPrBBkcINuAAZCbgdvYWQMbxlvGQewjUyYmg3SYeAmMAA6p10MgABwABkKwJ4cDBfSY32Bgns8iehQIAEcaBgCGtCJttkhdsR9iBlhsMDM5q8sBNJsQ4ABFGgQeDPKmvGC-CH0KFIABMhVmhAw-EmAGEIBstt8oNAcSAaMsACq-FqU5bGYxAA
)):

```jsx
this_really_should_split_across_lines = (
  <div>
    before{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{
      stuff
    }after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{stuff}after{
      stuff
    }after
  </div>
);
```

Output with this PR:

```jsx
this_really_should_split_across_lines = (
  <div>
    before
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
    {stuff}
    after
  </div>
);
```

### CODE REVIEW

**Comment by karl** [comment]
This PR is now in a good place and it would be great to get some reviews, but I'm not sure who is the best person to look at this!

@vjeux If you had time it would be great if you could run this PR over some code at Facebook that uses the `<fbt>` tag. Ideally they shouldn't be changed by this PR!

**Comment by vjeux** [comment]
I'll try it out tomorrow.

**Comment by vjeux** [comment]
I just ran it on a big chunk of our codebase and it barely changes anything (and what it changes is for the better). Should be good to go :)

**Comment by karl** [comment]
Yay! That is great news 😁

**Pull request merged**
