### PR TITLE
fix(css): remove other types of whitespace in `clean`

### PR DESCRIPTION
**Pull request by evilebottnawi**
Based on https://github.com/prettier/prettier/pull/3794#discussion_r163313410

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@lydell how much approval do I need to make merge?

**Comment by lydell** [comment]
A green check mark from Travis is all that is needed for small things like this, I'd say :) I think it's better not to slow you down on your CSS fixing spree. If somebody finds something bad after merge we can revert or do a follow-up PR.

**Comment by lydell** [comment]
Looks like me and @j-f1 gave different answers :)

**Comment by j-f1** [comment]
*\*defers to the collaborator with more time working with the project\**

**Comment by lydell** [comment]
My point was that the CSS printing is generally buggy and not so polished like the JS printing, so I think it's fine to "let you loose" and fix things quickly. Many small PRs is still good since it's easy to review even after merges.

As opposed to PRs to the JS printing, which is very stable, or the core printing logic. That should be reviewed more before merging.

**Pull request merged**
