### PR TITLE
Support formatting for embedded `gql` function call

### LINKED ISSUE #14567: Template literal `gql` not recognized as function, but `graphql` is.
**Prettier 2.8.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwHMBHAG3wF98AzHCdfAHRGJwENMALCgWhgdirZlAzY8hEhXwcAziU48ZNeoxZslvcgKEioosuQAUAA1H5LV6zdt2bMAJ6Y4+AGIQIhC5YBGHHCR8AGUYHFQoYgBCUSpRUwBKUUMKcyh7DMzbJxd3T290vwCg0PDImKg4qDTDLQozHyym+xzXDy9gRv9AkLCI6Nj4hJAAGhAITBhUaDlkUACGAHcABQCEWZQOckWOR1mx304wAGs4GGCOdDgAGQi4ZFotuTgDo9PzzA4wfuQwgFcXiA4OhfHAACZg8HXDiRP5COAeHDoDgwKaRZAgDh-GAQUYgbgwdDkADq3FQ8DknzAcGC63JqAAbuTHBiwHJ9mgoM88MtOMRkQ8noCAFZyAAewX65DgAEU-hB4ILyM8xp8cNyMf5QeQ8ZgyjBiagwTBuMgABwABlVDGexKUGL1cG5DPuY1I8vgvImG0xcj4UDg4PBeJwcHdqFDvKEAqQj2VgOe6FQvxwALGcilcAAgqjwr5sXBlnAcLcA0qVSAM5FpXKFfdY0KxoJfIbjaakAAmJucVDkfoAYUYMaBcgArHi-s8ACocXwbOMVhkAgCSUEhsGCYHCkyza9Cjml5bgVCoQA)

```sh
# Options (if any):
```

**Input:**

```jsx
import { gql } from "graphql-tag"
import { gql as graphql } from "graphql-tag"

gql(`
                                 type Foo {
   bar: String!
}
`)

gql`
                                 type Foo {
   bar: String!
}
`

graphql(`
                                 type Foo {
   bar: String!
}
`)
```

**Output:**

```jsx
import { gql } from "graphql-tag";
import { gql as graphql } from "graphql-tag";

gql(`
                                 type Foo {
   bar: String!
}
`);

gql`
  type Foo {
    bar: String!
  }
`;

graphql(`
  type Foo {
    bar: String!
  }
`);

```

**Expected behavior:**

```jsx
import { gql } from "graphql-tag";
import { gql as graphql } from "graphql-tag";

gql(`
  type Foo {
    bar: String!
  }
`);

gql`
  type Foo {
    bar: String!
  }
`;

graphql(`
  type Foo {
    bar: String!
  }
`);
```

`gql` with parentheses should work the same as without parens, and also the same as `graphql` with parens.

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Description

Fixes #14567

## Checklist

- [x] I’ve added tests to confirm my change works.
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
This feature is sealed.

https://github.com/prettier/prettier/pull/5993#issuecomment-660641484

Several similar PRs are rejected/on hold.

**Comment by sosukesuzuki** [comment]
I had forgotten about that option...

**Comment by pvinis** [comment]
it would be great to have that **until** prettier (v3?) or whatever, finally disables these. let us be able to use prettier until functionality changes.

**Review by pvinis — COMMENTED** [review]
nice!

**Pull request closed without merging**
