### PR TITLE
editorconfig: Only search for .editorconfig up to the VCS directory

### PR DESCRIPTION
**Pull request by josephfrazier**
This addresses https://github.com/prettier/prettier/issues/3558

I'm not sure if this is the best way to find the "project root", but it
seems better than before.

### CODE REVIEW

**Comment by rattrayalex** [comment]
Would this impact the behavior of something like 
`./prettier --write '../../some/where/else/**/*.js'`?

What about monorepo/lerna-style projects, which might have something like this: 

```
.editorconfig # establishes baseline
packages/
   foo/
     package.json
     .prettierrc # overrides something specific to foo
   bar/
     package.json
     .prettierrc
```
I actually don't know prettier's current behavior here, or what's desired.

**Comment by azz** [comment]
I think finding the VCS directory might work? 

Something like https://npmjs.com/package/find-project-root? Not sure...

**Comment by josephfrazier** [comment]
Yeah @azz, I think finding the VCS directory would work far better, and handle the cases that @rattrayalex pointed out. One potential issue is that projects that don't use source control wouldn't be able to take advantage of the `.editorconfig` support, but I imagine that use case is vanishingly small, and being able to format files (taking `.editorconfig` into account) outside the current directory is far more important.

**Comment by azz** [comment]
Actually, any way we could add a test for this?

**Comment by rattrayalex** [comment]
Do the docs for `.editorconfig` claim/imply that it must exist at a VCS root? (I also assume that it typically _would_). 

I'm not sure we need a test if we're using a third-party-package that has tests. _looks at npm package_ ah, it doesn't even have a repo listed.

**Comment by azz** [comment]
Here's the tests: https://github.com/kirstein/find-project-root/blob/master/test/index.spec.js

I'd like to have one integration test for this though to document the expected behaviour.

**Comment by josephfrazier** [comment]
I added a quick test in https://github.com/prettier/prettier/pull/3559/commits/d9b2447818965c3b146d52d47c5f0e0ff07bd440.

I also noticed that the `.prettierrc` search also doesn't stop at the VCS directory, currently. We should probably fix that too.

**Comment by josephfrazier** [comment]
Good point @azz, thanks for merging.

**Pull request merged**
