### PR TITLE
Revert "Enforce Single Attribute Per Line (#5501)"

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Reverts prettier/prettier#6644

# I don't disagree to this option. This option will be included in 2.6

I'm going to release 2.5.1 soon. And this option cannot be included in the patch version because it is a new feature.

So reverts #6644 for now.

We will revert this revert when we get closer to the 2.6 release.

/cc @alexander-akait

### CODE REVIEW

**Comment by alexander-akait** [comment]
Yep, let's do it, missed that we are preparing a new release

Another idea - do 2.7 release, there are only one feature

**Comment by sosukesuzuki** [comment]
@alexander-akait 

> Another idea - do 2.7 release, there are only one feature

2.7? Isn't it 2.6?

**Comment by alexander-akait** [comment]
Oh, yes, 2.6 :+1:

**Comment by fisker** [comment]
I don't know these kind of reverts are annoyance, we should figure a better way to do path release.

**Comment by duailibe** [comment]
Isn't it possible to create a branch from the 2.5 tag, and just cherry-pick the relevant commits?

**Comment by sosukesuzuki** [comment]
> Isn't it possible to create a branch from the 2.5 tag, and just cherry-pick the relevant commits?

It is possible, but I didn't like it because it requires more git operations. However, I agree using revert is also annoying, so I think I will use cherry-pick this time.

**Pull request closed without merging**
