### PR TITLE
Normalize SVGs using svgo

### PR DESCRIPTION
**Pull request by lipis**
We can also minify them completely and leave only one script in the `package.json`

### CODE REVIEW

**Comment by suchipi** [comment]
Whoops, I meant to approve that and I accidentally hit merge :x

**Comment by lipis** [comment]
No problem by me :)

**Comment by lipis** [comment]
The question remains if we want to keep it simpler... keep only one of the two scripts..
https://github.com/prettier/prettier/blob/master/website/package.json#L7

**Comment by suchipi** [comment]
I like the SVGs you had in the diff. So we could remove the minify one.

**Comment by lipis** [comment]
#3908

**Pull request merged**
