### PR TITLE
feat: support nested ternary formatting with indent.

### PR DESCRIPTION
**Pull request by a631807682**
- [ ] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by a631807682** [comment]
@evilebottnawi Flatten else-branch for nested ternaries is harder to read for me,  i can't update this package after `v1.14`, i wait a long time but this issue is still open https://github.com/prettier/prettier/issues/5814 . I hope this to be configurable.

**Comment by evilebottnawi** [comment]
Sorry, we don't merge this

**Comment by a631807682** [comment]
@evilebottnawi  Is there a plan to restore the old behavior?

**Comment by evilebottnawi** [comment]
Only improving, maybe we return indent for some cases

**Pull request closed without merging**
