### PR TITLE
Fix comments on class methods with decorators

### LINKED ISSUE #16889: [3.4.0, 3.4.1] Regression on decorators + async + jsdoc
**Prettier 3.4.0 (Also tested on 3.4.1)**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbAngETkgCcBDGCYzAXkwAoZTiBzOGAGkwAdiIu5iMXAGk4uTgBM4aMMQCWXCsQCUNAHyZgAHSiZMkKGggAbOADpjEZnSkz5iymYBupYwFc4ygNw6Avjp0wY1I0NBxcAGFg0M0dPQABPEIScko4zAB6ACoszHTMXIAVAAs4HDZiiAlMW1kFGDlofKz0rIz0kNwoMHCAWQqqugAzCAgkTAAxUc4AIyZxgCEmVW1dPX10E3NLaxGIb3T-KF8QdhA+BvRkUCZeAHcABSYENGQQVzvSXFezmbIwADWbAAyqRsHAADJyKBwZBDVxoOC-f5AmDArikMDQ5jIGDEDxnRHYOS4-FIkBwAAe-Hk4NgrkKAigTDk0jhCPJaGxpgAim4IPBSQSQAArNCU4HcuB8gWwpDw4yIs4AR358AevC4rxQIQAtDC4FIJKcQHjSHJjNiIhBsNhSG9pABWE1cqDMUwAQRgeLkMzc6oEUJh7MV5OKMGwxgA6sU5PA0BiwHBgS843InHHcG8wKETU4PABJKBSWDAuqKD3F4FCUwhpUgHgQRFRshcN48aQCJyws7QxGCDWkZh2uvkjHEftvIT8Oz1E08aEwKNyCQwYrIACMACYAAxnYhwVVyA+D4f2+Ucs6MGbL1frpBbs5uRGFUgzbUK+twbAzQ1GiGkG6bhDnAUzEHa3rYm8pD+hAIC+L4QA)

```sh
--parser typescript
--print-width 120
--single-quote
--trailing-comma es5
```

**Input:**

```tsx
const myDecorator = (target, propertyKey, descriptor) => {
  console.log(descriptor.value);
}

class myClass {
  @myDecorator
  /** 
   * The method description
   *
  */
  async myMethod(foo: Foo, bar: Bar) {
    console.log(foo);
  }
}
```

**Output:**

```tsx
const myDecorator = (target, propertyKey, descriptor) => {
  console.log(descriptor.value);
};

class myClass {
  @myDecorator
  async /**
   * The method description
   *
   */
  myMethod(foo: Foo, bar: Bar) {
    console.log(foo);
  }
}

```

**Expected output:**

```tsx
No change 
```

**Why?**

The `async` keyword gets hoisted above the jsdoc. Even worse, next prettier run adds a `;` after it, breaking the syntax :D

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #16889

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by ClementValot** [comment]
Is it relevant to add other keyword combinations to the methods in the unit tests? 
e.g. public/protected/abstract/async/static

**Review by sosukesuzuki — APPROVED** [review]
Thank you!!

**Comment by ClementValot** [comment]
Would this warrant a quick 3.4.2 release? It's quite the breaking bug

**Comment by fisker** [comment]
https://github.com/prettier/prettier/releases/tag/3.4.2

**Pull request merged**
