### PR TITLE
CI: remove `fetch-depth`

### PR DESCRIPTION
**Pull request by fisker**
Remove `fetch-depth:1` for checkout action, it default to `1`

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
But why?

**Comment by fisker** [comment]
Make these files cleaner

**Comment by thorn0** [comment]
Ah, sorry, I misunderstood what you did.

**Comment by fisker** [comment]
I thought it pull all history before, until I saw other people use `fetch-depth: 0`

**Pull request merged**
