### PR TITLE
Update `yaml` to v1.1

### PR DESCRIPTION
**Pull request by fisker**
https://github.com/prettier/prettier/pull/6224#issuecomment-536538898

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Need update snapshots

**Comment by fisker** [comment]
I don't think the new snap is right

**Comment by evilebottnawi** [comment]
@fisker what is wrong?

**Comment by fisker** [comment]
they are not the same thing

```diff
  # Strip
  # Comments:
  strip: |-
    # text
  
- # Clip
- # comments:
- 
  clip: |
    # text
  
- # Keep
+ # Clip
  # comments:
  
- keep: |+
+ ? # Keep
+   # comments:
+ 
+   keep
+ : |+
    # text
  
  # Trail
  # comments.
```

**Comment by fisker** [comment]
1.1 seems works, other version requires source changes, I will read the changelog later, maybe merge 1.1 first?

**Comment by fisker** [comment]
https://github.com/ikatyang/yaml-unist-parser/pull/123 , maybe @ikatyang can update it

**Comment by evilebottnawi** [comment]
@fisker can you open issue in `yaml-unist-parser`?

**Pull request merged**
