### PR TITLE
Add more tests for chain expressions

### PR DESCRIPTION
**Pull request by syi0808**
## Description
I have handling a few edge cases.
And `IS_PARENTHESIZED` make
`new ((a?.()).b)` to `new (a?.()).b();`
remove top parentheses in a above case. Would this be okay?

## Checklist

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

Ref: https://github.com/prettier/prettier/pull/16500#issuecomment-2253863045

### CODE REVIEW

**Comment by syi0808** [comment]
I will move tests in chain-expression and add changelog after review.

**Comment by fisker** [comment]
> And IS_PARENTHESIZED make

I can accept this as a temporary solution, since I already have a plan to solve these problems.
Please add tests for `MemberExpression` and `CallExpression` too.

**Comment by syi0808** [comment]
> > And IS_PARENTHESIZED make
> 
> I can accept this as a temporary solution, since I already have a plan to solve these problems. Please add tests for `MemberExpression` and `CallExpression` too.

We have already `MemberExpression` and `CallExpression` tests.
https://github.com/prettier/prettier/pull/16534/files#diff-b501e35c9be089b1dcc3c6c05d55ed76e484e7b5951d779b80958888d3cebd33R8-R9
Did you mean to separate this or do you need more cases?

**Comment by fisker** [comment]
Sorry, I wasn't clear.  Let's only add tests in this PR, I'll start fixing these broken cases found. Thank you for your time.

**Pull request merged**
