### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by davidascher**
I believe that the instructions for pre-commit config are off by a character.

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks!

**Comment by okonet** [comment]
That isn't correct BTW. There was no typo there. `pre-commit` needs an npm task to run which is defined here https://github.com/prettier/prettier/pull/891/files#diff-04c6e90faac2675aa89e2176d2eec7d8R142 and it's called `lint:staged`

**Comment by okonet** [comment]
But let me update the doc to use husky since it has a robuster install und uninstall script and requires less config as well.

**Comment by davidascher** [comment]
Ugh, sorry about that @okonet.  I was definitely having problems w/ the script as it was, but I'm happy to blame pilot error.

**Comment by okonet** [comment]
Probably something has changed in pre-commit package but it was working like ↑ before.

**Pull request merged**
