### PR TITLE
[WIP] Test Docusaurus's syntax highlighting

### PR DESCRIPTION
**Pull request by fisker**
Test Docusaurus's syntax highlighting for https://github.com/prettier/prettier/pull/7417#issuecomment-581129734

[one](https://deploy-preview-7527--prettier.netlify.com/blog/2020/00/00/2.0.0.html#generators) , [two](https://deploy-preview-7527--prettier.netlify.com/blog/2020/00/00/2.0.0.html#fix-remove-unnecessary-parens-when-yielding-jsx-7367httpsgithubcomprettierprettierpull7367-by-cola119httpsgithubcomcola119)

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
Please try also updating `prismjs` in `yarn.lock`. See https://github.com/PrismJS/prism/issues/1827

**Comment by fisker** [comment]
@thorn0 On my test `highlighting.js` can't work on `jsx` and `typescript`.

[`usePrism`](https://docusaurus.io/docs/en/site-config#useprism-array) can make them to use Prism syntax highlighter.

`usePrism` can be `array` of `true`(for all).

Another problem `prism` has `ts` alias for `typescript`, but seem `Docusaurus` can only load this language by `typescript`. So we have to replace ```` ```ts ```` to ```` ```typescript ````, also many other languages need full name(if we use `usePrism: true`).

I don't know how to write [`markdownPlugins`](https://docusaurus.io/docs/en/site-config#markdownplugins-array) to replace those `language`. But you can do this in your script, since those `.md` are well formatted by prettier, just replace ```` ```ts ```` with ```` ```typescript ```` should work.

**Comment by fisker** [comment]
I'm not going to make this PR merge, just test for you.

**Comment by thorn0** [comment]
Thanks, I understood all that from your commits. But what about [this comment](https://github.com/prettier/prettier/pull/7527#issuecomment-581359893)?

**Comment by fisker** [comment]
You already update `highlight.js` in your PR, right? Do one more.. :)

**Comment by fisker** [comment]
I missed your link, this problem seems fix already.

**Comment by fisker** [comment]
Can't build ... https://app.netlify.com/sites/prettier/deploys/5e3803bb3c71480008343af1

**Pull request closed without merging**
