### PR TITLE
Test: Use worker to run CLI test

### PR DESCRIPTION
**Pull request by fisker**
## Description

Maybe we can get rid of the default runner to use [`jest-light-runner`](https://github.com/nicolo-ribaudo/jest-light-runner)

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
I'm going to target next branch later.

**Review by sosukesuzuki — COMMENTED** [review]
Great work! Overall looks good.

One question, how can I try to run tests using worker on local?

**Comment by fisker** [comment]
The dev version still broken. 

```sh
yarn build
yarn test:dist
```

**Comment by fisker** [comment]
You can also play on gitpod.io https://gitpod.io/#https://github.com/prettier/prettier/pull/12705

**Comment by fisker** [comment]
> RUNS are shown on the left side still after done.

Didn't notice this, will take a look, I guess caused by jest-light-runner, because format test not running this.

**Comment by fisker** [comment]
`--runInBand` always shows `PASS`.

@nicolo-ribaudo  Maybe you already have a answer? https://github.com/prettier/prettier/pull/12705#issuecomment-1121235989

**Comment by fisker** [comment]
Since the problem in https://github.com/prettier/prettier/pull/12705#issuecomment-1121235989  already exists in the `next` branch, it's not related to this PR, I'm going to merge this now, so I can continue work on the tests.

**Pull request merged**
