### PR TITLE
Print JSON top comments as leading comments of root node

### LINKED ISSUE #3178: JSON comment at the top moved into object
**Prettier 1.8.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACADgQzAaxwHM4A6AKwGdoAdKYOjDdDGACwEtKMuMAzCBEYYaIAUOQiQAIxwAnUXQC+IADQgIWGB2iVkoHJRjI+OADaU466XLz44MAMq4wHKEWQw5AVysgAJhBgJuaW6lQAHgBCtgQOjjgAtnAAMm5wIRZ+EN4wWLkATJlhILhylnLIIFTQaqVybjAA6hz+7MgAHAAM6paJHJ4+fpRuRGZwAIreEPDFfjA40i1tbMgF6l44HGajAMIQiYk4VVDQGerelgAqi3pIpllKSkA)
```sh
--parser json
```

**Input:**
```json
// package.json
{
  // this is foo
  "foo": "bar"
}
```

**Output:**
```json
{
  // package.json
  // this is foo
  "foo": "bar"
}

```

**Expected behavior:**
I expected input to be unchanged.

### PR DESCRIPTION
**Pull request by duailibe**
Fix #3178

### CODE REVIEW

**Comment by SimenB** [comment]
Failed with a snapshot that looks to be correct.

**Comment by duailibe** [comment]
Looks like the snapshots changed orders and generated that huge diff :(

**Comment by SimenB** [comment]
Any chance of a 1.8.2 with this fix, whenever it's ready? If not, I'll go through with `prettier-ignore`s (no huge issue, but I'd prefer not to 🙂 )

**Comment by ikatyang** [comment]
@duailibe 

It seems like an os-specific issue, #3189 should fix it.

**Pull request merged**
