### PR TITLE
Docs build script

### LINKED ISSUE #3306: Consider using Netlify for the website
I don't have much experience with it but I'm aware of a few upsides considering other OSS projects that use (e.g. babel):

- no need to commit artifacts: we have seen several people send PRs that change code in `website/static/lib`. It runs the build step on the server and deploys, automatically on specified hooks (e.g. every commit to master)

- preview PRs: this is the actual a game changer for me. This would allow us to test changes made in PRs in the playground so easily. Babel has this and looks really nice.

There might be other upsides, but these looks pretty relevant to me.

### PR DESCRIPTION
**Pull request by duailibe**
This PR removes the playground artifacts from the repo and extracts the relevant part of the build script to a specific one, so it runs on every deploy. Also included a change in the script to build from the source on PRs, and from `node_modules` on new master commits.

Fixes #3306

### CODE REVIEW

**Comment by duailibe** [comment]
I've just noticed that we don't necessarily update our own prettier dependency on every release. Should we start doing that (and automate it)? Or do you have other suggestions how to fetch prettier from npm on the build script?

**Comment by azz** [comment]
Tried to push a commit here but got permission denied.

Could you add this commit:

```diff
diff --git a/.travis.yml b/.travis.yml
index 54625a78..de266037 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -23,10 +23,3 @@ script:
   - yarn lint-docs
   - AST_COMPARE=1 yarn test -- --runInBand
   - if [ "${NODE_ENV}" = "development" ]; then yarn codecov; fi
-deploy:
-  provider: script
-  script: website/deploy.sh
-  skip_cleanup: true
-  on:
-    branch: master
-    node: stable
diff --git a/package.json b/package.json
index 69ca9cce..2869d4e6 100644
--- a/package.json
+++ b/package.json
@@ -88,6 +88,7 @@
     "lint": "cross-env EFF_NO_LINK_RULES=true eslint . --format node_modules/eslint-friendly-formatter",
     "lint-docs": "prettylint {.,docs,website}/*.md",
     "build": "node ./scripts/build/build.js",
+    "build-docs": "node ./scripts/build/build-docs.js",
     "check-deps": "node ./scripts/check-deps.js"
   }
 }
```

**Comment by duailibe** [comment]
That's weird, the "Allow edits from maintainers." is checked..

Anyway, I've pushed the commit

**Comment by azz** [comment]
```
$ git push
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 393 bytes | 196.00 KiB/s, done.
Total 4 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/duailibe/prettier.git
 ! [remote rejected]   duailibe-netlify -> duailibe-netlify (permission denied)
error: failed to push some refs to 'https://github.com/duailibe/prettier.git'
```

**Comment by duailibe** [comment]
@azz would be nice to have the comment saying the deploy URL so we don't have to keep checking the PR to see if deploy's finished.. I know netlify has support for that automatically and we already have a bot user that could be used for that

wdyt?

**Comment by azz** [comment]
I'd vote no to comments on PRs, they can get a bit noisy.

**Pull request merged**
