### PR TITLE
fix(css): scss interpolation

### PR DESCRIPTION
**Pull request by evilebottnawi**

### CODE REVIEW

**Comment by lydell** [comment]
What does this PR fix?

**Comment by evilebottnawi** [comment]
@lydell 
Before:
```scss
a {
  line-height: #{$var} em;
  line-height: 1 #{$var};
}
```

After:
```scss
a {
  line-height: #{$var}em;
  line-height: 1#{$var};
}
```

**Comment by evilebottnawi** [comment]
@lydell right now don't normalize, i can do this in other PR, right now output as is

**Comment by lydell** [comment]
How does the logic work? `if ("something[nospace]#{" in declarationValue) { printEntireThingAsIs(declarationValue) }`?

**Comment by evilebottnawi** [comment]
@lydell add tests. What tests is still worth adding?

**Comment by lydell** [comment]
I see. Personally, I think it's fine to add tests that print badly right now. It's nice when you can see in PRs how the snapshots changed for the better. But if you want to do it in another PR I guess that's fine too.

**Comment by evilebottnawi** [comment]
@lydell let's add more tests :+1:

**Pull request merged**
