### PR TITLE
WIP: Update to new cosmiconfig API

### PR DESCRIPTION
**Pull request by olsonpm**
**This PR is awaiting davidtheclark/cosmiconfig#108**

---

- differentiate `load` from `search` (previously `load` was overloaded
  to both load a configuration file directly and search up the
  directory tree)

### CODE REVIEW

**Comment by sudo-suhas** [comment]
It is worth noting that this would pull in the changes for `cosmiconfig` from `v3 -> v4` documented here - [davidtheclark/cosmiconfig:CHANGELOG.md@`master`#400](https://github.com/davidtheclark/cosmiconfig/blob/master/CHANGELOG.md#400).

**Comment by olsonpm** [comment]
Though the tests did pass, I will confirm the other major changes are compatible with prettier tomorrow.  I admittedly overlooked them because I thought that PR was triggering the major bump.  Thanks for the note

**Comment by j-f1** [comment]
@olsonpm Any update on this?

**Comment by olsonpm** [comment]
sorry - I didn't realize davidtheclark had a bunch of other things he wanted to get done for v5 which was released just recently, and right now isn't a good time for me to pick this back up.  I expect to have more time in a couple weeks so I'll pick this back up when I do.

**Pull request closed without merging**
