### PR TITLE
add an example .prettierrc.js config

### PR DESCRIPTION
**Pull request by joshunger**
I thought a JS example would help too especially since comments are then valid.

### CODE REVIEW

**Comment by azz** [comment]
Would you be able to put it below the JSON version?

FYI:

```bash
$ yarn lint-docs
  docs/configuration.md:22:2
  ⚠  22:2  Replace "printWidth" with printWidth  prettier/prettier
  ⚠  23:2  Replace "parser" with parser          prettier/prettier
  ⚠  24:1  Insert ;                              prettier/prettier
```

**Comment by joshunger** [comment]
@azz fixed and thanks for the `lint-docs` issues

**Comment by azz** [comment]
I wonder if we should be recommending `.prettierrc.js` or `prettier.config.js`. The latter seems to be more common, but eslint uses the former.

**Comment by hawkrives** [comment]
My 2¢: `.prettierrc.js`

**Comment by joshunger** [comment]
I came to the same conclusion that it should be `.prettierrc.js` because eslint uses `.eslintrc.js`.  Why do they both exist?

**Comment by hawkrives** [comment]
@joshunger I believe it's because `cosmiconfig` (which I believe is still used for the config files) is not opinionated about where to store config options; they probably support "tool.config.js" and "toolrc.js" for the same reason that it handles .js, .json, and .yaml config files (and the package.json key too) – so that pretty much any tool can use cosmiconfig easily.

**Comment by joshunger** [comment]
Do you want me to do something different?  I could put `.prettierrc.js or prettier.config.js` in the comment as one option.

**Comment by azz** [comment]
That's fine, we already mention the alternative just above. Thanks.

**Pull request merged**
