### PR TITLE
Update babylon to 7.0.0-beta.4

### LINKED ISSUE #700: "export default async function" wraps function in parenthesis
`"export default async function"` adds an unnecessary parenthesis around the entire function:

```
export default async function foo() {
  console.log('Hello, World');
}
```

turns into:

```
export default (async function foo() {
  console.log("Hello, World!");
});
```

If I remove either the `"default"` or `"async"` modifiers, this issue is no longer triggered.

### PR DESCRIPTION
**Pull request by vjeux**
Fixes #700

### CODE REVIEW

**Comment by jlongster** [comment]
Awesome!

**Comment by SimenB** [comment]
@vjeux Would it be possible to remove the parens if they are present? After upgrading from a version of prettier which added the parens, the newer version doesn't remove them

**Comment by vjeux** [comment]
@SimenB unfortunately not. They have a different meaning with and without. I'm afraid that you're going to have to do it by hand :(

**Comment by SimenB** [comment]
Woah, you're crazy fast responding 😀 

That's fine, it only happened in a single function, easy enough to remove manually 😄

**Pull request merged**
