### PR TITLE
Add `acorn` parser

### PR DESCRIPTION
**Pull request by fisker**
## Description

`espree` is build on top of `acorn` parser, support `acorn` is very easy, this may also be needed for #12144, [comment](https://github.com/prettier/prettier/issues/12144#issuecomment-1021231222)

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
Adding a parser will make the user's `node_modules` larger.
Also I don't know why this is needed for #12172. Wouldn't they use Acorn that in a special location as a custom parser?

**Comment by fisker** [comment]
> Adding a parser will make the user's node_modules larger.

No, `acorn` is dependency of `espree`.

> Also I don't know why this is needed for #12172.

We need test for that.

**Comment by sosukesuzuki** [comment]
> No, acorn is dependency of espree, this is why we bundle them together.

Ah okay, I thought `acorn` and `espree` are bundled to different files.

> We need test for that.

I got it.

**Review by sosukesuzuki — APPROVED** [review]

**Comment by fisker** [comment]
Add this to changelog?

````
The `espree` parse location has been changed,

```diff
- const parserEspree = require('prettier/parser-espree.js');
+ const parserAcornAndEspree = require('prettier/parser-acorn-and-espree.js');
```
````

**Comment by sosukesuzuki** [comment]
> Add this to changelog?

Yes. I also realized that this is a breaking change. We shouldn't do it at minor version according to semver.
So can we make `parser-espree.js` refers to `parser-acorn-and-espree.js`?  And we should remove `parser-espree.js` at v3.

**Comment by fisker** [comment]
https://github.com/prettier/prettier/pull/12172/commits/4056b43e7c62c7f5f1998b220080b7831e6da18a

**Comment by fisker** [comment]
You may interest, the whole file size incread 1kb,

**Pull request merged**
