### PR TITLE
Add `--keep-indentation` option

### PR DESCRIPTION
**Pull request by josephfrazier**
When this option is enabled, prettier will get the indentation of the
first line, determine its width (taking `tabWidth` into account),
subtract that width from `printWidth`, format the input with the new
`printWidth`, then add the first line's indentation back to every line.

Fixes https://github.com/prettier/prettier/issues/1324

### CODE REVIEW

**Comment by vjeux** [comment]
Thanks for making a pull request for this but I don't think that this should be part of prettier core. The use case for this is to format JavaScript code embedded inside of some other context. So the call site knows the indentation of the `<script>` tag and should indent the resulting code accordingly.

**Comment by josephfrazier** [comment]
Hmm, this wasn't really intended to address https://github.com/prettier/prettier/issues/1567 so much as https://github.com/prettier/prettier/issues/1324 (the more general case, without `<script>` tags). Did you change your mind from earlier at https://github.com/prettier/prettier/issues/1324#issuecomment-294878202?

> Yeah, this is something we should implement at some point. I honestly thought that it would have been needed for adoption but it turns out that people are going all in and not only converting entire files but also entire projects using it. This is a better outcome as it makes prettier a lot more valuable. But we still should support reformatting a range.

**Comment by vjeux** [comment]
What I meant by that is having the ability to pass prettier a range (or even a cursor position) within the file and reformat it. We want it to be smart enough to find the nearest Statement and only reformat this statement and have the correct indentation.

**Comment by josephfrazier** [comment]
Ohhh, I see now. Do you not think this is nevertheless useful as-is? I've already found it handy while working on prettier itself, to be able to make sure that my changes are prettier-formatted, without having to format the entire file (which currently causes large diffs).

**Comment by vjeux** [comment]
I do think that it is useful and want to support it, but it should be done correctly, just adding a flag `--keep-indentation` is not the right API. We should add a way to pass a range within that file and tweak prettier to reprint only this part of the ast.

**Comment by josephfrazier** [comment]
That's fair :) I'm a bit biased towards my approach here, as it's easier to integrate with my editor (Vim). However, if a more robust solution is implemented, I imagine [Neoformat](https://github.com/sbdchd/neoformat) will be able to incorporate it.

**Comment by vjeux** [comment]
I'm not familiar with neoformat, what is the API that it expects for formatting a piece of code?

**Comment by vjeux** [comment]
This is the API I had in mind:
https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_rangeFormatting

**Comment by josephfrazier** [comment]
[Neoformat uses the command-line interface](https://github.com/sbdchd/neoformat/blob/9f8dd25ad9fc30332c91b15257729000156dbed2/autoload/neoformat/formatters/javascript.vim#L39-L45) `prettier --stdin`, and pipes in [the currently selected text, or the entire file if there is no selection](https://github.com/sbdchd/neoformat/blob/bc4d29f9b7fafd35647b574fc4592764a2e3d6c9/doc/neoformat.txt#L38). So, I'm hoping that the eventual implementation of range formatting will be available to the CLI (presumably, Neoformat would be extended to find and pass in the current range).

**Comment by vjeux** [comment]
So, every single code formatter supports a --keep-indentation option? That doesn't seem right.

**Comment by josephfrazier** [comment]
I don't understand what you're saying here. Can you clarify?

**Comment by lydell** [comment]
Note that it is not safe for a text editor plugin to simply add a bunch of spaces at the beginning of each line because of multiline strings and template literals.

**Comment by josephfrazier** [comment]
That's a great point. Yeah... this feature as it's currently implemented here would definitely mangle multiline literals :( I hadn't considered that until you mentioned it, but I agree that it shouldn't be merged as-is.

**Pull request closed without merging**
