### PR TITLE
Remove typescript-etw from build

### LINKED ISSUE #6903: TypeScript browser bundle has webpack warning
**Environments:**
- Prettier Version: 1.19.0 and 1.19.1
- Running Prettier via: Browser API
- Runtime: webpack 4.41.2
- Operating System: macOS

**Steps to reproduce:**

```js
import "prettier/parser-typescript";
```

**Expected behavior:**
Bundle continues to compile without warnings.

**Actual behavior:**
```
WARNING in ./node_modules/prettier/parser-typescript.js
Module not found: Error: Can't resolve '@microsoft/typescript-etw' in '/Users/nick/Repos/prettier-chrome-extension/node_modules/prettier'
 @ ./node_modules/prettier/parser-typescript.js
 @ ./src/content/parsers.js
 @ ./src/content/github.js
 @ ./src/content/extension.js
 @ ./src/content/index.js
```
Oddly enough, the parser continues to work properly. However the error is confusing and may cause potential issues as `typescript-etw` only supports running on Windows natively, and this version of the parser only supports running in web browsers.

### PR DESCRIPTION
**Pull request by nickmccurdy**
Fixes #6903 (tested with `yarn link` and webpack)

Thanks to @j-f1 for figuring out the fix

- [ ] I’ve added tests to confirm my change works. (N/A)
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory) (N/A)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`. (N/A)
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
@nickmccurdy since `prettier-chrome-extension` are bundling `prettier`, could you add some tests for this and #6658 , so we can prevent this happen again?

**Comment by nickmccurdy** [comment]
What should the test do, just import everything and assert there are no warnings?

**Comment by fisker** [comment]
maybe something like this

```js
webpack({
  entry: './parser-typescript.js', 
  mode: 'production'
}, (error, stats) => {
 // check error and stats
})
```

**Comment by nickmccurdy** [comment]
Thanks. I understand your test example, but where should I put this test? Test files? Integration test files (don't seem to run in CI)? After `test:dir`? Another script?

**Pull request merged**
