### PR TITLE
Add more number formatting

### PR DESCRIPTION
**Pull request by lydell**
- Remove trailing decimal zeroes. For example, `1.0` → `1`.
- Remove scientific notation form zero. For example, `0e6` → `0`.

What do you think?

### CODE REVIEW

**Comment by CiGit** [comment]
Isn't that the scope of a minifier?
I think this may break format on type features. I'm not aware of any implementation of this feature yet but this has come up in prettier-vscode repo.
It may also be the combination of format on save with save on blur (or any save after/on <Event>)
## Use Case
- User wants to insert `1.04`
- User inserts `1.0`, can't remember the last decimal
- User checks an other document / whatever for the exact value
- User insert `4` (expects `1.04`, gets `14`)

It may also be useful to explicit precision (physics).

**Comment by lydell** [comment]
> Isn't that the scope of a minifier?

Nope, we already do similar things.

> Use Case

We already remove trailing dots, so that can already happen ("User inserts `1.`, can't remember first decimal"). Also, I think this is a more likely scenario:

1. User wants to insert `1.04`.
2. User inserts `1.0`, but can't remember the last decimal.
3. User checks somewhere for the exact value.
4. User comes back and sees that their auto-format feature in their editor has kicked in and thinks "Oh, looks like that `.0` was automatically removed, neat" and  inserts `.04`.

Or, even more likely: The user _copies_ the exact value from somewhere and _pastes_ that into the code.

I don't think this is an issue at all.

> It may also be useful to explicit precision (physics).

I also though about physics, where `1000` doesn't tell you the precision while `1.000×10³` does. However, in JavaScript writing `1.000e3` gains you nothing; it's just as precise as `1e3`. You'd be better off with a comment explaining how precision is important here, or a `const PRECISION = 4;` somewhere and use that variable where appropriate.

---

I've seen people coming from other programming languages write `x / 2.0` in JavaScript, because they're used to having to "force floats" by adding `.0` when dividing and suchlike. `x / 2` is much nicer.

**Comment by CiGit** [comment]
> We already remove trailing dots

Didn't know that. It therefor make sens to also remove trailing 0.

> User comes back and sees that their auto-format feature in their editor has kicked in 

In the case you read your input again. And even harder to notice if it removed the trailing dot only. `1. -> 1` 
Case quickly fix my value (`|` representing the cursor):
- Here is my number `1.06`
- Remove decimals `1.|`
- Alt-tab
- Check decimal
- Don't copy/paste (you mostly have to use your mouse and its faster to enter 2 numbers you can remember for the next 5 seconds)
- Alt-tab
- `1|` Enter `04`
- Save/Close
- Done

I'll agree with you that you have to check your code ;-)

For precision I was mostly thinking about *documentation* precision, not *runtime* precision.
Other example, money: `0.10 + 0.20` ( 😕 float... I'm not talking about validity of such math)

**Comment by vjeux** [comment]
For the scientific notation, it's so rarely used that I don't care, feel free to do it.

For the trailing 0s, we have ~800 files that have trailing zeros. Most of them seem to be written by people from a C background where trailing `.0` is being used to show that the variable is a float instead of being an integer.

I'm a bit uneasy about removing it. Even though it doesn't do anything in practice, having a trailing 0 to signify a float can be useful.

What do you think?

**Comment by lydell** [comment]
I don't care that much either way. I just found an opportunity to normalize some more code style that was easy to implement :) So I can modify the PR if you want. Alternatively we could special case `x.0`: `2.50`→`2.5`, `2.00`→`2.0`, `2.0`→`2.0`, `2`→`2`. But I would really like to hear how `.0` to signify a float can be useful! I'm not convinced :)

**Comment by vjeux** [comment]
If you want to get rid of more than one trailing 0, I'm happy to. I only found a handful of calls like this on the fb codebase.

My fear is more that it's going to be controversial. Now, whenever I'm doing a prettier update inside of fb, people look at the changes and they are powerless if there's something that we changed that they don't like. Which is a bad feeling.

I don't really know how people feel attached to this, so I'd rather be on the cautious side for now if that makes sense.

**Comment by lydell** [comment]
I see what you mean. My opinion is that pretending that JavaScript has ints and floats is silly. I guess we'll leave this for now until we decide whether to merge, update or just close?

**Comment by vjeux** [comment]
Can you open an issue that references this PR so that we can track it, and let's close this PR for now?

**Pull request closed without merging**
