### PR TITLE
Update copyright line

### PR DESCRIPTION
**Pull request by j-f1**
Since @jlongster isn’t as involved in the project and it’s now more of a community project, I’ve updated the license file to reflect these changes. I requested @jlongster’s review because I think he needs to approve this kind of license change.

- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by kachkaev** [comment]
Is the current year necessary?

facebook/react folks were using `yyyy-present`, but recently dropped the year completely:
https://github.com/facebook/react/commit/b87aabdfe1b7461e7331abb3601d9e6bb27544bc

**Comment by j-f1** [comment]
Note to self: update https://github.com/freeCodeCamp/devdocs/pull/936 when merged.

**Comment by suchipi** [comment]
Woah, I didn't know about devdocs, that's cool

**Comment by lipis** [comment]
Hey @jlongster, have you seen this?

**Comment by j-f1** [comment]
Awesome, thanks @jlongster!

**Pull request merged**
