### PR TITLE
[WIP]Support `typescript` 3.7

### PR DESCRIPTION
**Pull request by fisker**
- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by merlinnot** [comment]
People really want to get their hands on 3.7, I can agree that TypeScript team shipped life-changing functionalities.

Thanks for working on adding support for it to Prettier!

**Comment by kachkaev** [comment]
@fisker it'd be cool if you added tests, that confirm that TS 3.7 syntax works in Prettier.

**Comment by fisker** [comment]
@kachkaev sure

**Comment by IljaDaderko** [comment]
Started playing with ts 3.7 in my project today and glad to see there is a prettier pr already. Will there be an alpha / beta release to try it out before 3.7 gets released by any chance?

**Comment by Cryrivers** [comment]
fyi #6657 has already addressed TypeScript 3.7

**Comment by fisker** [comment]
closing in favor of #6657

**Pull request closed without merging**
