### PR TITLE
Preserve comment position before super class

### PR DESCRIPTION
**Pull request by duailibe**
## Description

Related to #12220

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
`Bar` is enclosed by multiple parens.

**Prettier pr-12222**
[Playground link](https://deploy-preview-12222--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ5wAe8UAJrgPQBUtOAAjAJ4AOcOwmMATgJZQA5gF8ctajgAUAIXS8AlFxEAdKCAA0ICGxj9omZKHm8IAdwAK8hIZTpUZ9C0NaARr3RgA1nBgBldABbOAAZQThkADN7TDg3D29fPzZPQSFkPgBXOJA4QNc4CgpCkPRhTPQhOAJeQPQYPWFkEHRMmAhNEAALGEDUAHUu-nhMFLA4Pxth-gA3YZZmsGxOwVjeGAsPITqomJyAK0wSPzTUOABFTIh4XdRYrRTeNebXdALUTrYBWH7+ChgusgABwABgepli-Q8bGaXzgaxmES0AEcrvBNjpbC1MABaKBwQqFTq8OCo-gkzaVHZIaJ3HKxQL8DK8bJaTCnC5oiI0vZaGBvX7-QFIABMfI8-FQaQAwhBAtTcpgAKydTKxAAqb1stPuIBm2QAkpQEP4wAJdABBSh+VhnW6xEQiIA)

```sh
--parser babel
```

**Input:**

```jsx
class Foo extends /** @type {string} */ (Bar) {}

```

**Output:**

```jsx
class Foo extends /** @type {string} */ ((Bar)) {}

```

**Review by sosukesuzuki — COMMENTED** [review]
Can you add changelog?

**Comment by duailibe** [comment]
> Bar is enclosed by multiple parens

Yes, this isn't fixed in this PR.. that's why I didn't mark the issue to be closed. Wanted to keep things separate, as they're not exactly related.

Sorry about the changelog

**Comment by sosukesuzuki** [comment]
> Yes, this isn't fixed in this PR.. that's why I didn't mark the issue to be closed. Wanted to keep things separate, as they're not exactly related.

Okay, I got it. thanks

**Review by fisker — APPROVED** [review]

**Pull request merged**
