### PR TITLE
SCSS: Fix maps with keys that are lists or maps

### LINKED ISSUE #10000: SCSS parser breaks if maps have keys that are lists or maps.
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAtgQwA5IAQAUAOlETAQOToCeeANgJYDOMFAlPhQBZx10R4A7hABOdACYUANCTYBuEiCkgI2GA2hNkoTCJERBABV0ItKTHUGZqW5QCMRmMAGs4MAMrYnDKAHNkMCIArnDKcOh2cOLiUQAymH5BmL5wAGKiWDDqfsggmEEwEEogXDDodADqXAzwTF5gcO6mNQwAbjXUuWBMtiA+THAiMIaOvljIAGYWA8oAVkwAHgBCji5u7pjocLE+cJPToSDzC+4+vnRwAIpBEPD7dDMgXiIDIrlM3b3YIj4wFQziGBcZAADgADMpvhABhVHNhct84K9WntlABHG7wEaqMx5JgAWigcCiUWKIjgGIY5JGyXGSCmD0OA3QDACwSZZwu11ue3pB2UMEwdn+gOBSAATALHAxGH4AMIQdB0kBIgCsxSCAwAKkKzAzHq0QgBJKAxWDuMA-NQAQVN7hg1Au9wGAF8XUA)
```sh
--parser scss
```

**Input:**
```scss
$map: (
	('my list'): 'hello world',
);

```

**Output:**
```scss
print@https://prettier.io/lib/standalone.js:15:312563
_a@https://prettier.io/lib/standalone.js:15:114909
e/s<@https://prettier.io/lib/standalone.js:15:114372
printComments@https://prettier.io/lib/standalone.js:15:110812
e@https://prettier.io/lib/standalone.js:15:114350
map/<@https://prettier.io/lib/standalone.js:15:112965
each@https://prettier.io/lib/standalone.js:15:112878
map@https://prettier.io/lib/standalone.js:15:112946
print@https://prettier.io/lib/standalone.js:15:309448
_a@https://prettier.io/lib/standalone.js:15:114909
e/s<@https://prettier.io/lib/standalone.js:15:114372
printComments@https://prettier.io/lib/standalone.js:15:110812
e@https://prettier.io/lib/standalone.js:15:114350
print/<@https://prettier.io/lib/standalone.js:15:311852
map/<@https://prettier.io/lib/standalone.js:15:112965
each@https://prettier.io/lib/standalone.js:15:112878
map@https://prettier.io/lib/standalone.js:15:112946
print@https://prettier.io/lib/standalone.js:15:311819
_a@https://prettier.io/lib/standalone.js:15:114909
e/s<@https://prettier.io/lib/standalone.js:15:114372
printComments@https://prettier.io/lib/standalone.js:15:110812
e@https://prettier.io/lib/standalone.js:15:114350
call@https://prettier.io/lib/standalone.js:15:112604
print@https://prettier.io/lib/standalone.js:15:309182
_a@https://prettier.io/lib/standalone.js:15:114909
e/s<@https://prettier.io/lib/standalone.js:15:114372
printComments@https://prettier.io/lib/standalone.js:15:110812
e@https://prettier.io/lib/standalone.js:15:114350
call@https://prettier.io/lib/standalone.js:15:112604
print@https://prettier.io/lib/standalone.js:15:309182
_a@https://prettier.io/lib/standalone.js:15:114909
e/s<@https://prettier.io/lib/standalone.js:15:114372
printComments@https://prettier.io/lib/standalone.js:15:110812
e@https://prettier.io/lib/standalone.js:15:114350
call@https://prettier.io/lib/standalone.js:15:112604
print@https://prettier.io/lib/standalone.js:15:304743
_a@https://prettier.io/lib/standalone.js:15:114909
e/s<@https://prettier.io/lib/standalone.js:15:114372
printComments@https://prettier.io/lib/standalone.js:15:110812
e@https://prettier.io/lib/standalone.js:15:114350
call@https://prettier.io/lib/standalone.js:15:112604
$v/<@https://prettier.io/lib/standalone.js:15:303117
each@https://prettier.io/lib/standalone.js:15:112878
$v@https://prettier.io/lib/standalone.js:15:302940
print@https://prettier.io/lib/standalone.js:15:304189
_a@https://prettier.io/lib/standalone.js:15:114909
e/s<@https://prettier.io/lib/standalone.js:15:114372
printComments@https://prettier.io/lib/standalone.js:15:110812
e@https://prettier.io/lib/standalone.js:15:114350
ja@https://prettier.io/lib/standalone.js:15:114417
ts@https://prettier.io/lib/standalone.js:15:117522
us@https://prettier.io/lib/standalone.js:15:119853
eN/<@https://prettier.io/lib/standalone.js:55:37266
format@https://prettier.io/lib/standalone.js:55:37351
formatCode@https://prettier.io/worker.js:124:21
handleMessage@https://prettier.io/worker.js:75:18
self.onmessage@https://prettier.io/worker.js:36:14

```

**Expected behavior:**

Lists (and maps) are valid keys for Sass maps. This seems to have broken in v2.1.0 (it works in v2.0.5).

### PR DESCRIPTION
**Pull request by fisker**
## Description

Fixes #10000

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — APPROVED** [review]

**Comment by fisker** [comment]
It seems not right, when key and value both map

**Prettier pr-10005**
[Playground link](https://deploy-preview-10005--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEASAtgQwA5IAQAUAOlHoQOQDWcAnufuQG6YA2ArnOQDR5W329m7Tlz50GQjtzECmrKaOrjB8kQEp8JIjAIyJq7mq4kyupbMkje5-cOk2Vdxf1sK9jhRrxaYARmNQagDcIFwgENgwAJbQAM7IoJgATkkQAO4ACskI8SisaZg08WEARkmYYNQwAMrYFVFQAObIMEkcYXDoJXAAJj29ADKYTWyYjXAAYhBJWDDRTcggmGwwEKEgABYw6CwA6htR8LF1YHDVOYdRjIc0i2CxxSANsXBJMBnljVjIAGasL2EAFaxAAeACFypU4DVMOg4AMGnBfv84EDQdUGo0WHAAIpsCDwZEsAEgOpJF5JRaxe6PbBJBowXZRHowDbIAAcAAYwnSIC9duVsIs6XAKYwkWEAI74+AfCK5JaxAC0UDgvV66yScGlUS1HzG3yQf2JqJAL3QURabVNsUx2LxBKRRpRYRgmBKTJZbKQACZXeUoixMQBhCDoQ0gUUAVnWbBeABV3bljSTGBwAJJQfqwapgemRACCWeqMBo2KJLwAvpWgA)
```sh
--parser scss
```

**Input:**
```scss
$map: (
  ('key': 'value', 'key': 'value','key': 'value','key': 'value','key': 'value',): 
	('key': 'value',),
  ('key': 'value', 'key': 'value','key': 'value','key': 'value','key': 'value',): 
	1,
);
```

**Output:**
```scss
$map: (
  (
  "key": "value",
  "key": "value",
  "key": "value",
  "key": "value",
  "key": "value",
): (
    "key": "value",
  ),
  (
    "key": "value",
    "key": "value",
    "key": "value",
    "key": "value",
    "key": "value",
  ):
    1,
);

```

**Review by thorn0 — APPROVED** [review]
@fisker Let's merge unless you want to fix that case in this PR:

> It seems not right, when key and value both map/list

**Comment by fisker** [comment]
I'll take a quick look now, see if it's easy to fix.

**Comment by fisker** [comment]
I don't really understand what I did, but seems much better https://github.com/prettier/prettier/pull/10005/commits/a4ec8b713c25067ea03143224dbad7c9c8062619

**Pull request merged**
