### PR TITLE
Build: Switch to `esbuild` (backport #12052 and #10006)

### PR DESCRIPTION
**Pull request by fisker**
## Description

Due to https://github.com/evanw/esbuild/issues/1902, I can't make `babel` and `text-replace` plugin work togethor, I've split the build to 3 steps, `esbuild -> babel transform -> esbuild`, so this won't as fast as #12052, but still ~4x faster [85.52s](https://github.com/prettier/prettier/runs/4758415757?check_suite_focus=true#step:5:24) vs [365.34s](https://github.com/prettier/prettier/runs/4758415757?check_suite_focus=true#step:7:93)

**Size Change:** -1.11 MB (-9%) ✅

**Total Size:** 10.8 MB

| Filename | Size | Change |  |
| :--- | :---: | :---: | :---: |
| `dist/bin-prettier.js` | 463 kB | -62.2 kB (-12%) | 👏 |
| `dist/doc.js` | 176 kB | +8.51 kB (+5%) | 🔍 |
| `dist/index.js` | 1.52 MB | -210 kB (-12%) | 👏 |
| `dist/parser-angular.js` | 115 kB | +6.41 kB (+6%) | 🔍 |
| `dist/parser-babel.js` | 393 kB | +6.95 kB (+2%) |  |
| `dist/parser-espree.js` | 255 kB | +8.87 kB (+4%) |  |
| `dist/parser-flow.js` | 2.13 MB | -1.11 MB (-34%) | 🎉 |
| `dist/parser-glimmer.js` | 209 kB | +12.4 kB (+6%) | 🔍 |
| `dist/parser-graphql.js` | 57.3 kB | +16.2 kB (+39%) | 🚨 |
| `dist/parser-html.js` | 183 kB | +4.07 kB (+2%) |  |
| `dist/parser-markdown.js` | 177 kB | -4.01 kB (-2%) |  |
| `dist/parser-meriyah.js` | 258 kB | +8.13 kB (+3%) |  |
| `dist/parser-postcss.js` | 241 kB | +20.6 kB (+9%) | 🔍 |
| `dist/parser-typescript.js` | 3.63 MB | +169 kB (+5%) | 🔍 |
| `dist/parser-yaml.js` | 146 kB | -10.6 kB (-7%) | ✅ |
| `dist/standalone.js` | 567 kB | +24.3 kB (+4%) |  |
| `dist/third-party.js` | 325 kB | -609 B (0%) |  |

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
Good Work!!

I have a question. Why we need using Babel? Transpiling by esbuild is not enough for `main` branch source code?

**Comment by fisker** [comment]
esbuild only do syntax transform, not polyfill `globalThis` and `Array#flatMap()` and `Object.fromEntries()` for Node.js 10. I also tried to include these polyfills myself, but still broken, maybe because https://github.com/prettier/prettier/issues/12054#issuecomment-1008077129, we can try to improve later.

**Comment by sosukesuzuki** [comment]
Thank you. I got it. Btw, I also concern `dist/parser-graphql.js` has became bigger(+16.2 kB (+39%)).

**Comment by fisker** [comment]
Tried & failed... I don't think "+16.2 kB" is a big deal. Let's merge?

**Comment by sosukesuzuki** [comment]
Thank you for your trying! I'm fine with merging this. I don't think many users are interested in the file size of `dist/parser-graphql.js`.

**Review by sosukesuzuki — APPROVED** [review]

**Comment by RDIL** [comment]
> esbuild only do syntax transform, not polyfill `globalThis` and `Array#flatMap()` and `Object.fromEntries()` for Node.js 10. I also tried to include these polyfills myself, but still broken, maybe because [#12054 (comment)](https://github.com/prettier/prettier/issues/12054#issuecomment-1008077129), we can try to improve later.

@fisker why support Node 10 still?  It has reached end-of-life.

**Comment by fisker** [comment]
https://github.com/prettier/prettier/issues/10157

**Pull request merged**
