### PR TITLE
JavaScript: Fix bug when arrow fn as function parameter with newline

### LINKED ISSUE #6294: Arrow fn as function parameter with newline
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKBDAFF4GA066ARgL4CUABALwB8lwF6I+IEADjAJbQDOyoDACchEAO4AFYQn4oMANwhcAJixDEhGMAGs4MAMrstXKAHNkMIQFc4rABYwAtgBsA6na7xeRsHH0zPLnlPAE9kcF5+VhNeOCEYCU1TRwxkADMMZ1jWACteAA8AIU0dPX0MRzgAGRM4dMzskDz8-RNTZzgARSsIeHqs2xAjIVihcOIMYhDnaDV2IRMYVxUYO2QADgAGVnmIWNdNdnD5uFH5OtYARx74RI5ZEAxeAFooODhlD7UhOGuuH8SGGSqSQGQGrFiji4Fmsg14bQ63V6dVBDUGMEmy2Uq2QACZWJYMFxnG0AMIQRwpcJQaAXEBWWIAFUmsjBsVIpCAA)
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx

a(({a,

b}) => {})

```

**Output:**
```jsx
a(({ a,
  b }) => {});
```

**Expected behavior:**

```jsx
a(({ a, b }) => {});
```

or

```jsx
const a = ({
  a,

  b
}) => {};
```

### PR DESCRIPTION
**Pull request by sosukesuzuki**
Fix #6294

```js
// Input
foo(
  ({
    a,

    b
  }) => {}
);

// Output (Prettier stable)
foo(({ a,
  b }) => {});

// Output (Prettier master)
foo(
  ({
    a,

    b
  }) => {}
);
```

- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by sosukesuzuki** [comment]
@evilebottnawi I resolved conflicts.

**Comment by thorn0** [comment]
Still happens if the pattern is nested:
**Prettier pr-6301**
[Playground link](https://deploy-preview-6301--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEB6VACAklADgVxgB0oAzCCAChIw0uAEMlgbaMGAaE12gI1YC+AgJQYAvAD4MwASWEBuEiA4gIuGAEtoAZ2SgGAJwMQA7gAVDCXSgYA3CBoAmykLwMMwAazgwAyrg8NKABzZBgDfDgVAAsYAFsAGwB1aI14bQCwOF8rNI1bNIBPZHBtXRUg7TgDGDN3YLiGZFIGBKqVACttAA8AIXcvH18GOLgAGSC4Ztb2kC7u3yDghLgARXwIeGm2qJAAgyqDEt4GXkKE6BdcAyCYJKcYaOQADgAGFWuIKqT3XBLruCHWxTFQARw28DqamsIAY2gAtFA4HBHCiXAY4OCNBi6gwGk0kC0dioqnENGEIrttEsVutNlNCTNdjBTvdHI9kAAmFThBgaBJLADCEDijRKUGgIJA+CqABVTtYibNbJEcKjYL4wDd1ABBKCOXwwc4MpVwIRAA)
```sh
--parser babylon
```

**Input:**
```jsx
// Input
foo(
  ({a:{
    a,

    b
  }}) => {}
);

```

**Output:**
```jsx
// Input
foo(({ a: { a,
    b } }) => {});

```

**Pull request merged**
