### PR TITLE
Expose different doc objects

### PR DESCRIPTION
**Pull request by fisker**
## Description

Expose different doc objects for public APIs, so we can get ride of `concat` for internal use.

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by thorn0** [comment]
Looks like an unneeded indirection to me. We'll get rid of `concat` anyway, just not today. Is it causing any trouble now?

**Comment by fisker** [comment]
The doc utils should not exported directly, like https://github.com/prettier/prettier/blob/main/src/common/util-shared.js vs https://github.com/prettier/prettier/blob/main/src/common/util.js

**Comment by thorn0** [comment]
What's public and what's not is a matter of documentation. Let's keep things simple.

**Comment by fisker** [comment]
> What's public and what's not is a matter of documentation. 

I don't think documentation is the only thing, private function can do breaking change when needed, while public things should take compatibility into consideration.

**Comment by fisker** [comment]
Outdated.

**Pull request closed without merging**
