### PR TITLE
Update `html-element-attributes` to v2.2.0

### PR DESCRIPTION
**Pull request by fisker**
Actual change is add attribute `autofocus`

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
> Actual change is add attribute autofocus

Feature

**Comment by fisker** [comment]
Should add changelog ?

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AICCAqgCoDyAYqQMKEDKuAfKgPRbYMgA0IEADjJmgBnZKACGAJwkQA7gAVJCESjHYImdFxAAjCWLABrODFq99mKAHNkMCQFc43ABYwAtgBsA6k8zwhZsDhaJV8cXwBPZHAhEW4LITgJGDk9S1cxZAAzMXcE7gArIQAPACE9Q2NaMVc4ABkLOCycvJBCotoLS3c4AEU7CHgm3McQMwkEiSiXDy1eCQsYTw0YJ2QADgAGbjmIBM89Xii5uAnsRu4AR374FL5lEDEhAFooODh0d60JOCvMb5SxGkMkhssNuAlXJgbPYRkJOt0+gNGiDmiMYGJtEt0CtkAAmbi2MSYdydKgQVzpKJQaDnEB2BLEDHKUEJAC+rKAA

https://deploy-preview-6739--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AICCAqgCoDyAYqQMKEDKuAfKgPRbYMgA0IEADjJmgBnZKACGAJwkQA7gAVJCESjHYImdFxAAjCWLABrODFq99mKAHNkMCQFc43ABYwAtgBsA6k8zwhZsDhaJV8cXwBPZHAhEW4LITgJGDk9S1cxZAAzMXcE7gArIQAPACE9Q2NaMVc4ABkLOCycvJBCotoLS3c4AEU7CHgm3McQMwkEiSiXDy1eCQsYTw0YJ2QADgAGbjmIBM89Xii5uAnsRu4AR374FL5lEDEhAFooODh0d60JOCvMb5SxGkMkhssNuAlXJgbPYRkJOt0+gNGiDmiMYGJtEt0CtkAAmbi2MSYdydKgQVzpKJQaDnEB2BLEDHKUEtbAOACSUA+sFoYHm-HwXNoMHC3SGCQAvhKgA

lowercased

**Comment by evilebottnawi** [comment]
@fisker hm, before we don't do it, but make sense to write note in changelog about it

**Comment by fisker** [comment]
According to https://github.com/whatwg/html/pull/4830 ,  `autofocus` is global attribute now. 

That's spec change, I think we don't really need add this to changelog.

**Pull request merged**
