### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by sosukesuzuki**
## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
It's strange, I ran the script on my laptop, not changes, and the CI shows no differences too.

**Comment by DerekNonGeneric** [comment]
Would you mind bumping `json5` to 2.2.2 too before next release?

**Comment by fisker** [comment]
Do you have some particular reason mentioning this package? It's upgraded in `next` branch https://github.com/prettier/prettier/pull/14015

**Comment by DerekNonGeneric** [comment]
Oh, cool, not too sure, it was making noise on my fork, so wanted to be sure :)

**Pull request merged**
