### PR TITLE
ensure --list-different + --write reports status code 0

### LINKED ISSUE #4144: CLI: --list-different + --write = Exit status 1 if something was modified
It doesn't play very well with npm scripts:

```
d:\dev\foo>npm run format

> @ format d:\dev\foo
> prettier --write --list-different *.js

foo.js
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ format: `prettier --write --list-different *.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Without `--list-different` though it doesn't behave like this.

### PR DESCRIPTION
**Pull request by outofambit**
closes #4144 

let me know if i missed anything! 💖 

- [x] I’ve ~added~ modified tests to confirm my change works.
- [x] ~(If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)~
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by j-f1** [comment]
Thanks for contributing @outofambit!

**Comment by felixfbecker** [comment]
This is a breaking change and should have been in a major version. We rely on `--list-different` to check files are formatted in CI and break the build if they are not. There is no mention in the changelog of what different flags need to be provided to maintain this behaviour. I noticed this because files would constantly get reformatted despite us checking in CI with `--list-different`.

**Comment by felixfbecker** [comment]
There actually doesn't even seem to be any way to achieve this now because `--check` is not released yet

**Comment by j-f1** [comment]
If you don’t pass `--write`, Prettier will still exit with `1`.

**Comment by felixfbecker** [comment]
Yey. I have more than 25 repositories with an npm script that does both `--write` and `--list-different` and is used in CI.

**Comment by felixfbecker** [comment]
Yes, but I would have to define the glob twice, or have one script call into the other. I'm not saying it's not possible, I'm just saying this requires me to update _all_ these repositories and is therefor clearly a breaking change that should not have been introduced in a minor release (and reverted, tbh).

**Comment by j-f1** [comment]
cc @prettier/core

**Comment by outofambit** [comment]
@felixfbecker there was some discussion of this in https://github.com/prettier/prettier/issues/4144. I believe we determined this to be a bug, so fixing it would not constitute a breaking change.

**Comment by felixfbecker** [comment]
The workaround I am using now is
```json
    "prettier": "prettier --list-different --write \"**/{*.{js?(on),ts,md,yml},.*.yml}\"",
    "prettier-check": "npm run prettier -- --write=false",
```

**Pull request merged**
