### PR TITLE
Add forward/use scss parsing

### PR DESCRIPTION
**Pull request by AndrewLeedham**
- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Have you checked #7057?

**Comment by AndrewLeedham** [comment]
> Have you checked #7057?

I hadn't spotted that, my bad. Although that PR seems somewhat dead in the water.

**Comment by AndrewLeedham** [comment]
@fisker I'll see if I can fix the suggestions in that PR by branching from it.

**Comment by fisker** [comment]
You can start a new one, don't worry

**Pull request closed without merging**
