### PR TITLE
Treat <select> and <optgroup> as inline-block for whitespace sensitivity

### PR DESCRIPTION
**Pull request by thorn0**
- [x] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Is this #8272 ask for? 

I think @lydell mean `htmlWhitespaceSensitivity: "css" / "strict" / "ignore"` the same?

**Comment by lydell** [comment]
In theory I think it’s safe to do the nicer formatting even in `htmlWhitespaceSensitivity: ignore`, but that would be new machinery that we don’t have yet.

**Comment by thorn0** [comment]
I think with `strict`, users are supposed to add all the whitespace manually.

**Comment by lydell** [comment]
Oops, I meant `strict` in my comment.

**Pull request merged**
