### PR TITLE
Bump globby

### PR DESCRIPTION
**Pull request by duailibe**
Another attempt at #4715

### CODE REVIEW

**Comment by ikatyang** [comment]
I've tried that as well and it seems there're too many modules need to be loaded for `fast-glob`, which slows down the startup speed and we have a lot of test files.

We may want to switch to [`glob-gitignore`](https://github.com/kaelzhang/node-glob-gitignore) for ignoring folders based on `.ignore` file while traversing the file system (see https://github.com/prettier/prettier/issues/4989#issuecomment-414062231 for more info), which seems not supported in `globby@8` (`fast-glob`).

**Comment by ikatyang** [comment]
The `.ignore` issue for `fast-glob` should be tracked in mrmlnc/fast-glob#106 (use a custom `readdir` to return empty for `.ignore`d directories), though it seems there's not much interest on it.

**Comment by evilebottnawi** [comment]
@ikatyang He is working on C++ library (extension for `nodejs`) for reduce `fs` call and speedup glob

**Comment by evilebottnawi** [comment]
But better don't update `globby` (a lot of other bugs in `fast-glob`, not full compatibility with original glob)

**Pull request closed without merging**
