### PR TITLE
Add `.git-blame-ignore-revs`

### PR DESCRIPTION
**Pull request by fisker**
Inspired by https://github.com/babel/babel/pull/12063

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/pr-XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Review by sosukesuzuki — COMMENTED** [review]
Should we update this file in release-script?

**Comment by fisker** [comment]
Do we have the commit hash on release?

**Comment by fisker** [comment]
Maybe

**Comment by fisker** [comment]
Done https://github.com/prettier/prettier/pull/9415/commits/5bda0c9c163d6f0fdf8803787b4321012be58ebd

**Review by sosukesuzuki — APPROVED** [review]

**Review by evilebottnawi — APPROVED** [review]

**Review by thorn0 — APPROVED** [review]

**Pull request merged**
