### PR TITLE
Add support for TS config files (`prettier.config.ts`)

### PR DESCRIPTION
**Pull request by aryaemami59**
## Description

**This PR**:

  - [X] Adds `tsx` as a dependency.
  - [X] Adds support for TypeScript config files (`prettier.config.ts`, `prettier.config.cts`, `prettier.config.mts`, `.prettierrc.ts`, `.prettierrc.cts`, `.prettierrc.mts`).

## Checklist

- [ ] I’ve added tests to confirm my change works.
- [ ] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory).
- [ ] (If the change is user-facing) I’ve added my changes to `changelog_unreleased/*/XXXX.md` file following `changelog_unreleased/TEMPLATE.md`.
- [ ] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/main/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by fisker** [comment]
Sorry, we are not going to accept this.

**Comment by aryaemami59** [comment]
@fisker That's fair, but can I ask why?

**Comment by fisker** [comment]
a) We already have LOTS of supported formats https://prettier.io/docs/en/configuration
b) Support more files will cause performance issues https://github.com/prettier/prettier/issues/15653
c) We haven't received enough requests for this feature.

**Comment by aryaemami59** [comment]
@fisker Sure but TypeScript config files are slowly becoming the standard, more libraries are starting to add support for them, even libraries like Webpack and Docusaurus have started supporting them. If performance is your concern, I can look into it, run benchmarks and write tests to instill some confidence. I really do think the benefits of this will outweigh the potential negatives in the long run. If you re-open this I'll be more than happy to do a lot more work to make sure this gets through. I appreciate it!

**Comment by fisker** [comment]
> c) We haven't received enough requests for this feature.

Send a feature request first.

**Comment by aryaemami59** [comment]
@fisker Yes sir!

**Comment by aryaemami59** [comment]
@fisker #16119 is this okay?

**Pull request closed without merging**
