### PR TITLE
Improved multiline closure comment detection

### PR DESCRIPTION
**Pull request by yangsu**
Fixes https://github.com/prettier/prettier/issues/6067

- [x] I’ve added tests to confirm my change works.
- [x] (If changing the API or CLI) I’ve documented the changes I’ve made (in the `docs/` directory)
- [x] (If the change is user-facing) I’ve added my changes to the `CHANGELOG.unreleased.md` file following the template.
- [x] I’ve read the [contributing guidelines](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md).

**✨[Try the playground for this PR](https://prettier.io/playground-redirect)✨**

### CODE REVIEW

**Comment by evilebottnawi** [comment]
Something wrong with CI

**Comment by j-f1** [comment]
Restarted the CI.

**Comment by j-f1** [comment]
Looks like the changelog didn’t get updated. Can you add an entry for this change?

**Comment by yangsu** [comment]
oops. will do

**Comment by duailibe** [comment]
Thank you!

**Pull request merged**
