### PR TITLE
GraphQL: Directives

### PR DESCRIPTION
**Pull request by stubailo**
People usually don't have very long directives, and they usually don't have lots of arguments, but I made them wrap in the case of too many directives anyway.

### CODE REVIEW

**Comment by stubailo** [comment]
Will fix and reopen!

**Comment by vjeux** [comment]
I'm glad that you are able to do all those things on your own :)

**Comment by stubailo** [comment]
Haha I hope to be a low maintenance contributor!

**Comment by vjeux** [comment]
So far I just hit the merge button, so looks good on my end :p

**Pull request closed without merging**
